### ISSUE TITLE
升级到2.2.2后配置的证书报错

### ISSUE THREAD

**Issue by zonshy** [alibaba/tengine#1001]
升级到2.2.2后，之前配置的SSL报错
nginx: [emerg] SSL_CTX_new() failed (SSL: error:140A90A1:lib(20):func(169):reason(161))

具体的配置.conf
    ssl_certificate   cert/ssl.pem;
    ssl_certificate_key  cert/ssl.key;
    ssl_session_timeout 5m;
    ssl_ciphers ECDHE-RSA-AES128-GCM-SHA256:ECDHE:ECDH:AES:HIGH:!NULL:!aNULL:!MD5:!ADH:!RC4;
    ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
    ssl_prefer_server_ciphers on;

**Comment by cdcchen** [comment]
我升级了也有这个问题
openssl version：OpenSSL 1.0.2k-fips  26 Jan 2017

**Comment by wangfakang** [comment]
@cdcchen  你升级是执行的什么命令，我本地没有发现出来、麻烦提供下复现操作命令。

**Comment by cdcchen** [comment]
下载2.2.2源码包，然后：
./configure --with-http_dyups_module --with-http_v2_module  --enable-mods-shared=all

**Comment by wangfakang** [comment]
好的，多谢。 已经复现，我们修复下。

**Comment by wangfakang** [comment]
@zonshy @cdcchen 你们可以先使用这个[分支](https://github.com/mrpre/tengine)代码编译、然后执行看看，我们将在下周正式Release `Tengine-2.2.2`版本中修复这个问题。

https://github.com/alibaba/tengine/pull/1002

**Comment by cdcchen** [comment]
@wangfakang 已经测试，没有问题了。

**Comment by Tojaraliu** [comment]
我试了一下还是有同样的问题，环境是CentOS 7.4，openssl版本是OpenSSL 1.0.2k-fips  26 Jan 2017。
安装的话就是默认的./configure，不启用ssl的话是没有问题的。我的版本应该就是2.2.2。

**Comment by Alehap** [comment]
I'd the same issue with centos 7.4, openssl 1.1.0g and tengine 2.2.2 :(

**Comment by superinkfish** [comment]
The same issue with tengine 2.2.2 and openssl 1.0.2g on ubuntu 16.04.2 LTS
