### ISSUE TITLE
Tengine-2.2.2 (development version) has been released!

### ISSUE THREAD

**Issue by wangfakang** [alibaba/tengine#1004]
Tengine-2.2.2(开发)版本发布了！

[下载](http://tengine.taobao.org/download/tengine-2.2.2.tar.gz)           
[变更日志](http://tengine.taobao.org/changelog_cn.html#2_2_2)

新增如下新特性：
 - [异步OpenSSL的支持](http://tengine.taobao.org/document_cn/ngx_http_ssl_asynchronous_mode_cn.html) 可使用硬件如：[QAT](http://tengine.taobao.org/document_cn/tengine_qat_ssl_cn.html)进行HTTPS的加速与卸载；
 - [支持TLS1.3]() ssl_protocols 可配置TLSv1.3，具备TLS握手0-RTT特性；
 - [upstream配置块里面支持include]() upstream里面支持include配置指令，方便配置管理；

---

Tengine-2.2.2 (development version) has been released!

[download](http://tengine.taobao.org/download/tengine-2.2.2.tar.gz)  
[changelog](http://tengine.taobao.org/changelog.html#2_2_2)

Some features are as follows:
 - [asynchronous module](http://tengine.taobao.org/document/ngx_http_ssl_asynchronous_mode.html) Support asynchronous SSL/TLS mode, Could use [QAT to offload and accelerated SSL](http://tengine.taobao.org/document/tengine_qat_ssl.html).
 - [support TLS1.3]() Support TLS1.3 and 0-RTT data.
 - [upstream block support include]() Enabled `include` inside http upstreams.

**Comment by lidaohang** [comment]
赞

**Comment by chobits** [comment]
I'm closing this old release issue.

Tengine-2.3.0 has been released, it has been been upgraded to nginx 1.15.9.

For more details of new version, see https://github.com/alibaba/tengine/issues/1220.
