### ISSUE TITLE
请问大神 你们哪项目些还在用tengine

### ISSUE THREAD

**Issue by mrlixiansheng** [alibaba/tengine#1011]
请问大神 你们哪项目些还在用tengine

**Comment by chobits** [comment]
阿里核心业务系列的接入层和阿里云CDN都使用Tengine做前端负载

**Comment by chobits** [comment]
另外可以参考这个调查[调查：哪些用户在使用Tengine？](https://github.com/alibaba/tengine/issues/590)

**Comment by chobits** [comment]
thinks it resolved

**Comment by chobits** [comment]
thinks it resolved
