### ISSUE TITLE
Tengine Dyups Module with IP Hash

### ISSUE THREAD

**Issue by cngo-github** [alibaba/tengine#1013]
Hi. I am using Tengine with the `dyups` module installed. It seems to work fine, but I want to use the `ip_hash` load balancing scheme instead of `round robin`. Normally, I would just add this to the upstream server declaration. How would I do via the `dyups` module?

I found this:

https://github.com/alibaba/tengine/blob/master/tests/nginx-tests/cases/dyups.t#L266

However, when I add `ip_hash;` to my endpoint call:

`curl -d "ip_hash;server 127.0.0.1:8089;server 127.0.0.1:8088;" 127.0.0.1:8081/upstream/test`

the `dyups` config file does not have the line `ip_hash;`, only the two server lines.

**Comment by hongxiaolong** [comment]
Yes, the dyups modules would not show u "ip_hash" when u call the API `/detail get all upstreams and their servers`.  And u could find like this cases:
```
like(mhttp_post('/upstream/dyhost', 'ip_hash;server 127.0.0.1:8088; server 127.0.0.1:8089;', 8081), qr/success/m, '2013-03-04 15:53:41');
like(mhttp_get('/', 'dyhost', 8080), qr/8088/m, '2013-03-04 15:53:44');
like(mhttp_get('/', 'dyhost', 8080), qr/8088/m, '2013-03-04 15:53:46');
like(mhttp_get('/', 'dyhost', 8080), qr/8088/m, '2013-03-04 15:53:49');
```
As the cases show, the load balancing scheme is ip_hash.
