### ISSUE TITLE
nginx proxy + cloudflare + https = 403 Forbidden cloudflare-nginx

### ISSUE THREAD

**Issue by f4nff** [alibaba/tengine#1014]
> upstream ws {
> 	server 104.16.19.234:443;
> 	server 104.16.18.234:443;
> 	server 104.16.10.234:443;
> 	server 104.16.11.234:443;
>  
>  }
>  
>  
>  server {
>          listen      80; 
>  
> location /{
> 	proxy_pass_header	Server;
> 	proxy_pass			https://ws;
> 	proxy_set_header	Host "cloudflareapi.com";
> 	proxy_set_header	X-Real-IP $remote_addr;
> 	proxy_set_header	X-Scheme $scheme;
> 		}
> 	}
> 

> 403 Forbidden
cloudflare-nginx

**Comment by chobits** [comment]
hi f4nff,

 Could you give detail of this issue, you can output `$upstream_status` in access.log to check whether 403 is output by backend server.

Also you can request backend server directly to check.

**Comment by f4nff** [comment]
add

> 	proxy_ssl_server_name	        on;
> 	proxy_ssl_name			"www.cloudflare.com";	

ok~

**Comment by chobits** [comment]
> add
> > proxy_ssl_server_name	on;
> > proxy_ssl_name	"www.cloudflare.com";

> ok~

think it resolved, I am closing this issue. You can reopen this issue if having any problem.
