### ISSUE TITLE
dyups: https session重用的内存泄漏 // dyups: memory leak of ssl session reuse

### ISSUE THREAD

**Issue by powerdesigner** [alibaba/tengine#1016]
dyups组件是不是真如github上有人留言的那样，与https不兼容而导致内存泄漏。我目前就遇到跟那位反馈者类似的问题，场景也是https，困扰我半个多月了。经过持续跟踪，我发现lua的GC一直很小，怀疑泄漏点像是出在该组件上。能确认这是个BUG吗？如果是，有没有修复计划？

原反馈地址及讨论组帖子地址
https://github.com/yzprofile/ngx_http_dyups_module/issues/67
https://groups.google.com/forum/#!topic/openresty/C_rnBilveJM

**Comment by chobits** [comment]
能否提供一下内存泄露的一些数据。而且邮件里agentzh已经提供了1个方法来帮助分析nginx中内存占用了。

另外我们这边，有个探测ngx中pool内存占用的工具http://tengine.taobao.org/document_cn/ngx_debug_pool_cn.html，如果是dyups的pool中内存占用过高，使用该工具会出现：ngx_dyups_init_upstream这个项目会一直增大。

提供如上一些信息来帮助开发者来定位会加速问题解决。或者能够提供完整的reproduce方法。

**Comment by chobits** [comment]
referer to https://github.com/yzprofile/ngx_http_dyups_module/issues/67

**Comment by zhaiyan1234** [comment]
问题解决了吗？
目前改问题比较好复现，复现条件：
（1）使用dyups设置upstream；
（2）upstream server设置为短连接（Connection: close）;
（3）配置为proxy_ssl_session_reuse on; （该配置默认为on）；
当设置为这3个条件后，压测会出现内存泄露
不知道tengine是否计划解决这个问题？

**Comment by zhaiyan1234** [comment]
分别看了一下nginx round robin和dyups处理ssl session的代码，nginx round robin内的session是属于每个peer的，意味着单个upstream ip全局只会存在一个session，而dyups是分别属于每个的request的，这里是有坑的，request的pool relese的时根本没有调用ssl_free，造成这个session结构体泄露

**Comment by ygm521** [comment]
@zhaiyan1234 咋解决的？

**Comment by chobits** [comment]
> 分别看了一下nginx round robin和dyups处理ssl session的代码，nginx round robin内的session是属于每个peer的，意味着单个upstream ip全局只会存在一个session，而dyups是分别属于每个的request的，这里是有坑的，request的pool relese的时根本没有调用ssl_free，造成这个session结构体泄露

欢迎提交patch。这将是一个有意义得修复

**Comment by ygm521** [comment]
@chobits 我这也有此情况，与后端session 复用，开启会话保持，内存泄漏。nginx round robin内的session是属于每个peer的，意味着单个upstream ip全局只会存在一个session，而sticky模块针对每请求的。

**Comment by chobits** [comment]
> @chobits 我这也有此情况，与后端session 复用，开启会话保持，内存泄漏。nginx round robin内的session是属于每个peer的，意味着单个upstream ip全局只会存在一个session，而sticky模块针对每请求的。

我大致能力理解，但是需要对一下代码细节和复现方式（https://github.com/alibaba/tengine/issues/1016#issuecomment-483614571）。如果 直接开pr提交patch 可以加速开发者定位。

**Comment by chobits** [comment]
> 分别看了一下nginx round robin和dyups处理ssl session的代码，nginx round robin内的session是属于每个peer的，意味着单个upstream ip全局只会存在一个session，而dyups是分别属于每个的request的，这里是有坑的，request的pool relese的时根本没有调用ssl_free，造成这个session结构体泄露

ngx round robin中

```
ngx_http_upstream_save_round_robin_peer_session
  ->  peer->ssl_session = ssl_session;  
    // 这里将连接上SSL上得session抓取下来存在关联得peer上
    // peer关联peers(来自cf->pool)，实际相当于session得索引被 ngx conf抓取到+1
```

而dyups逻辑

```
ngx_http_dyups_save_peer_session
  ->  ctx->ssl_session = ssl_session;
// ctx是从r->pool上生成，相当于ssl_session得索引被r抓取，随着r释放后，这个索引没有-1（ssl session free)
// 另外还有一个问题，由于ssl_session是存在当前r的ctx上，下一个请求r'再次进来后其新生成的ctx上是没有ssl session
// 导致ssl reuse也不生效
```

产生 1. session 泄露，2. session reuse逻辑失效。
临时修复是关闭后端的session reuse逻辑 (关闭配置`proxy_ssl_session_reuse`)

**Comment by chobits** [comment]
hi @zhaiyan1234 @ygm521 

I have opened a pull request to fix this issue, you can try the patch firstly. More test cases need to be added.

https://github.com/alibaba/tengine/pull/1708

Patch: https://patch-diff.githubusercontent.com/raw/alibaba/tengine/pull/1708.patch

**Comment by chobits** [comment]
hi @zhaiyan1234 @ygm521

I also fixed memory leak of ssl reuse in session sticky module in the same pr: (https://github.com/alibaba/tengine/pull/1708)

try patch firstly: https://patch-diff.githubusercontent.com/raw/alibaba/tengine/pull/1708.patch
