### ISSUE TITLE
请问是否可以隐藏错误页面显示的 Server Name？

### ISSUE THREAD

**Issue by mashirozx** [alibaba/tengine#1021]
![image](https://user-images.githubusercontent.com/16148054/37271678-cead1a82-260e-11e8-968c-c74bc2bb16f4.png)

如图，没找到在哪改，好二的名字不想让人看到😂

**Comment by taoyuanyuan** [comment]
http://tengine.taobao.org/document/core.html
```server_info off；```  看看这个指令

**Comment by mashirozx** [comment]
@taoyuanyuan 感谢
