### ISSUE TITLE
配置proxy_upstream_tries后，upstream_response_time的时间是“-”

### ISSUE THREAD

**Issue by mrzhangxing** [alibaba/tengine#1025]
您好，当配置了upstream_response_time 2;后端确实重试了2次，而且日志中upstream_addr和upstream_status都是"xxx,xxx"这样，但是upstream_response_time只有一个"-"；
官网Nginx配置测试结果upstream_response_time也是"xxx,xxx"这样，请问Tengine可以取出来重试的每一个upstream_response_time值吗？

**Comment by wangfakang** [comment]
@mrzhangxing 我本地测试[tengine-2.2.2](http://tengine.taobao.org/download/tengine-2.2.2.tar.gz)，upstream_response_time是可以取到多次的时间的，请提供下你的测试配置。

**Comment by mrzhangxing** [comment]
@wangfakang 好的，了解了，感谢
