### ISSUE TITLE
使用tengine2.2.2的QAT卡SSL解码，QAT卡计数器无变化。

### ISSUE THREAD

**Issue by maikafei-chen** [alibaba/tengine#1031]
使用tengine2.2.2的通QAT卡SSL解码，QAT卡计数器（/sys/kernel/debug/qat_dh895xcc_06\:00.0/fw_counters），无变化。
tengine版本是2.2.2
QAT驱动qat1.7，QAT_Engine-0.5.32，openssl-1.1.0f
安装完成后，通过openssl自测计数器可以发现变化。
但是通过ab命令访问tengine测试。qat计数器没有变化.
tengine配置
server {

    listen 443;
    ssl_async   on;
    server_name ssl-test.xxx.net;
     ssl_certificate      server.crt; 
     ssl_certificate_key  server.key;
   
    location / {
        root   html;
        index  index.html index.htm;
     }
请问还需要配置哪里吗

**Comment by wangfakang** [comment]
@maikafei-chen 
1、你可以检查下编译后端的Tengine使用的OpenSSL库是那个版本【ldd tengine】，看是是否正确的引入了高版本OpenSSL。
2、确认下dev下的相关qat设备，在tengine的worker进程里面是否有读权限(你可以尝试把tengine配置里面的额user配置为root验证下)。qat相关的设备文件如下：
```
/dev/qat_adf_ctl
/dev/qat_contig_mem
/dev/qat_dev_processes
```

**Comment by maikafei-chen** [comment]
@wangfakang 
谢谢你的答复
1.检查了一下，Tenine使用的是高版本的OpenSSL
	libssl.so.1.1 => /usr/local/ssl/lib/libssl.so.1.1 (0x00007ff7c97d2000)
	libcrypto.so.1.1 => /usr/local/ssl/lib/libcrypto.so.1.1 (0x00007ff7c936b000)
2.修改了worker进程为root，计数器还是没有变化
3.qat相关设备文件没有找到/dev/qat_contig_mem，这个有影响吗?

**Comment by maikafei-chen** [comment]
@wangfakang 
谢谢，最后确认是权限问题。修改为root权限后就可以了
