### ISSUE TITLE
什么时候tengine升级到NGINX 1.9.0 支持stream模块呢？

### ISSUE THREAD

**Issue by kgc007** [alibaba/tengine#1036]
如题，什么时候tengine升级到NGINX 1.9.0，可以支持stream模块呢？

**Comment by moqianjun** [comment]
貌似一年一个版本

**Comment by sunsan05** [comment]
真期待更新啊……明明效率这么高效，但是1年才更1次。。

**Comment by hujingguang** [comment]
mark

**Comment by chobits** [comment]
v2.3.0 has been released, it has upgraded to nginx-1.15.9.

See https://github.com/alibaba/tengine/issues/1220.
