### ISSUE TITLE
make 出现错误error: this statement may fall through [-Werror=implicit-fallthrough=]

### ISSUE THREAD

**Issue by chengxingyao** [alibaba/tengine#1039]
make 出现错误error: this statement may fall through [-Werror=implicit-fallthrough=]
> make[1]: Entering directory '/app/lazy_balancer/resource/nginx/tengine'
cc -c -pipe  -O -W -Wall -Wpointer-arith -Wno-unused -Werror -g  -I src/core -I src/event -I src/event/modules -I src/os/unix -I src/proc -I objs \
	-o objs/src/core/ngx_murmurhash.o \
	src/core/ngx_murmurhash.c
src/core/ngx_murmurhash.c: In function ‘ngx_murmur_hash2’:
src/core/ngx_murmurhash.c:37:11: error: this statement may fall through [-Werror=implicit-fallthrough=]
         h ^= data[2] << 16;
         ~~^~~~~~~~~~~~~~~~
src/core/ngx_murmurhash.c:38:5: note: here
     case 2:
     ^~~~
src/core/ngx_murmurhash.c:39:11: error: this statement may fall through [-Werror=implicit-fallthrough=]
         h ^= data[1] << 8;
         ~~^~~~~~~~~~~~~~~
src/core/ngx_murmurhash.c:40:5: note: here
     case 1:
     ^~~~
cc1: all warnings being treated as errors
objs/Makefile:478: recipe for target 'objs/src/core/ngx_murmurhash.o' failed
make[1]: *** [objs/src/core/ngx_murmurhash.o] Error 1
make[1]: Leaving directory '/app/lazy_balancer/resource/nginx/tengine'
Makefile:8: recipe for target 'build' failed
make: *** [build] Error 2

**Comment by wu-geoff** [comment]
这问题已在PR # 1007 中被修复

**Comment by chobits** [comment]
fixed
