### ISSUE TITLE
合并nginx稳定版的大概周期是多少？

### ISSUE THREAD

**Issue by xingstudy** [alibaba/tengine#1048]
尊敬的阿里开源开发者们，你们好。
我是一名运维。
最近打算升级nginx，考虑直接使用阿里的tengine。
在做功能对比时，发现tengine是基于nginx的1.8.1版本。
通过变更日志也能看到tengine把一些主要功能也合并到了现有版本中，但是1.8.1至今两年时间时间有点长，nginx主版本又添加了一些功能模块。
请问一下，是否因为一些原因（如，tengine的差异已经比较大，工作场景限制等），不再考虑完整合并nginx功能？
如果为否，会考虑合并nginx所有功能至tengine吗？大概周期要多久？

**Comment by chobits** [comment]
7-8月将完成，见我们roadmap: https://github.com/alibaba/tengine/wiki/Roadmap.

目前已经在拆解大部门tengine内部功能，为merge最新官方稳定版准备

**Comment by sungy2014** [comment]
现在想在生产环境使用tengine，我看到最新的稳定版是2015年的，[2015-12-31] Tengine-2.1.2，
我们在生产环境应该使用哪个版本？

**Comment by chobits** [comment]
推荐用最新版本2.3.0，修复了大量bug，并且100%兼容nginx 1.15.9

Tengine-2.3.0 has been released, it has been been upgraded to nginx 1.15.9.

For more details of new version, see https://github.com/alibaba/tengine/issues/1220.
