### ISSUE TITLE
tnginx-2.2.1 是否支持 tcp 转发

### ISSUE THREAD

**Issue by huyipow** [alibaba/tengine#1057]
请问 默认的 tnginx -2.2.1 是否能反向代理tcp 连接。
如果可以 是哪个模块支持

**Comment by chobits** [comment]
需要三方库：目前我们内部一般使用的是tcp 模块。（https://github.com/yaoweibin/nginx_tcp_proxy_module）
官方nginx支持的是stream模块，后续我们会升级到官方最新的版本。

**Comment by GeXin666** [comment]
不建议用nginx做tcp4层转发，不如用LVS。

**Comment by johneexu** [comment]
nginx_tcp_proxy_module 模块相比nginx 的stream模块增加了健康检查， 但是tengine2.2.2打插件编译报错，试了稳定版本tengine-2.1.2 可以打进去，但是低版本bug很多bug都没修复

**Comment by chobits** [comment]
Stream module has been supported in latest Tengine 2.3.0.

Tengine-2.3.0 has been released, it has been been upgraded to nginx 1.15.9.

For more details of new version, see https://github.com/alibaba/tengine/issues/1220.
