### ISSUE TITLE
Tengine 2.2.2 + nginx_tcp_proxy_module 编译报错

### ISSUE THREAD

**Issue by jy00278439** [alibaba/tengine#1080]
-o objs/addon/nginx_tcp_proxy_module/ngx_tcp_session.o \
	/data/tools/nginx_tcp_proxy_module/ngx_tcp_session.c
In file included from src/core/ngx_core.h:62:0,
                 from /data/tools/nginx_tcp_proxy_module/ngx_tcp_session.c:3:
/data/tools/nginx_tcp_proxy_module/ngx_tcp_session.c: In function ‘ngx_tcp_send’:
/data/tools/nginx_tcp_proxy_module/ngx_tcp_session.c:351:20: error: ‘NGX_LOG_DEBUG_TCP’ undeclared (first use in this function)
     ngx_log_debug1(NGX_LOG_DEBUG_TCP, wev->log, 0, "nginx tcp send:%d", n);
                    ^
src/core/ngx_log.h:92:28: note: in definition of macro ‘ngx_log_debug’
     if ((log)->log_level & level)                                             \
                            ^
/data/tools/nginx_tcp_proxy_module/ngx_tcp_session.c:351:5: note: in expansion of macro ‘ngx_log_debug1’
     ngx_log_debug1(NGX_LOG_DEBUG_TCP, wev->log, 0, "nginx tcp send:%d", n);
     ^
/data/tools/nginx_tcp_proxy_module/ngx_tcp_session.c:351:20: note: each undeclared identifier is reported only once for each function it appears in
     ngx_log_debug1(NGX_LOG_DEBUG_TCP, wev->log, 0, "nginx tcp send:%d", n);
                    ^
src/core/ngx_log.h:92:28: note: in definition of macro ‘ngx_log_debug’
     if ((log)->log_level & level)                                             \
                            ^
/data/tools/nginx_tcp_proxy_module/ngx_tcp_session.c:351:5: note: in expansion of macro ‘ngx_log_debug1’
     ngx_log_debug1(NGX_LOG_DEBUG_TCP, wev->log, 0, "nginx tcp send:%d", n);
     ^
/data/tools/nginx_tcp_proxy_module/ngx_tcp_session.c: In function ‘ngx_tcp_finalize_session’:
/data/tools/nginx_tcp_proxy_module/ngx_tcp_session.c:410:20: error: ‘NGX_LOG_DEBUG_TCP’ undeclared (first use in this function)
     ngx_log_debug1(NGX_LOG_DEBUG_TCP, c->log, 0,
                    ^
src/core/ngx_log.h:92:28: note: in definition of macro ‘ngx_log_debug’
     if ((log)->log_level & level)                                             \
                            ^
/data/tools/nginx_tcp_proxy_module/ngx_tcp_session.c:410:5: note: in expansion of macro ‘ngx_log_debug1’
     ngx_log_debug1(NGX_LOG_DEBUG_TCP, c->log, 0,
     ^
/data/tools/nginx_tcp_proxy_module/ngx_tcp_session.c: In function ‘ngx_tcp_close_connection’:
/data/tools/nginx_tcp_proxy_module/ngx_tcp_session.c:431:20: error: ‘NGX_LOG_DEBUG_TCP’ undeclared (first use in this function)
     ngx_log_debug1(NGX_LOG_DEBUG_TCP, c->log, 0,
                    ^
src/core/ngx_log.h:92:28: note: in definition of macro ‘ngx_log_debug’
     if ((log)->log_level & level)                                             \
                            ^
/data/tools/nginx_tcp_proxy_module/ngx_tcp_session.c:431:5: note: in expansion of macro ‘ngx_log_debug1’
     ngx_log_debug1(NGX_LOG_DEBUG_TCP, c->log, 0,
     ^
/data/tools/nginx_tcp_proxy_module/ngx_tcp_session.c: In function ‘ngx_tcp_cleanup_add’:
/data/tools/nginx_tcp_proxy_module/ngx_tcp_session.c:519:20: error: ‘NGX_LOG_DEBUG_TCP’ undeclared (first use in this function)
     ngx_log_debug1(NGX_LOG_DEBUG_TCP, s->connection->log, 0,
                    ^
src/core/ngx_log.h:92:28: note: in definition of macro ‘ngx_log_debug’
     if ((log)->log_level & level)                                             \
                            ^
/data/tools/nginx_tcp_proxy_module/ngx_tcp_session.c:519:5: note: in expansion of macro ‘ngx_log_debug1’
     ngx_log_debug1(NGX_LOG_DEBUG_TCP, s->connection->log, 0,
     ^
make[1]: *** [objs/addon/nginx_tcp_proxy_module/ngx_tcp_session.o] Error 1
make[1]: *** Waiting for unfinished jobs....
make[1]: Leaving directory `/data/tools/tengine-2.2.2'
make: *** [build] Error 2

**Comment by wangwei123** [comment]
我看到这篇文章：https://www.cnblogs.com/jicki/p/5548538.html，应该可以解决楼主的问题，不知道这个模块是否有tcp session同步的功能

**Comment by chobits** [comment]
think it resolved, I'm closing this issue.
