### ISSUE TITLE
kill -USR1分割日志时，发现会引发kafka超时丢失数据

### ISSUE THREAD

**Issue by wuxin** [alibaba/tengine#1091]
我们通过`lua-resty-kafka`推送实时事件，日志在准点通过`kill -USR1`来进行切割。

最近在比对数据时发现，发出`kill -USR1`后，Kafka会报超时。因此想确认下，`kill -USR1`会影响到Kafka吗？

**Comment by chobits** [comment]
http://nginx.org/en/docs/control.html

> USR1 - re-opening log files

该信号会使得所有nginx worker close日志文件的fd并重新open。结合这个行为，可以分析下是否会影响kafka
