### ISSUE TITLE
tengine2.2.0 TFS CentOS7编译错误

### ISSUE THREAD

**Issue by bukebuhao** [alibaba/tengine#1093]
./configure --prefix=/usr/local/tengine2.2.0 --with-ld-opt="-Wl,-rpath,/usr/local/luajit/lib" --enable-mods-static=all --with-http_flv_module --with-http_mp4_module --with-http_gzip_static_module --with-http_stub_status_module --with-http_ssl_module --with-md5=/usr/lib --with-http_realip_module --with-pcre --with-http_sub_module --with-http_image_filter_module --with-http_upstream_check_module **--with-http_tfs_module** --with-http_concat_module --with-http_upstream_check_module --with-syslog --with-openssl=/usr/local/src/openssl-1.0.1t --add-module=/usr/local/src/lua-nginx-module-0.10.8 --add-module=/usr/local/src/ngx_devel_kit-0.3.0 --add-module=/usr/local/src/ngx_cache_purge-2.3 

先前在centos6.9等编译都是可以的，现在在centos7上 make的时候出现

        -o objs/src/http/modules/tfs/ngx_http_tfs_rc_server_info.o \
        src/http/modules/tfs/ngx_http_tfs_rc_server_info.c
src/http/modules/tfs/ngx_http_tfs_rc_server_info.c: 在函数‘ngx_http_tfs_dump_rc_info’中:
src/http/modules/tfs/ngx_http_tfs_rc_server_info.c:330:41: 错误：**变量‘physical_clusters’被设定但未被使用 [-Werror=unused-but-set-variable]**
     ngx_http_tfs_physical_cluster_t    *physical_clusters;
                                         ^
src/http/modules/tfs/ngx_http_tfs_rc_server_info.c:328:41: 错误：**变量‘group_info’被设定但未被使用 [-Werror=unused-but-set-variable]**
     ngx_http_tfs_group_info_t          *group_info;
                                         ^
cc1: all warnings being treated as errors
make[1]: *** [objs/src/http/modules/tfs/ngx_http_tfs_rc_server_info.o] 错误 1
make[1]: 离开目录“/usr/local/src/zhu/tengine-2.2.2”
make: *** [build] 错误 2

按照网上的说法，修改了Makefile 去除**-Werror**

**Comment by chobits** [comment]
This bug has been fixed in Tengine 2.3.0.

Tengine-2.3.0 has been released, it has been been upgraded to nginx 1.15.9.

For more details of new version, see https://github.com/alibaba/tengine/issues/1220.
