### ISSUE TITLE
我现在有这样一个问题

### ISSUE THREAD

**Issue by juincen** [alibaba/tengine#1094]
例如：a.com解析一个cname域名指向c.com，b.com也解析一个cname域名指向c.com，然后c.com解析到云服务器ip上，云服务器上的tengine（nginx）怎么识别是来自a.com还是b.com？？

**Comment by juincen** [comment]
@perusio @agentzh @chaoslawful @zhuzhaoyuan @jlund Please

**Comment by taoyuanyuan** [comment]
你的意思是  a.com cname 到 c.com,    b.com cname到c.com？
这样的话， 你服务器接受到的域名还是a.com和b.com的
```
server {
   server_name a.com
}
server {
  server_name b.com
}
```
这样就行

**Comment by billychou** [comment]
服务器能获取到 UA 和Host 信息，CNAME 到什么地方不影响请求的信息吧
