### ISSUE TITLE
502 bad gateway issue

### ISSUE THREAD

**Issue by angeljiang** [alibaba/tengine#1096]
你好！上个星期打开这个链接没问题，今天就出现502 bad gateway的页面。不清楚要怎么解决。

URL:	http://vg.yimieji.com/resource/broadcast
Server:	izj6c6g7jeqvh8i8hqbl9cz
Date:	2018/09/10 01:14:09

希望问题早日解决。感谢！

**Comment by wangfakang** [comment]
看tengine对应的错误日志，502一般是由于tengine代理的后端服务端口不可用了。
