### ISSUE TITLE
tegine跨域的设置如何做的？

### ISSUE THREAD

**Issue by clarkwang2008** [alibaba/tengine#1102]
nginx跨域是使用ngx_http_headers_module中的add_header 指令，在响应头中添加允许跨域。

tengine如何实现跨域设置的？

**Comment by wangfakang** [comment]
@clarkwang2008  tengine中也是支持`add_header`指令的。

**Comment by Miss-you** [comment]
通常是add_header吧。

**Comment by chobits** [comment]
think it resolved, I'm closing this issue.
