### ISSUE TITLE
淘宝登录框400错误

### ISSUE THREAD

**Issue by feng0824** [alibaba/tengine#1110]
400 Bad Request
Your browser sent a request that this server could not understand. Sorry for the inconvenience.
Please report this message and include the following information to us.
Thank you very much!

**Comment by MengqiWu** [comment]
这个，建议打淘宝客服

消费者热线 | 9510211
-- | --
商家热线 | 0571-88157858

**Comment by chobits** [comment]
Not tengine issue, I'm closing it.
