### ISSUE TITLE
升级至2.2.3后，版本没变化

### ISSUE THREAD

**Issue by relearn1** [alibaba/tengine#1118]
root@s0257-gz:/opt/packages/tengine-tengine-2.2.3# nginx -v
Tengine version: Tengine/2.2.2 (nginx/1.8.1)

**Comment by chobits** [comment]
thanks 还没发布，先打个tar测试用

**Comment by chobits** [comment]
fixed in https://github.com/alibaba/tengine/pull/1119.

**Comment by chobits** [comment]
See this new version：https://github.com/alibaba/tengine/releases/tag/tengine-2.2.3
