### ISSUE TITLE
dyups API导致节点流量倾斜问题

### ISSUE THREAD

**Issue by FengXingYuXin** [alibaba/tengine#1124]
dyups灌入upstream peer list后，会出现list前面的节点流量偏高，后面的节点流量偏低的问题，https://github.com/alibaba/tengine/pull/987 如这个PR进行修复

**Comment by wangfakang** [comment]
这块代码是已经merge进去，感谢你的contribute。

**Comment by FengXingYuXin** [comment]
“这块代码是已经merge进去”意思是说当前最新版本已经fix？（我没在2.2.3版本中找到相关修复），还是说会在下个版本 如#987 方式进行修复？

**Comment by Lax** [comment]
master 里还没有 @wangfakang 
现在要先签 CLA 才能合并？

**Comment by wangfakang** [comment]
@Lax 是的，需要签ACL.
@FengXingYuXin 我们将在下个版本中合入你的修改，谢谢你的贡献。

**Comment by FengXingYuXin** [comment]
好的 got it 多谢回复

**Comment by FengXingYuXin** [comment]
@wangfakang dyups添加init_random的代码 新开了 https://github.com/alibaba/tengine/pull/1140 辛苦评阅

**Comment by chobits** [comment]
已经merged，关闭issue中。

**Comment by chobits** [comment]
同时准备将此pr移入yzprofile/dyups:

合并回来有3个东西
1. 编译报错
2. cf.cycle初始化
这2个都修复在 https://github.com/yzprofile/ngx_http_dyups_module/pull/116

3. rr流量倾斜问题：https://github.com/alibaba/tengine/pull/1140/files https://github.com/alibaba/tengine/issues/1124
