### ISSUE TITLE
dso_tool --nginx-include不能添加多个文件夹吗？

### ISSUE THREAD

**Issue by littleplus** [alibaba/tengine#1128]
系统：Centos 7 x64

我在安装最新的ngx_http_lua模块时，提示我找不到luajit.h，我是通过yum安装lua和luajit的

用dso_tool编译的时候，用--nginx-include指定了luajit的位置，然后就提示我找不到ngx_config.h的位置

多次测试后发现，--nginx-include只能调用一次，后一次的输入会覆盖前一次，而且不能用逗号分号间隔文件夹目录......

怎么破....

**Comment by chobits** [comment]
Hi，新版本中我们已经支持官方nginx dynamic module，之前dsotool与nginx官方实现有较多冲出，无法维护。

# New version release

Hi all, current master is based on nginx 1.15.2, it has stream module. Please check it!
We'll release new version 2.3.x (based on nginx 1.15.x) soon.

# WARNING

Note that this version is slightly not backwards compatible, some tengine features have been replaced by nginx offical.  check the following list:
1. `--with-http_slice_module` configure option now works for [nginx slice module](http://nginx.org/en/docs/http/ngx_http_slice_module.html). Use `--add-module=modules/ngx_http_slice_module` for original [tengine slice module](http://tengine.taobao.org/document/http_slice.html).
2. Removed Tengine DSO feature, use [nginx dynamic modules feature](https://www.nginx.com/resources/wiki/extending/converting/) instead.
3. Removed `reuse_port` directive in `event {}` block, use [`listen .. reuseport;` directive](http://nginx.org/en/docs/http/ngx_http_core_module.html#listen) instead.
4. Extract the tengine modules to modules dir, if you need to use that module then use `--add-module=modules/xxx_module_name` way to compile.
5. The request counting logic for limit_req is consistent with the Nginx official. Now requests with all empty variable in `limit_req_zone` are not accounted. Original tengine does not account requests with any empty variable.
