### ISSUE TITLE
Tengine目前不支持ngx.worker.id函数

### ISSUE THREAD

**Issue by oliveryunchang** [alibaba/tengine#1130]
tengine编译
```
./configure --add-module=../lua-nginx-module-0.10.13 
```
[ngx.worker.id](https://github.com/openresty/lua-nginx-module#ngxworkerid)，官方文档显示此函数要求NGINX 1.9.1+，目前tengine开源依赖的NGINX是1.8.1

lua-nginx-module源码地址：https://github.com/openresty/lua-nginx-module/blob/master/src/ngx_http_lua_worker.c#L63
lua-resty-core源码地址：https://github.com/openresty/lua-resty-core/blob/master/lib/resty/core/worker.lua#L29

希望能将相关模块合并到开源tengine分支上，万分感谢！

**Comment by chobits** [comment]
hi，最新分支已经支持了新版的lua-nginx-module

# New version updated in master

Hi all, current master is based on nginx 1.15.2, it has stream module. Please check it!
We'll release new version 2.3.x (based on nginx 1.15.x) soon.

# WARNING

Note that this version is slightly not backwards compatible, some tengine features have been replaced by nginx offical.  check the following list:
1. `--with-http_slice_module` configure option now works for [nginx slice module](http://nginx.org/en/docs/http/ngx_http_slice_module.html). Use `--add-module=modules/ngx_http_slice_module` for original [tengine slice module](http://tengine.taobao.org/document/http_slice.html).
2. Removed Tengine DSO feature, use [nginx dynamic modules feature](https://www.nginx.com/resources/wiki/extending/converting/) instead.
3. Removed `reuse_port` directive in `event {}` block, use [`listen .. reuseport;` directive](http://nginx.org/en/docs/http/ngx_http_core_module.html#listen) instead.
4. Extract the tengine modules to modules dir, if you need to use that module then use `--add-module=modules/xxx_module_name` way to compile.
5. The request counting logic for limit_req is consistent with the Nginx official. Now requests with all empty variable in `limit_req_zone` are not accounted. Original tengine does not account requests with any empty variable.
