### ISSUE TITLE
tengine返回508

### ISSUE THREAD

**Issue by chen--johnny** [alibaba/tengine#1131]
请问tengine返回508问题，是什么原因呢

response:
4|user     |    { status: 508,
4|user     |      statusText: 'Loop Detected',
4|user     |      headers:
4|user     |       { server: 'Tengine',
4|user     |         'content-type': 'application/octet-stream',
4|user     |         'content-length': '0',
4|user     |         connection: 'close',
4|user     |         date: 'Wed, 28 Nov 2018 05:00:50 GMT',
4|user     |         via: 'cache14.l2eu95[,0], cache7.cn1187[32,0]',
4|user     |         'x-alicdn-da-ups-status': 'endInner,0,508,0',
4|user     |         'timing-allow-origin': '*',
4|user     |         eagleid: '77bc94d015433812505294225e' },
4|user     |      config:
4|user     |       { adapter: [Function: httpAdapter],
4|user     |         transformRequest: [Object],
4|user     |         transformResponse: [Object],
4|user     |         timeout: 0,
4|user     |         xsrfCookieName: 'XSRF-TOKEN',
4|user     |         xsrfHeaderName: 'X-XSRF-TOKEN',
4|user     |         maxContentLength: -1,
4|user     |         validateStatus: [Function: validateStatus],
4|user     |         headers: [Object],
4|user     |         method: 'post',
4|user     |         baseURL: 'http://localhost:8010/user/',
4|user     |         url: 'https://tp-pay-test.snssdk.com/gateway-u/',
4|user     |         data: 'app_id=800000070008&charset=utf-8&format=JSON&method=tp.cashdesk.user_info&version=1.0&biz_content={"method":"cashdesk.wap.user.userinfo","merchant_id":"1300000004","risk_info":{"risk_str":"{}"}}' },
4|user     |      request:
4|user     |       ClientRequest {
4|user     |         domain: null,
4|user     |         _events: [Object],
4|user     |         _eventsCount: 6,
4|user     |         _maxListeners: undefined,
4|user     |         output: [],
4|user     |         outputEncodings: [],
4|user     |         outputCallbacks: [],
4|user     |         outputSize: 0,
4|user     |         writable: true,
4|user     |         _last: true,
4|user     |         chunkedEncoding: false,
4|user     |         shouldKeepAlive: false,
4|user     |         useChunkedEncodingByDefault: true,
4|user     |         sendDate: false,
4|user     |         _removedConnection: false,
4|user     |         _removedContLen: false,
4|user     |         _removedTE: false,
4|user     |         _contentLength: null,
4|user     |         _hasBody: true,
4|user     |         _trailer: '',
4|user     |         finished: true,
4|user     |         _headerSent: true,
4|user     |         socket: [TLSSocket],
4|user     |         connection: [TLSSocket],
4|user     |         _header: 'POST /gateway-u/ HTTP/1.1\r\nAccept: application/json, text/plain, */*\r\nx-real-scheme: http\r\nx-real-ip: 10.14.41.20\r\nx-forwarded-for: 120.52.147.42, 183.131.234.148, 10.14.41.20\r\nconnection: close\r\nx-rewrite-url: /user/member/identity?merchant_id=&app_id=&service=40\r\nx-forwarded-protocol: http\r\nvia: cn857.l1, l2eu95.l2\r\neagleeye-traceid: 77bc94d015433812505294225e\r\nali-cdn-real-port: 63315\r\nali-cdn-real-ip: 120.52.147.42\r\nali-swift-log-host: tp-pay-test.snssdk.com\r\nali-swift-stat-host: all.snssdk.com\r\nx-client-scheme: https\r\nif-none-match: "494d-EC286LmrEoWs/o84g5nFdurWUHU"\r\nuser-agent: Mozilla/5.0 (iPhone; CPU iPhone OS 11_3 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E216 CaijingStock\r\naccept-language: zh-cn\r\naccept-encoding: br, gzip, deflate\r\ncookie: hello=nijhao;wang=xinhua;tp_lang=en\r\nali-swift-wildcard-dns: all.snssdk.com\r\nali-cdn-debug-link-log: 0\r\nx-alicdn-da-via: 119.188.148.61,124.160.156.251\r\nx-ss-birth: 1543381250.581\r\nx-ss-rid: 21079016543381250581\r\nx-forwarded-proto: https\r\nx-real-port: 63315\r\nx-toutiao-lb-ip: 36.110.186.15\r\nX-TT-LOGID: 20181128130050010008023075154F75\r\nContent-Type: application/x-www-form-urlencoded\r\ndevinfo: {"req_ip":"","ua":"WAP","lang":"zh-Hans"}\r\nContent-Length: 195\r\nHost: tp-pay-test.snssdk.com\r\n\r\n',
4|user     |         _onPendingData: [Function: noopPendingOutput],
4|user     |         agent: [Agent],
4|user     |         socketPath: undefined,
4|user     |         timeout: undefined,
4|user     |         method: 'POST',
4|user     |         path: '/gateway-u/',
4|user     |         _ended: true,
4|user     |         res: [IncomingMessage],
4|user     |         aborted: undefined,
4|user     |         timeoutCb: null,
4|user     |         upgradeOrConnect: false,
4|user     |         parser: null,
4|user     |         maxHeadersCount: null,
4|user     |         _redirectable: [Writable],
4|user     |         [Symbol(isCorked)]: false,
4|user     |         [Symbol(outHeadersKey)]: [Object] },

**Comment by chobits** [comment]
此为aliyun CDN自己定义的功能，工单提给aliyun CDN，此问题与本项目无关。
