### ISSUE TITLE
reload cpu 100% bugfix

### ISSUE THREAD

**Issue by FengXingYuXin** [alibaba/tengine#1136]
我们生产环境长链接集群链接量有38w，reload时，因为worker进程每个interval都会遍历空闲链接，导致cpu直接飙到了100%，针对这个问题Nginx官方已经在1.9.4版本修复，https://github.com/alibaba/tengine/issues/595 中也有提到，但没下文了。。参考官方的处理方式，在https://github.com/alibaba/tengine/pull/1135 中提了PR，实际效果：把持续的100%优化成一个小的抖动，如下图所示：
![image](https://user-images.githubusercontent.com/9688486/49458241-61060e80-f827-11e8-9df4-accb7fe418db.png)

**Comment by FengXingYuXin** [comment]
关于reload相关topic，如果Tengine用户遇到worker进程长时间处于shutting down的问题，可以参考官方Nginx 1.11.1新增的worker_shutdown_timeout指令的实现解决

**Comment by wangfakang** [comment]
@FengXingYuXin reload worker处于shutting down的问题，Tengine提供的有 force_exit指令（Tengine-2.2.0版本），详细如文档描述： http://tengine.taobao.org/document_cn/core_cn.html

**Comment by chobits** [comment]
最新master分支版本已经修复

# New version release

Hi all, current master is based on nginx 1.15.2, it has stream module. Please check it!
We'll release new version 2.3.x (based on nginx 1.15.x) soon.

# WARNING

Note that this version is slightly not backwards compatible, some tengine features have been replaced by nginx offical.  check the following list:
1. `--with-http_slice_module` configure option now works for [nginx slice module](http://nginx.org/en/docs/http/ngx_http_slice_module.html). Use `--add-module=modules/ngx_http_slice_module` for original [tengine slice module](http://tengine.taobao.org/document/http_slice.html).
2. Removed Tengine DSO feature, use [nginx dynamic modules feature](https://www.nginx.com/resources/wiki/extending/converting/) instead.
3. Removed `reuse_port` directive in `event {}` block, use [`listen .. reuseport;` directive](http://nginx.org/en/docs/http/ngx_http_core_module.html#listen) instead.
4. Extract the tengine modules to modules dir, if you need to use that module then use `--add-module=modules/xxx_module_name` way to compile.
5. The request counting logic for limit_req is consistent with the Nginx official. Now requests with all empty variable in `limit_req_zone` are not accounted. Original tengine does not account requests with any empty variable.
