### ISSUE TITLE
tengine-2.2.3丢失ngx_slab_sizes_init()函数调用，导致共享内存page耗尽，提示no memory

### ISSUE THREAD

**Issue by alvin008** [alibaba/tengine#1144]

**Comment by alvin008** [comment]
需要在nginx.c中，ngx_os_init成功后调用该函数，不然每次分配内存都会分配一个页

**Comment by alvin008** [comment]
请教下阿里高手，为什么在nginx.c中不去初始化slab相关的参数，如果不初始化会明显浪费共享内存，而没有用到slab的核心机制？

**Comment by yunoasgit** [comment]
Does the small tengine2.2.3 check_shm_size setting cause 502!
Compared with Tengine-2.1.2 stable version, memory consumption is 10 times higher!

**Comment by wangfakang** [comment]
the latest version of Tengine has been updated the logical.
if it's still a question plz reopen.
