### ISSUE TITLE
http2长连接导致reload操作不生效

### ISSUE THREAD

**Issue by ninglianjie** [alibaba/tengine#1146]
tengine版本:
Tengine version: Tengine/2.2.3 (nginx/1.8.1)
built by gcc 4.4.7 20120313 (Red Hat 4.4.7-23) (GCC)
TLS SNI support enabled

问题描述:
在执行./nginx -s reload操作时, 原来的线程不能正常shutdown, 从日志中发现, 有大量的HTTP/2.0连接. 

root      64268      1  0 20:38 ?        00:00:00 nginx: master process ./nginx -s start
nobody    64269  64268  2 20:38 ?        00:00:22 nginx: worker process is shutting down
nobody    64270  64268  3 20:38 ?        00:00:29 nginx: worker process is shutting down
nobody    64271  64268  4 20:38 ?        00:00:46 nginx: worker process is shutting down
nobody    64272  64268  3 20:38 ?        00:00:34 nginx: worker process is shutting down
nobody    65185  64268  2 20:52 ?        00:00:02 nginx: worker process
nobody    65186  64268  5 20:52 ?        00:00:04 nginx: worker process
nobody    65187  64268  3 20:52 ?        00:00:02 nginx: worker process
nobody    65188  64268  3 20:52 ?        00:00:03 nginx: worker process

**Comment by duantianliao** [comment]
这个是正常的，因为正常的连接还未释放，如果你要强制中断，你需要杀shutting down的进程

**Comment by wangfakang** [comment]
可配置使用这个命令： force_exit   exit_time;
详细文档参考： http://tengine.taobao.org/document/core.html

**Comment by wangfakang** [comment]
if it's still a question, plz reopen.
