### ISSUE TITLE
目前2.2.3是否支持SSH端口转发

### ISSUE THREAD

**Issue by lev-gc** [alibaba/tengine#1158]
在NginX上是使用stream模块进行ssh的内网端口转发，迁移过来发现不可用，看了一下issues了解到没有更新到这部分，请问有别的用法可以代替stream进行SSH端口转发？

**Comment by meigea** [comment]
是什么意思， 是把这个 http的端口发送到另外一个主机的某个端口？ 这个是无视应用层的啊；’

**Comment by lev-gc** [comment]
场景就是通过一台能连接外网的服务器转发ssh请求连接到不能接外网的其他服务器。之前都是用NginX的stream模块（dso）做的。

**Comment by MengqiWu** [comment]
下一个版本会合并Nginx官方的stream，稍等一段时间

**Comment by lev-gc** [comment]
Nice！
