### ISSUE TITLE
为什么配置了proxy_next_upstream off;从日志中发现还有重复发送的现象?请大神指点，谢谢！

### ISSUE THREAD

**Issue by maronggang** [alibaba/tengine#1160]
Tengine version: Tengine/2.2.1 (nginx/1.8.1)
nginx的日志为：
/?????/queryCardPaymentAccInfo|internal.nginx.com|internal.nginx.com|?.?.?.?|31019|-|10/Jan/2019:08:44:01 +0800|POST /?????/queryCardPaymentAccInfo HTTP/1.0|200|-, 0.043|481|-|Apache CXF 3.0.1|-|internal.nginx.com|-|-|172.168.120.181:7322, 172.168.120.182:7322

$status 为200，就出现1次是OK的。
$upstream_response_time为-, 0.043，出现了2次，其中有一次是 -
$upstream_addr为172.168.120.181:7322, 172.168.120.182:7322，出现了2次
截图为location相关配置
![20190110](https://user-images.githubusercontent.com/24536376/50940371-99021080-14bb-11e9-80e8-79db878c209d.png)

请大神指点，谢谢！

**Comment by MengqiWu** [comment]
有没有配置error

**Comment by maronggang** [comment]
有配置error_page，该如何排查该问题呢？
        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   html;
        }
        error_page   400 402 403 404  /40x.html;
        location = /40x.html {
            root   html;
        }

**Comment by wangfakang** [comment]
@maronggang  you could try to configure  `retry_cached_connection off; `  at the http (or server、location
）block .
