### ISSUE TITLE
Tengine 2.2.3 Http2 上传文件504. 

### ISSUE THREAD

**Issue by zhangshunbao** [alibaba/tengine#1161]
Tengine 2.2.3 Http2 上传文件时有504，用 http1.1正常。
换成原生Nginx 1.14也正常。

**Comment by lazyfighter** [comment]
请问解决了吗 我们也碰到上传文件失败

**Comment by chobits** [comment]
# New version release

Hi all, current master is based on nginx 1.15.2, it has stream module. Please check it!
We'll release new version 2.3.x (based on nginx 1.15.x) soon.

# WARNING

Note that this version is slightly not backwards compatible, some tengine features have been replaced by nginx offical.  check the following list:
1. `--with-http_slice_module` configure option now works for [nginx slice module](http://nginx.org/en/docs/http/ngx_http_slice_module.html). Use `--add-module=modules/ngx_http_slice_module` for original [tengine slice module](http://tengine.taobao.org/document/http_slice.html).
2. Removed Tengine DSO feature, use [nginx dynamic modules feature](https://www.nginx.com/resources/wiki/extending/converting/) instead.
3. Removed `reuse_port` directive in `event {}` block, use [`listen .. reuseport;` directive](http://nginx.org/en/docs/http/ngx_http_core_module.html#listen) instead.
4. Extract the tengine modules to modules dir, if you need to use that module then use `--add-module=modules/xxx_module_name` way to compile.
5. The request counting logic for limit_req is consistent with the Nginx official. Now requests with all empty variable in `limit_req_zone` are not accounted. Original tengine does not account requests with any empty variable.

**Comment by chobits** [comment]
hi @lazyfighter @zhangshunbao 可以尝试我们的最新master分支。
是否还此问题，最新版本对H2修复了上传部分逻辑（流式上传）。

**Comment by chobits** [comment]
2.3.0 has been released, please try it. I'am closing this issue.
