### ISSUE TITLE
compile error with ngx_http_dyups_module

### ISSUE THREAD

**Issue by binooetomo** [alibaba/tengine#1168]
dear all

I try to compile tengine with dynamic upstream.
Per the compilation part of https://github.com/alibaba/tengine/blob/master/docs/modules/ngx_http_dyups_module.md

but I got

[root@localhost tengine]# ./configure --with-http_dyups_module --with-http_dyups_lua_api
./configure: error: invalid option "--with-http_dyups_module"

kindly please tell me how to fix this

sincerely

-bino-

**Comment by binooetomo** [comment]
Sorry.

Please ignore this issue.

Fixed by reading curl -X delete -d "server 127.0.0.1:8089" 127.0.0.1:8081/upstream/dyhost

**Comment by binooetomo** [comment]
Sorry.
Please ignore this issue.

Fixed by reading https://github.com/alibaba/tengine/issues/1056#issuecomment-395389212

**Comment by chobits** [comment]
resolved
