### ISSUE TITLE
tengine的健康检查功能优势在哪里

### ISSUE THREAD

**Issue by chenqinhuang** [alibaba/tengine#1170]
tengine提供的ngx_http_upstream_check_module模块，相较于ngnix自带的健康检查功能，区别在哪，或者说是做了哪些优化吗？

**Comment by itchenyi** [comment]
nginx 并没有自带 ”健康检查“， 而是在某节点出现异常时进行切换

health_check_module 则是主动发起请求，去探测是否符合配置预期

**Comment by chobits** [comment]
ngx_http_upstream_check_module此功能为tengine独立实现的主动健康检查功能，和nginx默认的被动健康检查不同。该功能基本是线上系统必备功能，此功能优点是可以在请求访问异常的后端服务前把其摘除，最大限度保证线上请求的可用性。

BTW，此功能nginx plus商业版也具备，但是闭源收费的。
