### ISSUE TITLE
Bugs found by our scanner

### ISSUE THREAD

**Issue by yuanqilbx** [alibaba/tengine#1171]
Hi, we developed a taint analysis based static analysis tool named Vanguard, which could prognosis potential vulnerabilities by identifying security-sensitive operations (e.g. divide-zero, mod-zero, array-index-access, and sensitive function calls) without proper checks for their operands.

Some code locations are listed in the following, we think these locations maybe bugs after our manual analysis. Please check them, and add precondition checks if necessary.

**Bug-1:Array index bound**
1.in function `ngx_http_upstream_save_round_robin_peer_session`,[ http/ngx_http_upstream_round_robin.c#L725](https://github.com/alibaba/tengine/blob/2.2.3/src/http/ngx_http_upstream_round_robin.c#L725)
```c++
    peer = &rrp->peers->peer[rrp->current];
```
Array expression: rrp-&gt;peers-&gt;peer[rrp-&gt;current]
		needs bound checking:
		rrp-&gt;current &lt; 1;

2.in function `ngx_http_upstream_set_round_robin_peer_session`,[http/ngx_http_upstream_round_robin.c#L689](https://github.com/alibaba/tengine/blob/2.2.3/src/http/ngx_http_upstream_round_robin.c#L689)
```c++
    peer = &rrp->peers->peer[rrp->current];
```
Array expression: rrp-&gt;peers-&gt;peer[rrp-&gt;current]
		needs bound checking:
		rrp-&gt;current &lt; 1;
		
3.in function `ngx_http_upstream_free_round_robin_peer`,[http/ngx_http_upstream_round_robin.c#L635](https://github.com/alibaba/tengine/blob/2.2.3/src/http/ngx_http_upstream_round_robin.c#L635)
```c++
    peer = &rrp->peers->peer[rrp->current];
```
Array expression: rrp-&gt;peers-&gt;peer[rrp-&gt;current]
		needs bound checking:
		rrp-&gt;current &lt; 1;

4.in function `ngx_http_auth_basic_handler`,[http/modules/ngx_http_auth_basic_module.c#L277](https://github.com/alibaba/tengine/blob/2.2.3/src/http/modules/ngx_http_auth_basic_module.c#L277)
```c++
        ngx_cpystrn(pwd.data, &buf[passwd], pwd.len + 1);
```
Array expression: buf[passwd]
		needs bound checking:
		passwd &lt; 2048;

**Bug-2:Div/mod-zero**
1.in function `ngx_hash_add_key`,[core/ngx_hash.c#L775](https://github.com/alibaba/tengine/blob/2.2.3/src/core/ngx_hash.c#L775)
```c++
    k %= ha->hsize;
```
Divisor: ha-&gt;hsize
			Result: Could be 0, Please Check.

2.in function `ngx_pipe_do_rollback`,[os/unix/ngx_pipe.c#L782](https://github.com/alibaba/tengine/blob/2.2.3/src/os/unix/ngx_pipe.c#L782)
```c++
        } else if (sb.st_ctime / rbcf->interval < rbcf->time_now / rbcf->interval) {
```
Divisor: rbcf-&gt;interval
			Result: Could be 0, Please Check.

3.in function 'ngx_ssl_get_ciphers',[event/ngx_event_openssl.c#L3945](https://github.com/alibaba/tengine/blob/2.2.3/src/event/ngx_event_openssl.c#L3945)
```c++
    n /= bytes;
```
Divisor: bytes
			Result: Could be 0, Please Check.

4.in function `ngx_http_upstream_create_round_robin_peer`,[http/ngx_http_upstream_round_robin.c#L341](https://github.com/alibaba/tengine/blob/2.2.3/src/http/ngx_http_upstream_round_robin.c#L341)
```c++
    peers->init_number = ngx_random() % peers->number;
```
Divisor: peers-&gt;number
			Result: Could be 0, Please Check.
			
5.in function `ngx_http_map`,[http/modules/ngx_http_map_module.c#L443](https://github.com/alibaba/tengine/blob/2.2.3/src/http/modules/ngx_http_map_module.c#L443)
```c++
    key %= ctx->keys.hsize;
```
Divisor: ctx-&gt;keys.hsize
			Result: Could be 0, Please Check.
			
6.in function `ngx_http_limit_req_handler`,[http/modules/ngx_http_limit_req_module.c#L419](https://github.com/alibaba/tengine/blob/2.2.3/src/http/modules/ngx_http_limit_req_module.c#L419)
```c++
        delay_time = (ngx_msec_t) delay_excess * 1000 / ctx->rate;
```
Divisor: ctx-&gt;rate
			Result: Could be 0, Please Check.
			
**Bug-3:security-sensitive functions call**
1.in function `ngx_http_trim_parse`,[http/modules/ngx_http_trim_filter_module.c#L1582](https://github.com/alibaba/tengine/blob/2.2.3/src/http/modules/ngx_http_trim_filter_module.c#L582)
```c++
 write = ngx_cpymem(write, ngx_http_trim_saved_html.data,
                                   ctx->saved_comment);
```

**Comment by MengqiWu** [comment]
can you try fix and give a pull request？

**Comment by chobits** [comment]
> 2.in function `ngx_pipe_do_rollback`,[os/unix/ngx_pipe.c#L782](https://github.com/alibaba/tengine/blob/2.2.3/src/os/unix/ngx_pipe.c#L782)

> **Bug-3:security-sensitive functions call**
1.in function `ngx_http_trim_parse`,[http/modules/ngx_http_trim_filter_module.c#L1582](https://github.com/alibaba/tengine/blob/2.2.3/src/http/modules/ngx_http_trim_filter_module.c#L582)

These two erros should be checked again by tengine developers.

Other errors are false positive, runtime nginx will not trigger the bug.

**Comment by wangfakang** [comment]
2.in function ngx_pipe_do_rollback,os/unix/ngx_pipe.c#L782
ACK

Bug-3:security-sensitive functions call
1.in function ngx_http_trim_parse,http/modules/ngx_http_trim_filter_module.c#L1582
ACK
