### ISSUE TITLE
Tengine健康检查支持自定义服务器校验状态规则吗

### ISSUE THREAD

**Issue by chenqinhuang** [alibaba/tengine#1176]
Tengine健康检查支持自定义服务器校验状态规则吗，例如响应状态码、或者响应报文之类的

**Comment by MengqiWu** [comment]
https://github.com/alibaba/tengine/blob/master/docs/modules/ngx_http_upstream_check_module_cn.md

**Comment by chobits** [comment]
think it resolved. 规则设置请参考以上文档
