### ISSUE TITLE
反向代理websocket，关闭连接出现很多close_wait状态

### ISSUE THREAD

**Issue by f4nff** [alibaba/tengine#1177]
如果并发数较大，
会出现几千甚至一万多close_wait状态，
查了一下这个肯定是程序bug，
相同的条件使用caddy反代里websocket就没有任何close_wait状态，只有time_wait，

**Comment by MengqiWu** [comment]
能否补充更多一些信息和场景，包括官方nginx是否在你的场景有类似现象？

**Comment by f4nff** [comment]
官方也存在这样的问题，你反向代理websocket，然后通过tengline发起500个并发,然后关闭发起端，然后netstat -an看看tengline这服务器有很多close_wait

**Comment by f4nff** [comment]
我用caddyserver就不会出现这问题，

**Comment by f4nff** [comment]
https://github.com/gorilla/websocket/tree/master/examples/echo

自己搞个websocket测试并发脚本，然后关闭客户端，使用tengline 反代理websocket，然后看tcp状态就是了，

**Comment by f4nff** [comment]
现在的情况是，反向代理websocket根本没法用tengline，并发数一多，就出现一万多个close_wait状态，很卡，

**Comment by f4nff** [comment]
![image](https://user-images.githubusercontent.com/19538878/53783243-c7e0b400-3f4b-11e9-821d-3605f8b94a9a.png)
经过测试，官方最新版，已经没有问题。

**Comment by f4nff** [comment]
![image](https://user-images.githubusercontent.com/19538878/53785095-4dfff900-3f52-11e9-963e-edb1676eb527.png)
最新版本的nginx没有此问题，

**Comment by chobits** [comment]
@f4nff master分支已经是最新版ngx 1.15.9，尝试前注意列表见：https://github.com/alibaba/tengine/issues/1196

**Comment by chobits** [comment]
hi @f4nff 

we have released 2.3.0, please check it:)

**Comment by wangfakang** [comment]
if it's still a question,  plz reopen.
