### ISSUE TITLE
compilation error: openssl 1.1.0j with tengine 2.2.3

### ISSUE THREAD

**Issue by Jimmy-2019** [alibaba/tengine#1186]
objs/src/event/ngx_event_openssl.o：在函数‘ngx_openssl_exit’中：
/data/tools/tengine-2.2.3/src/event/ngx_event_openssl.c:4789：对‘EVP_cleanup’未定义的引用
/data/tools/tengine-2.2.3/src/event/ngx_event_openssl.c:4791：对‘ENGINE_cleanup’未定义的引用
objs/src/event/ngx_event_openssl.o：在函数‘ngx_ssl_init’中：
/data/tools/tengine-2.2.3/src/event/ngx_event_openssl.c:156：对‘SSL_library_init’未定义的引用
/data/tools/tengine-2.2.3/src/event/ngx_event_openssl.c:157：对‘SSL_load_error_strings’未定义的引用
/data/tools/tengine-2.2.3/src/event/ngx_event_openssl.c:159：对‘OPENSSL_add_all_algorithms_noconf’未定义的引用
/data/tools/tengine-2.2.3/src/event/ngx_event_openssl.c:183：对‘SSL_get_ex_new_index’未定义的引用
/data/tools/tengine-2.2.3/src/event/ngx_event_openssl.c:190：对‘SSL_CTX_get_ex_new_index’未定义的引用
/data/tools/tengine-2.2.3/src/event/ngx_event_openssl.c:198：对‘SSL_CTX_get_ex_new_index’未定义的引用
/data/tools/tengine-2.2.3/src/event/ngx_event_openssl.c:206：对‘SSL_CTX_get_ex_new_index’未定义的引用
/data/tools/tengine-2.2.3/src/event/ngx_event_openssl.c:214：对‘SSL_CTX_get_ex_new_index’未定义的引用
/data/tools/tengine-2.2.3/src/event/ngx_event_openssl.c:222：对‘X509_get_ex_new_index’未定义的引用
/data/tools/tengine-2.2.3/src/event/ngx_event_openssl.c:229：对‘X509_get_ex_new_index’未定义的引用
/data/tools/tengine-2.2.3/src/event/ngx_event_openssl.c:237：对‘X509_get_ex_new_index’未定义的引用
objs/src/event/ngx_event_openssl.o：在函数‘ngx_ssl_create’中：
/data/tools/tengine-2.2.3/src/event/ngx_event_openssl.c:251：对‘SSLv23_method’未定义的引用
objs/src/event/ngx_event_openssl.o：在函数‘ngx_ssl_ciphers’中：
/data/tools/tengine-2.2.3/src/event/ngx_event_openssl.c:674：对‘SSL_CTX_set_tmp_rsa_callback’未定义的引用
objs/src/event/ngx_event_openssl.o：在函数‘ngx_ssl_shutdown’中：
/data/tools/tengine-2.2.3/src/event/ngx_event_openssl.c:2362：对‘SSL_state’未定义的引用
objs/src/event/ngx_event_openssl.o：在函数‘ngx_ssl_session_id_context’中：
/data/tools/tengine-2.2.3/src/event/ngx_event_openssl.c:2881：对‘EVP_MD_CTX_create’未定义的引用
/data/tools/tengine-2.2.3/src/event/ngx_event_openssl.c:2918：对‘sk_num’未定义的引用
/data/tools/tengine-2.2.3/src/event/ngx_event_openssl.c:2921：对‘sk_value’未定义的引用
/data/tools/tengine-2.2.3/src/event/ngx_event_openssl.c:2943：对‘EVP_MD_CTX_destroy’未定义的引用
/data/tools/tengine-2.2.3/src/event/ngx_event_openssl.c:2955：对‘EVP_MD_CTX_destroy’未定义的引用
objs/src/event/ngx_event_openssl_stapling.o：在函数‘ngx_ssl_stapling_issuer’中：
/data/tools/tengine-2.2.3/src/event/ngx_event_openssl_stapling.c:308：对‘sk_num’未定义的引用
/data/tools/tengine-2.2.3/src/event/ngx_event_openssl_stapling.c:314：对‘sk_value’未定义的引用
/data/tools/tengine-2.2.3/src/event/ngx_event_openssl_stapling.c:319：对‘CRYPTO_add_lock’未定义的引用
objs/src/event/ngx_event_openssl_stapling.o：在函数‘ngx_ssl_stapling_responder’中：
/data/tools/tengine-2.2.3/src/event/ngx_event_openssl_stapling.c:404：对‘sk_value’未定义的引用
collect2: 错误：ld 返回 1
make[1]: *** [objs/nginx] 错误 1
make[1]: 离开目录“/data/tools/tengine-2.2.3”
make: *** [test] 错误 2

**Comment by wangfakang** [comment]
@Jimmy-2019 you could try to (master)[https://github.com/alibaba/tengine] branch to compile new OpenSSL.

**Comment by Jimmy-2019** [comment]
> @Jimmy-2019 you could try to [master](https://github.com/alibaba/tengine) branch to compile new OpenSSL.

thank you i'll try it .

**Comment by Jimmy-2019** [comment]
> > @Jimmy-2019 you could try to [master](https://github.com/alibaba/tengine) branch to compile new OpenSSL.
> 
> thank you i'll try it .

The installation was successful, but only four files were generated. Is this normal?

**Comment by wangfakang** [comment]
current master is based on nginx 1.15.x. Please check it!
We'll release new version 2.3.x (based on nginx 1.15.x) soon.

# WARNING

Note that this version is slightly not backwards compatible, some tengine features have been replaced by nginx offical.  check the following list:
1. `--with-http_slice_module` configure option now works for [nginx slice module](http://nginx.org/en/docs/http/ngx_http_slice_module.html). Use `--add-module=modules/ngx_http_slice_module` for original [tengine slice module](http://tengine.taobao.org/document/http_slice.html).
2. Removed Tengine DSO feature, use [nginx dynamic modules feature](https://www.nginx.com/resources/wiki/extending/converting/) instead.
3. Removed `reuse_port` directive in `event {}` block, use [`listen .. reuseport;` directive](http://nginx.org/en/docs/http/ngx_http_core_module.html#listen) instead.
4. Extract the tengine modules to modules dir, if you need to use that module then use `--add-module=modules/xxx_module_name` way to compile.
5. The request counting logic for limit_req is consistent with the Nginx official. Now requests with all empty variable in `limit_req_zone` are not accounted. Original tengine does not account requests with any empty variable.

**Comment by chobits** [comment]
hi @Jimmy-2019 

> The installation was successful, but only four files were generated. Is this normal?

**Comment by Jimmy-2019** [comment]
> 嗨@ Jimmy-2019
> 
> > 安装成功，但只生成了四个文件。这是正常的吗？
> 
> 你能展示这四个文件的文件名吗？

yes.it's conf sbin html and logs

**Comment by chobits** [comment]
hi @Jimmy-2019 

It's in line with expectations.

The `modules/` and `include/` directories are  deprecated.

**Comment by chobits** [comment]
Think it resolved, I'm closing this issue. Thanks for your report.
