### ISSUE TITLE
wtf?not supporting ngx_brotli?it's 2019!

### ISSUE THREAD

**Issue by cnrting** [alibaba/tengine#1198]
adding module in /root/tengine-2.2.3/modules/ngx_brotli
./configure: error: Brotli module requires recent version of NGINX (1.9.11+).

build on Linux ae2a 3.10.0-957.1.3.el7.x86_64

**Comment by wangfakang** [comment]
@cnrting  Because the Brotli  module relies on the Nginx core version, you could try to Tengine master [branch](https://github.com/alibaba/tengine)  `Note: which has been upgraded to Nginx official 1.15.9` . Please refer to https://github.com/alibaba/tengine/issues/1196 for more details.

**Comment by chobits** [comment]
hi @cnrting 

Can it work with Tengine latest master branch?

**Comment by chobits** [comment]
We have checked lastest master branch, it can work. Please check it. I'm closing this issue.

Feel free to reopen if you have any problem.

**Comment by cnrting** [comment]
hello @chobits ,branch version is still 2.2.2?! not 2.2.3?

[root@ae2a tengine]# nginx -V
Tengine version: Tengine/2.2.2 (nginx/1.15.9)
built by gcc 4.8.5 20150623 (Red Hat 4.8.5-36) (GCC) 
built with OpenSSL 1.0.2k-fips  26 Jan 2017
TLS SNI support enabled
configure arguments: --with-http_realip_module --with-http_v2_module --add-module=/root/tengine/modules/ngx_brotli --add-module=/root/tengine-2.2.3/modules/headers-more-nginx-module-0.33

**Comment by chobits** [comment]
hi @cnrting 

> hello @chobits ,branch version is still 2.2.2?! not 2.2.3?

It doesn’t matter.

We still have a new feature to add tengine 2.3.x. On completion of all features merged, we'll add version-bump-to-2.3.x commit.

**Comment by meilihao** [comment]
Use `https://github.com/eustas/ngx_brotli` with Tengine-2.3.1 is ok:
```
$ ./nginx -V
Tengine version: Tengine/2.3.1
nginx version: nginx/1.16.0
built by gcc 9.1.0 (GCC) 
built with OpenSSL 1.1.0j  20 Nov 2018
TLS SNI support enabled
configure arguments: --with-cc=/usr/local/gcc-9.1/bin/gcc-9.1 --with-jemalloc=/home/chen/test/jemalloc-5.2.0 --add-module=/home/chen/test/ngx_brotli
```
> brotli's version is to 78e7bbc.

resp:
```
HTTP/1.1 200 OK
Server: Tengine/2.3.1
Date: Wed, 10 Jul 2019 07:22:49 GMT
Content-Type: text/html
Last-Modified: Wed, 10 Jul 2019 06:56:21 GMT
Transfer-Encoding: chunked
Connection: keep-alive
ETag: W/"5d258c15-22b"
Content-Encoding: br
```

**Comment by meilihao** [comment]
By the way: [google/ngx_brotli is dead](https://github.com/google/ngx_brotli/issues/62) and [eustas is primary contributor to google/brotli](https://github.com/NixOS/nixpkgs/pull/34943).

**Comment by chobits** [comment]
> By the way: [google/ngx_brotli is dead](https://github.com/google/ngx_brotli/issues/62) and [eustas is primary contributor to google/brotli](https://github.com/NixOS/nixpkgs/pull/34943).

Thank you for letting us know.
