### ISSUE TITLE
compilation error: openssl 1.1.1b with tengine 2.3.0(master)

### ISSUE THREAD

**Issue by yunoasgit** [alibaba/tengine#1200]
Compile conf
./configure --prefix=/usr/local/tengine2.3.0 --user=www --group=www --with-openssl=../openssl-1.1.1b 

Compile error
Openssl-1.1.1b openssl-1.1.1a openssl-1.1.1 are all wrong
		
		-o objs/src/core/ngx_regex.o \
		src/core/ngx_regex.c
		src/event/ngx_event_openssl.c: In function ‘ngx_ssl_free_buffer’:
		src/event/ngx_event_openssl.c:2986: error: invalid type argument of ‘->’ (have ‘int’)
		src/event/ngx_event_openssl.c:2987: error: invalid type argument of ‘->’ (have ‘int’)
		src/event/ngx_event_openssl.c:2988: error: invalid type argument of ‘->’ (have ‘int’)
		make[1]: *** [objs/src/event/ngx_event_openssl.o] Error 1
		make[1]: *** Waiting for unfinished jobs....
		make[1]: Leaving directory `/usr/local/tengine-2.3.0'
		make: *** [build] Error 2
		
compilation error: openssl 1.1.1b with tengine 2.3.0(master)

**Comment by wangfakang** [comment]
Thanks for your report. you can try it https://github.com/alibaba/tengine/pull/1202 .


fixed as follows:

```
diff --git a/src/event/ngx_event_openssl.c b/src/event/ngx_event_openssl.c
index b03957af..e04b11bb 100644
--- a/src/event/ngx_event_openssl.c
+++ b/src/event/ngx_event_openssl.c
@@ -2982,13 +2982,6 @@ ngx_ssl_free_buffer(ngx_connection_t *c)
             c->ssl->buf->start = NULL;
         }
     }
-#if !defined(OPENSSL_IS_BORINGSSL) && (OPENSSL_VERSION_NUMBER >= 0x10101000L)
-    if (c->ssl->early_buf && c->ssl->early_buf->start) {
-        if (ngx_pfree(c->pool, c->ssl->early_buf->start) == NGX_OK) {
-            c->ssl->early_buf->start = NULL;
-        }
-    }
-#endif
 }
```
