### ISSUE TITLE
Does the small tengine2.2.3 proxy_cache_path keys_zone= setting cause 500!

### ISSUE THREAD

**Issue by yunoasgit** [alibaba/tengine#1201]
2.2.3 conf:
        proxy_cache_path /x_cache levels=1:2 keys_zone=x_cache:999m inactive=30d max_size=999m;
Otherwise, an error will be prompted.And 500 status code!

		01:43:57 [alert] 18053#0: could not allocate node in cache keys zone "x_cache"
		11:58:09 [crit] 18055#0: unlink() "/xxx/ada838b1ff2c6a8cef44815434dea094" failed (2: No such file or directory)
		22:43:57 [alert] 18053#0: could not allocate node in cache keys zone "xx_cache"
		14:11:14 [alert] 18054#0: could not allocate node in cache keys zone "xxx_cache"
		14:41:39 [alert] 18051#0: could not allocate node in cache keys zone "xxxx_cache"
		20:09:47 [crit] 18055#0: unlink() "/xxx/a4dacd485852db670e476b3e27b90495" failed (2: No such file or directory)
		03:49:01 [crit] 18055#0: unlink() "/xxx/94f4f6a02474b11be2e08ab9e7fff1d5" failed (2: No such file or directory)
		11:48:38 [alert] 18053#0: could not allocate node in cache keys zone "xxxxx_cache"
		13:31:02 [crit] 18053#0: unlink() "/xxx/9ccc29e71cb6435a644cf15e9d93a657" failed (2: No such file or directory)
		16:50:21 [crit] 18055#0: unlink() "/xxx/f7db15a73cf8404598b7b352f7e8c2d5" failed (2: No such file or directory)

Contrast 2.1.2 conf
Error is normal and there will be no errors. Notice that it's 99M, or even smaller.
        proxy_cache_path /x_cache levels=1:2 keys_zone=x_cache:99m inactive=30d max_size=999m; 

Compared with Tengine-2.1.2 stable version, memory consumption is 10 times higher!

@chobits @wangfakang Ask for help
Thank you.

**Comment by wangfakang** [comment]
@yunoasgit   we have merged nginx 1.15.9 into latest master, you can try it. Please refer to https://github.com/alibaba/tengine/issues/1196

**Comment by yunoasgit** [comment]
Thanks very much!

Prepare for memory consumption comparison tests
2.1.2 and 2.3.0master

**Comment by wangfakang** [comment]
@yunoasgit the problem been checked succ ?

**Comment by wangfakang** [comment]
if it's still a question plz reopen.
