### ISSUE TITLE
compilation error: ngx_http_upstream_keepalive_module with tengine 2.3.0(master) 

### ISSUE THREAD

**Issue by yunoasgit** [alibaba/tengine#1203]
Compile conf
./configure --prefix=/usr/local/tengine2.3.0 --user=www --group=www --with-openssl=../openssl-1.1.1b  --add-dynamic-module=./modules/ngx_http_upstream_keepalive_module 

Compile error

	objs/addon/ngx_http_upstream_keepalive_module/ngx_http_upstream_keepalive_module.o \
	objs/ngx_modules.o \
	-ldl -lrt -lpthread -lcrypt -lpcre ../openssl-1.1.1b/.openssl/lib/libssl.a ../openssl-1.1.1b/.openssl/lib/libcrypto.a -ldl -lpthread -lz \
	-Wl,-E
	objs/addon/ngx_http_upstream_keepalive_module/ngx_http_upstream_keepalive_module.o:(.data+0x0): multiple definition of `ngx_http_upstream_keepalive_module'
	objs/src/http/modules/ngx_http_upstream_keepalive_module.o:(.data+0x0): first defined here
	collect2: ld returned 1 exit status
	make[1]: *** [objs/nginx] Error 1
	make[1]: Leaving directory `/usr/local/tengine2.3.0'
	make: *** [build] Error 2

Change -lpthread to -pthread
Cannot pass

	objs/addon/ngx_http_upstream_keepalive_module/ngx_http_upstream_keepalive_module.o \
	objs/ngx_modules.o \
	-ldl -lrt -pthread -lcrypt -lpcre ../openssl-1.1.1b/.openssl/lib/libssl.a ../openssl-1.1.1b/.openssl/lib/libcrypto.a -ldl -pthread -lz \
	-Wl,-E
	objs/addon/ngx_http_upstream_keepalive_module/ngx_http_upstream_keepalive_module.o:(.data+0x0): multiple definition of `ngx_http_upstream_keepalive_module'
	objs/src/http/modules/ngx_http_upstream_keepalive_module.o:(.data+0x0): first defined here
	collect2: ld returned 1 exit status
	make[1]: *** [objs/nginx] Error 1
	make[1]: Leaving directory `/usr/local/tengine2.3.0'
	make: *** [build] Error 2

help,Thank you.

**Comment by chobits** [comment]
hi @yunoasgit

Added `--without-http_keepalive_module` option to your `./configure` command.

`modules/ngx_http_upstream_keepalive_module` is enhancement of `src/http/modules/ngx_http_upstream_keepalive_module`. If you want `modules/ngx_http_upstream_keepalive_module`, you should disable `src/http/modules/ngx_http_upstream_keepalive_module` with `--without-http_keepalive_module` configuration option.

**Comment by yunoasgit** [comment]
Thank you for your answer.

./configure: error: invalid option "--without-http_keepalive_module"

**Comment by chobits** [comment]
hi @yunoasgit 

this one: ` --without-http_upstream_keepalive_module`

**Comment by yunoasgit** [comment]
Thank you for your answer.

Have passed

**Comment by chobits** [comment]
added configuration checking for module conflict, see https://github.com/alibaba/tengine/pull/1204

**Comment by chobits** [comment]
resolved, I'am closing this issue.
