### ISSUE TITLE
宝塔环境中，使用ssl/https时server_tag和trim功能均失效，http时正常

### ISSUE THREAD

**Issue by KEN-studio** [alibaba/tengine#1206]
宝塔环境中，使用ssl/https时server_tag和trim功能均失效，http时正常。
环境为宝塔6.8中安装的tengine 2.2.3

**Comment by wangfakang** [comment]
@KEN-studio  下载了2.2.3版本，进行了本地编译测试server_tag和trim功能都可以正常运行，如下所示：

server_tag测试：
![image](https://user-images.githubusercontent.com/8215757/54276631-c016b480-45c8-11e9-99bb-96840e9ab3c1.png)

trim模块测试：
![image](https://user-images.githubusercontent.com/8215757/54276940-7ed2d480-45c9-11e9-897a-e6d79dbbf236.png)

另外trim模块生效与否是和响应的content_type以及响应状态码有关的（对于响应非200的会跳过），详细请参考[trim模块文档](http://tengine.taobao.org/document_cn/http_trim_filter_cn.html) .

**Comment by wangfakang** [comment]
BTW 

我们近期合并了Nginx官方1.15.9版本代码到Tengine master分支，可以先尝鲜使用master分支代码做测试（若上生产使用请一定要做好灰度验证、并阅读相关注意列表）。同时我们最近也会正式发布Tengine-2.3.x版本，欢迎使用，如有任何问题请随时反馈，谢谢。


# 警告

本次Tengine升级core代码到官方Nginx 1.15.9版本，由于其部分功能Nginx官方当前已经具备、所以本次直接弃用Tengine自身实现的部分配置指令，具体不兼容列表如下：

 1. 废弃Tengine自身实现的reuse_port指令，使用Nginx官方的reuseport。升级方法：将events配置块里面的reuse_port on|off注释掉，在对应的监听端口后面加reuseport参数、详细参考[文档](https://www.nginx.com/blog/socket-sharding-nginx-release-1-9-1/)
 2. 废弃Tengine的dso_tool工具以及dso配置指令，若之前有使用Tengine的dso功能、则可以切换到Nginx官方的load_module指令,详细文档[参考1](http://nginx.org/en/docs/ngx_core_module.html#load_module)  和 [参考2](https://www.nginx.com/resources/wiki/extending/converting/#compiling-dynamic)
 3. 移除Tengine加强版slice模块到modules、默认使用Nginx官方slice功能，如果依然需要使用Tengine的slice则编译slice时请使用 `--add-module=modules/ngx_http_slice_module`，否则使用 `--with-http_slice_module` 编译参数
 4. Tengine自身实现的模块，当前全部剥离到modules目录下，如果需要使用那个模块、则使用`--add-module=modules/<module_name>`的方式进行编译
 5. limit_req的请求计数逻辑和官方保持一致，去除limit_req_zone中任何一个变量值为空跳过请求计数的逻辑

详细请看 https://github.com/alibaba/tengine/issues/1196

**Comment by chobits** [comment]
think it resoleved, feel free to reopen if you still have some problem
