### ISSUE TITLE
tcp集群和session同步 // session sticky support for TCP/Stream module

### ISSUE THREAD

**Issue by wangwei123** [alibaba/tengine#1208]
tengine支持TCP集群和session同步吗

**Comment by wangfakang** [comment]
@wangwei123  当前master分支是合并了Nginx-1.9.15版本，详细参考https://github.com/alibaba/tengine/issues/1196 ，其中包含`Stream`模块可用于四层负载均衡。
另外你说的session同步不知道你说的是不是这个 [session_sticky](http://tengine.taobao.org/document_cn/http_upstream_session_sticky_cn.html)功能。

**Comment by chobits** [comment]
Think it resolved.
