### ISSUE TITLE
what does ngx_proc.c file do?

### ISSUE THREAD

**Issue by chunhodong** [alibaba/tengine#1209]
In nginx, i could not find ngx_proc.c,ngx_proc.h
In tengine, what is the role of ngx_proc??

**Comment by mrpre** [comment]
@chunhodong Ngx_proc module is used to start a signal process which is different from worker process but controlled by master.   

It's pretty useful when you want do some task that takes a long time and you do not want to run it   in worker process.   

See [proc](http://tengine.taobao.org/document_cn/proc_cn.html) for more information

**Comment by yunoasgit** [comment]
https://github.com/alibaba/tengine/commits/master/src/proc/ngx_proc.h
http://tengine.taobao.org/document/proc.html

provides a mechanism to support standalone processes
you can find the sample at http://tengine.taobao.org/examples/ngx_proc_daytime_module

**Comment by chunhodong** [comment]
Thank you for your answer. I understand the answer.
