### ISSUE TITLE
 Why does not tengine merge sources after nginx1.8.1

### ISSUE THREAD

**Issue by chunhodong** [alibaba/tengine#1211]
First, I am sorry to ask a question not related to a technical issue.
There was only one place to ask questions.
If you look at the realased log on the tengine homepage(http://tengine.taobao.org/changelog.html),
tengine will no longer merge sources after nginx1.8.1(Tengine-2.2.0 [02 Dec 2016])
On the other hand, nginx has released new versions after 1.8.1(1.9,1.10,....1.15)
Previously, tengine has merged sources from nginx1.0 to nginx1.8
Does tengine have a criteria to merge nginx ??
Is it a reason for company policy ??

**Comment by mrpre** [comment]
@chunhodong 
see [issue](https://github.com/alibaba/tengine/issues/1196) for more information.
