### ISSUE TITLE
2.2.2反向代理返回域名被重写

### ISSUE THREAD

**Issue by jlnkulaohu** [alibaba/tengine#1218]
反向代理配置如下
> location /wbcdss/ {
            proxy_pass http://127.0.0.1:8040;
            proxy_set_header Host $host;
            proxy_set_header Remote_Addr $remote_addr;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

当返回非本域名下的302时候，域名被重写，日志如下：
![image](https://user-images.githubusercontent.com/4589893/54881688-45357f80-4e8d-11e9-872c-377eb23f46f8.png)

在用同样配置下在nginx-1.10.2返回没有问题。

**请教是不是我哪里配置的不太对，谢谢**

**Comment by yunoasgit** [comment]
yes.
After careful comparison, we found that,
nginx / tengine / openresty
They all have slight differences.

**Comment by jlnkulaohu** [comment]
THX
