### ISSUE TITLE
Tengine-2.3.0 (development version) has been released!

### ISSUE THREAD

**Issue by wangfakang** [alibaba/tengine#1220]
Tengine-2.3.0(开发)版本发布了！

* [下载](http://tengine.taobao.org/download/tengine-2.3.0.tar.gz)           
* [变更日志](http://tengine.taobao.org/changelog_cn.html#2_3_0)
* [release信息](https://github.com/alibaba/tengine/releases/tag/2.3.0)

# 新增如下新特性

 - 新模块[ngx_http_proxy_connect_module](http://tengine.taobao.org/document_cn/proxy_connect_cn.html)，支持HTTP的CONNECT方法，可用于正向代理场景；
 
 - [http2 server粒度控制](http://tengine.taobao.org/document_cn/http_core_cn.html) 新增http2指令，可针对listen相同端口的server进行个性化开启与关闭http2；
 
 - Stream模块支持[server_name](http://tengine.taobao.org/document_cn/stream_sni_cn.html) 指令，即同一个端口可以配置多个虚拟`server`配置块；
 
 - 加强[limit_req模块](http://tengine.taobao.org/document_cn/http_core_cn.html)功能，limit_req_zone的rate参数支持变量模式配置，可以基于请求粒度动态设置限速大小；

# 注意

本次Tengine升级core代码到官方Nginx 1.15.9版本，由于其部分功能Nginx官方当前已经具备、所以本次直接弃用Tengine自身实现的部分配置指令，具体不兼容列表如下：

 1. 废弃Tengine自身实现的reuse_port指令，使用Nginx官方的reuseport。升级方法：将events配置块里面的reuse_port on|off注释掉，在对应的监听端口后面加reuseport参数、详细参考[文档](https://www.nginx.com/blog/socket-sharding-nginx-release-1-9-1/)；
 2. 废弃Tengine的dso_tool工具以及dso配置指令，若之前有使用Tengine的dso功能、则可以切换到Nginx官方的load_module指令,详细文档[参考1](http://nginx.org/en/docs/ngx_core_module.html#load_module)  和 [参考2](https://www.nginx.com/resources/wiki/extending/converting/#compiling-dynamic)；
 3. 移除Tengine加强版slice模块到modules、默认使用Nginx官方slice功能，如果依然需要使用Tengine的slice则编译slice时请使用 `--add-module=modules/ngx_http_slice_module`，否则使用 `--with-http_slice_module` 编译参数；
 4. Tengine自身实现的模块，当前全部剥离到modules目录下，如果需要使用那个模块、则使用`--add-module=modules/<module_name>`的方式进行编译；
 5. limit_req的请求计数逻辑和官方保持一致，去除limit_req_zone中任何一个变量值为空跳过请求计数的逻辑；

 
 -------------

We are very excited to announce that Tengine-2.3.0 (development version) has
been released!

* [download](http://tengine.taobao.org/download/tengine-2.3.0.tar.gz)  
* [changelog](http://tengine.taobao.org/changelog.html#2_3_0)
* [release](https://github.com/alibaba/tengine/releases/tag/2.3.0)

# Some features are as follows

- New module [ngx_http_proxy_connect_module](http://tengine.taobao.org/document/proxy_connect.html), it supports the CONNECT HTTP method for forward proxy.

- [http2 switch](http://tengine.taobao.org/document/http_core.html) adds http2 directive to enable or disable http2 in the server block.

- Support [server_name](http://tengine.taobao.org/document/stream_sni.html) in Stream modlue, now multiple virtual server blocks could be configured on the same port.

- Enhanced limit_req_zone `rate=$<nginx_variable>` parameter of  [limit_req](http://tengine.taobao.org/document/http_limit_req.html)  module, you can set the limit rate per a request.

# WARNING

Tengine has been upgraded core files from the Nginx 1.15.9 version. Note that this version is slightly not backwards compatible, some tengine features has been replaced by nginx offical, check the following list:

1. Removed Tengine `reuse_port` directive in `event {}` block, use [`listen .. reuseport;` directive](http://nginx.org/en/docs/http/ngx_http_core_module.html#listen) instead.
2. Removed Tengine DSO feature, use [nginx dynamic modules feature](https://www.nginx.com/resources/wiki/extending/converting/#compiling-dynamic) instead.
3. Deprecated Tengine slice module, `--with-http_slice_module` configure option now works for [nginx slice module](http://nginx.org/en/docs/http/ngx_http_slice_module.html). Use `--add-module=modules/ngx_http_slice_module` for original [tengine slice module](http://tengine.taobao.org/document/http_slice.html).
4. Put all Tengine's modules to the modules directory. Use `--add-module=modules/<tengine_module_name>` to compile.
5. Changed Tengine reqstatus feature. The request counting logic for limit_req is consistent with the Nginx official. Now requests with all empty variable in `limit_req_zone` are not accounted. Original tengine does not account requests with any empty variable.

**Comment by bukebuhao** [comment]
kit-0.3.0/objs -I objs/addon/ndk -I /usr/local/luajit/include/luajit-2.0 \
                -o objs/addon/src/ngx_http_tfs.o \
                /usr/local/src/nginx-tfs-master/src/ngx_http_tfs.c
/usr/local/src/nginx-tfs-master/src/ngx_http_tfs.c: In function ‘ngx_http_tfs_process_upstream_request’:
/usr/local/src/nginx-tfs-master/src/ngx_http_tfs.c:874: error: too few arguments to function ‘c->recv_chain’
make[1]: *** [objs/addon/src/ngx_http_tfs.o] Error 1
make[1]: Leaving directory `/usr/local/src/tengine-2.3.0'
make: *** [build] Error 2


添加TFS模块编译报错

**Comment by chobits** [comment]
hi @bukebuhao 

Try TFS module in tengine/modules/ngx_http_tfs_module via `  --add-module=modules/ngx_http_tfs_module` configuration option.

**Comment by chobits** [comment]
HTTP/2.0 server tag fix: https://github.com/alibaba/tengine/pull/1221

**Comment by bukebuhao** [comment]
Thanks !

**Comment by bukebuhao** [comment]
新特性，中文的链接都是同一个，英文是正确的。
如 加强[limit_req](http://tengine.taobao.org/document_cn/http_core_cn.html)模块功能，limit_req_zone的rate参数支持变量模式配置，可以基于请求粒度动态设置限速大小；

**Comment by heidsoft** [comment]
# 2.3编译
·`modules/ngx_http_tfs_module/ngx_http_tfs_rc_server_info.c: 在函数‘ngx_http_tfs_dump_rc_info’中:
modules/ngx_http_tfs_module/ngx_http_tfs_rc_server_info.c:330:41: 错误：变量‘physical_clusters’被设定但未被使用 [-Werror=unused-but-set-variable]
     ngx_http_tfs_physical_cluster_t    *physical_clusters;
                                         ^
modules/ngx_http_tfs_module/ngx_http_tfs_rc_server_info.c:328:41: 错误：变量‘group_info’被设定但未被使用 [-Werror=unused-but-set-variable]
     ngx_http_tfs_group_info_t          *group_info;
                                         ^
cc1: all warnings being treated as errors
make[1]: *** [objs/addon/ngx_http_tfs_module/ngx_http_tfs_rc_server_info.o] 错误 1
make[1]: *** 正在等待未完成的任务....
make[1]: 离开目录“/service/software/tengine-2.3.0”
make: *** [build] 错误 2`

**Comment by chobits** [comment]
For pre-release 2.3.1, see https://github.com/alibaba/tengine/issues/1292. Closing this one.
