### ISSUE TITLE
Tengine 2.3.0 sending nginx headers

### ISSUE THREAD

**Issue by roura356a** [alibaba/tengine#1225]
I can see `server: nginx/1.15.9` when using Tengine 2.3.0. In the old versions it reported as Tengine. Is this intentional? Or just an oversight

**Comment by wangfakang** [comment]
Thanks for your report, it will be fixed in this PR https://github.com/alibaba/tengine/pull/1221.

**Comment by roura356a** [comment]
Thank you, @wangfakang !
