### ISSUE TITLE
tengine --add-dynamic-module问题

### ISSUE THREAD

**Issue by GumpSun** [alibaba/tengine#1226]
nginx支持--add-dynamic-module添加动态外部模块，tengine把他去掉了，tengine如何添加动态模块的。THX

**Comment by mrpre** [comment]
@GumpSun Pls refer to [Nginx offical page](https://www.nginx.com/resources/wiki/extending/converting/#compiling-dynamic)

**Comment by yunoasgit** [comment]
Note that all tengine modules are currently not supported dynamic loading, which needs to modify module config. Add todo tag for these feature

https://github.com/alibaba/tengine/issues/1196

---
4.Extract the tengine modules to modules dir, if you need to use that module then use --add-module=modules/<module_name> way to compile.

In fact, I can understand that I need to select the required modules at the beginning.
There is a trade-off between the two methods.
Sometimes simplicity may be more effective.

**Comment by chobits** [comment]
Will modified tengine module config next release to support dynamic loading.

**Comment by chobits** [comment]
duplicate issue with https://github.com/alibaba/tengine/issues/1223
