### ISSUE TITLE
ngx_http_upstream_check_module 模块编译的问题

### ISSUE THREAD

**Issue by RichardWong2019** [alibaba/tengine#1227]
tengine版本： Tengine-2.3.0

ngx_http_upstream_check_module 模块在新版本怎么编译进去？默认开启的模块不包含这个模块。编译参数 --with-http_upstream_check_module 又不支持

下载的源码的modules目录下，有ngx_http_upstream_check_module
modules/ngx_http_upstream_check_module

以下是默认开启的模块：
Tengine version: Tengine/2.3.0 (nginx/1.15.9)
nginx: loaded modules:
nginx:     ngx_core_module (static)
nginx:     ngx_errlog_module (static)
nginx:     ngx_conf_module (static)
nginx:     ngx_openssl_module (static)
nginx:     ngx_regex_module (static)
nginx:     ngx_events_module (static)
nginx:     ngx_event_core_module (static)
nginx:     ngx_epoll_module (static)
nginx:     ngx_procs_module (static)
nginx:     ngx_proc_core_module (static)
nginx:     ngx_http_module (static)
nginx:     ngx_http_core_module (static)
nginx:     ngx_http_log_module (static)
nginx:     ngx_http_upstream_module (static)
nginx:     ngx_http_static_module (static)
nginx:     ngx_http_autoindex_module (static)
nginx:     ngx_http_index_module (static)
nginx:     ngx_http_mirror_module (static)
nginx:     ngx_http_try_files_module (static)
nginx:     ngx_http_auth_request_module (static)
nginx:     ngx_http_auth_basic_module (static)
nginx:     ngx_http_access_module (static)
nginx:     ngx_http_limit_conn_module (static)
nginx:     ngx_http_limit_req_module (static)
nginx:     ngx_http_geo_module (static)
nginx:     ngx_http_map_module (static)
nginx:     ngx_http_split_clients_module (static)
nginx:     ngx_http_referer_module (static)
nginx:     ngx_http_rewrite_module (static)
nginx:     ngx_http_ssl_module (static)
nginx:     ngx_http_proxy_module (static)
nginx:     ngx_http_fastcgi_module (static)
nginx:     ngx_http_uwsgi_module (static)
nginx:     ngx_http_scgi_module (static)
nginx:     ngx_http_memcached_module (static)
nginx:     ngx_http_empty_gif_module (static)
nginx:     ngx_http_browser_module (static)
nginx:     ngx_http_upstream_hash_module (static)
nginx:     ngx_http_upstream_ip_hash_module (static)
nginx:     ngx_http_upstream_least_conn_module (static)
nginx:     ngx_http_upstream_random_module (static)
nginx:     ngx_http_upstream_keepalive_module (static)
nginx:     ngx_http_upstream_zone_module (static)
nginx:     ngx_http_stub_status_module (static)
nginx:     ngx_http_write_filter_module (static)
nginx:     ngx_http_header_filter_module (static)
nginx:     ngx_http_chunked_filter_module (static)
nginx:     ngx_http_range_header_filter_module (static)
nginx:     ngx_http_gzip_filter_module (static)
nginx:     ngx_http_postpone_filter_module (static)
nginx:     ngx_http_ssi_filter_module (static)
nginx:     ngx_http_charset_filter_module (static)
nginx:     ngx_http_userid_filter_module (static)
nginx:     ngx_http_headers_filter_module (static)
nginx:     ngx_http_copy_filter_module (static)
nginx:     ngx_http_range_body_filter_module (static)
nginx:     ngx_http_not_modified_filter_module (static)

**Comment by wanghu-1986** [comment]
./configure --add-module=ngx_http_upstream_check_module

**Comment by yunoasgit** [comment]
to https://github.com/alibaba/tengine/issues/1196
https://github.com/alibaba/tengine/issues/1220

**Comment by chobits** [comment]
We have put all tengine modules into `tengine-source/module` directory.

Use `--add-module=./modules/ngx_http_upstream_check_module`  instead.

**Comment by RichardWong2019** [comment]
测试了下
使用  --add-module=ngx_http_upstream_check_module 这个不行。
使用  --add-module=./modules/ngx_http_upstream_check_module 这个可以

问题解决了，谢谢大家
Thanks all
