### ISSUE TITLE
编译--add-module=./modules/ngx_http_lua_module报错

### ISSUE THREAD

**Issue by hbt0755** [alibaba/tengine#1228]
In file included from ./modules/ngx_http_lua_module/src/ngx_http_lua_script.h:11:0,
                 from ./modules/ngx_http_lua_module/src/ngx_http_lua_script.c:13:
./modules/ngx_http_lua_module/src/ngx_http_lua_common.h:20:20: 致命错误：luajit.h：没有那个文件或目录
 #include <luajit.h>

**Comment by chobits** [comment]
需要自行安装luajit库，参考  https://github.com/openresty/lua-nginx-module#installation

**Comment by chobits** [comment]
hi @hbt0755 

have you resolved this problem?

**Comment by chobits** [comment]
think it resolved.

**Comment by lastboy1228** [comment]
yum install -y luajit-devel

add configure parameter:
--add-module=modules/ngx_http_lua_module --with-luajit-inc=/usr/include/luajit-2.0 --with-luajit-lib=/usr/lib64/liblua*
