### ISSUE TITLE
Tengine's description ngx_http_dyups_module updates the new version description and new function description

### ISSUE THREAD

**Issue by yunoasgit** [alibaba/tengine#1230]
Update new version description, new feature description
http://tengine.taobao.org/document/http_dyups.html
http://tengine.taobao.org/document_cn/http_dyups_cn.html
ngx_http_dyups_module.me https://github.com/yzprofile/ngx_http_dyups_module 

Thank you very much.

**Comment by chobits** [comment]
hi @yunoasgit 

I'am closing this issue, it will be fixed in https://github.com/alibaba/tengine/pull/1278

**Comment by chobits** [comment]
Has been fixed in #1278 (merged)
