### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by sunaihui** [alibaba/tengine#1232]
http {
     **lua_shared_dict dogs 10m;**
     ...
 }

加入这个参数 测试配置文件会报
nginx -t
nginx: the configuration file /usr/local/nginx/conf/nginx.conf syntax is ok
Segmentation fault

**Comment by wangfakang** [comment]
@sunaihui 请提供一个最小可复现的配置，我本地使用Tengine-2.3.0测试没有这个问题。另外提供下:
`./nginx -V` 的输出信息。

**Comment by sunaihui** [comment]
user  www;
worker_processes  auto;
worker_cpu_affinity auto;

#error_log  logs/error.log;
#error_log  logs/error.log  notice;
#error_log  logs/error.log  info;
#error_log  "pipe:rollback logs/error_log interval=1d baknum=7 maxsize=2G";

#pid        logs/nginx.pid;


events {
    worker_connections  1024;
}

# load modules compiled as Dynamic Shared Object (DSO)
#
#dso {
#    load ngx_http_fastcgi_module.so;
#    load ngx_http_rewrite_module.so;
#}

http {
    include       mime.types;
    default_type  application/octet-stream;

    #log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
    #                  '$status $body_bytes_sent "$http_referer" '
    #                  '"$http_user_agent" "$http_x_forwarded_for"';

    #access_log  logs/access.log  main;
    #access_log  "pipe:rollback logs/access_log interval=1d baknum=7 maxsize=2G"  main;
    access_log off;

    sendfile        on;
    #tcp_nopush     on;

    #keepalive_timeout  0;
    keepalive_timeout  65;
    server_tokens  off;
    gzip  on;

    lua_shared_dict limit 10m;
    lua_package_path '/usr/local/nginx/conf/waf/?.lua';
    init_by_lua_file  /usr/local/nginx/conf/waf/init.lua; 
    access_by_lua_file /usr/local/nginx/conf/waf/waf.lua;

**Comment by sunaihui** [comment]
Tengine version: Tengine/2.3.0 (nginx/1.15.9)
built by gcc 4.8.5 20150623 (Red Hat 4.8.5-36) (GCC)
built with OpenSSL 1.1.1b  26 Feb 2019
TLS SNI support enabled
configure arguments: --with-http_v2_module --with-http_realip_module --with-http_gzip_static_module --with-http_mp4_module --add-module=/root/ngx_brotli --with-openssl=/root/openssl-1.1.1b --with-openssl-opt=enable-tls1_3 --add-module=/root/ngx_devel_kit --with-http_lua_module --with-luajit-inc=/usr/local/include/luajit-2.1 --with-luajit-lib=/usr/lib64

**Comment by mrpre** [comment]
@sunaihui 
执行 `sudo gdb --args nginx -t`进入gdb环境  然后依次执行`r`+回车以及`bt`+回车，把shell输出的结果贴一下。退出然后按`q`+回车即可。

**Comment by sunaihui** [comment]
@mrpre 
[root@1 ~]# gdb --args nginx -t
GNU gdb (GDB) Red Hat Enterprise Linux 7.6.1-114.el7
Copyright (C) 2013 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-redhat-linux-gnu".
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>...
Reading symbols from /usr/local/nginx/sbin/nginx...done.
(gdb) r
Starting program: /usr/local/bin/nginx -t
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
nginx: the configuration file /usr/local/nginx/conf/nginx.conf syntax is ok

Program received signal SIGSEGV, Segmentation fault.
0x00007ffff72207ed in lua_pushfstring () from /lib64/libluajit-5.1.so.2
Missing separate debuginfos, use: debuginfo-install glibc-2.17-260.el7_6.3.x86_64 libgcc-4.8.5-36.el7_6.1.x86_64 nss-softokn-freebl-3.36.0-5.el7_5.x86_64 pcre-8.32-17.el7.x86_64 zlib-1.2.7-18.el7.x86_64
(gdb) bt
#0  0x00007ffff72207ed in lua_pushfstring () from /lib64/libluajit-5.1.so.2
#1  0x00007ffff7229e7d in luaL_loadfilex () from /lib64/libluajit-5.1.so.2
#2  0x000000000056634d in ngx_http_lua_init_by_file (log=0xb408e8, lmcf=<optimized out>, L=0x0) at modules/ngx_http_lua_module/src/ngx_http_lua_initby.c:36
#3  0x000000000056374f in ngx_http_lua_shared_memory_init (shm_zone=<optimized out>, data=<optimized out>) at modules/ngx_http_lua_module/src/ngx_http_lua_api.c:203
#4  0x00000000004747ed in ngx_init_cycle (old_cycle=old_cycle@entry=0x7fffffffe290) at src/core/ngx_cycle.c:533
#5  0x000000000046183c in main (argc=<optimized out>, argv=<optimized out>) at src/core/nginx.c:320

**Comment by sunaihui** [comment]
> @mrpre
> [root@1 ~]# gdb --args nginx -t
> GNU gdb (GDB) Red Hat Enterprise Linux 7.6.1-114.el7
> Copyright (C) 2013 Free Software Foundation, Inc.
> License GPLv3+: GNU GPL version 3 or later http://gnu.org/licenses/gpl.html
> This is free software: you are free to change and redistribute it.
> There is NO WARRANTY, to the extent permitted by law. Type "show copying"
> and "show warranty" for details.
> This GDB was configured as "x86_64-redhat-linux-gnu".
> For bug reporting instructions, please see:
> http://www.gnu.org/software/gdb/bugs/...
> Reading symbols from /usr/local/nginx/sbin/nginx...done.
> (gdb) r
> Starting program: /usr/local/bin/nginx -t
> [Thread debugging using libthread_db enabled]
> Using host libthread_db library "/lib64/libthread_db.so.1".
> nginx: the configuration file /usr/local/nginx/conf/nginx.conf syntax is ok
> 
> Program received signal SIGSEGV, Segmentation fault.
> 0x00007ffff72207ed in lua_pushfstring () from /lib64/libluajit-5.1.so.2
> Missing separate debuginfos, use: debuginfo-install glibc-2.17-260.el7_6.3.x86_64 libgcc-4.8.5-36.el7_6.1.x86_64 nss-softokn-freebl-3.36.0-5.el7_5.x86_64 pcre-8.32-17.el7.x86_64 zlib-1.2.7-18.el7.x86_64
> (gdb) bt
> #0 0x00007ffff72207ed in lua_pushfstring () from /lib64/libluajit-5.1.so.2
> #1 0x00007ffff7229e7d in luaL_loadfilex () from /lib64/libluajit-5.1.so.2
> #2 0x000000000056634d in ngx_http_lua_init_by_file (log=0xb408e8, lmcf=, L=0x0) at modules/ngx_http_lua_module/src/ngx_http_lua_initby.c:36
> #3 0x000000000056374f in ngx_http_lua_shared_memory_init (shm_zone=, data=) at modules/ngx_http_lua_module/src/ngx_http_lua_api.c:203
> #4 0x00000000004747ed in ngx_init_cycle (old_cycle=old_cycle@entry=0x7fffffffe290) at src/core/ngx_cycle.c:533
> #5 0x000000000046183c in main (argc=, argv=) at src/core/nginx.c:320

**Comment by mrpre** [comment]
@wangfakang https://github.com/openresty/lua-nginx-module/issues/1462 rc4的问题，rc5解决了。看是不是升级lua module
