### ISSUE TITLE
我通过tengine加载lua模块，然后反向代理了两个ws，连接ws的时候access.log日志中没有记录，但是断开ws时，access.log却有记录

### ISSUE THREAD

**Issue by xll970211** [alibaba/tengine#1235]

**Comment by xll970211** [comment]
附上我的配置文件，我反向代理代理的是两个ws，连接ws的时候没有日志记录，但是断开的时候却有记录
worker_processes  auto;
worker_cpu_affinity auto;

error_log  logs/error.log crit;

pid        logs/nginx.pid;

worker_rlimit_nofile 51200;

events {
    worker_connections  51200;
    multi_accept off;
    accept_mutex off;
}



http {
    include       mime.types;
    default_type  application/octet-stream;

    charset utf-8;

    server_names_hash_bucket_size 128;
    client_header_buffer_size 32k;
    large_client_header_buffers 4 32k;
    client_max_body_size 50m;    

    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';
  


    access_log  logs/access.log  main;

    sendfile        on;

    sendfile_max_chunk 512k;
    keepalive_timeout  65;


    tcp_nopush          on; 
    fastcgi_connect_timeout 300;
    fastcgi_send_timeout 300;
    fastcgi_read_timeout 300;
    fastcgi_buffer_size 64k;
    fastcgi_buffers 4 64k;
    fastcgi_busy_buffers_size 128k;
    fastcgi_temp_file_write_size 256k;    

    gzip on;
    gzip_min_length  1k;
    gzip_buffers     4 16k;
    gzip_http_version 1.1;
    gzip_comp_level 2;
    gzip_types     text/plain application/javascript application/x-javascript text/javascript text/css application/xml application/xml+rss;
    gzip_vary on;
    gzip_proxied   expired no-cache no-store private auth;
    gzip_disable   "MSIE [1-6]\.";

    server_tokens off;
    
    map $http_upgrade $connection_upgrade {
        default upgrade;
        ''      close;
    }

    lua_package_path "/opt/nginx/conf/waf/?.lua";
    lua_shared_dict limit 10m;
    init_by_lua_file  /opt/nginx/conf/waf/init.lua; 
    access_by_lua_file /opt/nginx/conf/waf/waf.lua;

    
    upstream blue_green {
        server 127.0.0.1:8899;
        server 192.168.1.180:8080;
    }

    server {
        listen       8445;
	
	location / {
	    proxy_set_header Upgrade $http_upgrade;
	    proxy_set_header Connection $connection_upgrade;
	    proxy_pass http://blue_green;
	    proxy_set_header  X-Forwarded-For $proxy_add_x_forwarded_for;
	    proxy_set_header Host $host;
	    proxy_set_header X-Real-IP $remote_addr;
	}
	
        location /nginx_status {
	    stub_status on;
        }

	location ~ /\. {
                deny all;
        }

        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   html;
        }
    }
}

**Comment by xll970211** [comment]
附上退出时写入access.log的内容
192.168.1.96 - - [11/Apr/2019:18:06:30 +0800] "GET /kxqp/websocket HTTP/1.1" 101 4076 "-" "BestHTTP" "-"

**Comment by mrpre** [comment]
正常行为。  

对于HTTP请求，HTTP的access log 是在 响应收完且发送到客户端后才写的。
对于websocket，Tengine并不感知具体协议，只有在TCP断连的时候才写日志。

**Comment by xll970211** [comment]
@mrpre 那有什么办法可以记录分发的日志吗？还是说只能这样了？

**Comment by mrpre** [comment]
@xll970211 只有这样，websocket断开才能写日志，

**Comment by xll970211** [comment]
@mrpre 好的，谢谢您的回答
