### ISSUE TITLE
2.3.0版本limit_req参数数量限制问题

### ISSUE THREAD

**Issue by CharleoSky** [alibaba/tengine#1242]
编译tengine 2.3.0之后，./sbin/nginx -t报错：
nginx: [emerg] invalid number of arguments in "limit_req" directive in test.conf:7

对应问题行：
`limit_req zone=request_auto_limit burst=200 forbid_action=@test nodelay;`

去掉一个或多个limit_req参数（非zone），-t就可以通过

nginx -m显示正常加载了对应模块：

> Tengine version: Tengine/2.3.0 (nginx/1.15.9)
> nginx: loaded modules:
> ...
> nginx:     ngx_http_limit_conn_module (static)
> nginx:     ngx_http_limit_req_module (static)
> ...

**Comment by wangfakang** [comment]
@CharleoSky  多谢反馈，可参考针对该问题的修复PR https://github.com/alibaba/tengine/pull/1245

**Comment by chobits** [comment]
thanks for your report, has been fixed in https://github.com/alibaba/tengine/pull/1245. so I am closing this issue:))

**Comment by chobits** [comment]
Please try master branch or wait our next version 2.3.1

**Comment by CharleoSky** [comment]
@wangfakang 谢谢

**Comment by CharleoSky** [comment]
@chobits Thank you
