### ISSUE TITLE
tengine 2.3.0 版本不支持 ngx_http_reqstat_module  模块

### ISSUE THREAD

**Issue by yujinqiu** [alibaba/tengine#1243]
Hi, 
升级到 2.3.0 版本之后,   ngx_http_reqstat_module 好像没有了,  

```
./sbin/nginx -t 
nginx: [emerg] unknown directive "req_status_zone"
```
这个是需要在编译的时候指定模块吗?  ./configure 没有发现对应的参数

**Comment by chobits** [comment]
编译时候需要使用 `--add-module=modules/ngx_http_reqstatus_module`
