### ISSUE TITLE
tengine-2.3.0bug太多了// 功能模块编译方式变更

### ISSUE THREAD

**Issue by hjun881** [alibaba/tengine#1244]
1.  nginx_upstream_check_module模块没有
2.  ngx_http_upstream_dynamic_module模块没有  

> 其它的功能还没用不知道有没问题，就用这两个功能命令都找不到。

**Comment by wangfakang** [comment]
@hjun881  2.3.0版本我们升级了Tengine的core代码到高版Nginx的，为了做到后续兼容、减少对core代码的直接修改，我们剥离了Tengine自身模块到modules目录下了，详细使用注意点请参考如下issue：
https://github.com/alibaba/tengine/issues/1220

**Comment by chobits** [comment]
* 变更列表中有一项说明：http://tengine.taobao.org/changelog_cn.html#2_3_0
 
> Change: 对Tengine自身模块全部剥离到modules目录下，减少对core的入侵

所有Tengine自身模块均被剥离到`<tengine-source>/modules`目录下
