### ISSUE TITLE
command(nginx -s relaod) cannot work

### ISSUE THREAD

**Issue by eagle2016** [alibaba/tengine#1249]
environment:  rhel  7.5    tengine: 2.3
question:  when I enable "reqstat" module.  and I have reload the new config, and I did not see the new  backend server (curl   http://127.0.0.1:8888/status).
step 1：

```
    nginx conf   as follows:
user nginx;
worker_processes  4;

#error_log  logs/error.log;
#error_log  logs/error.log  notice;
#error_log  logs/error.log  info;
#error_log  "pipe:rollback logs/error_log interval=1d baknum=7 maxsize=2G";

pid        logs/nginx.pid;


events {
    worker_connections  1024;
}

# load modules compiled as Dynamic Shared Object (DSO)
#
#dso {
#    load ngx_http_fastcgi_module.so;
#    load ngx_http_rewrite_module.so;
#}

http {
    include       mime.types;
    default_type  application/octet-stream;

    log_format  main  '$remote_addr - $remote_user [$time_local] $status $request_time "$request" '
                      '$request_uri $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';

    #access_log  logs/access.log  main;
    access_log  "pipe:rollback logs/access.log interval=1d baknum=7 maxsize=2G"  main;

    sendfile        on;
    #tcp_nopush     on;

    #keepalive_timeout  0;
    keepalive_timeout  65;

    #gzip  on;

    req_status_zone server "$host,$server_addr:$server_port" 10M;
    req_status_zone_add_indicator server $limit;

    server {
        listen       8888;

        location / {
	    proxy_pass http://backend;
	    client_max_body_size 1024m;
	    proxy_next_upstream_tries 1;
        }
	
	location /status {
	    check_status;
	    access_log off;
	}

        location /us {
            req_status_show;
            req_status_show_field req_total http_2xx http_3xx http_4xx http_5xx $limit;
	    access_log off;
        }
        
        set $limit 0;
        
        if ($arg_limit = '1') {
            set $limit 1;
        }

        req_status server;

    }

    upstream backend {
	server 10.80.36.224:8080;
	server 10.80.36.245:8080;
	check interval=3000 rise=2 fall=3 timeout=1000 type=http;
	check_http_send "HEAD / HTTP/1.0\r\n\r\n";
	check_http_expect_alive http_2xx http_3xx http_4xx http_5xx;        
    }


    # another virtual host using mix of IP-, name-, and port-based configuration
    #
    #server {
    #    listen       8000;
    #    listen       somename:8080;
    #    server_name  somename  alias  another.alias;

    #    location / {
    #        root   html;
    #        index  index.html index.htm;
    #    }
    #}


    # HTTPS server
    #
    #server {
    #    listen       443 ssl;
    #    server_name  localhost;

    #    ssl_certificate      cert.pem;
    #    ssl_certificate_key  cert.key;

    #    ssl_session_cache    shared:SSL:1m;
    #    ssl_session_timeout  5m;

    #    ssl_ciphers  HIGH:!aNULL:!MD5;
    #    ssl_prefer_server_ciphers  on;

    #    location / {
    #        root   html;
    #        index  index.html index.htm;
    #    }
    #}

}
```

 I have modified  the backend server.

step 2:  nginx -s reload
step 3:  curl  http://127.0.0.1:8888/status     IP of backend server  is old.
step 4:  modify nginx.conf

```
user nginx;
worker_processes  4;

#error_log  logs/error.log;
#error_log  logs/error.log  notice;
#error_log  logs/error.log  info;
#error_log  "pipe:rollback logs/error_log interval=1d baknum=7 maxsize=2G";

pid        logs/nginx.pid;


events {
    worker_connections  1024;
}

# load modules compiled as Dynamic Shared Object (DSO)
#
#dso {
#    load ngx_http_fastcgi_module.so;
#    load ngx_http_rewrite_module.so;
#}

http {
    include       mime.types;
    default_type  application/octet-stream;

    log_format  main  '$remote_addr - $remote_user [$time_local] $status $request_time "$request" '
                      '$request_uri $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';

    #access_log  logs/access.log  main;
    access_log  "pipe:rollback logs/access.log interval=1d baknum=7 maxsize=2G"  main;

    sendfile        on;
    #tcp_nopush     on;

    #keepalive_timeout  0;
    keepalive_timeout  65;

    #gzip  on;

    req_status_zone server "$host,$server_addr:$server_port" 10M;
    req_status_zone_add_indicator server $limit;

    server {
        listen       8888;

        location / {
	    proxy_pass http://backend;
	    client_max_body_size 1024m;
	    proxy_next_upstream_tries 1;
        }
	
	location /status {
	    check_status;
	    access_log off;
	}

        location /us {
            req_status_show;
            req_status_show_field req_total http_2xx http_3xx http_4xx http_5xx $limit;
	    access_log off;
        }
        
        set $limit 0;
        
        if ($arg_limit = '1') {
            set $limit 1;
        }

        req_status server;

    }

    upstream backend {
	server 10.80.36.224:8080;
	server 10.80.36.245:8080;
	check interval=3000 rise=2 fall=3 timeout=1000 type=http;
	check_http_send "HEAD / HTTP/1.0\r\n\r\n";
	check_http_expect_alive http_2xx http_3xx http_4xx http_5xx;        
    }


    # another virtual host using mix of IP-, name-, and port-based configuration
    #
    #server {
    #    listen       8000;
    #    listen       somename:8080;
    #    server_name  somename  alias  another.alias;

    #    location / {
    #        root   html;
    #        index  index.html index.htm;
    #    }
    #}


    # HTTPS server
    #
    #server {
    #    listen       443 ssl;
    #    server_name  localhost;

    #    ssl_certificate      cert.pem;
    #    ssl_certificate_key  cert.key;

    #    ssl_session_cache    shared:SSL:1m;
    #    ssl_session_timeout  5m;

    #    ssl_ciphers  HIGH:!aNULL:!MD5;
    #    ssl_prefer_server_ciphers  on;

    #    location / {
    #        root   html;
    #        index  index.html index.htm;
    #    }
    #}

}
```

step 5:  nginx -s reload
step 6:  curl  http://127.0.0.1:8888/status     IP of backend server  is new.

**Comment by mrpre** [comment]
@eagle2016 没复现，你把流程写清晰点。还有，你上面贴的2个配置文件，是一样的？没看出什么区别

**Comment by mrpre** [comment]
我拿你第一个配置文件，启动，然后curl，接着修改`upstream backend`里面的server，然后reload，然后再curl，curl得到的结果是新的？是这个复现步骤？

**Comment by eagle2016** [comment]
sorry.  as follows > 

the second config file:

user nginx;
worker_processes 4;

#error_log logs/error.log;
#error_log logs/error.log notice;
#error_log logs/error.log info;
#error_log "pipe:rollback logs/error_log interval=1d baknum=7 maxsize=2G";

pid logs/nginx.pid;

events {
worker_connections 1024;
}

load modules compiled as Dynamic Shared Object (DSO)
#dso {

load ngx_http_fastcgi_module.so;
load ngx_http_rewrite_module.so;
#}

http {
include mime.types;
default_type application/octet-stream;

log_format  main  '$remote_addr - $remote_user [$time_local] $status $request_time "$request" '
                  '$request_uri $body_bytes_sent "$http_referer" '
                  '"$http_user_agent" "$http_x_forwarded_for"';

#access_log  logs/access.log  main;
access_log  "pipe:rollback logs/access.log interval=1d baknum=7 maxsize=2G"  main;

sendfile        on;
#tcp_nopush     on;

#keepalive_timeout  0;
keepalive_timeout  65;

#gzip  on;

#req_status_zone server "$host,$server_addr:$server_port" 10M;
#req_status_zone_add_indicator server $limit;

server {
    listen       8888;

    location / {
    proxy_pass http://backend;
    client_max_body_size 1024m;
    proxy_next_upstream_tries 1;
    }

location /status {
    check_status;
    access_log off;
}

#    location /us {
#        req_status_show;
 #       req_status_show_field req_total http_2xx http_3xx http_4xx http_5xx $limit;
 #   access_log off;
#    }
    
#    set $limit 0;
    
 #   if ($arg_limit = '1') {
 #       set $limit 1;
 #   }

  #  req_status server;

}

upstream backend {
server 10.80.36.224:8080;
server 10.80.36.245:8080;
check interval=3000 rise=2 fall=3 timeout=1000 type=http;
check_http_send "HEAD / HTTP/1.0\r\n\r\n";
check_http_expect_alive http_2xx http_3xx http_4xx http_5xx;        
}


# another virtual host using mix of IP-, name-, and port-based configuration
#
#server {
#    listen       8000;
#    listen       somename:8080;
#    server_name  somename  alias  another.alias;

#    location / {
#        root   html;
#        index  index.html index.htm;
#    }
#}


# HTTPS server
#
#server {
#    listen       443 ssl;
#    server_name  localhost;

#    ssl_certificate      cert.pem;
#    ssl_certificate_key  cert.key;

#    ssl_session_cache    shared:SSL:1m;
#    ssl_session_timeout  5m;

#    ssl_ciphers  HIGH:!aNULL:!MD5;
#    ssl_prefer_server_ciphers  on;

#    location / {
#        root   html;
#        index  index.html index.htm;
#    }
#}
}

**Comment by wangfakang** [comment]
it has been solved.
if still a question plz Reopen.
