### ISSUE TITLE
[TODO] update dyups documentation

### ISSUE THREAD

**Issue by chobits** [alibaba/tengine#1257]
## Why you need it?

1. Tengine dyups documentation is an over-simplification, which makes Tengine user hard to use dyups module.
2. Note that we should compile lua module before dyups to enable dyups LUA API, `--add-module=./modules/ngx_http_lua_module --add-module=./modules/ngx_http_upstream_dyups_module`

## How it could be?

We should update Tengine dyups documentation to yzprofile/dyups master.

## Other related information

See this issue: https://github.com/alibaba/tengine/issues/985#issuecomment-353293797

**Comment by yunoasgit** [comment]
Tengine users find it difficult to use dyups module
https://github.com/alibaba/tengine/issues/1230 
It is recommended that documents be updated consistently or linked to the latest URL

**Comment by chobits** [comment]
fixed in https://github.com/alibaba/tengine/issues/1257
