### ISSUE TITLE
tengine 多server 的问题

### ISSUE THREAD

**Issue by yisangwu** [alibaba/tengine#1260]
安全组开了8080. 没开防火墙。
conf是独立的。
为什么 8080端口就是起不来？ 
netstat 看不到？

访问更不行？
1.conf

server{

listen 8080;
server_name 1.2.3.4;
location / {
    proxy_pass http://1.8.7.8:80;
    proxy_set_header Host $host:$server_port;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
}
}

2.conf
server{

listen 80;
server_name 1.2.3.4;
location / {
    proxy_pass http://1.8.7.8:80;
    proxy_set_header Host $host:$server_port;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
}
}

**Comment by mrpre** [comment]
1、确定使用的配置文件确实是你期望的配置文件。（可以在配置文件随便加入错误指令，看启动nginx是否报错，报错意味着nginx启动使用了你期望的配置文件）。
2、8080端口如果起不来，修改为其他端口，看是否能起来。（通过 ps -ef | grep nginx 查看是否存在nginx进程）。
3、如果不存在nginx进程，即1没有起来，查看错误日志(error_log)。
