### ISSUE TITLE
ssl加速，支持keyless吗？

### ISSUE THREAD

**Issue by xianlimei** [alibaba/tengine#1268]
支持远端秘钥在hsm中，获取hsm进行ssl加速吗？

**Comment by jinjiu** [comment]
目前没有支持哦

**Comment by MengqiWu** [comment]
咦，lurk还没有开源么，我怎么记得之前说要开源

**Comment by chobits** [comment]
目前还没有明确的开放的计划，未来keyless技术如果开放，应该是针对LURK协议。

**Comment by xianlimei** [comment]
嗨，我已经实现异步keyless，如果有需要，我可以帮忙提交代码，合进去哈！


发自我的iPhone

------------------ 原始邮件 ------------------
发件人: Xiaochen Wang <notifications@github.com>
发送时间: 2019年6月17日 10:57
收件人: alibaba/tengine <tengine@noreply.github.com>
抄送: hairy <348130346@qq.com>, Author <author@noreply.github.com>
主题: 回复：[alibaba/tengine] ssl加速，支持keyless吗？ (#1268)




目前还没有明确的开放的计划，未来keyless技术如果开放，应该是针对LURK协议。
