### ISSUE TITLE
tengine能自定义切割后的文件名吗？

### ISSUE THREAD

**Issue by rpmdeb** [alibaba/tengine#1270]
`access_log  "pipe:rollback /date/logs/nginx/access.log interval=1h baknum=100  maxsize=100M"  main;`

按照上面的配置，切割出来的文件名是 access.log.1  access.log.2  ...  access.log.100 

但是我想的是 按照每天每小时切割 ，并且每小时里面还按照大小切割，例如
access.log.2019051716.1   access.log.2019051716.2 ...    access.log.2019051717.1
不知道tengine 有没有 这样的功能？

**Comment by mrpre** [comment]
@MengqiWu

**Comment by MengqiWu** [comment]
但是我想的是 按照每天每小时切割 ，并且每小时里面还按照大小切割 。 这个功能是支持的，只是日志文件名是固定的，因为如果动态的文件名结合自动轮转删除，比较容易让人迷惑

**Comment by yunoasgit** [comment]
You need to use syslog
Try out http://tengine.taobao.org/document/http_log.html
