### ISSUE TITLE
Params for ./configure (backtrace, debug, sysguard and more).

### ISSUE THREAD

**Issue by trimstray** [alibaba/tengine#1273]
## Question

Hi!

Where are the configure parameters for following modules? I remember that some time ago these options were available:

```
--with-http_backtrace_module
--with-http_debug_pool_module
--with-http_debug_timer_module
--with-http_footer_filter_module
--with-http_sysguard_module
--with-http_upstream_check_module
--with-http_upstream_session_sticky_module
```

Or is another way to compile Tengine with them? Maybe I should `--add-module|--add-dynamic-module`?

Thanks for reply.

**Comment by wangfakang** [comment]
@trimstray  After tengine-2.3.0 version  put all Tengine's modules to the modules directory. Use --add-module=modules/<tengine_module_name> to compile. For more details, please refer to https://github.com/alibaba/tengine/issues/1220 .

**Comment by trimstray** [comment]
@wangfakang : thanks a lot! :1st_place_medal:
