### ISSUE TITLE
Tengine won't create log directories recursively since 2.3.0 with -t

### ISSUE THREAD

**Issue by CorefLava** [alibaba/tengine#1279]
### Ⅰ. Issue Description

Tengine won't create log directories recursively since 2.3.0 with -t

### Ⅱ. Describe what happened

Tengine 2.2.0 will test conf, create directory recursively and returns success, while tengine 2.3.0 will report failed.

### Ⅲ. Describe what you expected to happen

Tengine 2.3.0 is supposed to act as it did previously.

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. The nginx.conf contains:
```
error_log   /root/temp/logs/logs/error.log;
```

2. Tengine 2.2.0 will create error log directory `/root/temp/logs/logs/` and results in succcess simultaneously:
```
[root@test01 ~]# tengine-2.2.0/objs/nginx -t -c /root/nginx.conf -p /root/temp/tengine-2.2.0
nginx: [alert] could not open error log file: open() "/root/temp/tengine-2.2.0/logs/logs/error.log" failed (2: No such file or directory)
nginx: the configuration file /root/nginx.conf syntax is ok
nginx: configuration file /root/nginx.conf test is successful
```

3. While with Tengine 2.3.0, it results in failure and no log directory created:

```
[root@test01 ~]# rm -rf temp/logs
[root@test01 ~]# tengine-2.3.0/objs/nginx -t -c /root/nginx.conf -p /root/temp/tengine-2.3.0
nginx: [alert] could not open error log file: open() "/root/temp/tengine-2.3.0/logs/error.log" failed (2: No such file or directory)
nginx: the configuration file /root/nginx.conf syntax is ok
2019/05/29 00:53:59 [emerg] 13885#0: open() "/root/temp/logs/logs/error.log" failed (2: No such file or directory)
nginx: configuration file /root/nginx.conf test failed
```

### Ⅴ. Anything else we need to know?

1. Seems tengine remove this function in [this commit](https://github.com/alibaba/tengine/commit/ed08765c493343d824eb50d4831d8e218d9bcd9e#diff-dd48f92377222f6ae5ecc3123158a5f6) of [this pr](https://github.com/alibaba/tengine/pull/1151/commits). Is it a misoperation?
The key code is in ngx_cycle.c: ngx_init_cycle (keyword is `ngx_create_full_path`)

### Ⅵ. Environment:

- Tengine version (use `sbin/nginx -V`): `Tengine 2.2.0` and `Tengine 2.3.0`
- OS (e.g. from /etc/os-release): CentOS-6.10-x86_64-minimal.iso
- Kernel (e.g. `uname -a`): Linux test01 2.6.32-754.el6.x86_64 #1 SMP Tue Jun 19 21:26:04 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
- Others:

**Comment by wangfakang** [comment]
Tengine has been upgraded core files from the Nginx 1.15.9 version. Note that this version is slightly not backwards compatible, some processing logic is consistent with Nginx official. 
See more details https://github.com/alibaba/tengine/issues/1220.

**Comment by CorefLava** [comment]
All right. Thks for your reply.
