### ISSUE TITLE
limit_req_zone rate 设置变量报错

### ISSUE THREAD

**Issue by flapjackegg** [alibaba/tengine#1282]
## Question

版本：Tengine 2.1.1
下图是我的配置，limit_req_zone 的 rate 参数，我按照官网文档设置了一个变量 $limit_count，但是 nginx -t 的时候报错

```
nginx: [emerg] invalid rate "rate=$limit_count" in /usr/local/nginx/conf/site/default.conf:1
configuration file /usr/local/nginx/conf/nginx.conf test **failed**
```

![image](https://user-images.githubusercontent.com/33110052/58861905-11bf6e80-86e2-11e9-95ac-cf9acf11a20a.png)

**Comment by mrpre** [comment]
`rate=$var` only support since Tengine-2.3.0.

**Comment by flapjackegg** [comment]
thx

**Comment by chobits** [comment]
think it resolved
