### ISSUE TITLE
2.2.3升级到2.3.0后，session_sticky参数不支持

### ISSUE THREAD

**Issue by liuyinmessi** [alibaba/tengine#1283]
conf配置为：
session_sticky cookie=uid fallback=on path=/ mode=insert option=indirect;
session_sticky_hide_cookie upstream=app_list;

升级2.3.0后，执行关闭或者重载命令，报错：
nginx: [emerg] unknown directive "session_sticky" in /webapp/tengine/conf/confs/nginx_sichuan.conf:3
nginx: [emerg] unknown directive "cookie=uid" in /webapp/tengine/conf/confs/nginx_sichuan.conf:3
nginx: [emerg] unknown directive "session_sticky_hide_cookie" in /webapp/tengine/conf/confs/nginx_sichuan.conf:173

这是不支持了吗？
向各位大神求教，非常感谢。

**Comment by chobits** [comment]
> Tengine自身实现的模块，当前全部剥离到modules目录下，如果需要使用那个模块、则使用--add-module=modules/<module_name>的方式进行编译；


如 `--add-module=modules/ngx_http_upstream_session_sticky_module`

---

具体升级细节可以参考：https://github.com/alibaba/tengine/issues/1220

**Comment by liuyinmessi** [comment]
非常感谢，我自己先测试一下

**Comment by liuyinmessi** [comment]
> 
> 
> from 2.3.0 具体升级细节可以参考：#1220
> 
> > Tengine自身实现的模块，当前全部剥离到modules目录下，如果需要使用那个模块、则使用--add-module=modules/<module_name>的方式进行编译；
> 
> 编译时候使用参数如下 `./configure --add-module=modules/ngx_http_upstream_session_sticky_module`

我按照您的方法更新升级成功了。再次请问一下，我只替换了sbin下面的nginx，原来2.2.3的module文件夹是空的，是应该把2.3.0make后生成的module文件夹一起拷贝到原来2.2.3的module文件夹里面吧?

**Comment by chobits** [comment]
> 再次请问一下，我只替换了sbin下面的nginx，原来2.2.3的module文件夹是空的，是应该把2.3.0make后生成的module文件夹一起拷贝到原来2.2.3的module文件夹里面吧?

不需要，tengine里面的modules是方代码的，2.3.0里make install后生成的路径里的文件已经是全的（即 configure --prefix=<path>指定的路径），如果你动态安装模块会自动生成modules目录。

* 动态安装模块是指 类似这样的编译参数:`./configure --add-dynamic-module=./modules/ngx_http_reqstat_module/`

**Comment by liuyinmessi** [comment]
> 
> 
> > 再次请问一下，我只替换了sbin下面的nginx，原来2.2.3的module文件夹是空的，是应该把2.3.0make后生成的module文件夹一起拷贝到原来2.2.3的module文件夹里面吧?
> 
> 不需要，tengine里面的modules是方代码的，2.3.0里make install后生成的路径里的文件已经是全的（即 configure --prefix=指定的路径），如果你动态安装模块会自动生成modules目录。
> 
>     * 动态安装模块是指 类似这样的编译参数:`./configure --add-dynamic-module=./modules/ngx_http_reqstat_module/`

再次感谢你的回答。
我想表达的是，我在2.3.0的时候，只使用了make命令，没有使用install，然后是把生成的objs目录里面的nginx替换掉原来的2.2.3sbin下面的nginx，这样就完成升级了。这个时候tengine目录里面的modules目录下面是空的，因为当时你还没有答复我，我就把2.3.0解压后modules下面的目录都拷贝到tengine里面来了。

**Comment by chobits** [comment]
> 然后是把生成的objs目录里面的nginx替换掉原来的2.2.3sbin下面的nginx，这样就完成升级了
如果没有安装动态模块，这是可以的，只要能够启动即可。

> 我就把2.3.0解压后modules下面的目录都拷贝到tengine里面来了。
这是需要的。里面的目录都是source，对线上程序启动无影响。

**Comment by liuyinmessi** [comment]
> 
> 
> > 然后是把生成的objs目录里面的nginx替换掉原来的2.2.3sbin下面的nginx，这样就完成升级了
> 
> 如果没有安装动态模块，这是可以的，只要能够启动即可。
> 
> > 我就把2.3.0解压后modules下面的目录都拷贝到tengine里面来了。
> 
> 这是需要的。里面的目录都是source，对线上程序启动无影响。

感谢

**Comment by chobits** [comment]
刚刚回复出错了。应该是“不”需要

![image](https://user-images.githubusercontent.com/623062/59181810-c5b97180-8b9a-11e9-96a6-515eddb2bc1c.png)

问题已经解决，close了，如果有问题可以reopen
