### ISSUE TITLE
tengine2.3.0 dynamic_resolve功能无法启用

### ISSUE THREAD

**Issue by luweiv9988** [alibaba/tengine#1287]
### Ⅰ. Issue Description

dynamic_resolve无法启用，tengine错误提示：
```
nginx: [emerg] unknown directive "dynamic_resolve" in /usr/local/nginx/conf/nginx.conf:43
nginx: configuration file /usr/local/nginx/conf/nginx.conf test failed
```

### Ⅱ. Describe what happened
配置如下，非常简单的例子：
```
cat nginx.conf
```
```
upstream backend {
    dynamic_resolve fallback=stale fail_timeout=5s;
    server tengine.xxx.cn:8080;
}
server {
    listen       80;
    server_name  localhost;
    location / {
        proxy_pass  http://backend;
    }
}
```

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1.
2.
3.

### Ⅴ. Anything else we need to know?

1. 手动编译方式 ./configure --prefiex=/usr/local/nginx && make && make install
2.
3.

### Ⅵ. Environment:

- Tengine version ：2.3.0
- OS (e.g. from /etc/os-release): CentOS Linux release 7.4.1708 (Core)
- Kernel (e.g. `uname -a`): 3.10.0-693.el7.x86_64
- Others:

**Comment by wangfakang** [comment]
Put all Tengine's modules to the modules directory after the Tengine-2.3.0 version. You can  use `--add-module=modules/<tengine_module_name> ` to compile. 
See also tengine-2.3.0 version for more tips #1220 .
