### ISSUE TITLE
tengine-2.3.0 编译增加lua支持，出错

### ISSUE THREAD

**Issue by heidsoft** [alibaba/tengine#1291]
## Question
Lua 5.1.4
centos7 
/service/software/tengine-2.3.0/modules/ngx_http_lua_module/src/ngx_http_lua_util.h:373：对‘lua_pushlightuserdata’未定义的引用
/service/software/tengine-2.3.0/modules/ngx_http_lua_module/src/ngx_http_lua_util.h:374：对‘lua_setfield’未定义的引用
objs/addon/src/ngx_http_lua_ssl_session_storeby.o：在函数‘ngx_http_lua_ssl_sess_store_by_chunk’中：
/service/software/tengine-2.3.0/modules/ngx_http_lua_module/src/ngx_http_lua_ssl_session_storeby.c:388：对‘lua_createtable’未定义的引用
objs/addon/src/ngx_http_lua_ssl_session_storeby.o：在函数‘ngx_http_lua_get_globals_table’中：
/service/software/tengine-2.3.0/modules/ngx_http_lua_module/src/ngx_http_lua_util.h:382：对‘lua_pushvalue’未定义的引用
objs/addon/src/ngx_http_lua_ssl_session_storeby.o：在函数‘ngx_http_lua_ssl_sess_store_by_chunk’中：

**Comment by chobits** [comment]
Please use openresty luajit, for example, see my test configure shell script:

```
export LUAJIT_LIB=/Users/xiaochen/work/github/openresty_luajit/output/lib
export LUAJIT_INC=/Users/xiaochen/work/github/openresty_luajit/output/include/luajit-2.1

./configure --prefix=$(pwd)/output   --with-http_ssl_module \
    --with-http_lua_module \
    --add-module=./modules/ngx_http_upstream_check_module/ \
    --add-module=./modules/ngx_http_upstream_dyups_module/ \
    --with-cc-opt="-I/usr/local/opt/openssl/include -O0 -g" \
    --with-ld-opt="-L/usr/local/opt/openssl/lib" \
    --add-module=./modules/ngx_http_proxy_connect_module/ \
    --add-module=./modules/ngx_http_reqstat_module/ \
    --with-debug
```

**Comment by chobits** [comment]
ping? will be closed later.
