### ISSUE TITLE
Tengine-2.3.1 (development version) has been released!

### ISSUE THREAD

**Issue by MengqiWu** [alibaba/tengine#1292]
# CHANGES

*) Feature: add $ssl_handshake_time variable for stream ssl module (mrpre)
*) Feature: support websocket check of upstream check module (mrpre)
*) Fix: server version strings in http2 and stream response headers (AstroProfundis)
*) Fix: "-m" option to show dynamic module (wangfakang)
*) Fix：parameter number check for limit_req directive (wangfakang)
*) Fix: random index logical for round robin (wangfakang)
*) Fix: fixed compilation error on macOS for reqstatus (chobits)
*) Change: update ngx_http_lua_module v0.10.14 (mrpre)
*) Change: update dyups to master branch of yzprofile/dyups (chobits)
*) Change: support dynamic module for reqstatus (chobits)
*) Change: support dynamic build for upstream_dynamic module (wangfakang)
*) Change: support dynamic build for trim module (wangfakang)
*) Change: support dynamic build for footer module (wangfakang)
*) Change: support dynamic build for user_agent module (wangfakang)
*) Change: support dynamic build for ngx_http_concat_module (mathieu-aubin)
*) Change: update core to nginx-1.16.0 (MenqqiWu)

# All merged pull request

For all merged pull request for 2.3.1, see [Milestone 2.3.1](https://github.com/alibaba/tengine/milestone/14?closed=1).

# Release tag

For Pre-release and source code downloading, see [Release 2.3.1](https://github.com/alibaba/tengine/releases/tag/2.3.1).

**Comment by chobits** [comment]
For all merged pull request for 2.3.1, see [Milestone 2.3.1](https://github.com/alibaba/tengine/milestone/14?closed=1).

**Comment by netroby** [comment]
Glad to see, great hard works

**Comment by kangwy** [comment]
执行命令：./configure
报错如下，能否提供一些建议，系统Centos7：

checking for sys/filio.h ... not found
checking for EPOLLEXCLUSIVE ... not found
checking for /dev/poll ... not found
checking for kqueue ... not found
checking for crypt() ... not found
checking for F_READAHEAD ... not found
checking for F_NOCACHE ... not found
checking for directio() ... not found
checking for dlopen() ... not found
checking for SO_SETFIB ... not found
checking for SO_ACCEPTFILTER ... not found
checking for SO_BINDANY ... not found
checking for IP_BINDANY ... not found
checking for IP_BIND_ADDRESS_NO_PORT ... not found
checking for IP_RECVDSTADDR ... not found
checking for IP_SENDSRCADDR ... not found
checking for setproctitle() ... not found
checking for POSIX semaphores ... not found
checking for struct dirent.d_namlen ... not found

**Comment by chobits** [comment]
> 抱歉，我是初级linux用户。
> 在执行命令：./configure
> 报错如下，能否提供一些建议，系统Centos7：
> 
> checking for sys/filio.h ... not found
> checking for EPOLLEXCLUSIVE ... not found
> checking for /dev/poll ... not found
> checking for kqueue ... not found
> checking for crypt() ... not found
> checking for F_READAHEAD ... not found
> checking for F_NOCACHE ... not found
> checking for directio() ... not found
> checking for dlopen() ... not found
> checking for SO_SETFIB ... not found
> checking for SO_ACCEPTFILTER ... not found
> checking for SO_BINDANY ... not found
> checking for IP_BINDANY ... not found
> checking for IP_BIND_ADDRESS_NO_PORT ... not found
> checking for IP_RECVDSTADDR ... not found
> checking for IP_SENDSRCADDR ... not found
> checking for setproctitle() ... not found
> checking for POSIX semaphores ... not found
> checking for struct dirent.d_namlen ... not found

please file a new issue, and added more description ( issue will guide you how to do)

**Comment by goldensaints** [comment]
从tengine-2.2.3升级到2.3.1后，执行 nginx -m后没有任何模块显示了，同时还不支持了reuse_port
![image](https://user-images.githubusercontent.com/52484640/60570350-f492c400-9da3-11e9-86e9-40d842741aed.png)

**Comment by chobits** [comment]
> 从tengine-2.2.3升级到2.3.1后，执行 nginx -m后没有任何模块显示了，同时还不支持了reuse_port
> ![image](https://user-images.githubusercontent.com/52484640/60570350-f492c400-9da3-11e9-86e9-40d842741aed.png)

请参考: https://github.com/alibaba/tengine/issues/1220
