### ISSUE TITLE
2.3版本以及以上hash负载的支持

### ISSUE THREAD

**Issue by cnldw** [alibaba/tengine#1296]
## Question

2.3以及以上健康检查和hash负载无法使用
nginx: [emerg] unknown directive "consistent_hash" in /opt/nginx/conf/nginx.conf:62

请问是什么情况

**Comment by cnldw** [comment]
需要使用--add-module引入tengine特有模块才可以，这样做应该是方便后期和nginx保持同步更新吧

**Comment by chobits** [comment]
> 需要使用--add-module引入tengine特有模块才可以，这样做应该是方便后期和nginx保持同步更新吧

是的。新版tengine的三方模块都移入modules/目录了，需要通过`configure --add-module=moduels/<module_name>`开启
