### ISSUE TITLE
2.3.1中src/stream/ngx_stream.c编译报错

### ISSUE THREAD

**Issue by wanghy8166** [alibaba/tengine#1297]
### Ⅰ. Issue Description
2.3.1中src/stream/ngx_stream.c编译报错

### Ⅱ. Describe what happened
src/stream/ngx_stream.c: In function 'ngx_stream_add_ports':
src/stream/ngx_stream.c:604:47: error: 'listen->sockaddr' is a pointer; did you mean to use '->'?
         if (ngx_cmp_sockaddr(&listen->sockaddr.sockaddr, listen->socklen,
                                               ^
                                               ->
src/stream/ngx_stream.c:605:34: error: '(addr + (sizetype)(i * 160))->opt.sockaddr' is a pointer; did you mean to use '->'?
             &addr[i].opt.sockaddr.sockaddr,
                                  ^
                                  ->
make[1]: *** [objs/Makefile:1741: objs/src/stream/ngx_stream.o] Error 1
make[1]: *** Waiting for unfinished jobs....
make[1]: Leaving directory '/usr/src/tengine-2.3.1'
make: *** [Makefile:8: build] Error 2

### Ⅲ. Describe what you expected to happen
编译正常通过

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1.
cd /tmp
git clone https://github.com/wanghy8166/docker-tengine.git
cd docker-tengine
修改 Dockerfile 中 ENV TENGINE_VERSION 2.3.1
docker build -t test /tmp/docker-tengine | tee build-`date +%Y%m%d-%H%M%S`.log
出现src/stream/ngx_stream.c编译报错
用2.3.0则编译正常通过
2.
3.

### Ⅴ. Anything else we need to know?

1. If applicable, add nginx  [debug log doc](http://nginx.org/en/docs/debugging_log.html).
2.
3.

### Ⅵ. Environment:

- Tengine version (use `sbin/nginx -V`):
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Others:

**Comment by MengqiWu** [comment]
@mrpre may need update stream sni

**Comment by MengqiWu** [comment]
fixed by https://github.com/alibaba/tengine/commit/26160b47bf42fe43ebccb36ecbc029e4cdbace36
