### ISSUE TITLE
我该怎么添加 geoip2 模块呢？

### ISSUE THREAD

**Issue by Marco1221** [alibaba/tengine#1303]
## Question

没找到相关文档说明，麻烦各位指点一下

**Comment by chobits** [comment]
Maybe https://github.com/leev/ngx_http_geoip2_module#installing

**Comment by Marco1221** [comment]
可是我在编译 Tengine 的时候 提示不支持
![image](https://user-images.githubusercontent.com/18682119/60701495-84647980-9f2e-11e9-9fd2-77bf9c745b36.png)

**Comment by Marco1221** [comment]
抱歉 我看到了 --add-module 这个参数了，谢谢
