### ISSUE TITLE
Version tengine-2.3.1

### ISSUE THREAD

**Issue by johnripperdec** [alibaba/tengine#1318]
### Ⅰ. Issue Description
Upstream health checks are not supported in this release Version tengine-2.3.1
### Ⅱ. Describe what happened
can not found config "check_status"

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1.  ./configure --prefix=/usr/local/nginx --user=www --group=www --with-http_ssl_module --with-http_stub_status_module --with-file-aio --with-http_dav_module --with-pcre=/opt/pcre-8.37 --with-stream --with-stream_ssl_module
2. make
3. make install
4. /usr/local/nginx/sbin/nginx -t

my one of conf file like this:
cat vhost/zabbix.conf 
upstream zabbix1 {
   #server 10.10.24.19:8081 weight=3    max_fails=2 fail_timeout=5s;
   server 10.10.24.19:8081 ;
   check interval=3000 rise=2 fall=5 timeout=5000;
 				
               }
server {
        listen       80;
        server_name  zabbix.bol110.bo;
	location = / {
	rewrite ^(.*)$ $scheme://zabbix.bol110.bo/zabbix/$1 permanent;
#	proxy_pass http://zabbix1;
			}
location / {
                proxy_pass http://zabbix1;
		proxy_next_upstream error timeout invalid_header http_500 http_502 http_503 http_504 http_403 http_404;
        	proxy_set_header Host $host;
                proxy_set_header X-Forwarded-For $remote_addr;
		proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
		proxy_headers_hash_max_size 51200;
		proxy_headers_hash_bucket_size 6400;
		proxy_http_version 1.1;
    		proxy_set_header Upgrade $http_upgrade;
    		proxy_set_header Connection "upgrade";

             }

	location /status {
	check_status;
	access_log off;
	
	}

  }

### Ⅴ. Anything else we need to know?

1. If applicable, add nginx  [debug log doc](http://nginx.org/en/docs/debugging_log.html).
2.
3.

### Ⅵ. Environment:

- Tengine version (use `sbin/nginx -V`): Version tengine-2.3.1
- OS (e.g. from /etc/os-release):centos6.8
- Kernel (e.g. `uname -a`):Linux LA-JCJ-NGINX1-RED-10-10-22-4 2.6.32-358.el6.x86_64 #1 SMP Tue Jan 29 11:47:41 EST 2013 x86_64 x86_64 x86_64 GNU/Linux
- Others:

**Comment by wangfakang** [comment]
@johnripperdec  The `check_status` directive is provided by the `ngx_http_upstream_check_module` module, so it needs to be `--add-module=modules/ngx_http_upstream_check_module` at compile time.

**Comment by johnripperdec** [comment]
@wangfakang  Tengine brought her own health check,and I changed to version Tengine 2.2.3,it is worked. 
![image](https://user-images.githubusercontent.com/15044314/61596559-42e0f900-abd3-11e9-8e45-c895e4cd7981.png)
and i do not change the configure.
![image](https://user-images.githubusercontent.com/15044314/61596600-ae2acb00-abd3-11e9-9302-094acb790892.png)

And i create a test pc to test this problem, it is still have the same problem. so I think this problem is just have in version 2.3.1. And it is not include the nginx_upstream_check_module. i will still to test.

**Comment by wangfakang** [comment]
@johnripperdec   After tengine-2.3.0 version  put all Tengine's modules to the modules directory. Use `--add-module=modules/<tengine_module_name> ` to compile. For more details, please refer to https://github.com/alibaba/tengine/issues/1220 .

**Comment by johnripperdec** [comment]
@wangfakang thank you very much.
