### ISSUE TITLE
--with-http_upstream_check_module参数失效

### ISSUE THREAD

**Issue by LittlePageProgram** [alibaba/tengine#1319]
### Ⅰ. Issue Description
最新版本的tengine的--prefix和--with-http_upstream_check_module不能同时启用

### Ⅱ. Describe what happened
同时使用这两个参数，会显示无--prefix命令

### Ⅲ. Describe what you expected to happen
--希望能够修改./configure的脚本，使两个参数能够同时启用

### Ⅵ. Environment:

- Tengine version (use `sbin/nginx -V`):Tengine-2.3.1.tar.gz
- OS (e.g. from /etc/os-release):CentOS 7

**Comment by wangfakang** [comment]
@LittlePageProgram 由于tengine-2.3.x相关版本升级了core代码，同时调整了部分模块的编译方式和之前有所不同，更多使用注意事项请参考： https://github.com/alibaba/tengine/issues/1220 。
其中`--with-http_upstream_check_module` 参数已废弃，请使用该方式加载对应模块 ` --add-module=modules/ngx_http_upstream_check_module` 。

**Comment by chobits** [comment]
ping! 该问题是否已经解决，方案如 上comment。本问题将会在今天被closed
