### ISSUE TITLE
ngx_pipe.c：982行rbcf->interval作为除数，应去掉976行rbcf->interval==0的条件

### ISSUE THREAD

**Issue by log-a** [alibaba/tengine#1341]

**Comment by wangfakang** [comment]
此处有判断的：https://github.com/alibaba/tengine/blob/master/src/os/unix/ngx_pipe.c#L828

**Comment by log-a** [comment]
> 此处有判断的：https://github.com/alibaba/tengine/blob/master/src/os/unix/ngx_pipe.c#L828

所以不应该出现rbcf->interval==0的情况，976行的判断条件改成rbcf->interval > 0更合理。
