### ISSUE TITLE
tengine  invalid status "5xx"

### ISSUE THREAD

**Issue by shiweijie** [alibaba/tengine#1362]
新版的 tengine 不支持 2xx 3xx 5xx 状态码了吗？？ 

#  service nginx configtest
nginx: [emerg] invalid status "5xx" in /etc/nginx/conf.d/itv.conf:31
nginx: configuration file /etc/nginx/nginx.conf test failed

配置
location ~* /(s\d+)/.* {
                proxy_pass              http://$1;
                proxy_redirect          off;
                proxy_cache             cache_file;
                proxy_cache_key         $uri$is_args$args;
                proxy_cache_valid       200 206 302 301 10m;
                **proxy_cache_valid       5xx 503 404 0s;**
                proxy_cache_valid       any 0s;
                expires                 7d;

**Comment by wangfakang** [comment]
@shiweijie tengine-2.3.x这个逻辑和Nginx官方保持一致，详细请参考：http://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_cache_valid
