### ISSUE TITLE
Does Tengine support Google Quic plan? Plan to support ahead of nginx?

### ISSUE THREAD

**Issue by yunoasgit** [alibaba/tengine#1367]
Does Tengine support Google Quic plan? Plan to support ahead of nginx?
Thank you very much.

**Comment by yunoasgit** [comment]
https://github.com/evansun922/nginx-quic
@evansun922
Can I support Tengine(Nginx-1.17.3 version)
Thank you very much

**Comment by yunoasgit** [comment]
Is there a plan? Is there a higher priority
@wangfakang
Thank you very much

**Comment by InfoHunter** [comment]
What do you mean by 'supporting Google QUIC'?

Since the IETF QUIC draft has already been submitted to IESG for a final publication, it's expected that we should support IETF QUIC - which means we could probably prefer this instead of supporting the old Google QUIC.

**Comment by yunoasgit** [comment]
If you plan to support IETF QUIC, it's better.

Your suggestion is very good.

At present, we don't see any plan support from nginx

**Comment by chobits** [comment]
Has been supported https://tengine.taobao.org/document/xquic.html
