### ISSUE TITLE
ngx-upstream-fair coredump under version 2.3.2

### ISSUE THREAD

**Issue by tcp9** [alibaba/tengine#1375]
### Ⅰ. Issue Description

在tengine 2.3.2 版本中，使用fair模块 会产生core

### Ⅱ. Describe what happened
程序无法启动， Floating point exception (core dumped)

### Ⅲ. Describe what you expected to happen
程序正常运行

### Ⅳ. How to reproduce it (as minimally and precisely as possible)
1. cd work
1. git clone git://github.com/gnosek/nginx-upstream-fair.git
2. git clone https://github.com/alibaba/tengine-patches.git
3. cd ~/work/nginx-upstream-fair && patch -p1 < ../tengine-patches/nginx-upstream-fair/upstream-fair-upstream-check.patch && sed -i 's/default_port/no_port/g' ngx_http_upstream_fair_module.c
4. 编译
5. 在upstream配置中使用fair指令启动会coredump，观测到coredump在ngx_http_upstream_init_process
``` 
    tengine-2.3.2/src/http/ngx_http_upstream.c 
    6967├───────> peers->init_number = ngx_random() % peers->number;
```

我在代码中看到程序在执行ngx_http_upstream_init_process时，对每个server的peer->data节点都会进行ngx_http_upstream_rr_peers_t *的转换，但是对于nginx upstream fair模块来说，其peers的数据结构是ngx_http_upstream_fair_peers_t *， 这两个数据结构的不一致，导致了coredump, 请问是不是将不支持nginx upstream fair模块了？

**Comment by wangfakang** [comment]
@tcp9  你可以本地合并下这个地方的修改在编译测试下： https://github.com/alibaba/tengine/pull/1379

**Comment by tcp9** [comment]
> @tcp9 你可以本地合并下这个地方的修改在编译测试下： #1379

测试了一下，已确认正常运行，感谢～
