### ISSUE TITLE
ngx_http_reqstat_module怎么添加后端的proxy_host?

### ISSUE THREAD

**Issue by denwork** [alibaba/tengine#1380]
ccxx.test.com/api/mgAuth/index,766,952,1,1,1,0,0,0,0,9,1,8,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
现在只能定位到url级别。再细分一次，这样就能知道是那个upstream出现http_5xx错误了

**Comment by wangfakang** [comment]
@denwork  你可以通过`req_status_zone`指令里面增加`$upstream_addr`变量来实现这个需求，更多使用说明可以参考这个文档 http://tengine.taobao.org/document_cn/http_reqstat_cn.html  。

**Comment by denwork** [comment]
配置文件：
req_status_zone server_status $server_name,$uri,$upstream_addr 50M;
结果是：第三个地方为空
ccxx.test.com/api/mgAuth/index,,7720,16378,13,19,8,0,0,11,0,350,19,349,19,8,0,0,0,0,0,0,0,0,11,0,0,0,0,0,11

**Comment by denwork** [comment]
配置文件：
req_status_zone server_status $server_name,$uri,$upstream_addr 50M;
结果是：第三个地方为空
ccxx.test.com,/api/mgAuth/index,,7720,16378,13,19,8,0,0,11,0,350,19,349,19,8,0,0,0,0,0,0,0,0,11,0,0,0,0,0,11

**Comment by wangfakang** [comment]
@denwork  加上这个指令`req_status_lazy on;` ,详细使用方法参考：http://tengine.taobao.org/document_cn/http_reqstat_cn.html
