### ISSUE TITLE
关于ngx_http_upstream_init_virtual_peers的调用问题

### ISSUE THREAD

**Issue by huhaipeng** [alibaba/tengine#1384]
## Question

在ngx_http_upstream_get_vnswrr函数里有两个ngx_http_upstream_init_virtual_peers函数的调用，第一个调用我看明白了是在运行时分批初始化虚拟节点列表，但是第二个在for循环里面的调用是每次请求来到get peer的时候都会调用一次，我觉得没必要，可以删除。是这样吗？或者说使我哪里理解的有问题，能解答一下吗？

**Comment by wangfakang** [comment]
@huhaipeng 看的很细心哈，第二个地方调用主要是为了解决第一批初始化末尾节点机器为down状态时导致的流量不均问题。比如下面的这个场景：

```
upstream test {
    server 127.0.0.1 weight=1;
    server 127.0.0.2 weight=1;
    server 127.0.0.3 weight=2;
    server 127.0.0.4 weight=1 down;
}
```

![image](https://user-images.githubusercontent.com/8215757/66831725-ed767700-ef8a-11e9-92f5-3bd22e375768.png)

如果没有第二处的`ngx_http_upstream_init_virtual_peers`调用，则只会按照上面黑色区间轮训访问虚拟节点，虽然`127.0.0.3`的权重是2，但是最终看到的效果是按照1:1:1的轮训访问。如果增加`ngx_http_upstream_init_virtual_peers`后就会按照上图的红色箭头所在区间轮训机器列表。
