### ISSUE TITLE
Tengine-2.3.2 使用 ngx_http_reqstatus_module 报错

### ISSUE THREAD

**Issue by QinQiang666** [alibaba/tengine#1385]
### Ⅰ. Issue Description
在使用 tengine-2.3.2 的 req_status_zone 功能的时候出现如下错误

[root@sha2.idc3 ~]# /usr/local/nginx/sbin/nginx -t
nginx: [emerg] unknown directive "req_status_zone" in /usr/local/nginx/conf/nginx.conf:59
nginx: configuration file /usr/local/nginx/conf/nginx.conf test failed

### Ⅱ. Describe what happened
在GitHub上看到有人也提了这个问题，说是要编译 modules/ngx_http_reqstatus_module 模块，我重新编译后报错
./configure --add-module=./modules/ngx_http_upstream_vnswrr_module --with-stream_ssl_module --with-stream_sni --add-module=modules/ngx_http_reqstatus_module

adding module in modules/ngx_http_reqstatus_module
./configure: error: no modules/ngx_http_reqstatus_module/config was found

请问这种情况怎么处理？是这个模板被移除了吗？还是什么情况

**Comment by wangfakang** [comment]
@QinQiang666  参考这个https://github.com/alibaba/tengine/issues/1220 里面描述的注意点。

**Comment by QinQiang666** [comment]
好的，谢谢，模块名字错了
