### ISSUE TITLE
Tengine最新release

### ISSUE THREAD

**Issue by Yangzcy423911** [alibaba/tengine#1390]
当前最新版本可以用于生产环境？ ，当前版本属于开发版本，http://tengine.taobao.org/，什么时候出Release

**Comment by wangfakang** [comment]
可以用于生产环境，但是务必请做好灰度验证。

**Comment by Yangzcy423911** [comment]
恩，好的谢谢 ，  我想问一下 这个版本，http://tengine.taobao.org/  在这个网站显示是开发版本，这是什么原因呢
