### ISSUE TITLE
使用Tengine2.3.2版本，nginx -t 一直报nginx: [emerg] unknown directive "check" in /data/server/nginx/conf/nginx.conf:7

### ISSUE THREAD

**Issue by zhus2015** [alibaba/tengine#1394]
使用Tengine2.3.2版本，nginx -t 一直报nginx: [emerg] unknown directive "check" in /data/server/nginx/conf/nginx.conf:66

安装方法是使用的官方的默认方法
![image](https://user-images.githubusercontent.com/28441774/67464271-a61c7480-f675-11e9-8993-acd379145a55.png)

![image](https://user-images.githubusercontent.com/28441774/67465070-0d86f400-f677-11e9-90ca-b53531c4d8a9.png)

**Comment by wangfakang** [comment]
@zhus2015  参考这个里面的注意事项  https://github.com/alibaba/tengine/issues/1196

**Comment by zhus2015** [comment]
非常感谢

**Comment by yxlwfds** [comment]
说那么多干嘛 编译时直接加这个就可以 --add-module=./modules/ngx_http_upstream_check_module/
