### ISSUE TITLE
tengine 能否支持NTLM 认证

### ISSUE THREAD

**Issue by xiechundi** [alibaba/tengine#1410]
tengine 能否支持NTLM 认证

**Comment by hongxiaolong** [comment]
> The NTLM protocol was the default for network authentication in the Windows NT 4.0 operating system. It is retained in Windows 2000 for compatibility with down-level clients and servers. 

NTLM will not be considered in our near future because it may be a small demand.

Contributions are welcome.

**Comment by ltcon** [comment]
同问，能否增加 NTLM 验证的支持？本地 Exchange 服务器需要 NTLM 验证方式。
