### ISSUE TITLE
平滑升级最新版本后发现tengine删除了以前一些模块的编译

### ISSUE THREAD

**Issue by Ericmar** [alibaba/tengine#1413]
平滑升级最新版本后发现少以下模块
--with-http_concat_module
-with-http_dyups_module   
--with-http_dyups_lua_api
--with-http_sysguard_module
--with-http_upstream_check_module
这些模块是否以后就不提供了，官方文档看了还不是最新的啊

**Comment by timoseven** [comment]
--add-module=./modules/nginx_upstream_check_module --add-module=./modules/ngx_http_lua_module --add-module=./modules/ngx_http_dyups_module
