### ISSUE TITLE
module 'ngx.dyups' not found:

### ISSUE THREAD

**Issue by IYism** [alibaba/tengine#1439]
关于tengine-2.3.0后的版本废弃--with-http_dyups_lua_api参数后，导致ngx.dyups模块找不到。老版tengine-2.2.3测试没有问题，希望修复下。谢谢

**Comment by IYism** [comment]
已经找到问题了，原因是add-module先后顺序问题导致的。
--add-module=modules/ngx_http_lua_module \
--add-module=modules/ngx_http_upstream_dyups_module \

**Comment by piggsoft** [comment]
@IYism 你是如何解决的，我按照这个顺序也无法解决问题，能否发下你的配置

**Comment by IYism** [comment]
@piggsoft Hi，我是用openresty官方全新的lua版本进行构建编译的。
https://github.com/openresty/lua-nginx-module
https://github.com/openresty/luajit2

编译参数如下：
./configure \
  --prefix=/etc/nginx \
  --sbin-path=/usr/sbin/nginx \
  --modules-path=/usr/lib64/tengine/modules \
  --conf-path=/etc/nginx/nginx.conf \
  --error-log-path=/var/log/nginx/error.log \
  --http-log-path=/var/log/nginx/access.log \
  --pid-path=/var/run/nginx.pid \
  --lock-path=/var/run/nginx.lock \
  --http-client-body-temp-path=/var/cache/nginx/client_temp \
  --http-proxy-temp-path=/var/cache/nginx/proxy_temp \
  --http-fastcgi-temp-path=/var/cache/nginx/fastcgi_temp \
  --http-uwsgi-temp-path=/var/cache/nginx/uwsgi_temp \
  --http-scgi-temp-path=/var/cache/nginx/scgi_temp \
  --user=www \
  --group=www \
  --with-compat \
  --with-file-aio \
  --with-threads \
  --with-http_addition_module \
  --with-http_auth_request_module \
  --with-http_dav_module \
  --with-http_flv_module \
  --with-http_gunzip_module \
  --with-http_gzip_static_module \
  --with-http_mp4_module \
  --with-http_random_index_module \
  --with-http_realip_module \
  --with-http_secure_link_module \
  --with-http_slice_module \
  --with-http_ssl_module \
  --with-http_stub_status_module \
  --with-http_sub_module \
  --with-http_v2_module \
  --with-mail \
  --with-mail_ssl_module \
  --with-http_xslt_module \
  --with-http_image_filter_module \
  --with-http_degradation_module \
  --with-http_geoip_module \
  --with-stream \
  --with-stream_realip_module \
  --with-stream_ssl_module \
  --with-stream_ssl_preread_module \
  --with-stream_geoip_module \
  --with-pcre-jit \
  --with-zlib=modules/zlib-1.2.11 \
  --with-pcre=modules/pcre-8.44 \
  --with-openssl=modules/openssl-1.1.1d \
  --add-module=modules/ngx_http_concat_module \
  --add-module=modules/ngx_http_upstream_check_module \
  --add-module=modules/ngx_http_dyups_module \
  --add-module=modules/ngx_http_sticky_module \
  --add-module=modules/ngx_http_echo_module \
  --add-module=modules/ngx_http_lua_module \
  --add-module=modules/ngx_http_lua_upstream_module \
  --add-module=modules/ngx_devel_kit_module
