### ISSUE TITLE
Tengine reload single config nginx

### ISSUE THREAD

**Issue by buisongtoan** [alibaba/tengine#1459]
Hi Team,

I not found feature that support 'Reload single config nginx' in your Tengine document.
I have various nginx config files, I want reload single nginx file configuration at time.

Help me, thank bro.

**Comment by wojiushixiaobai** [comment]
是这个吗?
```
nginx -s reload
```

**Comment by wangfakang** [comment]
@buisongtoan The operating parameters of Tengine are the same as Nginx.

**Comment by khaiphan9x** [comment]
> Hi Team,
> 
> I not found feature that support 'Reload single config nginx' in your Tengine document.
> I have various nginx config files, I want reload single nginx file configuration at time.
> 
> Help me, thank bro.

English của người việt 😆
