### ISSUE TITLE
nginx -V 不显示默认安装的模块

### ISSUE THREAD

**Issue by fengdoudm** [alibaba/tengine#1468]
## Question
版本：2.3.0
安装命令
./configure --prefix=/usr/local/tengine-2.3.0
make &&make install

安装完成后使用nginx -V查看已安装的模块，发现什么也不显示
![image](https://user-images.githubusercontent.com/8956444/84492268-860af580-acd8-11ea-9c42-e50eef981405.png)

同样的安装命令，使用版本2.2.0，是显示的
![image](https://user-images.githubusercontent.com/8956444/84492432-c1a5bf80-acd8-11ea-9c7f-bfc90c3c45a7.png)

红色框里东西，在2.3.0以上的版不显示了
难道是后面的版本不显示已安装的模块了吗，还是我安装错了，麻烦看看，谢谢。

**Comment by yourchanges** [comment]
nginx -V -m

**Comment by fengdoudm** [comment]
@yourchanges   眼拙，没看到，谢谢。
