### ISSUE TITLE
configure --help 求助

### ISSUE THREAD

**Issue by cpu100** [alibaba/tengine#1477]
为什么 configure --help 显示的只有 nginx 原有模块，看不到 tengine 自研模块相关帮助信息！

**Comment by cpu100** [comment]
```
# ./configure --with-http_concat_module
./configure: error: invalid option "--with-http_concat_module"
```

**Comment by cpu100** [comment]
```
# ./configure --add-module=modules/ngx_http_concat_module
configuring additional modules
adding module in modules/ngx_http_concat_module
 + ngx_http_concat_module was configured
```
只能以这种方式编译么？

**Comment by Lin-Buo-Ren** [comment]
透過二元搜尋可以定位出引入相關變更的修訂提交為 736801a6848b56c9c013cb5221aa878ea0c41907 ：

```
736801a6848b56c9c013cb5221aa878ea0c41907 is the first bad commit
commit 736801a6848b56c9c013cb5221aa878ea0c41907
Author: wangfakang <fakangwang@gmail.com>
Date:   Sat Dec 22 16:07:53 2018 +0800

    Extract the concat module.

 auto/modules                                       |   1 -
 auto/options                                       |   7 -
 auto/sources                                       |   4 -
 modules/ngx_http_concat_module/config              |   4 +
 .../ngx_http_concat_module.c                       | 549 +++++++++++++++++++++
 src/http/modules/ngx_http_concat_module.c          | 549 ---------------------
 6 files changed, 553 insertions(+), 561 deletions(-)
 create mode 100644 modules/ngx_http_concat_module/config
 create mode 100644 modules/ngx_http_concat_module/ngx_http_concat_module.c
 delete mode 100644 src/http/modules/ngx_http_concat_module.c
 ```
 
不知道 @wangfakang 大神能不能說明下為何要做這個變更，以及有沒有在什麼地方有特別說明相關的異動，感謝

**Comment by wangfakang** [comment]
> 透過二元搜尋可以定位出引入相關變更的修訂提交為 [736801a](https://github.com/alibaba/tengine/commit/736801a6848b56c9c013cb5221aa878ea0c41907) ：
> 
> ```
> 736801a6848b56c9c013cb5221aa878ea0c41907 is the first bad commit
> commit 736801a6848b56c9c013cb5221aa878ea0c41907
> Author: wangfakang <fakangwang@gmail.com>
> Date:   Sat Dec 22 16:07:53 2018 +0800
> 
>     Extract the concat module.
> 
>  auto/modules                                       |   1 -
>  auto/options                                       |   7 -
>  auto/sources                                       |   4 -
>  modules/ngx_http_concat_module/config              |   4 +
>  .../ngx_http_concat_module.c                       | 549 +++++++++++++++++++++
>  src/http/modules/ngx_http_concat_module.c          | 549 ---------------------
>  6 files changed, 553 insertions(+), 561 deletions(-)
>  create mode 100644 modules/ngx_http_concat_module/config
>  create mode 100644 modules/ngx_http_concat_module/ngx_http_concat_module.c
>  delete mode 100644 src/http/modules/ngx_http_concat_module.c
> ```
> 
> 不知道 @wangfakang 大神能不能說明下為何要做這個變更，以及有沒有在什麼地方有特別說明相關的異動，感謝

https://github.com/alibaba/tengine/issues/1220 这个里面提到的注意事项中的第 4 条有说明的。

**Comment by Lin-Buo-Ren** [comment]
> [#1220](https://github.com/alibaba/tengine/issues/1220) 这个里面提到的注意事项中的第 4 条有说明的。

感謝說明
