### ISSUE TITLE
HTTp 3 都出来好久乐什么时候 支持,,,,, 3年了，估计挂了

### ISSUE THREAD

**Issue by icetech233** [alibaba/tengine#1488]
HTTp 3 都出来好久乐什么时候 支持

**Comment by mrpre** [comment]
已安排@Lynskylate 支持

**Comment by jack9603301** [comment]
等待中

**Comment by lianglli** [comment]
XQUIC后面会开源。

**Comment by jack9603301** [comment]
QUIC在nginx已经实现，请见nginx-quic技术预览版，我这里也有一个repo，涵盖了nginx的一些模块，并且采用的nginx是nginx-quic，
https://github.com/jack9603301/nginx-enhance-module
我的个人博客，www.qhjack.cn的前置代理服务器，已经完成到nginx-quic的支持和迁移，使用的就是我自己写的repo

**Comment by lianglli** [comment]
> QUIC在nginx已经实现，请见nginx-quic技术预览版，我这里也有一个repo，涵盖了nginx的一些模块，并且采用的nginx是nginx-quic，
> https://github.com/jack9603301/nginx-enhance-module
> 我的个人博客，www.qhjack.cn的前置代理服务器，已经完成到nginx-quic的支持和迁移，使用的就是我自己写的repo
> 
> node:由于nginx官方repo使用mercurial托管，所以要安装mercurial(hg)，支持quic目前最好的方法是切换上游核心源码到技术预览版（nginx-quic分支)

Tengine的XQUIC是自研的HTTP3/QUIC实现，已经在生产环境使用。

**Comment by jack9603301** [comment]
> > QUIC在nginx已经实现，请见nginx-quic技术预览版，我这里也有一个repo，涵盖了nginx的一些模块，并且采用的nginx是nginx-quic，
> > https://github.com/jack9603301/nginx-enhance-module
> > 我的个人博客，www.qhjack.cn的前置代理服务器，已经完成到nginx-quic的支持和迁移，使用的就是我自己写的repo
> > node:由于nginx官方repo使用mercurial托管，所以要安装mercurial(hg)，支持quic目前最好的方法是切换上游核心源码到技术预览版（nginx-quic分支)
> 
> Tengine的XQUIC是自研的HTTP3/QUIC实现，已经在生产环境使用。

使用nginx的话，nginx自身有一个QUIC的实现，可以去试试看，建议考虑nginx-quic

**Comment by jack9603301** [comment]
> > > QUIC在nginx已经实现，请见nginx-quic技术预览版，我这里也有一个repo，涵盖了nginx的一些模块，并且采用的nginx是nginx-quic，
> > > https://github.com/jack9603301/nginx-enhance-module
> > > 我的个人博客，www.qhjack.cn的前置代理服务器，已经完成到nginx-quic的支持和迁移，使用的就是我自己写的repo
> > > node:由于nginx官方repo使用mercurial托管，所以要安装mercurial(hg)，支持quic目前最好的方法是切换上游核心源码到技术预览版（nginx-quic分支)
> > 
> > 
> > Tengine的XQUIC是自研的HTTP3/QUIC实现，已经在生产环境使用。
> 
> 感觉遥遥无期

我建议使用来自上游的nginx-quic

**Comment by icetech233** [comment]
> 已安排@Lynskylate 支持

摸鱼工程师 是什么梗

**Comment by MengqiWu** [comment]
> > > > QUIC在nginx已经实现，请见nginx-quic技术预览版，我这里也有一个repo，涵盖了nginx的一些模块，并且采用的nginx是nginx-quic，
> > > > https://github.com/jack9603301/nginx-enhance-module
> > > > 我的个人博客，www.qhjack.cn的前置代理服务器，已经完成到nginx-quic的支持和迁移，使用的就是我自己写的repo
> > > > node:由于nginx官方repo使用mercurial托管，所以要安装mercurial(hg)，支持quic目前最好的方法是切换上游核心源码到技术预览版（nginx-quic分支)
> > > 
> > > 
> > > Tengine的XQUIC是自研的HTTP3/QUIC实现，已经在生产环境使用。
> > 
> > 
> > 感觉遥遥无期
> 
> 我建议使用来自上游的nginx-quic

你可以提一个mr，最好包含完整的文档介绍、测试case等，如果可能的话尽量详细一些，方便review，另外建议为了保证稳定性，增加编译宏等，如果质量比较高，社区大家一起review，如果能进去的话，应该会有还不错的应用场景

**Comment by jack9603301** [comment]
> > > > > QUIC在nginx已经实现，请见nginx-quic技术预览版，我这里也有一个repo，涵盖了nginx的一些模块，并且采用的nginx是nginx-quic，
> > > > > https://github.com/jack9603301/nginx-enhance-module
> > > > > 我的个人博客，www.qhjack.cn的前置代理服务器，已经完成到nginx-quic的支持和迁移，使用的就是我自己写的repo
> > > > > node:由于nginx官方repo使用mercurial托管，所以要安装mercurial(hg)，支持quic目前最好的方法是切换上游核心源码到技术预览版（nginx-quic分支)
> > > > 
> > > > 
> > > > Tengine的XQUIC是自研的HTTP3/QUIC实现，已经在生产环境使用。
> > > 
> > > 
> > > 感觉遥遥无期
> > 
> > 
> > 我建议使用来自上游的nginx-quic
> 
> 你可以提一个mr，最好包含完整的文档介绍、测试case等，如果可能的话尽量详细一些，方便review，另外建议为了保证稳定性，增加编译宏等，如果质量比较高，社区大家一起review，如果能进去的话，应该会有还不错的应用场景

只要更新nginx主线到nginx-quic就行了，它和nginx最新主线同步，并且在此基础上实现nginx

**Comment by meilihao** [comment]
@lianglli 请问xquic去年就开始宣传会在2020年底开源，后来说是2021年第一季度，结果就没消息了， 是黄了吗？

**Comment by yuchonghua** [comment]
QUIC 还没有戏吗？是黄了吗

**Comment by icetech233** [comment]
安排完了吗？？

**Comment by yuchonghua** [comment]
大佬，有关于 nginx-quic  和 nginx 的区别的一些更详细的资料吗?
目前想 把 动态更新 upstream 和  http代理 能集成到 nginx-quic 。。。
/ping @jack9603301

**Comment by GumpSun** [comment]
Tengine XQUIC怎么样了？

**Comment by icetech233** [comment]
支持了吗

**Comment by meilihao** [comment]
xquic [stable-1.0.0](https://github.com/alibaba/xquic/releases/tag/stable-1.0.0) 都已发布超一个月，这个issue还是没动静吗？

**Comment by icetech233** [comment]
> > xquic [stable-1.0.0](https://github.com/alibaba/xquic/releases/tag/stable-1.0.0) 都已发布超一个月，这个issue还是没动静吗？
> 
> [alibaba/xquic#147](https://github.com/alibaba/xquic/issues/147)

可以用了吗？

**Comment by aak1247** [comment]
Does this issue have any update?

**Comment by jack9603301** [comment]
> > Does this issue have any update?
> 
> 挂了吧

直接使用nginx

**Comment by Yanmei-Liu** [comment]
实际上我们已经准备了tengine支持http3的整包版本，近期在密集验证，将于4月初发布

**Comment by ff2035** [comment]
> 实际上我们已经准备了tengine支持http3的整包版本，近期在密集验证，将于4月初发布

5月中了，有什么进展吗？

**Comment by jack9603301** [comment]
> > 实际上我们已经准备了tengine支持http3的整包版本，近期在密集验证，将于4月初发布
> 
> 5月中了，有什么进展吗？

使用nginx的话，nginx自身有一个QUIC的实现，可以去试试看，建议考虑nginx-quic，nginx-quic在nginx社区和nginx主线版本同步

http://hg.nginx.org/nginx-quic

**Comment by HEMINSAN** [comment]
> 实际上我们已经准备了tengine支持http3的整包版本，近期在密集验证，将于4月初发布

请问这个有发布计划吗？

**Comment by clywm520** [comment]
when  tengin can support http3.0  . the nginx-1.25.0 mainline version already support

**Comment by StrangePeanut** [comment]
NGINX Mainline includes support for HTTP/3 but it's significantly slower than HTTP/2. Built with QuicTLS. I think it's a good idea to wait till it's ready and reaches NGINX Stable or Tengine publishes their implementation.

**Comment by jack9603301** [comment]
> NGINX Mainline includes support for HTTP/3 but it's significantly slower than HTTP/2 when built with quictls/openssl. I think it's a good idea to wait till it reaches NGINX Stable or Tengine introduces its own implementation.

use http://hg.nginx.org/nginx-quic

**Comment by drawing** [comment]
Tengine 3.0.0 版本已集成 xquic，支持 http3
http://tengine.taobao.org/document_cn/xquic_cn.html
https://github.com/alibaba/tengine/blob/master/modules/ngx_http_xquic_module/README.md

**Comment by clywm520** [comment]
我尝试了好多次，HTTP3.0 默认使用不了，访问总是HTTP2.0协议 。 K8S镜像 tengine-ingress-registry.cn-hangzhou.cr.aliyuncs.com/tengine/tengine-ingress:1.0.0
改了很多遍 configMap都不行。
能提供OK的配置不。

难道只能是 容器和宿主机的操作系统都必须是[Anolis] 么。centos不支持么

以下官方配置原文
默认不启用XUDP，如果设置use-xquic-xudp: 'true'，容器和宿主机的操作系统都必须是[Anolis](https://hub.docker.com/r/openanolis/anolisos)才能使用XUDP。
Tengine XUDP Module主要用于在服务端启用XUDP，支持bypass内核的用户态高性能UDP转发。
服务端启用HTTP3/QUIC监听服务，通过配合使用XUDP，可大幅提升HTTP3转发性能。

**Comment by jack9603301** [comment]
> 我尝试了好多次，HTTP3.0 默认使用不了，访问总是HTTP2.0协议 。 K8S镜像 tengine-ingress-registry.cn-hangzhou.cr.aliyuncs.com/tengine/tengine-ingress:1.0.0 改了很多遍 configMap都不行。 能提供OK的配置不。
> 
> 难道只能是 容器和宿主机的操作系统都必须是[Anolis] 么。centos不支持么
> 
> 以下官方配置原文 默认不启用XUDP，如果设置use-xquic-xudp: 'true'，容器和宿主机的操作系统都必须是[Anolis](https://hub.docker.com/r/openanolis/anolisos)才能使用XUDP。 Tengine XUDP Module主要用于在服务端启用XUDP，支持bypass内核的用户态高性能UDP转发。 服务端启用HTTP3/QUIC监听服务，通过配合使用XUDP，可大幅提升HTTP3转发性能。

use http://hg.nginx.org/nginx-quic

**Comment by clywm520** [comment]
@drawing  HTTP3.0是还没有完全实现么，能提供一份，完整的K8S配置么.试了好多遍，还是没有成功。 同类产品traefik一次成功

**Comment by jack9603301** [comment]
> @drawing HTTP3.0是还没有完全实现么，能提供一份，完整的K8S配置么.试了好多遍，还是没有成功。 同类产品traefik一次成功

你可以直接使用nginx-quic

**Comment by drawing** [comment]
https://github.com/alibaba/tengine/blob/master/modules/ngx_http_xquic_module/README.md#%E6%B5%8F%E8%A7%88%E5%99%A8%E4%BD%BF%E7%94%A8-http3
