### ISSUE TITLE
dyups.t fails in 2.3.3

### ISSUE THREAD

**Issue by harry-xm** [alibaba/tengine#1555]
### Ⅰ. Issue Description
The `tengine-2.3.3/tests/nginx-tests/tengine-tests/dyups.t` test FAILs.

### Ⅱ. Describe what happened
```
tengine-tests/dyups.t .. 
Dubious, test returned 22 (wstat 5632, 0x1600)
Failed 22/78 subtests 

Test Summary Report
-------------------
tengine-tests/dyups.t (Wstat: 5632 Tests: 78 Failed: 22)
  Failed tests:  1-3, 8-9, 15, 18-19, 21-23, 26, 54-56, 58-59
                61-64, 66
  Non-zero exit status: 22
Files=1, Tests=78,  7 wallclock secs ( 0.02 usr  0.00 sys +  0.15 cusr  0.21 csys =  0.38 CPU)
Result: FAIL
```

### Ⅲ. Describe what you expected to happen
`Result: PASS`

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. Build Tengine.
2. `TEST_NGINX_BINARY=/path/to/nginx/sbin/nginx prove -Inginx-tests/lib tengine-tests/dyups.t`

### Ⅴ. Anything else we need to know?

1. In Tengine 2.3.1, this test passes.

### Ⅵ. Environment:

- Tengine version (use `sbin/nginx -V`): 2.3.3
- OS (e.g. from /etc/os-release): CentOS 7
- Kernel (e.g. `uname -a`): 5.4
- Others:

**Comment by harry-xiaomi** [comment]
Git bisect shows that the regression was introduced in commit 8bd5ae2685a4262cbba05d13c292bae59296bad2 by @wangfakang in #1379.

This commit also introduces a bug that inhibits upstream updates in certain conditions. With the following Nginx configuration and test script, last line of output is `8088`. With this commit reverted, it will be `8089` instead.

```nginx
daemon off;

#user  nobody;
worker_processes  1;

events {
    worker_connections  1024;
}


http {
    include       mime.types;
    default_type  application/octet-stream;

    upstream host1 {
        server 127.0.0.1:8088;
    }

    upstream host2 {
        server 127.0.0.1:8089;
    }

    server {
        listen   8080;

        location / {
            proxy_pass http://$host;
        }
    }

    server {
        listen 8088;
        location / {
            return 200 "8088";
        }
    }

    server {
        listen unix:/tmp/dyupssocket;
        location / {
            return 200 "unix";
        }
    }

    server {
        listen 8089;
        location / {
            return 200 "8089";
        }
    }

    server {
        listen 8081;
        location / {
            dyups_interface;
        }
    }
}
```

Test script with Nginx running in background:

```sh
curl -H 'Host: host1' 127.0.0.1:8080
curl -X POST --data-binary 'server 127.0.0.1:8089;' 127.0.0.1:8081/upstream/dyhost
curl -X POST --data-binary 'server 127.0.0.1:8089;' 127.0.0.1:8081/upstream/host1
curl -vH 'Host: host1' 127.0.0.1:8080
```

**Comment by chobits** [comment]
fixed in https://github.com/alibaba/tengine/pull/1660
