### ISSUE TITLE
Bilibili网页崩溃

### ISSUE THREAD

**Issue by Ricardoxma** [alibaba/tengine#1569]
### Ⅰ. Issue Description
突然发生的网页502和404错误，网络没有问题。

### Ⅱ. Describe what happened
![image](https://user-images.githubusercontent.com/48750020/125475289-ee9690e6-b8bb-4607-82e8-f3a63fc9badc.png)

URL: | https://www.bilibili.com/
Server: | ks-sccd-dx-w-04
Date: | 2021/07/13 22:55:31

### Ⅲ. Describe what you expected to happen
期望检查是网站服务器问题还是个人问题，如果是个人问题应该如何避免。

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1.
2.
3.

### Ⅴ. Anything else we need to know?

1. If applicable, add nginx  [debug log doc](http://nginx.org/en/docs/debugging_log.html).
2.
3.

### Ⅵ. Environment:

- Tengine version (use `sbin/nginx -V`):
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Others:

**Comment by yujiaze00** [comment]
能看到tengine页面证明不是tengine的问题，单纯是叔叔的应用服务挂了而已。

**Comment by kuyenda** [comment]
肯定是服务器挂了啊

**Comment by ky90** [comment]
ping bilibili.com 没问题，但是出现404  Not Found 页面。 

![404 not found](https://user-images.githubusercontent.com/35365166/125484362-19f50902-d7c9-41c3-952b-1ed88cd8eb2b.png)

**Comment by mrpre** [comment]
@yujiaze00 是的，tengine挂了你就啥都看不到了
