### ISSUE TITLE
阿这，bilibili404了哇

### ISSUE THREAD

**Issue by atXuQian** [alibaba/tengine#1570]
## Question
显示：
Sorry for the inconvenience.
Please report this message and include the following information to us.
Thank you very much!
URL: | https://www.bilibili.com/
-- | --
Server: | ks-hnzz-cu-w-01
Date: | 2021/07/13 23:00:11

**Comment by sunzhiyu526** [comment]
今晚tengine要火（

**Comment by helloanzhe** [comment]
哈哈

**Comment by mrpre** [comment]
如果p站挂了也这样提示，tengine就能火遍全球了

**Comment by aholic** [comment]
@chobits  help

**Comment by chobits** [comment]
> @chobits help

应该是后台挂了。
