### ISSUE TITLE
使用nginx1.180+http_upstream_check_module

### ISSUE THREAD

**Issue by dddrecall** [alibaba/tengine#1573]
## Question

使用nginx1.180+http_upstream_check_module
访问状态页的时候出现看不到upstream节点 请问这是啥情况
![image](https://user-images.githubusercontent.com/8815759/126061359-4543b1fe-ec47-4e30-8ee9-c64a9b89bab8.png)

**Comment by yaoweibin** [comment]
给一下你的配置和编译参数

淡淡的回忆 ***@***.***> 于2021年7月18日周日 下午4:51写道：
