### ISSUE TITLE
Tengine 2.5.1 print log bug

### ISSUE THREAD

**Issue by liketic** [alibaba/tengine#1607]
### Ⅰ. Issue Description

msg:490#490: *978936 write() to "log file" failed (11: Resource temporarily unavailable) while logging request, client: 11.199.94.62, server: , request: "POST / HTTP/1.1", upstream: "fastcgi://unix:/dev/shm/fcgi.sock", host: "xxx"

### Ⅱ. Describe what happened

从错误时间看，可以确定和日志轮转有关。

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1.
2.
3.

### Ⅴ. Anything else we need to know?

1. If applicable, add nginx  [debug log doc](http://nginx.org/en/docs/debugging_log.html).
2.
3.

### Ⅵ. Environment:

- Tengine version (use `sbin/nginx -V`):
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Others:

**Comment by yangyingda2020** [comment]
I encountered the same issue using Tengine 2.5.4.

I can confirm  no relate with logrotate

**Comment by drawing** [comment]
tengine worker进程通过管道写入日志rollback进程，滚动时删除文件可能导致rollback进程卡顿导致，导致管道写满日志丢失。由于异步写入，无法绝对避免此问题：

缓解此问题方案：

1. 通过 https://github.com/alibaba/tengine/pull/1965 增加设置pipe大小指令，通过适当调大管道大小，可以在rollback进程卡顿时缓解问题
2. 通过第三方程序如 crontab 脚本定时删除一段时间内无写入的日志文件，通过外部进程异步删除文件，不会导致rollback卡顿
3. 如要保证完全不丢失日志，只能改为同步写文件，但是会导致磁盘卡顿时影响 worker 进程，不推荐使用
