### ISSUE TITLE
Tengine还在开发和维护吗？

### ISSUE THREAD

**Issue by cnmade** [alibaba/tengine#1615]
F5 宣布制裁和禁止俄罗斯程序员和公司访问nginx代码的新闻大家也都看到了。

没有自己研发和发展技术的后果，就是被别人无限制裁，穿小鞋。

Nginx本是俄罗斯人开发，但是被收购之后，现在直接翻脸。

那么我们的tengine是就这样失去了活力么？不再研发和维护了吗？

多么可惜 的一个项目，很重要，很基础。但是没有然后了。

**Comment by Yanmei-Liu** [comment]
非常感谢您对Tengine的关注。Tengine在内部一直有在更新和迭代，因为一些原因过去两年开源社区更新速度较慢，但今年我们会重新逐步升级和迭代开源社区版本。如果您有任何新功能需求或bugfix需求，欢迎在issue区提出。

**Comment by cnmade** [comment]
你好，bug倒是没有，就是看到跟上游nginx sync 同步没及时，感觉走远了。。。

**Comment by Hsuing** [comment]
tengine2.3.3 执行lua脚本的时候提示，nginx: [emerg] unknown directive "set_by_lua_block"，在openresty和nginx上执行就没有这个错误，这个是什么原因导致

**Comment by saintdianabless** [comment]
> 非常感谢您对Tengine的关注。Tengine在内部一直有在更新和迭代，因为一些原因过去两年开源社区更新速度较慢，但今年我们会重新逐步升级和迭代开源社区版本。如果您有任何新功能需求或bugfix需求，欢迎在issue区提出。

2022年已经快过去大半，不知道从什么时候开始重新逐步升级迭代开源版本呢？

**Comment by lihulanxx** [comment]
坑

**Comment by kaka2008** [comment]
看来真是KPI，晋升了之后就没人管了

**Comment by cnmade** [comment]
所以说：中国人，从来就不缺聪明的人，能干的人。问题是不持久，不坚挺。     

一开始给你一个非常Good idea，领先别人好几年。然后过几年，发现没有然后了。。。
就这么悄无声息的无了。。。


公司财源，部门解散，仿佛没来过一样。 就冒了一个泡。然后，幻灭。

中国是做不了基础软件，自己的操作系统的。

无他：不可持续。

**Comment by cnmade** [comment]
说句难听的，甚至不如我个人的项目，从2015一直积极维护更新，bug修复。直到今天，并将持续下去。已经维护了7年，还会维护更多年。

**Comment by kaka2008** [comment]
喜大普奔，终于更新了
