### ISSUE TITLE
pipe rollback and dirty process

### ISSUE THREAD

**Issue by 1092845214** [alibaba/tengine#1647]
我正在使用 pipe rollback log 功能, tengine(version2.3.2) in docker(version19)

配置部分如下, 容器并没有重启过
![image](https://user-images.githubusercontent.com/42507101/192742560-1a382ddd-996a-4e50-b4be-044dd50fee58.png)

1. 日志没有到达 interval时间, 就进行了切割, 而且日志并没有到达最大 size
![image](https://user-images.githubusercontent.com/42507101/192742390-400ed188-097a-4784-afdd-5c2de6763a37.png)

2. access.log.1 应该是 09.27 的日志, 但实际上它包含了很多 09.26 的日志
![image](https://user-images.githubusercontent.com/42507101/192744402-71c5d98d-efd8-4def-a052-451eac423c07.png)

3. 进程中出现了很多这样的进程
![image](https://user-images.githubusercontent.com/42507101/192743805-77413887-269b-4e91-b987-6430b733aac8.png)

**Comment by drawing** [comment]
使用 rollback 日志功能后，tengine 会通过管道传输日志给 rollback 进程打印，出现 rollback 进程是符合预期的

interval=1d，每天都会滚动，看第一个截图里 22-25 号每天一个日志不是符合预期的么，26号超过10G做了切分，而且看进程启动时间是 Sep26，应该是有重启吧，27凌晨没有切分导致 27号日志有部分26号的日志

**Comment by 732504350** [comment]
我也出现了大量没有释放的rollback进程
