### ISSUE TITLE
dyups module: inconsistent unlocking after trylock failure

### ISSUE THREAD

**Issue by harry-xm** [alibaba/tengine#1661]
## Question
In [ngx_http_dyups_module.c](https://github.com/alibaba/tengine/blob/6ad5e5ac8bdfd67caef3f00a0c1de07bbed1e6c2/modules/ngx_http_upstream_dyups_module/ngx_http_dyups_module.c), several functions may call `ngx_shmtx_trylock`, but only one of them keeps the mutex locked on failure.

Unlocking a mutex held by others doesn't make sense and destroys exclusivity. Is it intentional?

In `ngx_dyups_delete_upstream`, the mutex is not touched on failure.

https://github.com/alibaba/tengine/blob/6ad5e5ac8bdfd67caef3f00a0c1de07bbed1e6c2/modules/ngx_http_upstream_dyups_module/ngx_http_dyups_module.c#L747-L749

On the other hand, in `ngx_dyups_update_upstream`

https://github.com/alibaba/tengine/blob/6ad5e5ac8bdfd67caef3f00a0c1de07bbed1e6c2/modules/ngx_http_upstream_dyups_module/ngx_http_dyups_module.c#L1235-L1263

and `ngx_http_dyups_read_msg`, the mutex is unlocked with `ngx_shmtx_unlock(&shpool->mutex);`.

https://github.com/alibaba/tengine/blob/6ad5e5ac8bdfd67caef3f00a0c1de07bbed1e6c2/modules/ngx_http_upstream_dyups_module/ngx_http_dyups_module.c#L2083-L2096

---

Originally posted on https://github.com/alibaba/tengine/pull/1480/files#r615507046. I'm submitting a new issue to draw attention.

**Comment by chobits** [comment]
> Unlocking a mutex held by others doesn't make sense and destroys exclusivity. Is it intentional?

No. It's a bug, we should move "finished:" label to L2095

**Comment by chobits** [comment]
We should review this https://github.com/alibaba/tengine/pull/1480/ again.

The try_lock logic should be in `if (dyups->trylock)` instead of in `macro #UPSTREAM CHECK`. There is directive `dyups_trylock on|off;` also.

**Comment by chobits** [comment]
The following `goto finish` has the same problem:

https://github.com/alibaba/tengine/blob/6ad5e5ac8bdfd67caef3f00a0c1de07bbed1e6c2/modules/ngx_http_upstream_dyups_module/ngx_http_dyups_module.c#L1238-L1264

**Comment by chobits** [comment]
hi @harry-xm 

Although the code logic seems to have bugs, it will not cause real damage to nginx.
Because ngx_shmtx_unlock() will not unlock other worker's lock, it check the pid number with mutex, if the pid number(mutex lock) is not pid of current worker, it does nothing.
