### ISSUE TITLE
Is `dyups_trylock` stable?

### ISSUE THREAD

**Issue by harry-xm** [alibaba/tengine#1663]
## Question

#1480 uses trylock unconditionally if `NGX_HTTP_UPSTREAM_CHECK` is defined compile-time, but all other calls in the dyups module are guarded by a check for `dmcf->trylock`.

[`dyups_trylock`](https://github.com/alibaba/tengine/blob/6ad5e5ac8bdfd67caef3f00a0c1de07bbed1e6c2/docs/modules/ngx_http_dyups_module.md#dyups_trylock) is considered "maybe not stable" and is off by default. What are the trade-offs of enabling it and how might PR #1480 affect stability of service?

**Comment by chobits** [comment]
> [dyups_trylock](https://github.com/alibaba/tengine/blob/6ad5e5ac8bdfd67caef3f00a0c1de07bbed1e6c2/docs/modules/ngx_http_dyups_module.md#dyups_trylock) is considered "maybe not stable" and is off by default. What are the trade-offs of enabling it and how might PR https://github.com/alibaba/tengine/pull/1480 affect stability of service?

"maybe not stable" means that **your operating request** (include DELETE/UPDATE upstream dynamically) may fail sometimes. If it failed, you just need to do it again. It will not make **normal requests** from clients unstable.

 > https://github.com/alibaba/tengine/pull/1480 uses trylock unconditionally if NGX_HTTP_UPSTREAM_CHECK

This patch is ok. It makes health checking work better, but synchronizing upstream list will delay sometimes, which has almost no impact.
