### ISSUE TITLE
VNSWRR can reduce memory usage with GCD

### ISSUE THREAD

**Issue by jizhuozhi** [alibaba/tengine#1667]
## Why you need it?
VNSWRR generates peeking sequence according NGINX SWRR. After fully expanded, the number of virtual nodes are the sum of weights (named `total_weight`).

But in fact the NGINX sequence is generated according to the weight ratio, and the minimum positive period is the sum of all weight ratios. For example, if we have three upstream servers, with weights `1, 2, 4`, the minimum positive period is `7`. 
But if we scale up all the weights in equal proportions to `100, 200, 400` or more, the ratios are still `1, 2, 4`, the minimum positive period is still `7` but not the total weight `700`.

## How it could be?
The first 7 virtual nodes is also named recurring section, it means that the parts beyond these 7 nodes are repeating this section, and the number of repetitions is the GCD of all weights. So we could just generate recurring section and no longer generate  the parts beyond these.

**Comment by jizhuozhi** [comment]
In fact, VNSWRR takes `O(n)` time for each node to be expanded, but only `O(1)` time (evolved into Round Robin) is required when this node is accessed again after expanded, so an earlier full expansion can optimize this part of the bootstrap time.

**Comment by wangfakang** [comment]
> ## Why you need it?
> VNSWRR generates peeking sequence according NGINX SWRR. After fully expanded, the number of virtual nodes are the sum of weights (named `total_weight`).
> 
> But in fact the NGINX sequence is generated according to the weight ratio, and the minimum positive period is the sum of all weight ratios. For example, if we have three upstream servers, with weights `1, 2, 4`, the minimum positive period is `7`. But if we scale up all the weights in equal proportions to `100, 200, 400` or more, the ratios are still `1, 2, 4`, the minimum positive period is still `7` but not the total weight `700`.
> 
> ## How it could be?
> The first 7 virtual nodes is also named recurring section, it means that the parts beyond these 7 nodes are repeating this section, and the number of repetitions is the GCD of all weights. So we could just generate recurring section and no longer generate the parts beyond these.

Yes. BTW wouldn't it be better to handle the GCD of the weights in the control plane.


> In fact, VNSWRR takes `O(n)` time for each node to be expanded, but only `O(1)` time (evolved into Round Robin) is required when this node is accessed again after expanded, so an earlier full expansion can optimize this part of the bootstrap time.

This is to avoid resource burrs during full expansion initialization. Here is a document for a detailed introduction to [VNSWRR](https://mp.weixin.qq.com/s/3KZ99d94yqRDxEByn7nGWg).

**Comment by jizhuozhi** [comment]
> This is to avoid resource burrs during full expansion initialization. Here is a document for a detailed introduction to [VNSWRR](https://mp.weixin.qq.com/s/3KZ99d94yqRDxEByn7nGWg).

I'm sorry, I don't understand why earlier full expansion will bring the burrs. It just reduces repeating section after fully expanded but not full expansion at one time when the weights are changed.

**Comment by jizhuozhi** [comment]
> Yes. BTW wouldn't it be better to handle the GCD of the weights in the control plane.

Not all companies have a well-developed devops infrastructure. In many cases they may not have a control plane and instead use nginx configuration files directly to manage these upstream servers.

Take a simple business scenario (maybe not so reasonable in a large-scale technology company, but it does exist). We release a new version of the service to an online cluster for canary release (but independent grouping). In order to minimize the impact on production, we allocate one thousandth or one millionth of the traffic to this canary server, then because we are all non-negative integers, we can only weight other servers Turn up a very high value. When the canary release was over, we released the full volume. Maybe the person in charge of the release did not understand why the weight was set so high in the first place. He simply deleted the canary server, but all the machines are this relatively high weight. 

Then the number of repetitions at this time is very large, and we need a lot of time and very large memory to fully expand, but in fact we don't need that.

This example may not be very reasonable, but it reflects two problems
1. Not all companies have an adequate infrastructure to differentiate between the control plane and the data plane (maybe it's a server that is temporarily installed by interns)
2. The user may unconsciously set the weights to be very large, and no one tells him the impact of this

**Comment by chobits** [comment]
I think it is good to improve memory usage for those servers that had been configured with large number of ` weight`.
