### ISSUE TITLE
Some tests still seems to failed

### ISSUE THREAD

**Issue by u5surf** [alibaba/tengine#1670]
### Ⅰ. Issue Description

Some tests still failed on the github actions.

### Ⅱ. Describe what happened

I would like to introduce the automatic tests with github actions in this repository.

Although some below tests seem to fail yet. I don't see whether it may not be enough for its configrations or dependencies or not.

https://github.com/u5surf/tengine/actions/runs/3361731928/jobs/5572510956

```

Test Summary Report
785
-------------------
786
tengine-tests/dynamic_resolve_aaaa.t      (Wstat: 256 Tests: 4 Failed: 1)
787
  Failed test:  2
788
  Non-zero exit status: 1
789
tengine-tests/resolver_file.t             (Wstat: 3840 Tests: 0 Failed: 0)
790
  Non-zero exit status: 15
791
  Parse errors: No plan found in TAP output
792
tengine-tests/string.t                    (Wstat: 256 Tests: 6 Failed: 1)
793
  Failed test:  4
794
  Non-zero exit status: 1
795
Files=26, Tests=608, 237 wallclock secs ( 0.10 usr  0.02 sys + 216.52 cusr  2.14 csys = 218.78 CPU)
796
Result: FAIL
797
Error: Process completed with exit code 1.
```

### Ⅲ. Describe what you expected to happen

All tests should be passed.

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. it occurs in this branch which applied the executing all the tests with github actions 
https://github.com/u5surf/tengine/commit/91ecb77db0f4bdc96e552222fa9f4e1838bc4916

### Ⅴ. Anything else we need to know?

1. If applicable, add nginx  [debug log doc](http://nginx.org/en/docs/debugging_log.html).
2.
3.

### Ⅵ. Environment:

- Tengine version (use `sbin/nginx -V`):
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Others:

**Comment by chobits** [comment]
resolver_file.t has been fixed in latest master branch .

And also note that this case will listen on port 53, it should be runned under root permission. ( using `sudo` in github workflow container will make it work
`sudo  prveo ...`

**Comment by chobits** [comment]
hi @u5surf 

In your ci.yml, you can skip failed test case firstly.

* These cases can be skipped currently.
  * dns daemon server port 8900 of dynamic_resolver_aaa.t 's should be changed to other port(maybe 18900). I ll fix it later
  * resolver_file.t should be worked under root permission for enabling tto listen on port 53.

May change your command from

```
TEST_NGINX_BINARY=/usr/local/nginx/sbin/nginx prove -v -Inginx-tests/lib tengine-tests
```

to 

```
cases=\
aaaa.t \
bbbb.t \
<list of successful cases name> \
zzzz.t

TEST_NGINX_BINARY=/usr/local/nginx/sbin/nginx prove -v -Inginx-tests/lib $cases
```

**Comment by chobits** [comment]
> dns daemon server port 8900 of dynamic_resolver_aaa.t 's should be changed to other port(maybe 18900 but I dont know why it cannot listen on 8000-9000, may look into Nginx.pm source). I ll fix it later

Nginx.pm port() function will test  whether listening port 127.0.0.1:8\d\d\d) can work, if it cannot work. It will replace 8\d\d\d port to other 8yyy port. This logic *may* occupy 127.0.0.1:8900 port (from resolver 127.0.0.1:8900 config), then dns_daemon() in dynamic_resolver_aaa.t cannot listen on that port.

**Comment by chobits** [comment]
dynamic_resolver_aaa.t has been fixed in https://github.com/alibaba/tengine/pull/1677
