### ISSUE TITLE
Tengine 配置国密 无法开放8080端口

### ISSUE THREAD

**Issue by zhangzhende** [alibaba/tengine#1690]
## Question

配置如下
`server {
        listen       8080 ssl;
        enable_ntls  on;
        ssl_sign_certificate       server_sign.crt;
        ssl_sign_certificate_key    server_sign.key;
        ssl_enc_certificate         server_enc.crt;
        ssl_enc_certificate_key     server_enc.key;

        location / {
                        root   html;
                        index  index.html index.htm;
        }
    }`
对于8080端口【虽然拿8080很蠢，但是就是试到了】，访问都是客户端和服务器不支持一般 SSL 协议版本或加密套件。
但是我换个端口，比如8081,444,443【其他的我不确定】等又都是正常的，不清楚是什么地方的限制，
望各位支持一手，THX

**Comment by nandsky** [comment]
可以提供一下 debug 日志？ 以及测试用的证书和密钥文件？

**Comment by zhangzhende** [comment]
并无日志产生，不过经进一步测试发现，这个可能不是tengine的问题，可能是我使用的浏览器问题，之前用的密信，会报这个问题，但是换成奇安信8080是正常的，啊~~~，抱歉
