### ISSUE TITLE
编译Tengine 提示：./configure: error: invalid option "--with-http_dyups_module"

### ISSUE THREAD

**Issue by weilai201** [alibaba/tengine#1715]
编译Tengine 提示：./configure: error: invalid option "--with-http_dyups_module"
如下是执行的命令
`./configure --prefix=/etc/nginx \
--sbin-path=/usr/sbin/nginx \
--conf-path=/etc/nginx/nginx.conf \
--error-log-path=/var/log/nginx/error.log \
--http-log-path=/var/log/nginx/access.log \
--pid-path=/var/run/nginx.pid \
--lock-path=/var/run/nginx.lock \
--http-client-body-temp-path=/var/cache/nginx/client_temp \
--http-proxy-temp-path=/var/cache/nginx/proxy_temp \
--http-fastcgi-temp-path=/var/cache/nginx/fastcgi_temp \
--http-uwsgi-temp-path=/var/cache/nginx/uwsgi_temp \
--http-scgi-temp-path=/var/cache/nginx/scgi_temp \
--with-http_ssl_module \
--with-http_realip_module \
--with-http_addition_module \
--with-http_sub_module \
--with-http_dav_module \
--with-http_flv_module \
--with-http_mp4_module \
--with-http_gunzip_module \
--with-http_gzip_static_module \
--with-http_random_index_module \
--with-http_secure_link_module \
--with-http_stub_status_module \
--with-http_auth_request_module \
--with-http_dyups_module \
--with-http_dyups_lua_api \
--with-mail \
--with-mail_ssl_module \
--with-file-aio \
--with-ipv6 \
--with-http_v2_module  \
--with-cc-opt='-O2 -g -pipe -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic' \
--add-module=/tmp/ngx_devel_kit-0.2.19 \
--add-module=/tmp/ngx-set-misc-module-0.29 \
--with-http_lua_module \
--with-luajit-lib=/usr/local/lib/ \
--with-luajit-inc=/usr/local/include/luajit-2.0/ \
--with-ld-opt=-Wl,-rpath,/usr/local/lib \
--with-openssl=/tmp/openssl-0.9.8zh
`

操作系统CentOS7.3
Tengine 版本：2.3.4

**Comment by weilai201** [comment]
> Use `--add-module=./modules/ngx_http_upstream_dyups_module` instead, see https://github.com/alibaba/tengine/blob/master/docs/modules/ngx_http_upstream_dyups_module.md#installation.

Thank you! I solved it.  
But when I execute `make` command, I get another error `error: label 'finish' defined but not used [-Werror=unused-label]`. After execute `./configure`,  i execute `sed -i 's/\-Werror//g' ./objs/Makefile`, remove the complie warning. And then ,I execute `make`, all things are ok!

**Comment by chobits** [comment]
think it resolved

**Comment by ponphy** [comment]
按照上述方法可以成功编译安装，但是该功能不能使用。
配置如下：
![image](https://user-images.githubusercontent.com/11926876/216285590-3f0de58b-2033-4530-81d5-a123b5eed163.png)


结果如下：
![image](https://user-images.githubusercontent.com/11926876/216285073-dd134254-7f36-49a4-b30d-d3a10ce17451.png)
