### ISSUE TITLE
Aliexpress server

### ISSUE THREAD

**Issue by hydrafi** [alibaba/tengine#1725]
Sorry for the inconvenience.
Please report this message and include the following information to us.
Thank you very much!
URL:	https://home.aliexpress.com/index.htm?spm=5261.report_f133k.0.0.3e6f788bwQd4nk
Server:	wagbridge.033001244154.us44
Date:	2023/01/05 19:53:22
Powered by Tengine

**Comment by drawing** [comment]
Tengine will return 500 when there is no machine in the backend upstream.

**Comment by hydrafi** [comment]
Hi,
but never available?

today error
 
Sorry for the inconvenience.
Please report this message and include the following information to us.
Thank you very much!URL:https://home.aliexpress.com/index.htm?spm=5261.report_f133k.0.0.1c46788bmEWBwpServer:wagbridge.033003033199.us68Date:2023/05/19 17:42:23Powered by Tengine 
 


(Le informazioni contenute in questo messaggio di posta elettronica o nei
suoi allegati sono riservate e confidenziali e ne è vietata la diffusione in
qualunque modo eseguita senza autorizzazione scritta. Qualora Lei non fosse
la persona a cui il presente messaggio è destinato, La invitiamo ad
eliminarlo e a non utilizzare in alcun caso il suo contenuto, dandone
gentilmente comunicazione al mittente. Grazie.
This e-mail message, the information it contains and any files attached are
subject to attorney-client privilege and D.Lgs. 196/2003 and contain
confidential information intended only for the person(s) to whom it is
addressed.  If you are not the intended recipient, you are hereby notified
that any use or distribution of this e-mail is strictly prohibited:  please
notify the sender and delete the original message.  Thank you.)
 





Da: "Bobo" ***@***.***
A: "alibaba/tengine" ***@***.***
Cc: "hydrafi" ***@***.***,"Author" ***@***.***
Data: Thu, 18 May 2023 00:22:33 -0700
Oggetto: Re: [alibaba/tengine] Aliexpress server (Issue #1725)



Tengine will return 500 when there is no machine in the backend upstream.

**Comment by drawing** [comment]
There is no business machine, this problem is not related to tengine, please consult within the alibaba group.
