### ISSUE TITLE
Advice: Don't re-tag in a public repository

### ISSUE THREAD

**Issue by harry-xm** [alibaba/tengine#1734]
## Question
It's not recommended to re-tag tags that have been pushed to github.com/alibaba/tengine to another commit. Checksums of GitHub-generated archives will change, breaking validation in downstream package managers like [Nix](https://github.com/NixOS/nixpkgs/blob/54cf191a16f67d4904dacdce8a6722dfc86fe42a/pkgs/servers/http/tengine/default.nix#L20).

This has happened at least twice before. Please cut a new release instead of updating an existing one.

**Comment by jiuzhoucui** [comment]
Thank you for your advice, we will pay attention to it in the future

**Comment by chobits** [comment]
ty, will pay attention later.

This issue was introduced by our mistake of releasing a wrong verison and then deleting it.

**Comment by chobits** [comment]
Should release new version to fix wrong version and not delete wrong version directly
