### ISSUE TITLE
configure error: stream_set module

### ISSUE THREAD

**Issue by seaurching** [alibaba/tengine#1741]
### Ⅰ. Issue Description
using `configure` to prepare install 
![image](https://user-images.githubusercontent.com/7349963/225866306-52c74cf3-a277-4fec-b670-4a76c52b0dbf.png)
![image](https://user-images.githubusercontent.com/7349963/225866538-10b14b6f-6b5e-4ea4-bb60-51bf9469dd8f.png)

auto/modules: line 1150: [: =: unary operator expected

### Ⅱ. Describe what happened

![image](https://user-images.githubusercontent.com/7349963/225866104-1c72f811-e765-4b5e-8197-735bda248fd1.png)

### Ⅵ. Environment:

![image](https://user-images.githubusercontent.com/7349963/225866792-d65d395e-5d4a-46b3-b8d4-57fc7bcea94d.png)

**Comment by seaurching** [comment]
ADD environment STREAM_SET=YEW befor configure,like
`STREAM_SET=YES ./configure --prefix=/opt/tengine-2.4.0`

**Comment by chobits** [comment]
fixed in https://github.com/alibaba/tengine/pull/1749

**Comment by chobits** [comment]
I am closing this issue. Please feel free to reopen it if you have any further questions.
