### ISSUE TITLE
官网更新

### ISSUE THREAD

**Issue by DevHaoZi** [alibaba/tengine#1745]
## Question
[http://tengine.taobao.org/](http://tengine.taobao.org/)
官网上的描述还是Nginx-1.18.0，下载页面的最新版也还是2.3.3。

**Comment by DevHaoZi** [comment]
还有[https://tengine.taobao.org/download/tengine-2.4.0.tar.gz](https://tengine.taobao.org/download/tengine-2.4.0.tar.gz)404，2.4.0的安装包未上传

**Comment by chobits** [comment]
从里看更新并下载https://github.com/alibaba/tengine/releases/tag/2.4.0，官网在维护中

**Comment by chobits** [comment]
I am closing this issue. Please feel free to reopen it if you have any further questions.
