### ISSUE TITLE
https listener allow http request with a directive

### ISSUE THREAD

**Issue by lianglli** [alibaba/tengine#1751]

**Comment by chobits** [comment]
We highly recommend that you differentiate between xquic and Nginx Quic implementations by using compilation options (maybe switch option `--with-quic-implement=xquic`) . Then in the documentation we can clearly explain the differences and advantages/disadvantages of each implementation. The final decision on which implementation to choose during the compilation phase should be up to Tengine's customers. It may seem unusual to support two implementations of the same protocol simultaneously at runtime.

**Comment by lianglli** [comment]
> I highly recommend that you differentiate between xquic and nginx quic implementations by using compilation options (maybe switch option `--with-quic-implementation=xquic` or `--with-xquic`) . Then in the documentation we can clearly explain the differences and advantages/disadvantages of each implementation. The final decision on which implementation to choose during the compilation phase should be up to Tengine's customers. It may seem unusual to support two implementations of the same protocol simultaneously at runtime.

This feature is not bind to XQUIC. It is a common feature for H1, H2 and H3.

**Comment by chobits** [comment]
I mean any tengine feature need to be incldued in a standalone macro, like `#T_XXX_QUIC_XXXX`, which makes it seperated with nginx source. You can enabled this macro in auto/have by default(see [some examples](https://github.com/alibaba/tengine/blob/master/auto/modules#L1454)) or enabled it by other module (see [tongsuo option](https://github.com/alibaba/tengine/blob/master/modules/ngx_tongsuo_ntls/config)).

**Comment by lianglli** [comment]
of course, all the tengine feature which includs xquic has T macro T_NGX_XQUIC.

**Comment by lianglli** [comment]
Yes, if user wants to use xquic as HTTP/3 implementation, user will need to enable it which has the macro T_NGX_XQUIC specifically.

**Comment by chobits** [comment]
> Yes, if user wants to use xquic as HTTP/3 implementation, user will need to enable it which has the macro T_NGX_XQUIC specifically.

Yeah, I have observed it has been enabled in ./modules/ngx_http_xquic_module/config

**Comment by lianglli** [comment]
If the SSL 443 listen add a new option https_allow_http, https listener will allow http traffic.

```
        ## start server _
        server {
                server_name _ ;

                listen 80 default_server reuseport backlog=4096 ;
                listen [::]:80 default_server reuseport backlog=4096 ;
                listen 443 default_server reuseport backlog=4096 ssl http2 https_allow_http ;
                listen [::]:443 default_server reuseport backlog=4096 ssl http2 https_allow_http ;
                listen 443 default_server reuseport backlog=4096 xquic ;
                listen [::]:443 default_server reuseport backlog=4096 xquic ;

                ingress_gateway shm_service_cfg;
                ingress_gateway_metadata "ssl-protocols" $metadata_ssl_protocols;

                # set log host
                set $log_host $host;

                set $proxy_upstream_name "-";

                ssl_certificate_by_lua_block {
                        certificate.call()
                }

                location = /status.tengine {
                if ($host !~* "^\d{1,3}(\.\d{1,3}){3}|^status\.tengine\.com$") {
                        return 404;
                        break;
                }
                sysguard off;
                access_log off;
                root /etc/nginx/htdocs;
        }
```

```
sh-4.4# curl -i http://127.0.0.1:80/status.tengine
HTTP/1.1 200 OK
Server: Tengine/3.1.0
Date: Thu, 02 Nov 2023 03:34:31 GMT
Content-Type: text/html
Content-Length: 0
Last-Modified: Thu, 02 Nov 2023 03:31:20 GMT
Connection: keep-alive
ETag: "65431808-0"
Accept-Ranges: bytes

sh-4.4# curl -i http://127.0.0.1:443/status.tengine
HTTP/1.1 200 OK
Server: Tengine/3.1.0
Date: Thu, 02 Nov 2023 03:34:35 GMT
Content-Type: text/html
Content-Length: 0
Last-Modified: Thu, 02 Nov 2023 03:31:20 GMT
Connection: keep-alive
ETag: "65431808-0"
Accept-Ranges: bytes
```
