### ISSUE TITLE
Cerbot compatibility

### ISSUE THREAD

**Issue by agb80** [alibaba/tengine#1752]
## Question

Is there any incompatibility between Tengine and Cerbot? We are trying to using together but we got this message:

Saving debug log to /var/log/letsencrypt/letsencrypt.log

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Processing /etc/letsencrypt/renewal/canh.canhefern.com.conf
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Error while running nginx -c /etc/nginx/nginx.conf -t.

nginx: [emerg] unknown directive "load_module" in /etc/nginx/modules-enabled/50-mod-http-image-filter.conf:1
nginx: configuration file /etc/nginx/nginx.conf test failed

Failed to renew certificate canh.canhefern.com with error: The nginx plugin is not working; there may be problems with your existing configuration.
The error was: MisconfigurationError('Error while running nginx -c /etc/nginx/nginx.conf -t.\n\nnginx: [emerg] unknown directive "load_module" in /etc/nginx/modules-enabled/50-mod-http-image-filter.conf:1\nnginx: configuration file /etc/nginx/nginx.conf test failed\n')

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Processing /etc/letsencrypt/renewal/canh.sintesis-it.mx.conf
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Error while running nginx -c /etc/nginx/nginx.conf -t.

nginx: [emerg] unknown directive "load_module" in /etc/nginx/modules-enabled/50-mod-http-image-filter.conf:1
nginx: configuration file /etc/nginx/nginx.conf test failed

Failed to renew certificate canh.sintesis-it.mx with error: The nginx plugin is not working; there may be problems with your existing configuration.
The error was: MisconfigurationError('Error while running nginx -c /etc/nginx/nginx.conf -t.\n\nnginx: [emerg] unknown directive "load_module" in /etc/nginx/modules-enabled/50-mod-http-image-filter.conf:1\nnginx: configuration file /etc/nginx/nginx.conf test failed\n')

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Processing /etc/letsencrypt/renewal/gugf.canhefern.com.conf
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Error while running nginx -c /etc/nginx/nginx.conf -t.

nginx: [emerg] unknown directive "load_module" in /etc/nginx/modules-enabled/50-mod-http-image-filter.conf:1
nginx: configuration file /etc/nginx/nginx.conf test failed

Failed to renew certificate gugf.canhefern.com with error: The nginx plugin is not working; there may be problems with your existing configuration.
The error was: MisconfigurationError('Error while running nginx -c /etc/nginx/nginx.conf -t.\n\nnginx: [emerg] unknown directive "load_module" in /etc/nginx/modules-enabled/50-mod-http-image-filter.conf:1\nnginx: configuration file /etc/nginx/nginx.conf test failed\n')

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
All renewals failed. The following certificates could not be renewed:
  /etc/letsencrypt/live/canh.canhefern.com/fullchain.pem (failure)
  /etc/letsencrypt/live/canh.sintesis-it.mx/fullchain.pem (failure)
  /etc/letsencrypt/live/gugf.canhefern.com/fullchain.pem (failure)
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
3 renew failure(s), 0 parse failure(s)
Ask for help or search for solutions at https://community.letsencrypt.org. See the logfile /var/log/letsencrypt/letsencrypt.log or re-run Certbot with -v for more details.

**Comment by chobits** [comment]
It appears that your version of tengine (nginx core) is outdated.The latest version of tengine has supported the "load_module" directive since tengine version 2.4.0.
