### ISSUE TITLE
tengine-2.4.x or 3.0.0 build failed with pcre2

### ISSUE THREAD

**Issue by DevHaoZi** [alibaba/tengine#1764]
### Ⅰ. Issue Description

I try to build tengine-3.0.0 brunch with pcre2-10.42, it return a error.

### Ⅱ. Describe what happened

```
cd ../pcre2-10.42 \
&& make libpcre.la
make[2]: Entering directory '/root/pcre2-10.42'
make[2]: *** No rule to make target 'libpcre.la'.  Stop.
make[2]: Leaving directory '/root/pcre2-10.42'
make[1]: *** [objs/Makefile:1318: ../pcre2-10.42/.libs/libpcre.a] Error 2
make[1]: Leaving directory '/root/tengine'
make: *** [Makefile:10: build] Error 2
```
![image](https://user-images.githubusercontent.com/115467771/230918202-2e53de3c-45ca-40f2-aed8-9f3e8b80691e.png)

### Ⅲ. Describe what you expected to happen

Build success without error.

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. Download pcre2-10.42 from [https://github.com/PCRE2Project/pcre2/releases](https://github.com/PCRE2Project/pcre2/releases)
2. unzip it.
3. `git clone -b tengine-3.0.0 https://github.com/alibaba/tengine.git`
4. `cd tengine`
5. `./configure --prefix=/usr/local/nginx --with-pcre=../pcre2-10.42`
6. `make`
7. Wait until see the error.

### Ⅴ. Anything else we need to know?

1. none

### Ⅵ. Environment:

- Tengine version (use `sbin/nginx -V`): Tengine/2.4.0
- OS (e.g. from /etc/os-release): Rocky Linux 8.6 (Green Obsidian)
- Kernel (e.g. `uname -a`): Linux VM-0-4-rockylinux 4.18.0-372.9.1.el8.x86_64 #1 SMP Tue May 10 14:48:47 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
- Others: none

**Comment by ultraman-nuedu** [comment]
编译2.4.0版本，我有同样的问题。仅添加-with-pcre=DIR 这个参数的前提下进行编译，反复尝试了好多次总算成功了。

尝试调用系统自带pcre编译（该参默认设置），发现没有问题，猜想是不是编译相关的配置有些问题。
于是我下载了nginx1.24版本的源码包，**用nginx1.24.0/auto/lib/pcre/conf替换tengine-2.4.0/auto/lib/pcre/conf（建议使用tengine 3.0.0对应版本的nginx源码包内的文件进行替换）**，再次尝试编译，总算成功了。

我判断可能是这个conf文件内部逻辑与我们实际的编译环境不匹配。


-----------------------------------------------------------------------------------------

PS：I'm sorry ,My English is very poor, So the following text was translated by Bing Translation。


Compiling version 2.4.0, I have the same issue. Compile only under the premise of adding the -with-pcre=DIR parameter, and tried many times and finally succeeded.

Try to call the system's own PCRE compilation (the default setting of this parameter), find that there is no problem, guess if there is some problem with the compilation-related configuration.
**So I downloaded the nginx version 1.24 source package, replaced tengine-2.4.0/auto/lib/pcre/conf with nginx1.24.0/auto/lib/pcre/conf (it is recommended to replace the files in the nginx source package corresponding to tengine 3.0.0)**, tried to compile again, and finally succeeded.

I judged it might be that the internal logic of this conf file doesn't match our actual compilation environment.

**Comment by chobits** [comment]
> 编译2.4.0版本，我有同样的问题。仅添加-with-pcre=DIR 这个参数的前提下进行编译，反复尝试了好多次总算成功了。
> 
> 尝试调用系统自带pcre编译（该参默认设置），发现没有问题，猜想是不是编译相关的配置有些问题。 于是我下载了nginx1.24版本的源码包，**用nginx1.24.0/auto/lib/pcre/conf替换tengine-2.4.0/auto/lib/pcre/conf（建议使用tengine 3.0.0对应版本的nginx源码包内的文件进行替换）**，再次尝试编译，总算成功了。
> 
> 我判断可能是这个conf文件内部逻辑与我们实际的编译环境不匹配。
> 
> PS：I'm sorry ,My English is very poor, So the following text was translated by Bing Translation。
> 
> Compiling version 2.4.0, I have the same issue. Compile only under the premise of adding the -with-pcre=DIR parameter, and tried many times and finally succeeded.
> 
> Try to call the system's own PCRE compilation (the default setting of this parameter), find that there is no problem, guess if there is some problem with the compilation-related configuration. **So I downloaded the nginx version 1.24 source package, replaced tengine-2.4.0/auto/lib/pcre/conf with nginx1.24.0/auto/lib/pcre/conf (it is recommended to replace the files in the nginx source package corresponding to tengine 3.0.0)**, tried to compile again, and finally succeeded.
> 
> I judged it might be that the internal logic of this conf file doesn't match our actual compilation environment.

ty this is a compilation bug. We will release a version to fix

We have merged nginx-1.22.1 into tengine-2.4.0, but there were files not updated. However, `diff -up auto/` did not check all recursively nested files within this directory, should use `diff -upr auto/` instead.

**Comment by chobits** [comment]
I found that why we did not included PCRE2 at that time, because ngx-lua module does not support PCRE2 which is included in tengine project. For more details about PCRE2 and ngx-lua, see https://github.com/openresty/lua-nginx-module/issues/1984

**Comment by chobits** [comment]
also note that ngx-lua included in tengine project cannot support PCRE2. For more details about PCRE2 and ngx-lua, see https://github.com/openresty/lua-nginx-module/issues/1984

**Comment by chobits** [comment]
has been fix in latest master branch, pls retry
