### ISSUE TITLE
Some directives has some limits using active check

### ISSUE THREAD

**Issue by NagamineLee** [alibaba/tengine#1769]
### Ⅰ. Issue Description
use `ngx_http_upstream_check_module` has happened some errors:

- error1: nginx: [emerg] invalid check_http_send for type "tcp"
- error2:  nginx: [emerg] invalid check_http_send should set [check] first

### Ⅱ. Describe what happened

error1's configuration:
```
upstream test{
    server 127.0.0.1:1970;
    check_keepalive_requests 10;
    check interval=3000 rise=1 fall=1 timeout=1000 type=tcp;
    check_http_send "GET / HTTP/1.0\r\nConnection: keep-alive\r\n\r\n";
    check_http_expect_alive http_2xx http_3xx;
}
```

error2's configuration:
```
    upstream test{
        server 127.0.0.1:1970;
        check_keepalive_requests 10;
        check_http_send "GET / HTTP/1.0\r\nConnection: keep-alive\r\n\r\n";
        check interval=3000 rise=1 fall=1 timeout=1000 type=http;
        check_http_expect_alive http_2xx http_3xx;
    }
```

### Ⅲ. Describe what you expected to happen

these 2 limits are permitted:

- limit-1: check type is non-http, also can use check_http_send, even if it is not affected
- limit-2: both `check ` and `check_http_send ` have no  no sequential restrictions.

### Ⅴ. Anything else we need to know?
the two limits are in function(ngx_http_upstream_check_http_send):
```
static char *
ngx_http_upstream_check_http_send(ngx_conf_t *cf, ngx_command_t *cmd,
    void *conf)
{
    ngx_str_t                           *value;
    ngx_http_upstream_check_srv_conf_t  *ucscf;

    value = cf->args->elts;

    ucscf = ngx_http_conf_get_module_srv_conf(cf,
                                              ngx_http_upstream_check_module);
    ---- limit-2
    if (ucscf->check_type_conf == NGX_CONF_UNSET_PTR) {
        ngx_conf_log_error(NGX_LOG_EMERG, cf, 0,
                           "invalid check_http_send should set [check] first");
        return NGX_CONF_ERROR;
    }

    ---- limit-1
    if (value[1].len
        && (ucscf->check_type_conf->name.len != 4
            || ngx_strncmp(ucscf->check_type_conf->name.data,
                           "http", 4) != 0))
    {
        ngx_conf_log_error(NGX_LOG_EMERG, cf, 0,
                           "invalid check_http_send for type \"%V\"",
                           &ucscf->check_type_conf->name);
        return NGX_CONF_ERROR;
    }

    ucscf->send = value[1];

    return NGX_CONF_OK;
}
```

### Ⅵ. Environment:

Tengine: 2.4.0

**Comment by chobits** [comment]
Hi,

These reported errors are as expected. Removing the `limit-1` or `limit-2` checking would result in more ambiguous configurations being allowed.

For your "error1's configuration:", if you want to check backend using `tcp` protocol, you should not add the setting of check_http_send directive. 

For your "error2's configuration:", it is important always to place the`check` directive as first line above other check module directives. This is a legacy problem with nginx configuration system and checking other directives in every directive would make the source code complicated. To address the issue, we typically check top-level directives in low-level directives, which means that we need to add top-level directives at the beginning of other directives.

**Comment by chobits** [comment]
Furthermore, if it possible, we prefer to fix problems via modifying configuration rather than modifying the source code.

**Comment by chobits** [comment]
closing it, feel free to reopen if you have any further questions or concerns in the future
