### ISSUE TITLE
2.4版本的，健康检查貌似有点问题

### ISSUE THREAD

**Issue by fengyue0001** [alibaba/tengine#1771]
配置如下：
upstream test {
    vnswrr;
    keepalive 32;
   server 1.1.1.1:8080;
   server 2.2.2.2:8080;
   server 3.3.3.3:8080;
   server 4.4.4.4:8080;
  check interval=5000 rise=3 fall=3 timeout=3000 type=http;
  check_http_send "GET /health.htm  HTTP/1.1\r\nConnection: keep-alive\r\n\r\n";
}

检查过网络没有问题，使用过GET/HEAD ,均提示 check protocol http error hith peer : xx.xx.xx.xx
使用tcp进项健康检查，没有问题

**Comment by fengyue0001** [comment]
补充一下，好像 换成http1.0 就可以了，，这是正常的吗？

**Comment by fengyue0001** [comment]
经过测试使用http1.1 header 里面必须要有Host 信息，应该是合理的

**Comment by chobits** [comment]
> 经过测试使用http1.1 header 里面必须要有Host 信息，应该是合理的

如你所说后端服务器 识别check_http_send "GET /health.htm HTTP/1.1\r\nConnection: keep-alive\r\n\r\n"; http/1.1发现缺少Host判定协议失败了。
