### ISSUE TITLE
openssl3.0提供了provider机制，tengine是否支持？

### ISSUE THREAD

**Issue by foxriver1025** [alibaba/tengine#1773]
openssl3.0提供了provider机制，tengine是否支持？如果不支持，会在什么时候支持？

**Comment by chobits** [comment]
详尽信息可以看这里：https://trac.nginx.org/nginx/ticket/2449
对于主干的更新，会紧贴nginx core的更新，tengine不会不必要的改动。目前看用户反馈（从这个nginx ticket），是可以简单实用。（未做测试，请自行检测）

**Comment by foxriver1025** [comment]
@chobits 好的，非常感谢

**Comment by chobits** [comment]
closing it, If you have any further questions or concerns in the future, feel free to reopen
