### ISSUE TITLE
tengine+tongsuo测试国密套件编译时找不到符号 // cannot find symbol during compiling

### ISSUE THREAD

**Issue by foxriver1025** [alibaba/tengine#1776]
**1.tongsuo配置选项如下**
./Configure --strict-warnings --prefix=/home/app/tongsuo -Wl,-rpath,/home/app/tongsuo/lib64 enable-ec_elgamal enable-paillier enable-ntls

**2.tengine配置选项如下，因为我要链接tongsuo的动态库，所以使用了--with-cc-opt和--with
-ld-opt**
./configure --prefix=/home/app/tengine  --with-cc-opt='-I/home/app/tongsuo/include '  --with-ld-opt='-Wl,-rpath=/home/app/tongsuo/lib64' --add-module=modules/ngx_tongsuo_ntls --with-http_ssl_module  --with-stream  --with-stream_ssl_module  --with-stream_sni

**3.编译tengine时报如下错误**
-Wl,-rpath=/home/app/tongsuo/lib64 -lcrypt -lpcre -lssl -lcrypto -lz \
-Wl,-E
/usr/bin/ld: objs/src/event/ngx_event_openssl.o: in function `ngx_ssl_certificate':
/home/code/tengine/src/event/ngx_event_openssl.c:710: undefined reference to `SSL_CTX_use_enc_certificate'
/usr/bin/ld: /home/code/tengine/src/event/ngx_event_openssl.c:720: undefined reference to `SSL_CTX_use_sign_certificate'
/usr/bin/ld: /home/code/tengine/src/event/ngx_event_openssl.c:821: undefined reference to `SSL_CTX_use_enc_PrivateKey'
/usr/bin/ld: /home/code/tengine/src/event/ngx_event_openssl.c:830: undefined reference to `SSL_CTX_use_sign_PrivateKey'
/usr/bin/ld: objs/src/http/ngx_http_request.o: in function `ngx_http_ssl_handshake':
/home/code/tengine/src/http/ngx_http_request.c:823: undefined reference to `SSL_enable_ntls'
/usr/bin/ld: objs/src/http/ngx_http_upstream.o: in function `ngx_http_upstream_ssl_init_connection':
/home/code/tengine/src/http/ngx_http_upstream.c:1831: undefined reference to `NTLS_method'
/usr/bin/ld: /home/code/tengine/src/http/ngx_http_upstream.c:1824: undefined reference to `NTLS_method'
/usr/bin/ld: /home/code/tengine/src/http/ngx_http_upstream.c:1825: undefined reference to `NTLS_method'
/usr/bin/ld: /home/code/tengine/src/http/ngx_http_upstream.c:1828: undefined reference to `SSL_CTX_enable_ntls'
/usr/bin/ld: /home/code/tengine/src/http/ngx_http_upstream.c:1835: undefined reference to `SSL_CTX_disable_ntls'
/usr/bin/ld: objs/src/stream/ngx_stream_proxy_module.o: in function `ngx_stream_proxy_ssl_init_connection':
/home/code/tengine/src/stream/ngx_stream_proxy_module.c:1110: undefined reference to `NTLS_method'
/usr/bin/ld: /home/code/tengine/src/stream/ngx_stream_proxy_module.c:1111: undefined reference to `NTLS_method'
/usr/bin/ld: /home/code/tengine/src/stream/ngx_stream_proxy_module.c:1114: undefined reference to `SSL_CTX_enable_ntls'
/usr/bin/ld: /home/code/tengine/src/stream/ngx_stream_proxy_module.c:1117: undefined reference to `NTLS_method'
/usr/bin/ld: /home/code/tengine/src/stream/ngx_stream_proxy_module.c:1121: undefined reference to `SSL_CTX_disable_ntls'
/usr/bin/ld: objs/src/stream/ngx_stream_ssl_module.o: in function `ngx_stream_ssl_init_connection':
/home/code/tengine/src/stream/ngx_stream_ssl_module.c:505: undefined reference to `SSL_enable_ntls'
collect2: error: ld returned 1 exit status
make[1]: *** [objs/Makefile:281: objs/nginx] Error 1
make[1]: Leaving directory '/home/code/tengine'
make: *** [Makefile:10: build] Error 2

**4.在libssl.so中能找到这些符号**
~/code/tongsuo$ nm /home/app/tongsuo/lib64/libssl.so  | grep  -e SSL_enable_ntls -e NTLS_method -e SSL_CTX_use_enc_certificate
0000000000029281 T NTLS_method
0000000000051eb7 T SSL_CTX_use_enc_certificate
0000000000052100 T SSL_CTX_use_enc_certificate_file
000000000004b86e T SSL_enable_ntls

**5.请教下是什么原因导致的？我该如何解决？**

**Comment by chobits** [comment]
参考下：https://github.com/alibaba/tengine/blob/master/.github/workflows/test-ntls.yml，容器测试是可以编译通过的 。近期通过的一个自动化github workflow测试结果：https://github.com/alibaba/tengine/actions/runs/5108043456/jobs/9181501273

---

对一下tengine的编译参数是否和这个容器测试一致

**Comment by foxriver1025** [comment]
这个问题我已经知道原因了，--with-cc-opt中指定的-Wl,-rpath在-lcrypto之前，所以未生效，然后重新用-L指定tongsuo的lib就可以了。最终的configure如下
./configure --prefix=/home/app/tengine --with-cc-opt='-I/home/app/tongsuo/include ' --with-ld-opt='-Wl,-rpath=/home/app/tongsuo/lib64 -L/home/app/tongsuo/lib64' --add-module=modules/ngx_tongsuo_ntls --with-http_ssl_module --with-stream --with-stream_ssl_module --with-stream_sni
