### ISSUE TITLE
location.proxy_pass是否支持国密双向认证

### ISSUE THREAD

**Issue by solio** [alibaba/tengine#1779]
location.proxy_pass是否支持国密双向认证以及TLCP
nginx <-TLCP_ECC_SM4_GCM_SM3-> 应用服务器

**Comment by chobits** [comment]
参考下这里的测试用例 https://github.com/alibaba/tengine/pull/1637/files#diff-232b9defa7c9a8ff339579a68103a1d87c8ebb91281b3853ca6b573c7d068d40

**Comment by chobits** [comment]
@wa5i proxy_pass的ntls是不是需要一个文档，类似之前nginx做ntls服务器那种文档

**Comment by solio** [comment]
非常感谢，建议：如果新增文档的话最好说明一下proxy_ssl_ciphers，目前很多开源中间件国密ssl_ciphers并不统一

**Comment by solio** [comment]
再问一下proxy_ssl_enc_certificate是什么意思，加密过程不是对称加密吗，也需要公钥证书？

**Comment by wa5i** [comment]
> @wa5i proxy_pass的ntls是不是需要一个文档，类似之前tengine的ntls服务器那种文档
ok，回头我整理一下

**Comment by wa5i** [comment]
> 非常感谢，建议：如果新增文档的话最好说明一下proxy_ssl_ciphers，目前很多开源中间件国密ssl_ciphers并不统一

tengine 的国密是基于铜锁(Tongsuo)的，铜锁支持的加密套件都可以

**Comment by wa5i** [comment]
> 再问一下proxy_ssl_enc_certificate是什么意思，加密过程不是对称加密吗，也需要公钥证书？

国密双证书分为签名证书和加密证书，这个指令是配置加密证书。加密过程是对称加密，但密钥交换时用到加密证书和私钥。
