### ISSUE TITLE
stream proxy module: how to specify backend address for proxying oracle adg data

### ISSUE THREAD

**Issue by lijincai198843-lc** [alibaba/tengine#1787]
## Question
你好，我们现在有个场景，就是使用oracle的adg搭建了2套异地容灾数据库，由于oracle的限制，servername不能一样，但是使用stream 代理Oracle的时候只能是指定ip，没办法像7层http代理可以指定Location来解决java程序中的jdbc url中的配置，比如我在程序中配置192.168.0.1:1521/db,然后我可以在stram中指向多个相同的servername的db，但是adg的两个名字不一样，我没办法在url中既能配置db1又能配置db2，这个要如何实现

---
Hello, we have encountered a challenge in setting up our remote disaster recovery databases using Oracle's ADG. The limitation with ADG is that the server names cannot be the same, but using a stream proxy for Oracle only allows for the IP address to be specified. This makes it difficult to configure JDBC URLs in Java programs, as we can only specify the IP address. For example, if I have configured the URL as 192.168.0.1:1521/db in my program, I cannot use the same server name for both the primary and secondary databases, as they are hosted on different servers.

Is there a way to implement this scenario using ADG and a stream proxy?

**Comment by chobits** [comment]
stream自身无法实现，你这个需求需要一个stream子模块来根据你的业务数据流来指定后端地址，可能通过stream lua 模块来实现 或者 需要写一个stream 的子模块，因为我不熟悉adg具体格式，需要你从中自行提取信息来判断选择哪个后端地址。

---

The stream module itself may be unable to meet this demond. Instead, you will need to use a stream submodule to specify the backend address based on your business data flow, oracle adg data flow here. This can be achieved through the use of the stream Lua module, or you may need to write your own stream C submodule.
