### ISSUE TITLE
希望能够将tengine的nginx升级至1.25版本

### ISSUE THREAD

**Issue by pmkol** [alibaba/tengine#1790]
因为1.25版本原生支持quic

并原生支持由akamai与microsoft维护的quic版openssl库 https://github.com/quictls/openssl

目前tongsuo还不支持KTLS特性，这样可以让用户多一些SSL库的选择，真心希望tengine能做的更强大

**Comment by ahgaoyong** [comment]
ngninx1.25是属于开发版本, 你可以了解下, nginx 的基数版本都是开发版本, 只有偶数版本才是正式稳定版本, nginx的历史版本下载页面你会发现全是偶数版本

![image](https://github.com/alibaba/tengine/assets/13848697/5d117cf2-547e-4323-aa81-81ddc4a2dca6)

**Comment by pmkol** [comment]
> ngninx1.25是属于开发版本, 你可以了解下, nginx 的奇数版本都是开发版本, 只有偶数版本才是正式稳定版本, nginx的历史版本下载页面你会发现全是偶数版本
> 
> ![image](https://private-user-images.githubusercontent.com/13848697/296536912-5d117cf2-547e-4323-aa81-81ddc4a2dca6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcwMTkxMTUsIm5iZiI6MTcwNzAxODgxNSwicGF0aCI6Ii8xMzg0ODY5Ny8yOTY1MzY5MTItNWQxMTdjZjItNTQ3ZS00MzIzLWFhODEtODFkZGM0YTJkY2E2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA0VDAzNTMzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM1YTdmZGM1NzQyZTMxODFiMGM2MWIwY2Y2YmUwZjYxODQwYTgwY2I0YjdhM2I4YmRjM2ViMDU1NmZjYzk0MTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.KFz6apZM4OJmBFsXc0ktXsHalFr5kPyU0nI20Tt9mrU)

1、Mainline version并非开发版，只是一些中文媒体的错误叫法被延续至今，真正的开发版位于：https://hg.nginx.org/nginx/

2、由于更新Nginx的频率较低，所以为了获得最新的Nginx特性，Tengine、OpenResty这些分支版本，会使用Mainline version迭代3~4个小版本后的版本，可以查看一下历史代码：
https://github.com/alibaba/tengine/tree/master/src/core
https://github.com/openresty/openresty/tree/nginx-1.25.3

3、建议及时更新1.25版本的原因，是因为这个版本原生对http3支持，而目前tengine只能使用tongsuo来支持http3，但tongsuo不支持ktls，会导致http2/1.1享受不到ktls的加成，而阿里自己的业务环境由于使用硬件级的异步SSL方案，而无需使用内核级的KTLS方案，所以KTLS这里一直没及时跟进，这才是提建议的原因
