### ISSUE TITLE
tengine+tongsuo+qatprovider测试NTLS时tengine coredump

### ISSUE THREAD

**Issue by foxriver1025** [alibaba/tengine#1793]
### Ⅰ. Issue Description
1.使用tengine开启异步模式(ssl_async on)，并且使用qat硬件，以provider方式加载
2.使用密信浏览器，加密套件是ECC-SM2-SM4-CBC-SM3
3.等到连接超时，此时tengine的work进程会coredump

### Ⅱ. Describe what happened
tengine走到shutdown流程会发生coredump

### Ⅲ. Describe what you expected to happen
tengine走到shutdown流程不会coredump

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1.使用tengine开启异步模式(ssl_async on)，并且使用qat硬件，以provider方式加载
2.使用密信浏览器，加密套件是ECC-SM2-SM4-CBC-SM3
3.等到连接超时，此时tengine的work进程会coredump

### Ⅴ. Anything else we need to know?

1. tengine完整日志见附件
    2023/06/21 17:48:19 [debug] 192099#0: timer delta: 65061
2023/06/21 17:48:19 [debug] 192099#0: *3 event timer del: 3: 17265452
2023/06/21 17:48:19 [debug] 192099#0: *3 http keepalive handler
2023/06/21 17:48:19 [debug] 192099#0: *3 close http connection: 3
2023/06/21 17:48:19 [debug] 192099#0: *3 SSL_shutdown: -1
2023/06/21 17:48:19 [debug] 192099#0: *3 ngx_ssl_async_process_fds called
2023/06/21 17:48:19 [debug] 192099#0: *3 SSL_get_error: 9
2023/06/21 17:48:19 [debug] 192099#0: *3 ngx_ssl_async_process_fds called
2023/06/21 17:48:19 [debug] 192099#0: *3 epoll del async connection: fd:24
2023/06/21 17:48:19 [debug] 192099#0: *3 epoll del connection: fd:3
2023/06/21 17:48:19 [debug] 192099#0: *3 reusable connection: 0
2023/06/21 17:48:19 [debug] 192099#0: *3 free: 0000000000000000
2023/06/21 17:48:19 [debug] 192099#0: *3 free: 0000000000000000
2023/06/21 17:48:19 [debug] 192099#0: *3 free: 000055BE47452F50, unused: 40
2023/06/21 17:48:19 [debug] 192099#0: *3 free: 000055BE47464390, unused: 320
2023/06/21 17:48:19 [debug] 192099#0: worker cycle
2023/06/21 17:48:19 [debug] 192099#0: epoll timer: -1
2023/06/21 17:48:20 [notice] 192097#0: signal 17 (SIGCHLD) received from 192099
2023/06/21 17:48:20 [alert] 192097#0: worker process 192099 exited on signal 11 (core dumped)
2.初步原因分析如下
(1)keepalive(默认65秒)超时后，tengine进入ngx_ssl_shutdown流程，调用SSL_shutdown会触发进行sm3计算，此时会把请求发送给硬件，但是硬件还没处理完，所以当前job是pause状态。
(2)tengine继续调用SSL_free，此函数会调用ASYNC_WAIT_CTX_free释放wait_ctx
(3)等到硬件处理完请求后硬件会从job中获取wait_ctx，然后从wait_ctx调用ASYNC_WAIT_CTX_get_fd获取fd，由于此时的wait_ctx已经被释放，所以会访问非法内存从而coredump

3.通过走读tengine代码发现了疑似出问题的地方，commit [e8a9939](https://github.com/alibaba/tengine/pull/1719/files#diff-9ee36b3af9944c6e9ed3eddada89eabb0712ddad62c82416c1be142f84a15959)对ngx_event_openssl.c的ngx_ssl_shutdown函数进行了修改，使用ERR_peek_error进行了判断，导致此条件成立，从而goto done;
应该先进行sslerr == SSL_ERROR_WANT_ASYNC的判断，如果有job没处理完一定要等待job处理完成，否则会发生很多问题，比如资源泄露(job资源，job中任务申请的资源等)或者coredump

4.发现此疑点后，我尝试修改了tengine代码，把if (sslerr == SSL_ERROR_WANT_ASYNC)这个分支的代码移到if (sslerr == SSL_ERROR_ZERO_RETURN || ERR_peek_error() == 0)这个分支之前，意味着如果有job没完成那么会返回NGX_AGAIN，此时coredump问题解决，也没有发生资源泄露现象。
以上分析望参考

### Ⅵ. Environment:

- Tengine version (use `sbin/nginx -V`):
 Tengine version: Tengine/2.4.0
 nginx version: nginx/1.22.1

- OS (e.g. from /etc/os-release):
  PRETTY_NAME="Ubuntu 22.04.2 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.2 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy

- Kernel (e.g. `uname -a`):
 `Linux tianmu-fpga3-host 5.14.11 #1 SMP Tue Dec 6 14:08:58 CST 2022 x86_64 x86_64 x86_64 GNU/Linux`
- Others:

**Comment by foxriver1025** [comment]
此问题对我来说非常重要，只要tengine走到shutdown流程必然会发生coredump。
初步原因我已经分析了，我也尝试修改了tengine代码能解决这个问题，衷心希望官方能看到，能帮忙解决这个问题

**Comment by foxriver1025** [comment]
@chobits 又看了qat修改的nginx的代码，[asynch_mode_nginx(https://github.com/intel/asynch_mode_nginx/tree/master)](https://github.com/intel/asynch_mode_nginx/blob/master/src/event/ngx_event_openssl.c#L1948)，也确实是先判断if (sslerr == SSL_ERROR_WANT_ASYNC)再判断if (sslerr == SSL_ERROR_ZERO_RETURN || ERR_peek_error() == 0)的，能否帮忙确认下，咱tengine此处的修改是不是有问题呢

**Comment by chobits** [comment]
hi 

> 4.发现此疑点后，我尝试修改了tengine代码，把if (sslerr == SSL_ERROR_WANT_ASYNC)这个分支的代码移到if (sslerr == SSL_ERROR_ZERO_RETURN || ERR_peek_error() == 0)这个分支之前，意味着如果有job没完成那么会返回NGX_AGAIN，此时coredump问题解决，也没有发生资源泄露现象。

你可以先提个pr 我cc个开发看看，我看你这里分析基本已经完全了

**Comment by chobits** [comment]
> @chobits 又看了qat修改的nginx的代码，[asynch_mode_nginx(https://github.com/intel/asynch_mode_nginx/tree/master)](https://github.com/intel/asynch_mode_nginx/blob/master/src/event/ngx_event_openssl.c#L1948)，也确实是先判断if (sslerr == SSL_ERROR_WANT_ASYNC)再判断if (sslerr == SSL_ERROR_ZERO_RETURN || ERR_peek_error() == 0)的，能否帮忙确认下，咱tengine此处的修改是不是有问题呢

对 直接可以backport过来先，放在pr里，review下。feel free to open ur pull request

**Comment by chobits** [comment]
另外 试下 2.4.1新版本。有一个修复关于qat的https://github.com/alibaba/tengine/pull/1774/。 但是 感觉应该和你说的不是同一个问题，但是最好升级到最新版本测一下

**Comment by foxriver1025** [comment]
@chobits [用了最新的2.4.1版本测试还是有问题。我已经提了一个[PR](https://github.com/alibaba/tengine/pull/1795)进行修复，修复后本地环境测试无问题，帮忙review以下，多谢
