### ISSUE TITLE
proxy_connect: SNI checking failed when ssl_verify_client is enabled

### ISSUE THREAD

**Issue by Homqyy** [alibaba/tengine#1794]
### Ⅰ. Issue Description

【使用场景】：HTTP CONNECT + SSL证书认证
【问题描述】：当同时启用两者功能时，会报错“client attempted to request the server name different from the one that was negotiated while reading client request headers”，配置如下：

```
    server {
        listen 443 ssl;
        server_name example.com.cn;

        ssl_certificate certs/example.com.cn/fullchain.pem;
        ssl_certificate_key certs/example.com.cn/privkey.pem;
        ssl_verify_client       on;
        ssl_client_certificate  proxy_ca_chain.pem;
        ssl_verify_depth        3;

        # 启用WEB代理，即代理CONNECT请求
        proxy_connect;
        proxy_connect_allow             all;
        proxy_connect_connect_timeout   120;
        proxy_connect_read_timeout      120;
        proxy_connect_send_timeout      120;

        location / {
            proxy_http_version   1.1;
            proxy_pass           $scheme://$host:$server_port;
        }
    }
```

### Ⅱ. Describe what happened

按照上述配置（同时配置`proxy_connect`和`ssl_verify_client on`）时，装了相应证书的客户端访问代理服务器时，查看NGINX日志可以看到。

### Ⅲ. Describe what you expected to happen

装了相应证书的客户端访问代理服务器应当能正常代理

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. 按上述配置配置Nginx
2. 客户端安装好证书（由配置中的`proxy_ca_chain.pem`证书签发）
3. 客户端发起HTTP CONNECT请求（HTTPS）

**Comment by Homqyy** [comment]
问题代码所在函数：`ngx_http_set_virtual_server`

报错位置：

```
        if (sscf->verify) {
            ngx_log_error(NGX_LOG_INFO, r->connection->log, 0,
                          "client attempted to request the server name "
                          "different from the one that was negotiated");
            ngx_http_finalize_request(r, NGX_HTTP_MISDIRECTED_REQUEST);
            return NGX_ERROR;
        }
```

**Comment by chobits** [comment]
应该是客户端的ssl协议上携带的hostname（SSL_CTRL_SET_TLSEXT_HOSTNAME）和 CONNECT请求里面携带的`Host: xxx`字段不匹配导致的。这里判断直接是拒绝还是放行，主要但看开发者如何选择，因为proxy_connect没有开发相关逻辑，所以默认继承了nginx的逻辑。不过对客户端友好的情况下可能是 将两个逻辑（SSL 与proxy_connect) 交叉判断的时候自动忽略（比如 这里拒绝请求的逻辑直接跳过了当发现是CONNECT请求的话）

CONNECT请求里面的Host字段实际与非CONNECT请求的Host意义不同。CONNECT的host是指向选择转发后端的host，而非CONNECT请求指向的是当前服务器所能服务的servername

**Comment by chobits** [comment]
这个问题提醒我们proxy_connect模块需要挑掉整个ngx_http_set_virtual_server()逻辑。应该直接用default_server或者由SSL SNI指定的hostname对应的server {}.

否则惠出现一个奇怪的问题。比如 使用 `curl  https://x.com -x localhost:8881 -sv -o /dev/null` 做CONNECT tunnel代理时候并不会成功，击中了第二个 `server {}`

```
server {
        listen 8881;
        resolver 223.5.5.5 ipv6=off;

        proxy_connect;
        proxy_connect_allow all;
        proxy_connect_connect_timeout 10s;
        proxy_connect_data_timeout 120s;

        location / {
            proxy_pass http://$host;
            proxy_set_header Host $host;
        }
    }

server {
        listen 8881;
        server_name x.com;

        proxy_connect;
        proxy_connect_allow all;
        return 400;
    }
```

**Comment by Homqyy** [comment]
> 应该是客户端的ssl协议SNI上携带的hostname（对应nginx逻辑宏SSL_CTRL_SET_TLSEXT_HOSTNAME）和 CONNECT请求里面携带的`Host: xxx`字段不匹配导致的。这里判断直接是拒绝还是放行，主要但看开发者如何选择，因为proxy_connect没有开发相关逻辑，所以默认继承了nginx的逻辑。不过对客户端友好的情况下可能是 将两个逻辑（SSL 与proxy_connect) 交叉判断的时候自动忽略（比如 这里拒绝请求的逻辑直接跳过了当发现是CONNECT请求的话）
> 
> CONNECT请求里面的Host字段实际与非CONNECT请求的Host意义不同。CONNECT的host是指向选择转发后端的host，而非CONNECT请求指向的是当前服务器所能服务的servername

是的，目前我的临时方案是“判断是CONNECT就绕过拒绝的流程”。不知这个有计划放入正式版本吗，或有更好的正式方案。

**Comment by Homqyy** [comment]
> 这个问题提醒我们proxy_connect模块需要skip整个ngx_http_set_virtual_server()逻辑。应该直接用default_server或者由SSL SNI指定的hostname对应的server {}.
> 
> 否则出现一个奇怪的问题。比如 使用 `curl https://x.com -x localhost:8881 -sv -o /dev/null` 做CONNECT tunnel代理时候并不会成功，击中了第二个 `server {}`
> 
> ```
> server {
>         listen 8881;
>         resolver 223.5.5.5 ipv6=off;
> 
>         proxy_connect;
>         proxy_connect_allow all;
>         proxy_connect_connect_timeout 10s;
>         proxy_connect_data_timeout 120s;
> 
>         location / {
>             proxy_pass http://$host;
>             proxy_set_header Host $host;
>         }
>     }
> 
> server {
>         listen 8881;
>         server_name x.com;
> 
>         proxy_connect;
>         proxy_connect_allow all;
>         return 400;
>     }
> ```
> 
> 不过这里改动涉及到nginx core比较麻烦，还得再想想，你说的这个问题临时规避就是 SSL的connect请求上ssl不要设置SNI hostname或者简单代码 skip掉verify的逻辑

期待～

**Comment by chobits** [comment]
I have given a simple fix, try this patch in https://github.com/alibaba/tengine/pull/1797/files

**Comment by chobits** [comment]
I'm closing it.

The current bugfix patch may change the default logic of the original proxy_connect module, so we will not fix it now. But you still can fix the problem from this patch https://github.com/alibaba/tengine/pull/1797/patch
