### ISSUE TITLE
Does tengine support  openSSL cipher PIPELINE feature

### ISSUE THREAD

**Issue by foxriver1025** [alibaba/tengine#1798]
Does tengine support  openSSL cipher PIPELINE feature?
Deitals information about the pipeline settings, please refer to [openSSL Docs](https://www.openssl.org/docs/man1.1.1/man3/SSL_CTX_set_split_send_fragment.html)

**Comment by chobits** [comment]
Whether or not your OpenSSL library supports pipeline ciphers depends on its version. To check, you can add the ssl_cipher directive to your Nginx configuration with the value `ssl_cipher "cipher_a+cipher_b";`. If the `nginx -t` command passes, then pipeline ciphers are supported. Be default, tengine does not added specific logic to support PIPELINE cipher into nginx core.

The "+" sign in the cipher name indicates that the two ciphers are used in a pipeline. This means that the encryption process is divided into two stages

**Comment by foxriver1025** [comment]
Thanks
