### ISSUE TITLE
Request to resume regular updates for tengine

### ISSUE THREAD

**Issue by easyhhvm** [alibaba/tengine#1817]
## Question

tengine is a great open source web server that provides high performance and stability. However， it appears development has stalled， with the last release being over a year ago.
As an active user of tengine， I wanted to kindly request that the development team consider resuming regular updates to the project. New releases with bug fixes， security patches and enhancements would be very beneficial for the community.
Some potential reasons to restart regular releases：
- There are likely bug fixes and security issues that should be addressed in newer versions. Keeping tengine up-to-date improves security and stability.
- New web standards and protocols continue to emerge. Updating tengine allows it to support modern web development needs.
- Regular releases give users confidence that the project is still active. This encourages more widespread adoption.
- Contributions from the open source community may increase if new releases are happening.
I'm happy to provide any feedback or assistance that may help drive development. Please consider bringing tengine releases back onto a regular cadence. Many thanks for your valuable work on this great web server！

**Comment by drawing** [comment]
The Tengine community has been continuously updated. The latest master branch has been synchronized with nginx-1.24.0 version, and HTTP3 protocol support has been added. Version 3.0.0 will be released in the near future. [Tengine-ingress](https://github.com/alibaba/tengine-ingress) will also be released to support the kubernetes cloud-native platform, adding many features, welcome to use. The official website tengine.taobao.org has not been updated for a long time, and we will increase the update frequency in the future.
