### ISSUE TITLE
Documentation for new modules added in 3.0.0

### ISSUE THREAD

**Issue by harry-xm** [alibaba/tengine#1820]
Documentation for these modules is missing from docs/modules.

* ingress
* xquic
* xudp

**Comment by drawing** [comment]
xquic: 
http://tengine.taobao.org/document_cn/xquic_cn.html
https://github.com/alibaba/tengine/blob/master/modules/ngx_http_xquic_module/README.md

xudp:
http://tengine.taobao.org/document_cn/xudp_cn.html

ingress:
http://tengine.taobao.org/guide_cn.html

**Comment by drawing** [comment]
> @drawing Will you copy the documentation on tengine.taobao.org to this repository?

Except for xquic compilation documents, other documents are already on the official website. At present, the official website does not have compilation documents for specific modules. Putting them in the module readme may be more friendly to users who compile the module. And more closely matches the version.
