### ISSUE TITLE
编译ngx_http_lua_module 这个模块报错

### ISSUE THREAD

**Issue by uepuer** [alibaba/tengine#1823]
Tengine 版本:v3.0

openssl :3.1
ngx_devel_kit:0.3.0 - 2
ngx_http_lua_module : 偿试过：v.[v0.10.17v- 24]

在编译时都报：
p_lua_module/src/ngx_http_lua_ssl.c:33: first defined here
/usr/bin/ld: objs/addon/src/ngx_http_lua_ssl.o:/root/tengine/modules/ngx_http_lua_module/src/ngx_http_lua_ssl.c:16: multiple definition of `ngx_http_lua_ssl_ctx_index'; objs/addon/src/ngx_http_lua_ssl.o:/root/tengine/modules/ngx_http_lua_module/src/ngx_http_lua_ssl.c:16: first defined here
/usr/bin/ld: objs/addon/src/ngx_http_lua_log_ringbuf.o: in function `ngx_http_lua_log_ringbuf_init':
/root/tengine/modules/ngx_http_lua_module/src/ngx_http_lua_log_ringbuf.c:36: multiple definition of `ngx_http_lua_log_ringbuf_init'; objs/addon/src/ngx_http_lua_log_ringbuf.o:/root/tengine/modules/ngx_http_lua_module/src/ngx_http_lua_log_ringbuf.c:36: first defined here
/usr/bin/ld: objs/addon/src/ngx_http_lua_log_ringbuf.o: in function `ngx_http_lua_log_ringbuf_reset':
/root/tengine/modules/ngx_http_lua_module/src/ngx_http_lua_log_ringbuf.c:52: multiple definition of `ngx_http_lua_log_ringbuf_reset'; objs/addon/src/ngx_http_lua_log_ringbuf.o:/root/tengine/modules/ngx_http_lua_module/src/ngx_http_lua_log_ringbuf.c:52: first defined here
/usr/bin/ld: objs/addon/src/ngx_http_lua_log_ringbuf.o: in function `ngx_http_lua_log_ringbuf_write':
/root/tengine/modules/ngx_http_lua_module/src/ngx_http_lua_log_ringbuf.c:159: multiple definition of `ngx_http_lua_log_ringbuf_write'; objs/addon/src/ngx_http_lua_log_ringbuf.o:/root/tengine/modules/ngx_http_lua_module/src/ngx_http_lua_log_ringbuf.c:159: first defined here
/usr/bin/ld: objs/addon/src/ngx_http_lua_log_ringbuf.o: in function `ngx_http_lua_log_ringbuf_read':
/root/tengine/modules/ngx_http_lua_module/src/ngx_http_lua_log_ringbuf.c:196: multiple definition of `ngx_http_lua_log_ringbuf_read'; objs/addon/src/ngx_http_lua_log_ringbuf.o:/root/tengine/modules/ngx_http_lua_module/src/ngx_http_lua_log_ringbuf.c:196: first defined here
/usr/bin/ld: objs/addon/src/ngx_http_lua_input_filters.o: in function `ngx_http_lua_read_bytes':
/root/tengine/modules/ngx_http_lua_module/src/ngx_http_lua_input_filters.c:20: multiple definition of `ngx_http_lua_read_bytes'; objs/addon/src/ngx_http_lua_input_filters.o:/root/tengine/modules/ngx_http_lua_module/src/ngx_http_lua_input_filters.c:20: first defined here
/usr/bin/ld: objs/addon/src/ngx_http_lua_input_filters.o: in function `ngx_http_lua_read_all':
/root/tengine/modules/ngx_http_lua_module/src/ngx_http_lua_input_filters.c:46: multiple definition of `ngx_http_lua_read_all'; objs/addon/src/ngx_http_lua_input_filters.o:/root/tengine/modules/ngx_http_lua_module/src/ngx_http_lua_input_filters.c:46: first defined here
/usr/bin/ld: objs/addon/src/ngx_http_lua_input_filters.o: in function `ngx_http_lua_read_any':
/root/tengine/modules/ngx_http_lua_module/src/ngx_http_lua_input_filters.c:62: multiple definition of `ngx_http_lua_read_any'; objs/addon/src/ngx_http_lua_input_filters.o:/root/tengine/modules/ngx_http_lua_module/src/ngx_http_lua_input_filters.c:62: first defined here
/usr/bin/ld: objs/addon/src/ngx_http_lua_input_filters.o: in function `ngx_http_lua_read_line':
/root/tengine/modules/ngx_http_lua_module/src/ngx_http_lua_input_filters.c:91: multiple definition of `ngx_http_lua_read_line'; objs/addon/src/ngx_http_lua_input_filters.o:/root/tengine/modules/ngx_http_lua_module/src/ngx_http_lua_input_filters.c:91: first defined here
collect2: error: ld returned 1 exit status
make[1]: *** [objs/Makefile:484: objs/nginx] Error 1
make[1]: Leaving directory '/root/tengine'
make: *** [Makefile:10: build] Error 2

**Comment by uepuer** [comment]
@chobits  help

**Comment by ylwzbk** [comment]
这个是原nginx的问题 你去参考nginx1.23版本以上解决添加lua模块的相关文档

**Comment by chobits** [comment]
Please also check our automated testing script and its results. The compilation and testing steps were recently completed successfully. 
* compilation script: https://github.com/alibaba/tengine/actions/runs/5611699229/workflow
* result: https://github.com/alibaba/tengine/actions/runs/5611699229/job/15203769998

**Comment by uepuer** [comment]
感谢！已经按你们的自动化测试，我已调整好！--with-http_lua_module  有一些东西跟这个冲突了！
