### ISSUE TITLE
server header incorrect  when using xquic

### ISSUE THREAD

**Issue by meilihao** [alibaba/tengine#1827]
### Ⅰ. Issue Description
![2023-07-25_10-40-20](https://github.com/alibaba/tengine/assets/4382586/a4731e20-1c0b-4f1e-a37a-1b828ce0bda4)

h2 return `Server: Tengine/3.0.0`
h3 return `Server: nginx/1.24.0`
### Ⅱ. Describe what happened
via `https://localhost`

### Ⅲ. Describe what you expected to happen
all return `Server: Tengine/3.0.0`

### Ⅳ. How to reproduce it (as minimally and precisely as possible)
build tengine follow [ngx_http_xquic_module readme](https://github.com/alibaba/tengine/tree/master/modules/ngx_http_xquic_module#readme) with [3.0.0](https://github.com/alibaba/tengine/releases/tag/3.0.0), then via `https://localhost`.

### Ⅵ. Environment:

- Tengine version (use `sbin/nginx -V`):
  Tengine version: Tengine/3.0.0
  nginx version: nginx/1.24.0
  built with OpenSSL 1.1.1h  22 Sep 2020
  TLS SNI support enabled
  configure arguments: --prefix=/usr/local/tengine --sbin-path=sbin/tengine --with-xquic-inc=../xquic-1.6.0/include --with-xquic-lib=../xquic-1.6.0/build --with-http_v2_module --without-http_rewrite_module --add-module=modules/ngx_http_xquic_module --with-openssl=../Tongsuo-8.3.2
- OS:
 Ubuntu 22.04

**Comment by drawing** [comment]
The master branch has fixed this problem, and will release it in version 3.0.1 after full testing.
