### ISSUE TITLE
xquic 是否可以直接监听443端口？

### ISSUE THREAD

**Issue by ff2035** [alibaba/tengine#1851]
## Question

listen       443 reuseport xquic;   
listen       443 reuseport http2 ssl;
如上配置中xquic 监听443后启动
此时tengine会正常运行,udp监听也正常，但访问站点时，只会走http2 协议。

如果改成 1024以上端口或者在nginx.conf 中添加 user root; 配置，访问站点时就能走到xquic http3。

**Comment by drawing** [comment]
xquic如果要监听443端口，worker进程需要以 root 身份启动，否则会由于权限问题无法完成 http3 的连接，使用`user root;` 指令指定 worker 进程用户身份

**Comment by ff2035** [comment]
> xquic如果要监听443端口，worker进程需要以 root 身份启动，否则会由于权限问题无法完成 http3 的连接，使用`user root;` 指令指定 worker 进程用户身份

这个后续能支持非root用户吗？  像nginx官方1.25上的quic 就是普通用户就行

**Comment by lianglli** [comment]
Tengine基于xquic实现机制的内部约束，worker进程启动初始化bind，小于1024系统端口，必须追加root权限。
在生产环境，对外暴露的SLB/LVS使用443端口，映射Tengine RS的2443 (举例> 1024端口)，使用admin权限启动work进程，也是一种标准部署模式。
tengine HTTP/3支持multipath以及多种congestion control算法NewReno, Cubic, BBRv1和BBRv2。而nginx core实验版本，功能和稳定性相对并不具备生产使用。
