### ISSUE TITLE
How can native nginx be introduced into modules in Tenginx?

### ISSUE THREAD

**Issue by swzaaaaaaa** [alibaba/tengine#1855]
How can native nginx be introduced into modules in Tenginx?

**Comment by lianglli** [comment]
What is the meaning specifically? 

Pls. give an example.

**Comment by swzaaaaaaa** [comment]
For example, how can I introduce the module "nginx-http-upward-dynamic-module" into native nginx?

**Comment by chobits** [comment]
Some modules in Tengine can be seamlessly integrated with nginx, essentially acting as a third-party module that can be compiled together with the official nginx distribution.

However, there are some modules that require modifications to the nginx core. You can determine if a module requires such modifications by checking whether it has its own defined macro in the module's configuration file(modules/<some_module>/config: T_XXX macro, then check the macro in tengine source core tengine/src/...). In such cases, you'll need to apply these modifications to the official nginx source code.

In addition to this, there are instances where two Tengine modules are interdependent and require patches between each other. One notable example of this complexity involves the ngx_http_dyups_module and ngx_http_upstream_check_module, also you can check their own defined macro in tengine/src/ and tengine/modules/. I think the only case of its kind is: ngx_http_dyups_module and ngx_http_upstream_check_module.

**Comment by swzaaaaaaa** [comment]
I see.Thank you.
