### ISSUE TITLE
tengine执行configure怎么安装lua模块？

### ISSUE THREAD

**Issue by veniwang** [alibaba/tengine#1856]
## Question

./configure --prefix=../bin \
--add-module=modules/ngx_tongsuo_ntls \
--add-module=modules/ngx_http_lua_module \
--with-openssl=../Tongsuo-8.4-stable \
--with-openssl-opt="--strict-warnings enable-ntls" \
--with-ld-opt="-Wl,-rpath,/usr/local/openresty/luajit/lib" \
--with-http_lua_module \
--with-http_ssl_module \
--with-stream \
--with-stream_ssl_module \
--with-stream_sni
以上的配置报错“ ./configure: error: unsupported LuaJIT version; ngx_http_lua_module requires LuaJIT 2.x.”

**Comment by lianglli** [comment]
The Tengine modules/ngx_http_lua_module is based on lua-nginx-module v0.10.25 (https://github.com/openresty/lua-nginx-module/releases/tag/v0.10.25).

The ngx_http_lua_module v0.10.25 requires LuaJIT 2.x.

Hence, you should Install LuaJIT 2.x from openresty fork.

Pls. check the ( https://github.com/alibaba/tengine-ingress/blob/master/images/tengine/rootfs/build.sh ) for your information specifically.
