### ISSUE TITLE
collect2: error: ld returned 1 exit status

### ISSUE THREAD

**Issue by ancenye** [alibaba/tengine#1857]
## Question

objs/addon/ngx_http_xquic_module/ngx_http_v3_stream.o: In function `ngx_http_v3_recv_body':
ngx_http_v3_stream.c:(.text+0x1e54): undefined reference to `xqc_h3_request_recv_body'
objs/addon/ngx_http_xquic_module/ngx_http_v3_stream.o: In function `ngx_http_v3_request_read_notify':
ngx_http_v3_stream.c:(.text+0x20ca): undefined reference to `xqc_h3_request_recv_headers'
objs/addon/ngx_http_xquic_module/ngx_http_v3_stream.o: In function `ngx_http_v3_stream_cancel':
ngx_http_v3_stream.c:(.text+0x2994): undefined reference to `xqc_h3_request_close'
objs/addon/ngx_http_xquic_module/ngx_http_xquic_filter_module.o: In function `ngx_http_xquic_stream_send_header':
ngx_http_xquic_filter_module.c:(.text+0x43): undefined reference to `xqc_h3_request_send_headers'
objs/addon/ngx_http_xquic_module/ngx_http_xquic_filter_module.o: In function `ngx_http_xquic_stream_send_body':
ngx_http_xquic_filter_module.c:(.text+0x136): undefined reference to `xqc_h3_request_send_body'
objs/addon/ngx_healthcheck_module-master/ngx_stream_upstream_check_module.o: In function `ngx_stream_upstream_check_init_main_conf':
ngx_stream_upstream_check_module.c:(.text+0x3479): undefined reference to `ngx_stream_upstream_module'
objs/addon/ngx_healthcheck_module-master/ngx_stream_upstream_check_module.o: In function `ngx_stream_upstream_check_init_process':
ngx_stream_upstream_check_module.c:(.text+0x4201): undefined reference to `ngx_stream_module'
ngx_stream_upstream_check_module.c:(.text+0x421e): undefined reference to `ngx_stream_module'
collect2: error: ld returned 1 exit status
make[1]: *** [objs/nginx] Error 1
make[1]: Leaving directory `/home/Tengine/tengine-3.0.0'
make: *** [build] Error 2

**Comment by lianglli** [comment]
The tengine ngx_http_xquic_module is depend on xquic library.

Pls. check  ( https://github.com/alibaba/tengine/blob/master/modules/ngx_http_xquic_module/README.md ) your information specifically.
