### ISSUE TITLE
Tengine官网很多错误信息

### ISSUE THREAD

**Issue by gatware-1** [alibaba/tengine#1869]
Tengine官网很多错误信息：

1）如域名证书已过期，页面打开不显示信任。
2）模块介绍部分显示很多重复模块（还中英文混杂）。

建议整改。

**Comment by lianglli** [comment]
1）具体证书过期的页面URL是什么？麻烦提供一下URL和截图信息。 

2）tengine官网中涉及重复模块和中英文混用问题，欢迎你提交commit到tengine官网仓库：https://github.com/alibaba/tengine-website-generator

**Comment by gatware-1** [comment]
http://tengine.taobao.org/

**Comment by gatware-1** [comment]
证书不信任问题，刚发现默认网站没有使用https协议，手动改为https证书显示是信任的。
另外就是模块介绍中，有重复信息。

**Comment by gatware-1** [comment]
证书不信任问题，刚发现默认网站没有使用https协议，手动改为https证书显示是信任的。
模块功能介绍部分，英文界面有以下信息，我看内容是一样的：
健康检查模块功能        - Upstream check module 
后端长连接超时功能    - Upstream keepalive timeout
变量                             -  Variables

**Comment by drawing** [comment]
现在官网并未强制跳转 https，通过 http 跟 https 都可以访问

**Comment by drawing** [comment]
> 证书不信任问题，刚发现默认网站没有使用https协议，手动改为https证书显示是信任的。 模块功能介绍部分，英文界面有以下信息，我看内容是一样的： 健康检查模块功能 - Upstream check module 后端长连接超时功能 - Upstream keepalive timeout 变量 - Variables

中英文的问题我们下个版本改进一下，感谢反馈，官网的问题也欢迎大家提交pull request到仓库：https://github.com/alibaba/tengine-website-generator
