### ISSUE TITLE
Tengine模块ngx_multi_upstream_module功能是什么？

### ISSUE THREAD

**Issue by gatware-1** [alibaba/tengine#1870]
Tenginx模块ngx_multi_upstream_module功能是什么？

官方未发现相关说明。

**Comment by chobits** [comment]
是dubbo协议模块需要依赖的一个功能模块，dubbo看这个文档：https://github.com/alibaba/tengine/blob/311ec0439f863dccdc56e7b997140b3e0d7476eb/docs/modules/ngx_http_dubbo_module.md?plain=1

Its a dependent module for the dubbo module. For more details, see this doc: https://github.com/alibaba/tengine/blob/311ec0439f863dccdc56e7b997140b3e0d7476eb/docs/modules/ngx_http_dubbo_module.md?plain=1

**Comment by gatware-1** [comment]
谢谢，各位的解惑。祝大家中秋节快乐。
