### ISSUE TITLE
Tengine为什么不包含nginx_tcp_proxy_module模块？

### ISSUE THREAD

**Issue by gatware-1** [alibaba/tengine#1871]
在Nginx官方第三方模块部分，看到了TCP Proxy模块，包含TCP proxy with NGINX, includes health check and status monitor；
https://github.com/yaoweibin/nginx_tcp_proxy_module

检查发现Tengine modules文件夹不包含此模块，为什么呢？ 放弃维护了吗，还是什么？

谢谢

**Comment by chobits** [comment]
参考官方stream模块 ，tcp proxy模块实现早于nginx。但是后期nginx自己实现了stream模块，然后tengine基于nginx core开发的，所以 也含有stream功能，stream功能和tcpproxy功能基本一样。

**Comment by gatware-1** [comment]
好的，谢谢。中秋节快乐。

**Comment by gatware-1** [comment]
感谢您的解惑，节日快乐。

**Comment by chobits** [comment]
> 感谢您的解惑，节日快乐。

:smile:

**Comment by wcollin** [comment]
tengine能否支持下nginx_tcp_proxy_module模块原来的stream的check功能。
