### ISSUE TITLE
新版本tengine3+，lua 报错

### ISSUE THREAD

**Issue by liuxinagxiang** [alibaba/tengine#1894]
## Question

报错信息类似如下输出：
nginx: [error] lua_load_resty_core failed to load the resty.core module from https://github.com/openresty/lua-resty-core; ensure you are using an OpenResty release from OpenResty - Download (rc: 2, reason: module 'resty.core' not found:
no field package.preload['resty.core']
no file './resty/core.lua'
no file '/usr/local/share/luajit-2.1.0-beta3/resty/core.lua'
no file '/usr/local/share/lua/5.1/resty/core.lua'
no file '/usr/local/share/lua/5.1/resty/core/init.lua'
no file './resty/core.so'
no file '/usr/local/lib/lua/5.1/resty/core.so'
no file '/usr/local/lib/lua/5.1/loadall.so'
no file './resty.so'
no file '/usr/local/lib/lua/5.1/resty.so'
no file '/usr/local/lib/lua/5.1/loadall.so')

**Comment by drawing** [comment]
tengine3+ 升级了 ngx_http_lua_module 到 v0.10.25 版本，在 ngx_http_lua_module v0.10.16 以上版本，resty.core 是必选的，没有 resty.core 无法完成初始化，可以参考 lua module 文档：https://github.com/alibaba/tengine/tree/master/modules/ngx_http_lua_module#installation

**Comment by lianglli** [comment]
参考：https://github.com/alibaba/tengine/blob/master/.github/workflows/test-nginx-core.yml

**Comment by liuxinagxiang** [comment]
好的 感谢！

**Comment by BobFang2023** [comment]
> https://github.com/alibaba/tengine/blob/master/.github/workflows/test-nginx-core.yml

具体怎么操作呢，单独下载 lua-resty-core编译吗？
