### ISSUE TITLE
安装ngx_http_xquic_module模块报错：modules/ngx_http_xquic_module/ngx_http_xquic.c:24:37: fatal error: ngx_http_lua_ssl_certby.h: No such file or directory

### ISSUE THREAD

**Issue by BobFang2023** [alibaba/tengine#1901]
tengine版本：3.1.0

参考文档：https://github.com/alibaba/tengine/blob/master/modules/ngx_http_xquic_module/README.md

最小依赖库编译没有问题：
`./configure --user=www --group=www --prefix=/data/app/tengine-3.1.0 --with-http_ssl_module --with-http_v2_module --without-http_rewrite_module --with-xquic-inc="../xquic-1.6.0/include" --with-xquic-lib="../xquic-1.6.0/build" --add-module=modules/ngx_http_xquic_module --with-openssl="../Tongsuo-8.3.2"`

加上Lua编译报错，应该是由冲突。完整编译参数：
`./configure --user=www --group=www --prefix=/data/app/tengine-3.1.0 --with-http_ssl_module --with-http_v2_module --with-http_realip_module --with-http_addition_module --with-http_geoip_module --with-http_gzip_static_module --with-http_auth_request_module --with-http_secure_link_module --with-http_degradation_module --with-http_stub_status_module --add-module=modules/ngx_http_concat_module --add-module=modules/ngx_http_footer_filter_module --add-module=modules/ngx_http_proxy_connect_module --add-module=modules/ngx_http_reqstat_module --add-module=modules/ngx_http_sysguard_module --add-module=modules/ngx_http_trim_filter_module --add-module=modules/ngx_http_upstream_check_module --add-module=modules/ngx_http_upstream_consistent_hash_module --add-module=modules/ngx_http_upstream_dynamic_module --add-module=modules/ngx_http_upstream_dyups_module --add-module=modules/ngx_http_upstream_session_sticky_module --add-module=modules/ngx_http_upstream_vnswrr_module --add-module=modules/ngx_http_user_agent_module --add-module=modules/ngx_multi_upstream_module --with-jemalloc --with-http_lua_module --with-stream --with-stream_ssl_module --with-stream_realip_module --with-http_dav_module --with-luajit-lib=/usr/local/lib/ --without-http_rewrite_module --with-luajit-inc=/usr/local/include/luajit-2.1/ --with-ld-opt=-Wl,-rpath,/usr/local/lib --with-xquic-inc="../xquic-1.6.0/include" --with-xquic-lib="../xquic-1.6.0/build" --add-module=modules/ngx_http_xquic_module --with-openssl="../Tongsuo-8.3.2"`

make过程报错截图：
![image](https://github.com/alibaba/tengine/assets/150411728/d40f6668-a855-4fdc-a078-c24fe04a3fda)

**Comment by BobFang2023** [comment]
tengine版本：3.1.0

**Comment by lianglli** [comment]
CC_OPT="-g -Og -fstack-protector-strong \
  -DT_HTTP_X_BODY_STREAM \
  -Wformat \
  -Werror=format-security \
  -Wno-deprecated-declarations \
  -fno-strict-aliasing \
  -D_FORTIFY_SOURCE=2 \
  --param=ssp-buffer-size=4 \
  -DTCP_FASTOPEN=23 \
  -fPIC \
  -Wp,-U_FORTIFY_SOURCE -I modules/ngx_http_lua_module/src"

WITH_MODULES="--add-module=modules/ngx_http_lua_module \

./configure \
--with-cc-opt="${CC_OPT}" \
${WITH_MODULES}

**Comment by lianglli** [comment]
参考： https://github.com/alibaba/tengine-ingress/blob/master/images/tengine/rootfs/build.sh

**Comment by BobFang2023** [comment]
> CC_OPT="-g -Og -fstack-protector-strong -DT_HTTP_X_BODY_STREAM -Wformat -Werror=format-security -Wno-deprecated-declarations -fno-strict-aliasing -D_FORTIFY_SOURCE=2 --param=ssp-buffer-size=4 -DTCP_FASTOPEN=23 -fPIC -Wp,-U_FORTIFY_SOURCE -I modules/ngx_http_lua_module/src"
> 
> WITH_MODULES="--add-module=modules/ngx_http_lua_module \
> 
> ./configure --with-cc-opt="${CC_OPT}" ${WITH_MODULES}

解决了，回答的很清晰，速度也快，多谢！
