### ISSUE TITLE
ngx_stream_multi_upstream_module 应用示例

### ISSUE THREAD

**Issue by zhsnew** [alibaba/tengine#1908]
没有找到使用 ngx_stream_multi_upstream_module 模块的代码。

请问是否有示例代码？或者支持multi模式的模块可以开源出来？

**Comment by lianglli** [comment]
https://github.com/alibaba/tengine/blob/master/modules/ngx_multi_upstream_module/ngx_stream_multi_upstream_module.h

https://github.com/alibaba/tengine/blob/master/modules/ngx_multi_upstream_module/ngx_stream_multi_upstream_module.c
