### ISSUE TITLE
Tengine属于信创软件吗？

### ISSUE THREAD

**Issue by iFence** [alibaba/tengine#1912]
## Question

我们在做软件的国产化适配，请问Tengine在信创名单里面吗，Tengine算国产化软件吗，做政府项目要求的国产化软件，可以使用Tengine代替nginx吗

**Comment by lianglli** [comment]
https://kylinos.cn/about/news/275.html

**Comment by lianglli** [comment]
Tengine作为高性能网关本身是没有申请信创软件名录的，信创主要是操作系统和数据库，例如：飞天企业版集成了tengine，支持信创的海光平台 ( https://apsarastackdocument.oss-cn-hangzhou.aliyuncs.com/01_ApsaraStackEnterprise/V3.6.0/%E9%98%BF%E9%87%8C%E4%BA%91%20%E4%B8%93%E6%9C%89%E4%BA%91%E4%BC%81%E4%B8%9A%E7%89%88%20V3.6.0%20%E6%8A%80%E6%9C%AF%E7%99%BD%E7%9A%AE%E4%B9%A6%20-%2020191028.pdf )；国产麒麟系统默认集成了tengine ( https://kylinos.cn/about/news/275.html ) 等。
