### ISSUE TITLE
YoReader 404 Not found

### ISSUE THREAD

**Issue by kiu52** [alibaba/tengine#1915]
### Ⅰ. Issue Description
404 not found on a website, the app also stopped working.

### Ⅱ. Describe what happened
URL:	http://www.yoreader.com/app
Server:	90.1.119.52.ptr.fantomservers.com
Date:	2024/01/28 08:57:22

### Ⅲ. Describe what you expected to happen
I saw underneath the error message that I should report it, not sure if this is the right way to do so. Please fix it if you can.

**Comment by lianglli** [comment]
Pls. debug the web config on the server 90.1.119.52.ptr.fantomservers.com specifically.

**Comment by kiu52** [comment]
Hi i dont know anything about programmes, I'm just a user of the website, what am i supposed to do?

**Comment by kiu52** [comment]
> Pls. debug the web config on the server 90.1.119.52.ptr.fantomservers.com specifically.

Hi i dont know anything about programmes, I'm just a user of the website, what am i supposed to do?
