### ISSUE TITLE
tengine xquic 如何实现被lvs的 udp的健康检查探测到

### ISSUE THREAD

**Issue by longmaythesunshine-zx** [alibaba/tengine#1917]
我们接入架构是 lvs + tengine。lvs 会定期像tengine发送几个udp报文，需要tengine回复指定报文udp才认为健康。但实际使用中xquic会认为这是个错误请求，tengine不会返回任何数据，导致tengine节点会被认为一直不可用。不知道有没有什么方案解决？

**Comment by lianglli** [comment]
#define NGX_XQUIC_HEALTH_CHECK_REQ  "UDPSTATUS"
#define NGX_XQUIC_HEALTH_CHECK_RSP  "UDPOK"

请求报文含magic string "UDPSTATUS"，tengine会回包"UDPOK"

![image](https://github.com/alibaba/tengine/assets/44351259/fbae4a44-5fa1-4c9a-8b48-6f9d60e37194)

![image](https://github.com/alibaba/tengine/assets/44351259/12454e05-13bb-40c9-b38f-1831cb3aca43)

**Comment by longmaythesunshine-zx** [comment]
感谢解答~  我发现我们健康检查的探测报文并不能通过。看了下ngx_xquic_recv.c中 会对udp报文做一个简单的头检测
`     /* check QUIC magic bit */
    if (!NGX_XQUIC_CHECK_MAGIC_BIT(packet->buf)) {
        ngx_log_error(NGX_LOG_WARN, c->log, 0,
                      "|xquic|invalid packet head|");
        return;
    }

#define NGX_XQUIC_CHECK_MAGIC_BIT(pos) (((*(pos)) & 0x40) == 0x40)
`
看起来是需要第一个字符的第二个二进制位是1才行。我看字母都是在这个区间，但是数字不行，我测试了一下也确实如此。

不知道咱们后续有没有考虑优化这块健康检查逻辑？在头检测前先进行healcheck？
以及后续将健康检查报文配置化？这样方便我们自定义配置~
