### ISSUE TITLE
Project dead?

### ISSUE THREAD

**Issue by yonas** [alibaba/tengine#1919]
## Question

Is this project still being maintained?

1. The last commit was 4 months ago
2. There are PRs older than 5 years still open
3. There are 400 open issues

**Comment by lianglli** [comment]
[Tengine ](https://tengine.taobao.org/)

The basic formula for Tengine(& Tengine-Ingress) releases is to expect big releases every two to four months.

**Comment by chobits** [comment]
> [Tengine](https://tengine.taobao.org/)
> 
> @lianglli Thanks. You didn't respond to the other two points:
> 
> * There are PRs older than 5 years still open
> * There are 400 open issues

hi, most unresolved issues and PRs are stale, I think we could closed them now. And some older PRs have been not active.

Don't hesitate to use the Tengine project. It's active, and any outdated issues or pull requests won't hinder your experience. If you encounter any problems, simply open a new issue. The developers and community will respond to you promptly, as they've done with this issue:)
