### ISSUE TITLE
dyups module: 多worker问题场景下worker挂掉后新拉齐的worker是否有之前动态加载的upstream数据？

### ISSUE THREAD

**Issue by zhuzelei** [alibaba/tengine#1920]
请问一下，dyups模块，在多worker场景下，如果某条upstream动态加载完成后，某一个worker挂掉，新启动的worker会有之前动态加载的upstream吗？

**Comment by chobits** [comment]
不会。目前没有重启加载机制，这里是有 https://github.com/yzprofile/ngx_http_dyups_module，但是性能会有问题
