### ISSUE TITLE
What are the advantages of using ngx_ingress_module over ngx_http_lua_module?

### ISSUE THREAD

**Issue by tangxiao187** [alibaba/tengine#1922]
I find Tengine implement a C module _ngx_ingress_module_ to dynamic load domain and certificates, instead of _ngx_http_lua_module_. Is there some special considerations or advantages of using ngx_ingress_module rather than lua?

**Comment by lianglli** [comment]
ngx_ingress_module 是云原生网关tengine-ingress配套tengine的C module，支持K8s Ingress标准规范，且所有域名，路由，证书均支持无损动态生效。在功能和性能方面都远超Lua脚本。

详见：https://tengine.taobao.org/blog.html

**Comment by tangxiao187** [comment]
Thanks. Is there any router-searching benchmark between _ngx_ingress_module_ and Lua？
