### ISSUE TITLE
Tengine支持的底层lib最新版本

### ISSUE THREAD

**Issue by tangds1234** [alibaba/tengine#1931]
## Question

hi~

请问目前Tengine支持icelake上的cpu加速么(qat_sw)，支持的话，目前支持的底层lib版本是哪些？

**Comment by lianglli** [comment]
https://tengine.taobao.org/document_cn/tengine_qat_ssl_cn.html

**Comment by lianglli** [comment]
支持 icelake 型号的SSL硬件加速 。

**Comment by lianglli** [comment]
可以看下：Ice Lake SSL/TLS加速实践
https://openanolis.cn/sig/crypto/doc/390714951012679780

**Comment by tangds1234** [comment]
> 可以看下：Ice Lake SSL/TLS加速实践 https://openanolis.cn/sig/crypto/doc/390714951012679780

好的，谢谢
