### ISSUE TITLE
500 Internal Server Error

### ISSUE THREAD

**Issue by Caedorus** [alibaba/tengine#1972]
### Ⅰ. Issue Description
Attempted to access an Alibaba webpage, was greeted with a message asking to "Please report this message and include the following information to us."

### Ⅱ. Describe what happened
Logged in, reloaded webpage, was greeted with this message.

### Ⅲ. Describe what you expected to happen
Webpage loaded.

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. Go to webpage.
2. Log in.
3. Reload webpage

### Ⅴ. Anything else we need to know?
Full message:

> Sorry for the inconvenience.
> Please report this message and include the following information to us.
> Thank you very much!
> URL:	https://home.aliexpress.com/index.htm
> Server:	wagbridge.033001244159.us44
> Date:	2024/11/26 06:00:15

Screenshot:

![Screenshot from 2024-11-25 22-00-55](https://github.com/user-attachments/assets/4ec69621-7794-40fb-a89f-0a120a96a629)

Excuse me if this is not the right place, if it isn't, please tell me the right place to submit this.

1. If applicable, add nginx  [debug log doc](http://nginx.org/en/docs/debugging_log.html).
2.
3.

### Ⅵ. Environment:

- Tengine version (use `sbin/nginx -V`): N/A
- OS (e.g. from /etc/os-release):
```
- NAME="Linux Mint"
VERSION="21.1 (Vera)"
ID=linuxmint
ID_LIKE="ubuntu debian"
PRETTY_NAME="Linux Mint 21.1"
VERSION_ID="21.1"
HOME_URL="https://www.linuxmint.com/"
SUPPORT_URL="https://forums.linuxmint.com/"
BUG_REPORT_URL="http://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/"
PRIVACY_POLICY_URL="https://www.linuxmint.com/"
VERSION_CODENAME=vera
UBUNTU_CODENAME=jammy
```
- Kernel (e.g. `uname -a`): Linux name 6.8.0-49-generic #49~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Wed Nov  6 17:42:15 UTC 2 x86_64 x86_64 x86_64 GNU/Linux
- Others: N/A

**Comment by chobits** [comment]
These reports indicate that the backend server of AliExpress encountered a failure. I believe they will resolve this issue soon. Additionally, Tengine, acting as a proxy, has logged a 500 backend error.

Thanks for reporting it.
