### ISSUE TITLE
Tengine 2.0的ngx_http_upstream_check_module 好像有问题。

### ISSUE THREAD

**Issue by huopen** [alibaba/tengine#384]
Tengine 2.0的ngx_http_upstream_check_module如果后台是weblogic 11g，会经常出现错误。错误提示如下： 
2014/01/13 14:37:36 [error] 17793#0: http parse status line error with peer: 210.xxx.xx.145:8089 
2014/01/13 14:37:36 [error] 17793#0: check protocol http error with peer: 210.xxx.xx.145:8089 
错误表现是：每检查几次成功后就出现1、2次错误，生成很多错误提示。如果后台是jbss4.2就没有这种错误。
后来我退回Tengine 1.52就正常了，没再出现错误，麻烦检查一下是否有bug！

配置文件如下：
        check interval=2000 rise=2 fall=3 timeout=30000 type=http;  
        check_http_send "GET / HTTP/1.0\r\n\r\n";
        check_http_expect_alive http_2xx http_3xx;

**Comment by jiacheo** [comment]
@cfsego 这个问题在
> Tengine version: Tengine/2.1.0 (nginx/1.6.2)
这个版本上还是存在， 而且加了
> check_keepalive_requests 1;
也没有解决问题。
确定不是防火墙问题， 因为我有一台机是本地的。
我的配置如下：
```
 upstream log-service {
        server localhost:8101;
        server 10.173.83.215:8101;
        check interval=1000 rise=2 fall=2 timeout=1000 type=http;
        check_keepalive_requests 1;
        check_http_send "GET /status.stat HTTP/1.1\r\n\r\n";
        check_http_expect_alive http_2xx http_3xx;
    }
```
部分错误日志如下：

>>>
2015/08/22 11:19:10 [error] 14387#0: check protocol http error with peer: 127.0.0.1:8101 
2015/08/22 11:19:10 [error] 14387#0: check protocol http error with peer: 10.173.83.215:8101 
2015/08/22 11:19:11 [error] 14387#0: check protocol http error with peer: 127.0.0.1:8101 
2015/08/22 11:19:12 [error] 14387#0: check protocol http error with peer: 10.173.83.215:8101 
2015/08/22 11:19:12 [error] 14387#0: check protocol http error with peer: 127.0.0.1:8101 
2015/08/22 11:19:13 [error] 14387#0: check protocol http error with peer: 10.173.83.215:8101 
2015/08/22 11:19:13 [error] 14387#0: check protocol http error with peer: 127.0.0.1:8101 
2015/08/22 11:19:14 [error] 14387#0: check protocol http error with peer: 127.0.0.1:8101 
2015/08/22 11:19:15 [error] 14387#0: check protocol http error with peer: 10.173.83.215:8101 
2015/08/22 11:19:15 [error] 14387#0: check protocol http error with peer: 127.0.0.1:8101 
2015/08/22 11:19:16 [error] 14387#0: check protocol http error with peer: 10.173.83.215:8101 
2015/08/22 11:19:16 [error] 14387#0: check protocol http error with peer: 127.0.0.1:8101 
2015/08/22 11:19:17 [error] 14387#0: check protocol http error with peer: 127.0.0.1:8101 
2015/08/22 11:19:18 [error] 14387#0: check protocol http error with peer: 10.173.83.215:8101 
2015/08/22 11:19:18 [error] 14387#0: check protocol http error with peer: 127.0.0.1:8101 
2015/08/22 11:19:19 [error] 14387#0: check protocol http error with peer: 10.173.83.215:8101 
2015/08/22 11:19:19 [error] 14387#0: check protocol http error with peer: 127.0.0.1:8101 

我去curl这些链接都是没问题的

**Comment by jiacheo** [comment]
好吧， 问题出在  HTTP/1.1，改成HTTP/1.0 就没问题了。。 之所以有HTTP/1.1，是因为我其他机器写的就是HTTP/1.1 。。。

**Comment by yujinqiu** [comment]
@jiacheo 如果你用 HTTP/1.1 的话, 你需要指定 Host, 类似下面的
```
check_http_send "GET / HTTP/1.0\r\nconnection: keep-alive\r\nHost: foo.bar.com\r\n\r\n";
```
[Refer RFC rfc2616#section-14.23](https://tools.ietf.org/html/rfc2616#section-14.23) 
A client MUST include a Host header field in all HTTP/1.1 request messages .

HTTP1.0 只能是短连接, 并且不支持多 Host, 所以没有问题.
