### ISSUE TITLE
 tengine的reuse_port提升到底有多大?我们来对比一下

### ISSUE THREAD

**Issue by wangbin579** [alibaba/tengine#566]
针对Tengine/2.1.0版本，我们试验如下几种情况下的性能对比：
1）默认tengine情况下采用reuse_port on
2）采用reuse_port on,且设置lingering_close on;
3）reuse_port off且lingering_close on;
4）reuse_port off且lingering_close off;

## 硬件条件如下：
[root@zw1-12-190 sbin]# cat /proc/cpuinfo 
processor       : 0
vendor_id       : GenuineIntel
cpu family      : 6
model           : 15
model name      : Intel(R) Xeon(R) CPU            5130  @ 2.00GHz
stepping        : 6
cpu MHz         : 1994.866
cache size      : 4096 KB
physical id     : 0
siblings        : 2
core id         : 0
cpu cores       : 2
apicid          : 0
initial apicid  : 0
fpu             : yes
fpu_exception   : yes
cpuid level     : 10
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx lm constant_tsc arch_perfmon pebs bts rep_good aperfmperf pni dtes64 monitor ds_cpl vmx tm2 ssse3 cx16 xtpr pdcm dca lahf_lm dts tpr_shadow
bogomips        : 3989.73
clflush size    : 64
cache_alignment : 64
address sizes   : 36 bits physical, 48 bits virtual
power management:

processor       : 1
vendor_id       : GenuineIntel
cpu family      : 6
model           : 15
model name      : Intel(R) Xeon(R) CPU            5130  @ 2.00GHz
stepping        : 6
cpu MHz         : 1994.866
cache size      : 4096 KB
physical id     : 3
siblings        : 2
core id         : 0
cpu cores       : 2
apicid          : 6
initial apicid  : 6
fpu             : yes
fpu_exception   : yes
cpuid level     : 10
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx lm constant_tsc arch_perfmon pebs bts rep_good aperfmperf pni dtes64 monitor ds_cpl vmx tm2 ssse3 cx16 xtpr pdcm dca lahf_lm dts tpr_shadow
bogomips        : 3989.46
clflush size    : 64
cache_alignment : 64
address sizes   : 36 bits physical, 48 bits virtual
power management:

processor       : 2
vendor_id       : GenuineIntel
cpu family      : 6
model           : 15
model name      : Intel(R) Xeon(R) CPU            5130  @ 2.00GHz
stepping        : 6
cpu MHz         : 1994.866
cache size      : 4096 KB
physical id     : 0
siblings        : 2
core id         : 1
cpu cores       : 2
apicid          : 1
initial apicid  : 1
fpu             : yes
fpu_exception   : yes
cpuid level     : 10
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx lm constant_tsc arch_perfmon pebs bts rep_good aperfmperf pni dtes64 monitor ds_cpl vmx tm2 ssse3 cx16 xtpr pdcm dca lahf_lm dts tpr_shadow
bogomips        : 3989.73
clflush size    : 64
cache_alignment : 64
address sizes   : 36 bits physical, 48 bits virtual
power management:

processor       : 3
vendor_id       : GenuineIntel
cpu family      : 6
model           : 15
model name      : Intel(R) Xeon(R) CPU            5130  @ 2.00GHz
stepping        : 6
cpu MHz         : 1994.866
cache size      : 4096 KB
physical id     : 3
siblings        : 2
core id         : 1
cpu cores       : 2
apicid          : 7
initial apicid  : 7
fpu             : yes
fpu_exception   : yes
cpuid level     : 10
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx lm constant_tsc arch_perfmon pebs bts rep_good aperfmperf pni dtes64 monitor ds_cpl vmx tm2 ssse3 cx16 xtpr pdcm dca lahf_lm dts tpr_shadow
bogomips        : 3989.46
clflush size    : 64
cache_alignment : 64
address sizes   : 36 bits physical, 48 bits virtual
power management:

## 内存：4G
Mem:   3923920k total

## 1）默认tengine情况下采用reuse_port on
user  xxx;
worker_processes auto;
worker_cpu_affinity auto;
worker_rlimit_nofile 65535;

events {
        worker_connections 65535;
        reuse_port on;
}

http {
        #lingering_close on;
        include mime.types;
        default_type application/octet-stream;
        access_log off;
        keepalive_timeout 0;
        server {
                listen 80 backlog=65535;
                server_name localhost;
                location = /empty.gif {
                        empty_gif;
                }
        }
}

wangbin@ubuntu-191:~/webbench-1.5$ ./webbench -c 500 -t 20 http://10.110.12.190:80/index.html 
Webbench - Simple Web Benchmark 1.5
Copyright (c) Radim Kolar 1997-2004, GPL Open Source Software.

Benchmarking: GET http://10.110.12.190:80/index.html
500 clients, running 20 sec.

Speed=568074 pages/min, 2281836 bytes/sec.
Requests: 189358 susceed, 0 failed.

wangbin@ubuntu-192:~/webbench-1.5$ ./webbench -c 500 -t 20 http://10.110.12.190:80/index.html 
Webbench - Simple Web Benchmark 1.5
Copyright (c) Radim Kolar 1997-2004, GPL Open Source Software.

Benchmarking: GET http://10.110.12.190:80/index.html
500 clients, running 20 sec.

Speed=542682 pages/min, 2179965 bytes/sec.
Requests: 180894 susceed, 0 failed.

[root@zw1-12-193 webbench-1.5]# ./webbench -c 500 -t 20 http://10.110.12.190:80/index.html
Webbench - Simple Web Benchmark 1.5
Copyright (c) Radim Kolar 1997-2004, GPL Open Source Software.

Benchmarking: GET http://10.110.12.190:80/index.html
500 clients, running 20 sec.

Speed=516690 pages/min, 2075516 bytes/sec.
Requests: 172230 susceed, 0 failed.

## 2）在1基础上设置lingering_close on;
user  xxx;
worker_processes auto;
worker_cpu_affinity auto;
worker_rlimit_nofile 65535;

events {
        worker_connections 65535;
        reuse_port on;
}

http {
        lingering_close on;
        include mime.types;
        default_type application/octet-stream;
        access_log off;
        keepalive_timeout 0;
        server {
                listen 80 backlog=65535;
                server_name localhost;
                location = /empty.gif {
                        empty_gif;
                }
        }
}

wangbin@ubuntu-191:~/webbench-1.5$ ./webbench -c 500 -t 20 http://10.110.12.190:80/index.html 
Webbench - Simple Web Benchmark 1.5
Copyright (c) Radim Kolar 1997-2004, GPL Open Source Software.

Benchmarking: GET http://10.110.12.190:80/index.html
500 clients, running 20 sec.

Speed=507789 pages/min, 2039775 bytes/sec.
Requests: 169263 susceed, 0 failed.

wangbin@ubuntu-192:~/webbench-1.5$ ./webbench -c 500 -t 20 http://10.110.12.190:80/index.html 
Webbench - Simple Web Benchmark 1.5
Copyright (c) Radim Kolar 1997-2004, GPL Open Source Software.

Benchmarking: GET http://10.110.12.190:80/index.html
500 clients, running 20 sec.

Speed=496092 pages/min, 1992756 bytes/sec.
Requests: 165364 susceed, 0 failed.

[root@zw1-12-193 webbench-1.5]# ./webbench -c 500 -t 20 http://10.110.12.190:80/index.html 
Webbench - Simple Web Benchmark 1.5
Copyright (c) Radim Kolar 1997-2004, GPL Open Source Software.

Benchmarking: GET http://10.110.12.190:80/index.html
500 clients, running 20 sec.

Speed=464064 pages/min, 1864942 bytes/sec.
Requests: 154688 susceed, 0 failed.

## 3）reuse_port off且lingering_close on;

user  xxx;
worker_processes auto;
worker_cpu_affinity auto;
worker_rlimit_nofile 65535;

events {
        worker_connections 65535;
        #reuse_port on;
}

http {
        lingering_close on;
        include mime.types;
        default_type application/octet-stream;
        access_log off;
        keepalive_timeout 0;
        server {
                listen 80 backlog=65535;
                server_name localhost;
                location = /empty.gif {
                        empty_gif;
                }
        }
}

[root@zw1-12-193 webbench-1.5]# ./webbench -c 500 -t 20 http://10.110.12.190:80/index.html
Webbench - Simple Web Benchmark 1.5
Copyright (c) Radim Kolar 1997-2004, GPL Open Source Software.

Benchmarking: GET http://10.110.12.190:80/index.html
500 clients, running 20 sec.

Speed=524040 pages/min, 2105002 bytes/sec.
Requests: 174680 susceed, 0 failed.

wangbin@ubuntu-192:~/webbench-1.5$ ./webbench -c 500 -t 20 http://10.110.12.190:80/index.html 
Webbench - Simple Web Benchmark 1.5
Copyright (c) Radim Kolar 1997-2004, GPL Open Source Software.

Benchmarking: GET http://10.110.12.190:80/index.html
500 clients, running 20 sec.

Speed=491772 pages/min, 1975344 bytes/sec.
Requests: 163924 susceed, 0 failed.

wangbin@ubuntu-191:~/webbench-1.5$ ./webbench -c 500 -t 20 http://10.110.12.190:80/index.html 
Webbench - Simple Web Benchmark 1.5
Copyright (c) Radim Kolar 1997-2004, GPL Open Source Software.

Benchmarking: GET http://10.110.12.190:80/index.html
500 clients, running 20 sec.

Speed=599019 pages/min, 2406156 bytes/sec.
Requests: 199673 susceed, 0 failed.

## 4) reuse_port off且lingering_close off;

user  xxx;
worker_processes auto;
worker_cpu_affinity auto;
worker_rlimit_nofile 65535;

events {
        worker_connections 65535;
        #reuse_port on;
}

http {
        #lingering_close on;
        include mime.types;
        default_type application/octet-stream;
        access_log off;
        keepalive_timeout 0;
        server {
                listen 80 backlog=65535;
                server_name localhost;
                location = /empty.gif {
                        empty_gif;
                }
        }
}

wangbin@ubuntu-191:~/webbench-1.5$ ./webbench -c 500 -t 20 http://10.110.12.190:80/index.html 
Webbench - Simple Web Benchmark 1.5
Copyright (c) Radim Kolar 1997-2004, GPL Open Source Software.

Benchmarking: GET http://10.110.12.190:80/index.html
500 clients, running 20 sec.

Speed=414852 pages/min, 1666322 bytes/sec.
Requests: 138284 susceed, 0 failed.

wangbin@ubuntu-192:~/webbench-1.5$ ./webbench -c 500 -t 20 http://10.110.12.190:80/index.html 
Webbench - Simple Web Benchmark 1.5
Copyright (c) Radim Kolar 1997-2004, GPL Open Source Software.

Benchmarking: GET http://10.110.12.190:80/index.html
500 clients, running 20 sec.

Speed=388119 pages/min, 1558920 bytes/sec.
Requests: 129373 susceed, 0 failed.

[root@zw1-12-193 webbench-1.5]# ./webbench -c 500 -t 20 http://10.110.12.190:80/index.html
Webbench - Simple Web Benchmark 1.5
Copyright (c) Radim Kolar 1997-2004, GPL Open Source Software.

Benchmarking: GET http://10.110.12.190:80/index.html
500 clients, running 20 sec.

Speed=399519 pages/min, 1604722 bytes/sec.
Requests: 133173 susceed, 0 failed.

## 总结
换成其它压力测试工具weighttp,也是类似的结果

从上面可以看出，tengine默认的lingering_close off，大大降低了短连接的吞吐量，而加上reuse_port on，明显弥补了这个缺陷。

跟默认的nginx相比，tengine reuse_port on的设置，并没有那么大的吞吐量提升，因为nginx默认是lingering_close on的，没有tengine的性能下降缺陷。

这里不排除硬件或者其他环境不一样导致的问题

**Comment by taoyuanyuan** [comment]
你多找几台, 多开几个webbench 看看呢? 
一个webbeach感觉压不满吧

**Comment by wangbin579** [comment]
上面数据已经是3台机器压了

**Comment by taoyuanyuan** [comment]
第三种和第四种场景相差太大了.
注释 reuse_port参数要restart才能生效,  reload不行.
能不能压测时候用 sudo lsof -i :80  看下 FD是不是都是一样的?

**Comment by wangbin579** [comment]
nginx都是重新启动的，没有用reload。

压力测试的时候：
[190 sbin]# sudo lsof -i :80
COMMAND  PID    USER   FD   TYPE  DEVICE SIZE/OFF NODE NAME
nginx   1793 wangbin    6u  IPv4 2352053      0t0  TCP *:http (LISTEN)
nginx   1794 wangbin    8u  IPv4 2352056      0t0  TCP *:http (LISTEN)
nginx   1795 wangbin   10u  IPv4 2352059      0t0  TCP *:http (LISTEN)
nginx   1796 wangbin   12u  IPv4 2352060      0t0  TCP *:http (LISTEN)

FD是不同的

其实这里影响最大的，是lingering_close的设置，不管是对于nginx是啥版本

至于tengine，是因为1.2.2默认设置成了lingering_close off，导致压力测试工具测试后，吞吐量下降

当然我没有用ab来测试，用的是webbench和weightttp

不同环境可能测试结果不一样，但我这里测试都是一样的结果

**Comment by taoyuanyuan** [comment]
hi, 刚才测试了一下. 在我的测试环境 , tengine和nginx两种情况下, lingering_close  的开关对性能基本都没有影响.
哥能帮忙在你的测试环境, 测试一下nginx对于lingering_close的对比情况吗? 
帮忙确认一下是不是我的环境不对.

**Comment by wangbin579** [comment]
经过确认，是webbench和weighttp自身能力不足的问题，导致不同环境下，测试结果不一样。

如果用webbench或者weighttp，那么不管对于nginx还是tengine，lingering_close都是一样的反应。

利用非传统压力测试工具，lingering_close不管是开还是关，均差别不大。
