### ISSUE TITLE
关于使用tengine做app日志收集的想法.

### ISSUE THREAD

**Issue by nice2mu** [alibaba/tengine#568]
目前在安卓,ios上最方便的传送日志的方法通过http协议 如果使用更低层的socket需要在安卓客户端自己处理协议,并且还需要开发服务端.
所以我的想法是安卓,ios客户端通过http将 客户端日志 压缩 发送到nginx 然后 nginx通过 $request_body 打印在日志文件里头.    然后再将日志文件加工入库分析.

我的担心是
在文档上看 写 access_log 
<quote>
写缓冲无效；
每条日志写入都会打开和关闭文件
</quote>

我想问下
1,每条日志 是否是flush之后,在给客户端返回的200 ?
2,这种写日志的方式,是不是会造成性能瓶颈,多个线程等待日志完成?

**Comment by tanguofu** [comment]
1 楼主使用strace 跟踪nginx 就能发现,先返回 http 200 然后再写access日志, 并且没有调用flush.
2 理论上 写日志 是直接写到了操作系统的缓存,一般SATA 硬盘顺序写入的性能是100MB+,如果单条1K 的话 每秒可以写10W条以上. 
建议楼主还是 实际自测下

**Comment by cfsego** [comment]
楼上正解，感谢tanguofu。
补充一点，直接写access日志一般都没有问题，只是删除日志需要在流量低谷时进行，因为对日志进行外部操作时性能会差。如果不在意日志丢失的话，建议用tengine的pipe或者syslog的功能记日志。

**Comment by nice2mu** [comment]
由于  "先返回 http 200 然后再写access日志"    但是app客户端200会认为成功.这里有丢日志的可能.   而且我实验了下,post的字段,如果没有发送到后端,$request_body 是不会初始化的. 这样子复杂了. 所以这个方案不太适合我这个收集的场景. 谢谢个位.

谢谢各位.
