### ISSUE TITLE
Compilation error on MAC OSX 10.9.5

### ISSUE THREAD

**Issue by 24glinka** [alibaba/tengine#569]
Hi,

after make I look on terminal this kind of error, attached as image.
Environment: Mac OSX 10.9.5
![error make osx 10-9-5](https://cloud.githubusercontent.com/assets/10682732/5904645/532971b0-a58a-11e4-8539-dd14a4d2e7d2.png)
.

**Comment by taoyuanyuan** [comment]
./configure --with-cc-opt="-Wno-deprecated-declarations"

You can refer to here 
http://forum.nginx.org/read.php?2,212794,212794#msg-212794

**Comment by 24glinka** [comment]
Ok, it compiles.
