### ISSUE TITLE
请问什么时候会合并nginx 1.7

### ISSUE THREAD

**Issue by deltay** [alibaba/tengine#579]

**Comment by Profforgr** [comment]
When 1.7 will be marked stable, it will be merged, i guess.

**Comment by chobits** [comment]
@deltay 
As @Profforgr said, if nginx 1.8 is released (stable version of nginx 1.7), we will merge it.

**Comment by cfsego** [comment]
@deltay
If you like some feature of nginx 1.7, please tell us. we will look into it, and it is possible to merge it separately.

**Comment by deltay** [comment]
@cfsego, 1.7比1.6.2也没增加多少特性。我只是觉得tengine这种脉冲式的合并有点不习惯， 只等stable才一次合并一大堆，而不是平时阶段性跟进合并。

**Comment by deltay** [comment]
我的问题我已经得到答案了，这个issue可以关闭了, :)
