### ISSUE TITLE
tengine内置变量ngx_http_variables.c中有没有location_id或者server_id之类的？

### ISSUE THREAD

**Issue by zacard-orc** [alibaba/tengine#581]
tengine内置变量ngx_http_variables.c中有没有location_id或者server_id之类的？主要用于location级的经过正则的req_stat统计。

**Comment by chobits** [comment]
如果要用req_stat 模块统计location级别可以用$uri或者 定义一些其他变量
如果要用req_stat 模块统计server级别可以用$host。
--
不过你问题，我还不是非常清楚。

**Comment by cfsego** [comment]
目前肯定是没有的，这个id是否只是在不关心location或者server的具体名称的情况下用来区别location或者server的？

**Comment by zacard-orc** [comment]
如果不关心loc和server，就没法将id映射到这些log和svr上。

不过没关系，后来我们还是从日志中想办法区分了。




还是要谢谢你





--------------------------------------------------------------------------------




------------------ 原始邮件 ------------------




 
 发件人: Chuanwen Chen  <notifications@github.com>
 

 
 发送时间: 2015-04-01 18:40:06
 

 
 收件人: alibaba/tengine  <tengine@noreply.github.com> 
 

 
 抄送: Leiyin Lin  <13816025562@139.com> 
 

 
 主题: Re: [tengine] tengine内置变量ngx_http_variables.c中有没有location_id或者server_id之类的？ (#581)
 



目前肯定是没有的，这个id是否只是在不关心location或者server的具体名称的情况下用来区别location或者server的？
