### ISSUE TITLE
accept_mutex对reuseport有什么影响

### ISSUE THREAD

**Issue by jlijian3** [alibaba/tengine#582]
accept_mutex on和accept_mutex off，对reuseport有什么影响吗？accept_mutex 应该on还是off？

**Comment by jlijian3** [comment]
刚看了代码，开了reuseport，accept_mutex on无用
  if (ccf->master && ccf->worker_processes > 1 && ecf->accept_mutex              
#if (NGX_HAVE_REUSEPORT)
        && !ecf->reuse_port                                                        
#endif
       ) {                                                                         
        ngx_use_accept_mutex = 1

**Comment by monadbobo** [comment]
开了reuseport ， 就不需要accept_mutex了,两个解决的是同样的问题。
