### ISSUE TITLE
SPDY/3.1 support?

### ISSUE THREAD

**Issue by infinitnet** [alibaba/tengine#585]
Support for SPDY/3.0 has recently been deprecated in Google Chrome (they "forgot" to announce it). I would have expected SPDY/3.1 with the Tengine 2.1.0 release, but it's still 3.0 which renders SPDY unusable for Chrome users.. What are your plans for this?

**Comment by chobits** [comment]
We will update spdy module to SPDY/3.1 recently.
The SPDY/2 & SPDY/3 will be preserved, but they cannot be compiled with SPDY/3.1.

**Comment by chobits** [comment]
Fixed in https://github.com/alibaba/tengine/pull/587.

**Comment by infinitnet** [comment]
Thank you, @chobits! As soon as your pull request has been merged with the master branch (it's still pending as far as I can see), I'll try the git master branch instead of the release code.
