### ISSUE TITLE
监控模块（ngx_http_reqstat_module）

### ISSUE THREAD

**Issue by libear** [alibaba/tengine#588]
我有两个建议：
1、增加一个清空共享内存的API。
2、目前的req_status_bypass只实现了1 or 0的功能，能不能更近一步，实现配正则呀，即某些正则下的才统计。

**Comment by chobits** [comment]
@libear 
> 2、目前的req_status_bypass只实现了1 or 0的功能，能不能更近一步，实现配正则呀，即某些正则下的才统计。

req_status_bypass可以配置一个变量，
你可以用nginx的if来改变这个变量值为1或者0，这里你可以把你希望的条件（正则等）写成if的条件
示例：
```
req_status_bypass $req_bypass;

set $req_bypass 0;
if ($uri ~ ^/bypass)  { #  条件: /bypass开头的uri都跳过
  set $req_bypass 1;
}
```

**Comment by cfsego** [comment]
第一个需求我们会来做。
第二个需求我个人感觉如果不能用chobits的方法实现，那么如果能实现在处理完响应后执行if，也可以解决问题。

**Comment by libear** [comment]
是的，希望尽快有 “淘汰机制” 的监控模块的tengine版本出来，我们急着用，呜呜。

**Comment by cfsego** [comment]
'淘汰机制'
2.1.1版本已经发布出来了。
