### ISSUE TITLE
1.7.12 became stable, probably should merge

### ISSUE THREAD

**Issue by Profforgr** [alibaba/tengine#600]
1.7.12 (actually 1.8) became stable. Probably should merge.

**Comment by deltay** [comment]
+1

**Comment by ym** [comment]
+1

**Comment by Am1GO** [comment]
+1 :)

**Comment by han4235** [comment]
+1

**Comment by imleon** [comment]
+1 
1.7.11（或以上版本）

**Comment by yourtion** [comment]
+1

**Comment by magro** [comment]
+1

**Comment by himpich** [comment]
+10

**Comment by derjohn** [comment]
+1 !

**Comment by cfsego** [comment]
now we are working on this.
a lot of collisions at this stage, so a little more time is needed, but it won't be too long.

**Comment by magro** [comment]
@cfsego Great that you're working on this!

**Comment by derjohn** [comment]
Any updates about that issue?

**Comment by chobits** [comment]
@derjohn nginx-1.8 stable has been merged.
You can try the latest tengine git master.
