### ISSUE TITLE
why the method of subrequest is setted NGX_HTTP_GET, instread of the method of  parent request ?

### ISSUE THREAD

**Issue by tanguofu** [alibaba/tengine#604]
in line 2650 of ngx_http_core_module.c: (https://github.com/alibaba/tengine/blob/master/src/http/ngx_http_core_module.c#L2650)

```
sr->method = NGX_HTTP_GET;
```
so, why the method of subrequest is setted NGX_HTTP_GET, instread of parent request method ? is there a bug?

**Comment by yaoweibin** [comment]
There is no relationship between subrequest and its parent. Why do you think it should inherit the method?

**Comment by tanguofu** [comment]
In  the  ngx_http_subrequest function of ngx_http_core_module.c: (https://github.com/alibaba/tengine/blob/master/src/http/ngx_http_core_module.c#L2638),  sr->headers_in,  sr->request_body,  sr->request_line  and some other fields both shared with parents request, but why method don't inherit from its parent?

In out application , we use subrequests to get the response from upstream and make some encoding before return to client. And I think subrequest is “ internal redirects” of parents request.  If the method of parent request is POST, how can I redirect it to upstream by subrequest without change its method? 

please give me some guidance  thinks a lot！

**Comment by cfsego** [comment]
for your case, I think you should use output body filter, but not subrequest.
In my opinion, subrequest is too hacky and bad for both software arctitacture and programmer, so I wish nginx module developer and developer of nginx secondary developmentit to forget it.
