### ISSUE TITLE
Is there a variable - $request_uri without $args ?

### ISSUE THREAD

**Issue by Profforgr** [alibaba/tengine#618]
Hello.

Is there a variable which is $request_uri but without query string ($args)?

$uri (=$document_uri) is different thing, because it's after internal rewrites.

**Comment by chobits** [comment]
hi @Profforgr 
You can use `$raw_uri` in tengine.

**Comment by Profforgr** [comment]
> You can use $raw_uri in tengine.

I hoped Tengine has this feature and it is!

So love Tengine!

Thank you!
