### ISSUE TITLE
Upstream Health Check 模块是否支持 Https 的健康检查

### ISSUE THREAD

**Issue by bjrara** [alibaba/tengine#621]
使用 ssl_hello type 只能做 https 的服务端口检查。是否有类似于 check_http_send 的功能，可指定特定 https uri 路径获取返回码进行健康检查的功能？

**Comment by chobits** [comment]
目前没有再ssl下实现7层的http协议，只是简单的ssl握手。

**Comment by bjrara** [comment]
那你们有类似的需求么？是如何解决的？

**Comment by cfsego** [comment]
因为机器规模太大，所以我们正在努力把健康检查放到别的组件中，而不是在tengine里面做。
对https，内部现在还没有这类需求，主要是lvs来做。
