### ISSUE TITLE
tengine is support thread pool? 

### ISSUE THREAD

**Issue by rfyiamcool** [alibaba/tengine#624]
tengine is support thread pool? 

and, nginx1.7.1 release is support , how abort this future performance ？

**Comment by imleon** [comment]
2015-04-21	
nginx-1.8.0 stable version has been released, incorporating many new features from the 1.7.x mainline branch - including hash load balancing method, backend SSL certificate verification, experimental thread pools support, proxy_request_buffering and more.

We need nginx 1.7.11+ too.

**Comment by tanguofu** [comment]
thread pool is a suitable solution for some block or sync compute task. but port this feature has a lot of work to do, so please wait for a while~

**Comment by cfsego** [comment]
it has been merged for now in tengine 2.2.0 (in development).
but we prefer co-routine for thread pool.
