### ISSUE TITLE
nginx -t时提示[emerg] invalid port in resolver

### ISSUE THREAD

**Issue by marionette-curtain** [alibaba/tengine#626]
提示在nginx.conf的最后一行有错误。但最后一行明显只有一个右花括号。所以请问一下这是怎么回事。
完整出错信息：nginx: [emerg] invalid port in resolver "2400:8500:1101:698:210:157:3:4" in /usr/local/nginx/conf/nginx.conf:43

**Comment by Profforgr** [comment]
Can you give us a dump of nginx.conf 40-45 lines?

**Comment by marionette-curtain** [comment]
Of course.Here it is.
   
    #gzip  on;

    include /home/co/main.conf;
}

**Comment by Profforgr** [comment]
First 5 lines of /home/co/main.conf is needed also -)

**Comment by marionette-curtain** [comment]
#Auto To www
server{
    listen 80;
    server_name www.metaworld.xyz;
    rewrite ^/.(.*) https://metaworld.xyz/$1 permanent;
}

**Comment by chobits** [comment]
Maybe there is a IPV6 record in /etc/resolv.conf.
Tengine will parse every record in /etc/resolv.conf as internal resolver by default.

**Comment by cfsego** [comment]
FIXED in tengine-2.1.1.

**Comment by nic329** [comment]
invalid port in resolver "fd6c:4bb1:87bd::1" in /usr/local/nginx/conf/nginx.conf:123
tengine-2.2.0

**Comment by cyoncan** [comment]
check your file /etc/resolv.conf

**Comment by ldw4033** [comment]
invalid port in resolver "fd6c:4bb1:87bd::1" in /usr/local/nginx/conf/nginx.conf:123
tengine-2.2.2
