### ISSUE TITLE
有没有yum源安装  而且我想安装成service

### ISSUE THREAD

**Issue by nice2mu** [alibaba/tengine#627]
有没有yum源安装  而且我想安装成service

因为是集群来着,我想

yum源方便我:自动安装部署
安装成服务方便我将:启动停止监控

就不想那个编译安装了.
麻烦帮看看?

**Comment by qzlaobi** [comment]
这个可以自己做成服务，自动部署有很多方法实现的，谷歌下。

**Comment by nice2mu** [comment]
是可以做成自己服务的.   但是亲要考虑  普通运维人员的嘛. 

自动部署确实有很多方法实现. 但是我想用最简单的嘛.



继续up下!

**Comment by cfsego** [comment]
没有提供这种服务。
抱歉
