### ISSUE TITLE
Flooding log: accept4() failed (53: Software caused connection abort)

### ISSUE THREAD

**Issue by ghost** [alibaba/tengine#630]
2015/07/30 00:04:12 [error] 15877#0: accept4() failed (53: Software caused connection abort)
2015/07/30 00:04:14 [error] 15877#0: accept4() failed (53: Software caused connection abort)
2015/07/30 00:04:16 [error] 15877#0: accept4() failed (53: Software caused connection abort)
2015/07/30 00:04:18 [error] 15877#0: accept4() failed (53: Software caused connection abort)
2015/07/30 00:04:20 [error] 15877#0: accept4() failed (53: Software caused connection abort)
2015/07/30 00:04:22 [error] 15877#0: accept4() failed (53: Software caused connection abort)
2015/07/30 00:04:26 [error] 15877#0: accept4() failed (53: Software caused connection abort)
2015/07/30 00:04:28 [error] 15877#0: accept4() failed (53: Software caused connection abort)
2015/07/30 00:04:30 [error] 15877#0: accept4() failed (53: Software caused connection abort)
2015/07/30 00:04:32 [error] 15877#0: accept4() failed (53: Software caused connection abort)
2015/07/30 00:04:34 [error] 15877#0: accept4() failed (53: Software caused connection abort)
2015/07/30 00:04:38 [error] 15877#0: accept4() failed (53: Software caused connection abort)
2015/07/30 00:04:40 [error] 15877#0: accept4() failed (53: Software caused connection abort)
2015/07/30 00:04:42 [error] 15877#0: accept4() failed (53: Software caused connection abort)
2015/07/30 00:04:44 [error] 15877#0: accept4() failed (53: Software caused connection abort)
2015/07/30 00:04:48 [error] 15877#0: accept4() failed (53: Software caused connection abort)
2015/07/30 00:04:50 [error] 15877#0: accept4() failed (53: Software caused connection abort)
2015/07/30 00:04:52 [error] 15877#0: accept4() failed (53: Software caused connection abort)
2015/07/30 00:04:56 [error] 15877#0: accept4() failed (53: Software caused connection abort)
2015/07/30 00:04:58 [error] 15877#0: accept4() failed (53: Software caused connection abort)
2015/07/30 00:05:00 [error] 15877#0: accept4() failed (53: Software caused connection abort)
2015/07/30 00:05:04 [error] 15877#0: accept4() failed (53: Software caused connection abort)
2015/07/30 00:05:06 [error] 15877#0: accept4() failed (53: Software caused connection abort)
2015/07/30 00:05:08 [error] 15877#0: accept4() failed (53: Software caused connection abort)
2015/07/30 00:05:10 [error] 15877#0: accept4() failed (53: Software caused connection abort)
2015/07/30 00:05:12 [error] 15877#0: accept4() failed (53: Software caused connection abort)
2015/07/30 00:05:14 [error] 15877#0: accept4() failed (53: Software caused connection abort)
2015/07/30 00:05:16 [error] 15877#0: accept4() failed (53: Software caused connection abort)
2015/07/30 00:05:18 [error] 15877#0: accept4() failed (53: Software caused connection abort)
2015/07/30 00:05:20 [error] 15877#0: accept4() failed (53: Software caused connection abort)
2015/07/30 00:05:22 [error] 15877#0: accept4() failed (53: Software caused connection abort)
2015/07/30 00:05:24 [error] 15877#0: accept4() failed (53: Software caused connection abort)
2015/07/30 00:05:28 [error] 15877#0: accept4() failed (53: Software caused connection abort)
2015/07/30 00:05:30 [error] 15877#0: accept4() failed (53: Software caused connection abort)
2015/07/30 00:05:34 [error] 15877#0: accept4() failed (53: Software caused connection abort)
2015/07/30 00:05:36 [error] 15877#0: accept4() failed (53: Software caused connection abort)
2015/07/30 00:05:42 [error] 15877#0: accept4() failed (53: Software caused connection abort)
2015/07/30 00:05:46 [error] 15877#0: accept4() failed (53: Software caused connection abort)
2015/07/30 00:05:49 [error] 15877#0: accept4() failed (53: Software caused connection abort)
2015/07/30 00:05:51 [error] 15877#0: accept4() failed (53: Software caused connection abort)
2015/07/30 00:05:53 [error] 15877#0: accept4() failed (53: Software caused connection abort)
2015/07/30 00:05:55 [error] 15877#0: accept4() failed (53: Software caused connection abort)
2015/07/30 00:05:57 [error] 15877#0: accept4() failed (53: Software caused connection abort)
2015/07/30 00:05:59 [error] 15877#0: accept4() failed (53: Software caused connection abort)
2015/07/30 00:06:01 [error] 15877#0: accept4() failed (53: Software caused connection abort)
2015/07/30 00:06:03 [error] 15877#0: accept4() failed (53: Software caused connection abort)
2015/07/30 00:06:05 [error] 15877#0: accept4() failed (53: Software caused connection abort)
2015/07/30 00:06:07 [error] 15877#0: accept4() failed (53: Software caused connection abort)
2015/07/30 00:06:11 [error] 15877#0: accept4() failed (53: Software caused connection abort)
2015/07/30 00:06:13 [error] 15877#0: accept4() failed (53: Software caused connection abort)
2015/07/30 00:06:19 [error] 15877#0: accept4() failed (53: Software caused connection abort)
2015/07/30 00:06:23 [error] 15877#0: accept4() failed (53: Software caused connection abort)
2015/07/30 00:06:27 [error] 15877#0: accept4() failed (53: Software caused connection abort)
2015/07/30 00:06:29 [error] 15877#0: accept4() failed (53: Software caused connection abort)
2015/07/30 00:06:35 [error] 15877#0: accept4() failed (53: Software caused connection abort)
2015/07/30 00:06:39 [error] 15877#0: accept4() failed (53: Software caused connection abort)
2015/07/30 00:06:41 [error] 15877#0: accept4() failed (53: Software caused connection abort)
2015/07/30 00:06:49 [error] 15877#0: accept4() failed (53: Software caused connection abort)
2015/07/30 00:06:51 [error] 15877#0: accept4() failed (53: Software caused connection abort)
2015/07/30 00:06:53 [error] 15877#0: accept4() failed (53: Software caused connection abort)
2015/07/30 00:06:57 [error] 15877#0: accept4() failed (53: Software caused connection abort)
2015/07/30 00:06:59 [error] 15877#0: accept4() failed (53: Software caused connection abort)
2015/07/30 00:07:01 [error] 15877#0: accept4() failed (53: Software caused connection abort)
2015/07/30 00:07:03 [error] 15877#0: accept4() failed (53: Software caused connection abort)
2015/07/30 00:07:05 [error] 15877#0: accept4() failed (53: Software caused connection abort)
2015/07/30 00:07:07 [error] 15877#0: accept4() failed (53: Software caused connection abort)
2015/07/30 00:07:09 [error] 15877#0: accept4() failed (53: Software caused connection abort)
2015/07/30 00:07:13 [error] 15877#0: accept4() failed (53: Software caused connection abort)

**Comment by chobits** [comment]
See this Q&A: http://nginx.org/en/docs/faq/accept_failed.html.

Note that `It is a non-critical error`.
