### ISSUE TITLE
请教下nginx本身的fair 这个，tengine也继承了么？

### ISSUE THREAD

**Issue by modoojunko** [alibaba/tengine#632]
upstream中的fair算法。这个做类似CDN的镜像网站时经常用得到

**Comment by chobits** [comment]
upstream fair模块是个第三方模块，nginx本身并没有这个模块功能。
可否提供你使用的fair模块链接。正常情况下，此模块可以在nginx中使用，也可以在tengine中使用。

**Comment by lhjay1** [comment]
https://github.com/gnosek/nginx-upstream-fair/tree/master 这作者3年没更新了

**Comment by modoojunko** [comment]
那tengine扩展了类似的负载均衡算法么？将访问到tengine的用户分到后端响应时间最短的那个节点？

**Comment by cfsego** [comment]
没有，我们没有用到这个

**Comment by modoojunko** [comment]
那请教下你们如何实现把用户分到后面的响应时间最短的节点？

**Comment by cfsego** [comment]
对不起，我们不涉及这方面的讨论
