### ISSUE TITLE
css.js合并出现问题

### ISSUE THREAD

**Issue by klaus-pd** [alibaba/tengine#643]
安装了concat模块..
css合并请求可以正常.但是js则无法访问.
```
location / {
        concat on;
        concat_types text/css application/x-javascript text/javascript;
        concat_unique off;
        concat_delimiter "\n";
        concat_ignore_file_error on;
   }.
```

```
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html>
<head><title>400 Bad Request</title></head>
<body bgcolor="white">
<h1>400 Bad Request</h1>
<p>Your browser sent a request that this server could not understand. Sorry for the inconvenience.<br
/>
Please report this message and include the following information to us.<br/>
Thank you very much!</p>
<table>
<tr>
<td>URL:</td>
<td>http://misc.fangxuehuijia.com/static/assets/js/??base64.js,common.js</td>
</tr>
<tr>
<td>Server:</td>
<td>03e1b1a56c4e</td>
</tr>
<tr>
<td>Date:</td>
<td>2015/09/11 14:40:33</td>
</tr>
</table>
<hr/>Powered by Tengine/2.1.1</body>
</html>
```

**Comment by cfsego** [comment]
配置能不能贴一下，整个 server的部分

**Comment by klaus-pd** [comment]
server {
   listen       80;
   server_name  misc.fangxuehuijia.com ;
   root /data/nginx/;

   location ~* \.(eot|otf|ttf|woff)$ {
        add_header Access-Control-Allow-Origin *;
        expires 24h;
   }
   location ~* \.(htm|html|gif|jpg|jpeg|png|bmp|swf|ioc|rar|zip|txt|flv|mid|doc|ppt|pdf|xls|mp3|wma)$ {
        expires 24h;
   }

   location / {
        concat on;
        concat_types text/css application/x-javascript text/javascript;
        concat_unique off;
        concat_delimiter "\n";
        concat_ignore_file_error on;
   }

}

好的..麻烦帮忙看看

**Comment by cfsego** [comment]
抱歉，这个问题回答得太迟了。
这个问题的原因是mimes.conf中javascript的content-type已经是application/javascript。早先的 text/javascript和application/x-javascript已经不用了。

@IYism 
Thank you for this bugfix.
https://github.com/alibaba/tengine/pull/663

**Comment by chobits** [comment]
问题关闭，如果疑问可以再打开。
