### ISSUE TITLE
Health Check Failed  Abnormally

### ISSUE THREAD

**Issue by guaiguaihw** [alibaba/tengine#662]
我的tengine版本是：
![image](https://cloud.githubusercontent.com/assets/11972366/11140119/da11bd42-8a11-11e5-8f45-fbfd440a38df.png)
线上配置如下：
![image](https://cloud.githubusercontent.com/assets/11972366/11140136/0caf3b58-8a12-11e5-83ce-745d167aa05c.png)
![image](https://cloud.githubusercontent.com/assets/11972366/11140144/2330f8d0-8a12-11e5-8967-9a29e1374b0c.png)
我后端的两台机器有两个接口，分别是：
ip:10000/regular-expression 和 ip:10000/regular-expression/nginxcheck
因为前一个接口是post的，所以我专门写了后面这个接口，做健康检查。但是健康检查一直显示failed。
我用curl是通的，返回hello world：
![image](https://cloud.githubusercontent.com/assets/11972366/11140188/bc7ddc7e-8a12-11e5-9a53-758ac8286071.png)
然而，健康检查从来没通过过，求问，这是什么情况啊！！！

**Comment by guaiguaihw** [comment]
![image](https://cloud.githubusercontent.com/assets/11972366/11140218/15e44410-8a13-11e5-9ef5-3d6cf2a06bab.png)
日志就是这么简单粗暴，直接说我不过！无论是把http改成1.0或者1.1，长连接还是短连接，有没有keep alive，check_keepalive_requests改成多少都不好使！以前配置都没问题啊，怎么会这样，真心求问啊

**Comment by yaoweibin** [comment]
抓一下跟后端通信的包，我怀疑你发送的数据包格式不对。看起来好像多了一个空格？

**Comment by guaiguaihw** [comment]
真的是，多了一个空格！没想到格式这么严格，涨姿势了！！
![image](https://cloud.githubusercontent.com/assets/11972366/11205282/6dcf2ad8-8d41-11e5-82a2-5fada26674c0.png)
