### ISSUE TITLE
nginx: [emerg] unknown "request_time_usec" variable

### ISSUE THREAD

**Issue by linsfg** [alibaba/tengine#665]
Branches:master 
Tengine version: Tengine/2.2.0 (nginx/1.8.0)

reappear：nginx: [emerg] unknown "request_time_msec" variable

**Comment by cfsego** [comment]
Fixed in branch master

BTW,  we are merging Nginx 1.8, some features are not finished, and some are obsolete and deprecated. Sorry for inconvenience.

**Comment by linsfg** [comment]
Ok, thank you!
