### ISSUE TITLE
Does tengine support long pull request?

### ISSUE THREAD

**Issue by wangxiangyu** [alibaba/tengine#666]
不知道tengine是否支long pull类型的请求，也就请求一次，但是结果是以流式方式返回的。这种方式的使用场景是更新推送（server->client），如果server端没有更新，连接就hang住，只有心跳信息传送。我测试了一下，貌似不支持。

**Comment by cfsego** [comment]
确实不支持。
但可以用spdy/http 2.0,或者websocket实现类似的效果。

**Comment by chobits** [comment]
关闭此issue，有新问题和建议可重新打开。
