### ISSUE TITLE
Feature Request: Per-vhost upstream keepalive connection cache

### ISSUE THREAD

**Issue by Dead2** [alibaba/tengine#668]
We use Apache with mpm-itk as our upstream server and tengine as frontend proxy with caching of static resources.

Apache with mpm-itk means that apache preforks processes that listens for connections, and when it knows what vhost the connection will use, it changes its user and group to that vhosts settings. This thus drops root privileges and means that the connection cannot be re-used for another vhost. It can however be reused within the same vhost. If a keepalive connection attemts to access another vhost than the process can handle, then the connection is reset and the client will have to start a new connection.

If tengine could keep a small cache of upstream keepalive connections, since reusing existing connections would be beneficial for performance and scalability, and especially latency.
But for this to work with mpm-itk, I request the possibility to set those connections to be vhost-local, thus only re-using a connection if one exists for the same vhost. This could be solved either by setting a key to differentiate them (like how proxy cache is solved), or by just comparing the hostname and domain parts of the url (less flexible, but still a lot better than nothing.

This could also have limits on how many connections to cache per vhost, to avoid one vhost dominating the cache. And a upper time limit for each connection, to override keepalive timeout sent by the upstream server if it is too long. (it could be out of the control of the tengine user and could thus potentially be set too long).

**Comment by cfsego** [comment]
I think it is practical to make a load balance module solving this problem.
I am not quite sure if you want set limitation on how many connections to cache per vhosts one by one, or just in general.

**Comment by Dead2** [comment]
Well, limiting the number of connections in cache and per vhost should be global in my opinion, or per upstream server would probably be better.
Setting this per vhost is diminishing returns in my opinion, since these connections are meant to be short-lived (typically keepalive is less than 60 seconds). Having one vhost dominate the cache just because it uses many files per pageload would not be fair to the rest of the vhosts.

In my case I would likely set the cache to a total of 30 connections per upstream and max 2 per vhost/domain, since that would then mostly cover the last 15 active vhosts. The total number of vhosts in my setup is about 100-200.

LRU policies (would probably be simple to implement since it needs to keep track of the connections idle-time anyway) could be useful, but I think just adding a connection to the cache if there is a free slot would be more than good enough. The keepalive timeout acts as a poor-mans LRU anyway.

**Comment by cfsego** [comment]
I'm sorry for my English. What does 'poor-mans' refer to?

**Comment by Dead2** [comment]
It means a simple implementation that does ok.

Urban dictionary defines "poor man's" as:
"A knock-off of inferior quality, or something similar to something else, but not as good."

**Comment by cfsego** [comment]
Thank you for explanation.
I'll try to make a prototype first in a few days.
BTW,  I think I can support a variable so that we can use 'map' to define how many connections for each  vhost.

**Comment by cfsego** [comment]
Directive:
Syntax: keepalive connections [key=A] [count=B] [map=$m];
Context: ups

for each key defined by 'key' parameter, upstream holds some keep-alive connections, and the number is defined by 'count' in general. If you want to define the count individually, use the 'map' parameter.

Example1:

    map $host $n {
         A.example 1;
         B.example 2;
         default 0;
    }

    upstream {
        keepalive 10 key=$host map=$n;
    }

Example2:

    upstream {
        keepalive 10 key=$host count=2;
    }

**Comment by Dead2** [comment]
That looks great.

Only thing missing is a timeout parameter for limiting timeout if the host advertises too high timout value. (Ex: Host advertises 10min keepalive timeout, but we want to limit it to 15sec.) This avoids one url (ex: cron.busysite.com) hogging valuable connections better used by the real sites.

Apache also set a max-use number for how many times one keepalive connection can be re-used. I do not see any real need for setting that in tengine, but others might.

**Comment by cfsego** [comment]
I will add a 'keepalive_timeout' as nginx do.

**Comment by cfsego** [comment]
being working on this, I found something new. I believe this module can work well if you use it for local proxy. for example:
 upstream {
    server 127.0.0.1:8080;
    keepalive 10 slice_key=$host slice_conn=2;
 }
but if you use it in the case,
 upstream {
    server 10.10.10.1:8080;
    server 10.10.10.2:8080;
    keepalive 1 slice_key=$host slice_conn=2;
 }
It will have some problem, because it will first get the ip and port, then check if there is keepalive connection.

nginx has removed 'single' param, which helps in the latter case, from 'keepalive', and I won't get it back.

**Comment by cfsego** [comment]
I have finished programming, but no test it yet.

**Comment by cfsego** [comment]
passed nginx testcase
https://github.com/alibaba/tengine/pull/673

**Comment by cfsego** [comment]
add some cases, and passed

**Comment by cfsego** [comment]
add document

**Comment by Dead2** [comment]
Looking good.

I attempted to test from your branch, but got errors about duplicate listen options (where 2.1.1 does not complain on the same config, and there are no options on the line it complains about "listen :80;").

So I created my own fork of 2.1.1 and cherry-picked just the keepalive patches, this works better.

The documentetion says keepalive_time while the code says keepalive_timeout, so that naturally gives an error.

I also get an error about wrong number of parameters when using "keepalive 30 slice_key=$host slice_conn=2;". (This is copied directly from the documentation)
Running just "keepalive 30;" passes the syntax testing and tengine starts and serves fine.

I have verified that keepliave itself is working, and that apache is not forking new processes for each connection. The slice functions I was not able to test due to the above error, and I am not familiar enough with the code to spot the error.

Running ab to stress-test was interesting, 100000 requests with, 200 concurrent and keepalive enabled in ab, apache serving an empty static file. Teninge was tested with upstream keepalive disabled and with 200 connections.
With keepalive it succeeded with 1493 req/sec, without keepalive ab failed around 80k requests stating "apr_socket_recv: Connection reset by peer (104)". Had to lower to 80k requests and retest.

Performance data is pretty much identical for this best-case single-vhost test with a local apache server. Not having to spawn 1500 new processes per second seems to have some impact on stability, but I do not know where that error originates from.

**Comment by cfsego** [comment]
> The documentetion says keepalive_time while the code says keepalive_timeout, so that naturally gives an error.

Sorry, I've made a mistake, it was a typo in document. It has been fixed.

> I also get an error about wrong number of parameters when using "keepalive 30 slice_key=$host slice_conn=2;".

Did you configure nginx with '--without-http_upstream_keepalive_module --add-module=modules/ngx_http_upstream_keepalive_module/'. It is a substitution of nginx original keepalive  module, so you should not compile the origin into binary.

**Comment by cfsego** [comment]
and you said
> I attempted to test from your branch, but got errors about duplicate listen options (where 2.1.1 does not complain on the same config, and there are no options on the line it complains about "listen :80;").

can you paste your configuration, please?

**Comment by Dead2** [comment]
http://pastebin.com/mrvpPTt3

The second server's listen parameters causes errors.

**Comment by Dead2** [comment]
Looks like it is the "reuse_port on;" that is making this problem appear. If I remove that, it works again.
I also noticed I get a segmentation fault if I comment out "worker_connections 1024;"

**Comment by Dead2** [comment]
I have now done some basic testing of the new keepalive module, and it runs without errors while providing a slight performance boost compared to running without it. :)
I will be doing some more preliminary testing before giving it a go on a production server.

**Comment by Dead2** [comment]
reuse_port and segfault problem are easily reproducible with this config:

```
user nginx;
error_log  /var/log/nginx/error.log warn;
pid        /var/run/nginx.pid;

events {
    reuse_port on;
    worker_connections 1024;
}

http {
    include	  /etc/nginx/mime.types;
    default_type  application/octet-stream;

    server { # DEFAULT SITE
        listen *:80 default_server;
        listen 443 default_server ssl spdy;
    }

    server {
        listen *:80;
        listen 443;
    }
}
```

**Comment by cfsego** [comment]
em, It seems we have not dealt with reuse-port right. we merged nginx official reuse-port in branch master and tried to do something to ours, it was still not stable.

**Comment by Dead2** [comment]
This keepalive feature seems to be working great. We have not had any instability or problems since we started using it. I would recommend pulling it into tengine proper.

Great work @cfsego :)

**Comment by cfsego** [comment]
honor to help
