### ISSUE TITLE
Strange issue with regex - direct match returns false

### ISSUE THREAD

**Issue by Profforgr** [alibaba/tengine#671]
Hello.

I am trying to understand these debug log lines and can not. Direct regex match returns false. I've already tried to copy it from debug log to location (in case if some characters differs internally but not visually - does not help).

```nginx
2015/12/03 06:21:06 [debug] 14099#0: *970 http script var: "/index.php?route=module/cart"
2015/12/03 06:21:06 [debug] 14099#0: *970 http script regex: "/index.php?route=module/cart"
2015/12/03 06:21:06 [notice] 14099#0: *970 "/index.php?route=module/cart" does not match "/index.php?route=module/cart", client: x.x.x.x, server: domain.ltd, request: "GET /index.php?route=module/cart HTTP/1.1", host: "domain.ltd"
```

The config lines:
```nginx
if ($request_uri ~* "/index.php?route=module/cart")
{
	set $skip_cache 1;
}
```

I've temporary fixed it using the following configuration:

```nginx
if ($request_uri = "/index.php?route=module/cart")
{
	set $skip_cache 1;
}
```
which works correctly but obviously will not work for URI's like "/index.php?route=module/cart&arg2".

Is there any idea which can lead me to the right direction? 

Thanks in advance for any help.

**Comment by cfsego** [comment]
you can find how to write regex by google.
the question mark is the key.

**Comment by Profforgr** [comment]
> the question mark is the key. 
> if ($request_uri ~* "/index.php\?route=module/cart")
> {
> set $skip_cache 1;
> }

Oh, i am so stupid. Thank you. Your answers are always brilliant.
