### ISSUE TITLE
HTTP/2 Support ?

### ISSUE THREAD

**Issue by squarepants** [alibaba/tengine#672]
Does Tengine support HTTP/2 which introduced in nginx 1.9.5 ?

**Comment by PeterDaveHello** [comment]
We have an issue here: #649

**Comment by cfsego** [comment]
Yes, it's there, passed testcase
I didn't merge it because spdy was removed

**Comment by cfsego** [comment]
you can refer to 2.1.2 branch，so that spdy can still be available
