### ISSUE TITLE
lua-upstream-nginx-module cann't compile successfully on tengine-2.1.1

### ISSUE THREAD

**Issue by saga1015** [alibaba/tengine#674]
Hello,dana
when i compile lua-upstream-nginx in tengine-2.1.1,i see same error

/root/source/tengine/lua-upstream-nginx-module/src/ngx_http_lua_upstream_module.c
/root/source/tengine/lua-upstream-nginx-module/src/ngx_http_lua_upstream_module.c: In function 'ngx_http_lua_upstream_get_servers':
/root/source/tengine/lua-upstream-nginx-module/src/ngx_http_lua_upstream_module.c:175: error: 'ngx_http_upstream_server_t' has no member named 'name'
/root/source/tengine/lua-upstream-nginx-module/src/ngx_http_lua_upstream_module.c:189: error: 'ngx_http_upstream_server_t' has no member named 'name'
/root/source/tengine/lua-upstream-nginx-module/src/ngx_http_lua_upstream_module.c:191: error: 'ngx_http_upstream_server_t' has no member named 'name'
/root/source/tengine/lua-upstream-nginx-module/src/ngx_http_lua_upstream_module.c:192: error: 'ngx_http_upstream_server_t' has no member named 'name'
make[1]: *** [objs/addon/src/ngx_http_lua_upstream_module.o] Error 1
make[1]: Leaving directory `/root/source/tengine/src/tengine-2.1.1'
make: *** [build] Error 2

please help me ,thx very very much! :-)

my compile options:
./configure --prefix=/opt/websuite/tengine \
--conf-path=/opt/config/tengine/nginx.conf \
--error-log-path=/opt/logs/tengine/error.log \
--http-log-path=/opt/logs/tengine/access.log \
--pid-path=/opt/run/tengine \
--user=websuite \
--group=websuite \
--dso-path=/opt/websuite/tengine/modules \
--without-select_module \
--without-poll_module \
--with-file-aio \
--with-http_spdy_module \
--with-http_realip_module \
--with-http_gzip_static_module \
--with-http_auth_request_module \
--with-http_addition_module=shared \
--with-http_image_filter_module=shared \
--with-http_geoip_module=shared \
--with-http_concat_module=shared \
--with-http_random_index_module=shared \
--with-http_secure_link_module=shared \
--with-http_sysguard_module=shared \
--with-http_charset_filter_module=shared \
--with-http_userid_filter_module=shared \
--with-http_footer_filter_module=shared \
--with-http_trim_filter_module=shared \
--with-http_access_module=shared \
--with-http_autoindex_module=shared \
--with-http_map_module=shared \
--with-http_referer_module=shared \
--with-http_fastcgi_module=shared \
--with-http_uwsgi_module=shared \
--with-http_scgi_module=shared \
--with-http_empty_gif_module=shared \
--with-http_limit_conn_module=shared \
--with-http_limit_req_module=shared \
--with-http_browser_module=shared \
--with-http_user_agent_module=shared \
--with-http_upstream_session_sticky_module=shared \
--with-http_upstream_ip_hash_module=shared \
--with-http_dyups_module \
--with-http_reqstat_module=shared \
--without-http_ssi_module \
--without-http_split_clients_module \
--without-http_memcached_module \
--without-http_empty_gif_module \
--without-http_upstream_least_conn_module \
--without-http_upstream_ip_hash_module \
--with-http_tfs_module=shared \
--with-luajit-inc=/opt/websuite/tengine/include/luajit \
--with-luajit-lib=/opt/websuite/tengine/lib \
--with-lua-inc=/opt/websuite/tengine/include \
--with-lua-lib=/opt/websuite/tengine/lib \
--http-client-body-temp-path=/opt/websuite/tengine/cache/client_temp \
--http-proxy-temp-path=/opt/websuite/tengine/cache/proxy_temp \
--http-fastcgi-temp-path=/opt/websuite/tengine/cache/fastcgi_temp \
--http-uwsgi-temp-path=/opt/websuite/tengine/cache/uwsgi_temp \
--http-scgi-temp-path=/opt/websuite/tengine/cache/scgi_temp \
--without-mail_pop3_module \
--without-mail_imap_module \
--without-mail_smtp_module \
--with-pcre=../pcre-8.36 \
--with-pcre-opt=-fPIC \
--with-pcre-jit \
--with-libatomic \
--with-jemalloc \
--with-libyajl-inc=/usr/local/include/yajl \
--with-libyajl-lib=/usr/local/lib \
--with-cc-opt='-w -pipe -march=native -mtune=native -m64 -fno-builtin-malloc' \
--add-module=/root/source/tengine/echo-nginx-module \
--add-module=/root/source/tengine/headers-more-nginx-module \
--add-module=/root/source/tengine/memc-nginx-module \
--add-module=/root/source/tengine/nginx-module-vts \
--add-module=/root/source/tengine/ngx_cache_purge \
--add-module=/root/source/tengine/ngx_devel_kit \
--add-module=/root/source/tengine/ngx_image_thumb \
--add-module=/root/source/tengine/redis2-nginx-module \
--add-module=/root/source/tengine/set-misc-nginx-module \
--add-module=/root/source/tengine/srcache-nginx-module \
--add-module=/root/source/tengine/nginx-hmux-module \
--add-module=/root/source/tengine/nginx-access-plus/src/c \
--add-module=/root/source/tengine/lua-nginx-module \
--add-module=/root/source/tengine/lua-upstream-nginx-module \
--add-module=/root/source/tengine/ngx_small_light \
--add-module=/root/source/tengine/testcookie-nginx-module

**Comment by cfsego** [comment]
For now there is no available version to this.
Please try the master branch, or wait a few days, until we add this part into 2.1.2 branch.

**Comment by cfsego** [comment]
it is in 2.1.2 branch
