### ISSUE TITLE
在http里面配置了trim，html结尾的页面不会进行trim

### ISSUE THREAD

**Issue by webeasymail** [alibaba/tengine#677]
我是用tengine后面proxy的tomcat，已经在http里面配置了trim，目前不是html结尾的给我trim了，html结尾的就不会给我trim，请问这个是什么原因呀？
 trim on;
 trim_js on;
 trim_css on;

**Comment by webeasymail** [comment]
后缀是.gsp的界面也会被trim，就是后缀为html不会trim

**Comment by webeasymail** [comment]
比如一个界面，我通过以下几种方式访问：
http://127.0.0.1//coupon/                      ----   会trim
http://127.0.0.1//coupon/index.gsp       ----   会trim
http://127.0.0.1//coupon/index.jsp        ----   会trim
http://127.0.0.1//coupon/index.html      ----   不会trim
完全不明白，为什么html结尾就不trim了

**Comment by taoyuanyuan** [comment]
不是看后缀，是看你返回头的 content-type。

**Comment by webeasymail** [comment]
访问 http://127.0.0.1/list.html  返回的头文件
![image](https://cloud.githubusercontent.com/assets/4695614/11945845/23bcab00-a88f-11e5-9fdd-adeccce70b41.png)


访问 http://127.0.0.1/lc/ 返回的头文件

![image](https://cloud.githubusercontent.com/assets/4695614/11945865/53f302ec-a88f-11e5-9c70-0de194d78452.png)

**Comment by webeasymail** [comment]
content-type 我看是相同的，最大的不同是，不缓存的response header 头有不一样
不缓存的header多了 accept-ranges 和content-length 
缓存的header头多了 transfer-encoding 和 vary

**Comment by webeasymail** [comment]
就是因为content返回相同，所以觉得很奇怪，搞不清楚为什么会这样，不知道是不是accept-ranges 影响的，一会尝试一下

**Comment by taoyuanyuan** [comment]
你抓包把tomcat返回给tengine的返回头发出来看看
如果tomcat返回的是 gzip压缩文件， tengine的trim不会生效。

**Comment by webeasymail** [comment]
我们后端是这样的 nginx -> varnish -> tomcat 

nginx 用来支持https 

varnish 用来做内存缓存 

tomcat 是我们的应用服务器

我直接访问tomcat  返回的 response header  也是一样的

Content-Language:zh-CN
Content-Type:text/html;charset=UTF-8
Date:Tue, 22 Dec 2015 05:42:17 GMT
Server:Apache-Coyote/1.1
Transfer-Encoding:chunked

访问 varnish  返回的 response header  也是一样的

Accept-Ranges:bytes
Age:10
Connection:keep-alive
Content-Language:zh-CN
Content-Type:text/html;charset=UTF-8
Date:Tue, 22 Dec 2015 05:45:18 GMT
Transfer-Encoding:chunked
Via:1.1 varnish (v4)
X-Cache:MISS
X-Hits:0
X-Varnish:3444032

通过 tengine 访问，我发现 不带后缀的地址 和 带后缀的不太一样

不带后缀的header多了 accept-ranges 和content-length 

带后缀的header头多了 transfer-encoding 和 vary

**Comment by taoyuanyuan** [comment]
访问 http://127.0.0.1/list.html  返回的头文件
![image](https://cloud.githubusercontent.com/assets/4695614/11945845/23bcab00-a88f-11e5-9fdd-adeccce70b41.png)


仔细看了你的图， varnish返回给tengine的数据就已经是gzip的了， filter模块会跳过不处理。
如果是tengine做的压缩， 应该是chunked包，不会有content-length这个头。

你可以通过抓包看下nginx与varnish的请求交互， 或者直接用 curl http://127.0.0.1/list.html  访问一下，看是否有trim效果。

**Comment by webeasymail** [comment]
@taoyuanyuan 额。。还真是的，太粗心了，非常感谢。
