### ISSUE TITLE
编译tengine2.1.2  v2 或spdy模块报错

### ISSUE THREAD

**Issue by lj2007331** [alibaba/tengine#681]
系统：阿里云 CentOS7
编译参数：--prefix=/usr/local/nginx --user=www --group=www --with-http_stub_status_module --with-http_v2_module --with-http_ssl_module --with-ipv6 --with-http_gzip_static_module --with-http_realip_module --with-http_flv_module --with-ld-opt='-ljemalloc'
make报如下错误：
cc -c -pipe  -O -W -Wall -Wpointer-arith -Wno-unused-parameter -Werror -g  -I src/core -I src/event -I src/event/modules -I src/os/unix -I src/proc -I objs -I src/http -I src/http/modules -I src/http/v2 \
        -o objs/src/http/ngx_http_core_module.o \
        src/http/ngx_http_core_module.c
cc -c -pipe  -O -W -Wall -Wpointer-arith -Wno-unused-parameter -Werror -g  -I src/core -I src/event -I src/event/modules -I src/os/unix -I src/proc -I objs -I src/http -I src/http/modules -I src/http/v2 \
        -o objs/src/http/ngx_http_special_response.o \
        src/http/ngx_http_special_response.c
cc -c -pipe  -O -W -Wall -Wpointer-arith -Wno-unused-parameter -Werror -g  -I src/core -I src/event -I src/event/modules -I src/os/unix -I src/proc -I objs -I src/http -I src/http/modules -I src/http/v2 \
        -o objs/src/http/ngx_http_request.o \
        src/http/ngx_http_request.c
src/http/ngx_http_request.c: In function ‘ngx_http_ssl_handshake_handler’:
src/http/ngx_http_request.c:795:50: error: ‘ngx_http_addr_conf_t’ has no member named ‘spdy’
         if (hc->addr_conf->http2 || hc->addr_conf->spdy) {
                                                  ^
src/http/ngx_http_request.c:810:31: error: ‘NGX_SPDY_NPN_NEGOTIATED’ undeclared (first use in this function)
             if (len == sizeof(NGX_SPDY_NPN_NEGOTIATED) - 1
                               ^
src/http/ngx_http_request.c:810:31: note: each undeclared identifier is reported only once for each function it appears in
src/http/ngx_http_request.c:813:17: error: implicit declaration of function ‘ngx_http_spdy_init’ [-Werror=implicit-function-declaration]
                 ngx_http_spdy_init(c->read);
                 ^
cc1: all warnings being treated as errors
make[1]: *** [objs/src/http/ngx_http_request.o] Error 1
make[1]: Leaving directory `/root/oneinstack/src/tengine-2.1.2'
make: *** [build] Error 2

**Comment by chobits** [comment]
使用master分支最新commit试试，最新的代码中已经没有NGX_SPDY_NPN_NEGOTIATE这个宏使用了。

**Comment by cfsego** [comment]
sorry, it's our miss.
now branch 2.1.2 is ok for this case.

Thank you

**Comment by zjhzxhz** [comment]
The same problem for the source code downloaded from `tengine.taobao.org`.
