### ISSUE TITLE
error: variable ‘hc’ set but not used [-Werror=unused-but-set-variable]

### ISSUE THREAD

**Issue by lj2007331** [alibaba/tengine#682]
OS: CentOS-7 64bit
./configure  --prefix=/usr/local/nginx --user=www --group=www --with-http_stub_status_module --with-http_v2_module --with-http_ssl_module --with-ipv6 --with-http_gzip_static_module --with-http_realip_module --with-http_flv_module --with-ld-opt='-ljemalloc'
make error:
cc -c -pipe  -O -W -Wall -Wpointer-arith -Wno-unused-parameter -Werror -g  -I src/core -I src/event -I src/event/modules -I src/os/unix -I src/proc -I objs -I src/http -I src/http/modules -I src/http/v2 \
        -o objs/src/http/ngx_http_request.o \
        src/http/ngx_http_request.c
src/http/ngx_http_request.c: In function ‘ngx_http_ssl_handshake_handler’:
src/http/ngx_http_request.c:791:33: error: variable ‘hc’ set but not used [-Werror=unused-but-set-variable]
         ngx_http_connection_t  *hc;
                                 ^
cc1: all warnings being treated as errors
make[1]: *** [objs/src/http/ngx_http_request.o] Error 1
make[1]: Leaving directory `/root/oneinstack/src/tengine-tengine-2.1.2_f'
make: *** [build] Error 2

**Comment by cfsego** [comment]
please help check out branch 2.1.2 to verify.
