### ISSUE TITLE
关于tengine tls1.2 1.1的bug

### ISSUE THREAD

**Issue by IYism** [alibaba/tengine#684]
配置均一样

使用编译参数（正常）：
./configure --prefix=/opt/tengine
正常打开https 显示是tls1.2

使用编译参数（问题）：
./configure \
--prefix=/etc/nginx \
--sbin-path=/usr/sbin/nginx \
--dso-tool-path=/usr/sbin/ \
--includedir=/usr/include/nginx \
--conf-path=/etc/nginx/nginx.conf \
--error-log-path=/var/log/nginx/error.log \
--http-log-path=/var/log/nginx/access.log \
--pid-path=/var/run/nginx.pid \
--lock-path=/var/run/nginx.lock \
--http-client-body-temp-path=/var/cache/nginx/client_temp \
--http-proxy-temp-path=/var/cache/nginx/proxy_temp \
--http-fastcgi-temp-path=/var/cache/nginx/fastcgi_temp \
--http-uwsgi-temp-path=/var/cache/nginx/uwsgi_temp \
--http-scgi-temp-path=/var/cache/nginx/scgi_temp
正常打开https 显示是tls1.0，不支持tls1.1 1.2.

另外：OPENSSL版本都是一致，用nginx按照以上编译均没有出现问题。

**Comment by cfsego** [comment]
这个我们得测试一下。谢谢

**Comment by IYism** [comment]
@cfsego 麻烦尽快检查下，这个问题困扰好久了

**Comment by IYism** [comment]
@cfsego 不好意思。已经找到问题了，配置导致。
