### ISSUE TITLE
安装2.1.2的版本后反而出现了js合并的问题

### ISSUE THREAD

**Issue by ruitingh** [alibaba/tengine#686]
我升级tengine-2.1.2之后反而出现了concat模块对javascript无效的问题，tengine-2.1.1没有这个问题，请问这是什么情况，谢谢
>$ curl -x 10.x.x.x:80 "http://res.xxxcdn.com/v2/js/webclient/index/index2015/topics/??jquery.fullPage.min.js,jquery-ui.min.js?v=20151209001" -I 
HTTP/1.1 400 Bad Request
Server: Tengine/2.1.2
Date: Wed, 06 Jan 2016 02:33:27 GMT
Content-Type: text/html
Content-Length: 2356
Connection: close
ETag: "548fff99-934"

**Comment by cfsego** [comment]
请把error log级别设置成info，再贴一下error log

**Comment by cfsego** [comment]
另外2.1.2中concat_types默认值现在是text/css application/javascript
看是不是你的js的MIME类型反而不匹配了。

**Comment by ruitingh** [comment]
@cfsego  非常感谢，问题已解决，是concat_types默认值和js的MIME类型不匹配导致的

**Comment by miaoyaoyao** [comment]
这怎么改呢？我也遇到了

**Comment by nottellyou** [comment]
@miaoyaoyao mime.types文件
application/x-javascript              js;
上面这一句把x-去掉，重启tengine就行了。
