### ISSUE TITLE
May be it's a bug about dyups

### ISSUE THREAD

**Issue by wangfakang** [alibaba/tengine#689]
hi @cfsego I found the function `ngx_dyups_init_upstream`  the `cf` structure variable only assignment
part of the member variables. But call `module->create_srv_conf(&cf)` and `cf` some members is 
random value, so it's very dangerous.   
There are two solutions:     
* first: make `cf` variable memzero. Here is a [PR](https://github.com/alibaba/tengine/pull/688).        
* second:using `ngx_cycle` etc. to initialize the  `cf` variable others members.          
what do you think?   
``` c     
static ngx_int_t 
ngx_dyups_init_upstream(ngx_http_dyups_srv_conf_t *duscf, ngx_str_t *name,
    ngx_uint_t index)
{
    ...
    cf.module_type = NGX_HTTP_MODULE;
    cf.cmd_type = NGX_HTTP_MAIN_CONF;
    cf.pool = duscf->pool;
    cf.ctx = ngx_cycle->conf_ctx[ngx_http_module.index];
    ...

    for (m = 0; ngx_modules[m]; m++) {
        if (ngx_modules[m]->type != NGX_HTTP_MODULE) {
            continue;
        }

        if (ngx_modules[m]->index == ngx_http_core_module.index) {
            continue;
        }

        module = ngx_modules[m]->ctx;

        if (module->create_srv_conf) {
            mconf = module->create_srv_conf(&cf);
            if (mconf == NULL) {
                return NGX_ERROR;
            }

            ctx->srv_conf[ngx_modules[m]->ctx_index] = mconf;
        }
    }

}
```

**Comment by yzprofile** [comment]
Merged: https://github.com/alibaba/tengine/pull/688

**Comment by cfsego** [comment]
good to us
thanks very much

**Comment by cfsego** [comment]
and i have a mail to you, please check.

**Comment by wangfakang** [comment]
Oh,I have received and I''ll back to your mail.  Thx.
