### ISSUE TITLE
Tengine - 2.1.2 使用re_useport问题！

### ISSUE THREAD

**Issue by Michael754267513** [alibaba/tengine#704]
Dear 
编译完Tengine，使用re_useport出现以下问题！
[root@michael modules]# /etc/init.d/rc.tengine start
Starting Tengine daemon: tenginenginx: [emerg] setsockopt(SO_REUSEPORT) 0.0.0.0:80 failed (92: Protocol not available)
tengine already running.
内核版本号：2.6.32-358.el6.x86_64
操作系统：CentOS release 6.4 (Final)

**Comment by nav666** [comment]
When you add to config re_useport then listen directive specifies once at all

**Comment by Michael754267513** [comment]
[root@michael ~]# cd /opt/project/tengine/sbin/
[root@michael sbin]# netstat -tunlp 
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address               Foreign Address             State       PID/Program name   
tcp        0      0 0.0.0.0:12345               0.0.0.0:*                   LISTEN      1073/sshd           
[root@michael sbin]# ./nginx 
nginx: [emerg] setsockopt(SO_REUSEPORT) 0.0.0.0:80 failed (92: Protocol not available)

**Comment by Michael754267513** [comment]
when i install the other computer，this feature is ok！

**Comment by nav666** [comment]
Then your OS not support for SO_REUSEPORT. My server is too good work with this feature. But for 1 site for this need a dedicated ip.

**Comment by nav666** [comment]
May be, you must recompile kernel. Give a kernel version & OS that you use.

**Comment by Michael754267513** [comment]
thinks~i think  so

**Comment by chobits** [comment]
It seems that this issue has been resolved. I am closing it.
Reopen it if you have any problem.
