### ISSUE TITLE
ssl和http2不兼容，添加http2后无法进行加密连接。

### ISSUE THREAD

**Issue by Bing1024** [alibaba/tengine#707]
http2 添加 后在  IE 11、chrome 48以下等浏览器都可以打开，chrome 49版本和firefox无法打开。
本来以为是ssl_ciphers配置问题（其实没问题），后来测试删除 http2 就可正常访问。
附上ssl配置，证书代码未包含：

<pre>
ssl_session_cache           shared:SSL:50m;
ssl_session_timeout 1d;
ssl_stapling                on;
ssl_stapling_verify     on;
ssl_session_tickets off;
ssl_protocols           TLSv1 TLSv1.1 TLSv1.2;
# Maximum secure cipher list from https://cipherli.st/. Not support some clients: IF6/XP, IE8/XP, Java 6u45, Java 7u25, OpenSSL 0.9.8y
#ssl_ciphers                 "EECDH+AESGCM:EDH+AESGCM:AES256+EECDH:AES256+EDH";
# Less secure cipher list from https://cipherli.st/. Not support some clients: IF6/XP, Java 6u45

ssl_ciphers 'ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES256-SHA384:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA:ECDHE-RSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA:DHE-RSA-AES256-SHA256:DHE-RSA-AES256-SHA:ECDHE-ECDSA-DES-CBC3-SHA:ECDHE-RSA-DES-CBC3-SHA:EDH-RSA-DES-CBC3-SHA:AES128-GCM-SHA256:AES256-GCM-SHA384:AES128-SHA256:AES256-SHA256:AES128-SHA:AES256-SHA:DES-CBC3-SHA:!DSS';
ssl_prefer_server_ciphers on;

# Use unique [Diffie-Hellman Group](https://weakdh.org/sysadmin.html): `openssl dhparam -out dhparams.pem 2048`
ssl_dhparam                 dhparams.pem;
add_header          Strict-Transport-Security max-age=15768000;
add_header                  X-Content-Type-Options nosniff;

resolver 8.8.8.8 8.8.4.4 valid=300s;
resolver_timeout 5s;
</pre>

**Comment by cfsego** [comment]
你可能的把tlsv1.2放前面

**Comment by cfsego** [comment]
理论上http 2用的ALPN是TLS v1.2加进去的

**Comment by EliBing** [comment]
没有啊，是在最后一个

发自我的诺基亚

**Comment by InfoHunter** [comment]
最好能在访问不了的时候抓包看下出错原因

On Wed, Apr 20, 2016 at 2:00 PM, E·L·I <notifications@github.com> wrote:

> 没有啊，是在最后一个
>
> 发自我的诺基亚
>
> > 在 2016年4月19日，17:36，Chuanwen Chen <notifications@github.com> 写道：
> >
> > 你可能的把tlsv1.2放前面
> >
> > —
> > You are receiving this because you authored the thread.
> > Reply to this email directly or view it on GitHub
> >
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/alibaba/tengine/issues/707#issuecomment-212273410>
>



-- 
Regards

Paul Yang

**Comment by InfoHunter** [comment]
最好能在访问不了的时候抓包看下出错原因

On Wed, Apr 20, 2016 at 2:00 PM, E·L·I <notifications@github.com> wrote:
>
> 没有啊，是在最后一个
>
> 发自我的诺基亚
>
> > 在 2016年4月19日，17:36，Chuanwen Chen <notifications@github.com> 写道：
> >
> > 你可能的把tlsv1.2放前面
> >
> > —
> > You are receiving this because you authored the thread.
> > Reply to this email directly or view it on GitHub
> >
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub




-- 
Regards

Paul Yang

**Comment by cfsego** [comment]
我输错了，是“你可能要把tlsv1.2放前面”

**Comment by EliBing** [comment]
放在前面也无效，加密错误

发自我的诺基亚

**Comment by lilydjwg** [comment]
看看是不是[这里](https://imququ.com/post/why-tls-handshake-failed-with-http2-enabled.html)描述的原因？

**Comment by cfsego** [comment]
这个写得很好啊
