### ISSUE TITLE
tengine2.1.2  第一次请求响应时间慢 js文件加载慢 。。我需要怎么优化呢？

### ISSUE THREAD

**Issue by peirancao** [alibaba/tengine#711]
使用的 ssl http2 spdy 开启了 gzip

ping 的延迟在 20ms 左右

第一次请求 响应很慢 有可能是 dns 解析慢
第二次 直接刷新 秒开
第二次 跳过缓存 刷新 响应很快 站内 js脚本文件 加载 慢 gzip后几十kb 的文件 需要 1-2秒多(TTFB) （之前是合并的单文件 现在webpack拆分成了多个文件 平均 20-30kb 5个文件 其它js根据路由按需加载的，SPA，纯静态文件）

另外问下  2.1.2 支持server push吗？

**Comment by cfsego** [comment]
还不支持server push.
另外我没看懂你的问题，到底是快还是慢。

**Comment by cfsego** [comment]
你要是想跳过dns解析，你就自己做基于IP的请求分发方案。比如写在客户端上等等。

**Comment by alexblair** [comment]
![image](https://cloud.githubusercontent.com/assets/4616320/15144091/d1c7d12a-16df-11e6-80fd-2b4c865d8d45.png)
你可以跟踪一下页面的DNS消耗时间，正常情况下，DNS解析在
1、浏览器打开后未访问
2、本地DNS cache中未记录
情况下 才会比较长。
如果排除DNS的等待时间问题，那么就检查一下服务器的 TIMEWAIT是不是过多，在 /etc/sysctrl 里优化一下timewait的访问。

如果依然不行的话，暂时不知道。希望有用。
