### ISSUE TITLE
How to upload a file in Tengine with my c++ fastcgi application?

### ISSUE THREAD

**Issue by myseemylife** [alibaba/tengine#712]
For some reasons ,i can't use Nginx upload module.
Browser end is a html file form，I got a fastcgi application listen at local pc 9000 port。
when user submit ， how can i use upstream  pass the http body data to my fastcgi app。I need to do writing data operations by myfastcgi application！
Maybe there are other ways to upload？Please give me a advise！

**Comment by yaoweibin** [comment]
Here is the docs for you:  http://nginx.org/en/docs/http/ngx_http_fastcgi_module.html#fastcgi_pass <http://nginx.org/en/docs/http/ngx_http_fastcgi_module.html#fastcgi_pass>
