### ISSUE TITLE
http2 proxy_request_buffering off not work

### ISSUE THREAD

**Issue by LittlePeng** [alibaba/tengine#717]
nginx already fix it:

https://trac.nginx.org/nginx/ticket/892

**Comment by chobits** [comment]
Thanks for report. There are several http/2 patches merged in official nginx recently.
We will merge all these patches soon and pass related test cases.

**Comment by chobits** [comment]
Has been fixed in latest tengine.

Tengine-2.3.0 has been released, it has been been upgraded to nginx 1.15.9.

For more details of new version, see https://github.com/alibaba/tengine/issues/1220.
