### ISSUE TITLE
在tengine中启用spdy问题

### ISSUE THREAD

**Issue by Zeymo** [alibaba/tengine#722]
tngine 已经编了ngx_http_spdy_module (static)，ngnix.conf已经修改成433 ssl spdy，直接https请求目标机TLS证书验证通过，但是同过chrome的SPDY Indicator，无法探测到启用spdy，请问还需要额外的什么配置么(Tengine version: Tengine/2.1.0 (nginx/1.6.2))

**Comment by Zeymo** [comment]
本来就走LVS->Proxy（enginx）-> （tengine + tomcat）无法探测到支持spdy，现在直接连tengine（如上）也探测不到

**Comment by Zeymo** [comment]
升级到Tengine/2.1.2解决

**Comment by leeweir** [comment]
我在2.1.2上测试，用spdylay测试一直不行，handshake成功后，马上就报错了
