### ISSUE TITLE
ngx_http_lua_module  tengine 2.1.2

### ISSUE THREAD

**Issue by Michael754267513** [alibaba/tengine#728]
[root@michael sbin]# ./nginx -m
Tengine version: Tengine/2.1.2 (nginx/1.6.2)
loaded modules:
    ngx_core_module (static)
    ngx_errlog_module (static)
    ngx_conf_module (static)
    ngx_dso_module (static)
    ngx_syslog_module (static)
    ngx_events_module (static)
    ngx_event_core_module (static)
    ngx_epoll_module (static)
    ngx_procs_module (static)
    ngx_proc_core_module (static)
    ngx_openssl_module (static)
    ngx_regex_module (static)
    ngx_http_module (static)
    ngx_http_core_module (static)
    ngx_http_log_module (static)
    ngx_http_upstream_module (static)
    ngx_http_spdy_module (static)
    ngx_http_static_module (static)
    ngx_http_gzip_static_module (static)
    ngx_http_index_module (static)
    ngx_http_access_module (shared, 3.1)
    ngx_http_limit_req_module (shared, 3.1)
    ngx_http_auth_request_module (static)
    ngx_http_auth_basic_module (static)
    ngx_http_limit_conn_module (shared, 3.1)
    ngx_http_realip_module (static)
    ngx_http_geo_module (static)
    ngx_http_rewrite_module (shared, 3.1)
    ngx_http_ssl_module (static)
    ngx_http_proxy_module (static)
    ngx_http_fastcgi_module (static)
    ngx_http_concat_module (shared, 3.1)
    ngx_http_upstream_consistent_hash_module (static)
    ngx_http_upstream_check_module (static)
    ngx_http_upstream_keepalive_module (static)
    ngx_http_upstream_dynamic_module (static)
    ngx_http_stub_status_module (static)
    ngx_http_cache_purge_module (static)
    ngx_http_redis2_module (static)
    ngx_http_write_filter_module (static)
    ngx_http_header_filter_module (static)
    ngx_http_chunked_filter_module (static)
    ngx_http_spdy_filter_module (static)
    ngx_http_range_header_filter_module (static)
    ngx_http_gzip_filter_module (static)
    ngx_http_trim_filter_module (shared, 3.1)
    ngx_http_footer_filter_module (shared, 3.1)
    ngx_http_upstream_session_sticky_module (shared, 3.1)
    ngx_http_headers_filter_module (static)
    ngx_http_testcookie_access_module (static)
    ngx_http_lua_module (static)
    ngx_http_reqstat_module (shared, 3.1)
    ngx_http_copy_filter_module (static)
    ngx_http_range_body_filter_module (static)
    ngx_http_not_modified_filter_module (static)

unknown directive "content_by_lua_block" in /opt/project/tengine/conf/vhost/www.qa.xjh.com.conf:24

        location /lua_content {
                default_type 'text/plain';
                content_by_lua_block {
                ngx.say('Hello,world!')
                }
        }

**Comment by cfsego** [comment]
please compile with '--add-module=ngx_devel_kit'
