### ISSUE TITLE
feature in tengine！Do you have a plan？

### ISSUE THREAD

**Issue by Michael754267513** [alibaba/tengine#732]
ngx_dynamic_upstream is not support！

ngx_dynamic_upstream requires the directive zone in upstream context for sharing upstreams with each nginx worker process. But tengine does not have it.

**Comment by PeterDaveHello** [comment]
The code base is a little bit messy, for a long-term development, maybe it worth to clean it up, try to sync with upstream directly.

**Comment by Michael754267513** [comment]
thinks

**Comment by PeterDaveHello** [comment]
@Michael754267513 but that's my personal thoughts, I'm not part of tengine maintainers.

**Comment by Michael754267513** [comment]
ok！
