### ISSUE TITLE
"zero size buf in output t:0 r:0 f:1" in error log

### ISSUE THREAD

**Issue by Zeymo** [alibaba/tengine#733]
在开启spdy的日志中一直刷"[alert] 25022#0: *50629265 zero size buf in output t:0 r:0 f:1 0000000000000000 0000000000000000-0000000000000000 0000000000C49EC0 0-0 while sending request to upstream"，打得比access还多很多，是第三方模块的问题么？

**Comment by chobits** [comment]
能列出你用了哪些模块吗，这个请求？
一般是某些模块产生数据后经过upstream转发到后端时候，发现构造出来的数据buf的size是0.（这其实算是bug，不过如果没有开启debug point的话，忽略即可，Tengine/nginx会自动跳过这个buf)

**Comment by chobits** [comment]
https://www.ruby-forum.com/topic/4422340 "Zero size buf" Error on file upload
https://www.ruby-forum.com/topic/6877956 Nginx Zero size buffer Alert
