### ISSUE TITLE
can ngx_http_upstream_check_module expose api to check upstream status?

### ISSUE THREAD

**Issue by detailyang** [alibaba/tengine#740]
Hello, can ngx_http_upstream_check_module expose api which is convenient to other modules for  check upstream status? 
We wish check the specified upstream status by ngx_http_upstream_check_module, but there is ngx_http_upstream_check_peer_down to check peer down.

**Comment by chobits** [comment]
have been fixed.

**Comment by detailyang** [comment]
can't agree any more, it's useful api for other modules  :rocket: :rocket: :rocket:
