### ISSUE TITLE
关于tengine中使用http2的稳定性问题？

### ISSUE THREAD

**Issue by BBBao** [alibaba/tengine#759]
nginx 今年年初最新版本已经发布了稳定的可生产环境使用的http2；而且要去openssl 1.0.2版本。

转而tengine去年年底的2.1.2的版本，支持http2，但nginx还是1.6的稳定版本；

所以关于http2，目前 tengine支持的是否跟nginx官方一样确保稳定线上环境使用？

没有找到http2相关稳定性介绍，心里有点虚不太敢用啊？ 还麻烦帮忙给个解答.

谢谢.

**Comment by chobits** [comment]
There is a bug that HTTP/2 post request will trigger timeout in Tengine 2.2.2.

This bug has been fixed in Tengine 2.3.0.

Tengine-2.3.0 has been released, it has been been upgraded to nginx 1.15.9.
For more details of new version, see https://github.com/alibaba/tengine/issues/1220.
