### ISSUE TITLE
支持njs（nginScript）

### ISSUE THREAD

**Issue by goto100** [alibaba/tengine#762]
相较于 Lua，nginx 官方出的 nginScript 应该更适合做 nginx 的嵌入开发。

是否考虑默认编译进此插件？

**Comment by chobits** [comment]
* njs本身是个nginx模块，与nginx core不耦合，所以暂时不会merge进tengine
* 可以直接使用该模块于tengine中，可以参考nginx编译打开njs：https://www.nginx.com/resources/wiki/nginScript/#section-2-installing-the-nginscript-module
