### ISSUE TITLE
2.1.2版本使用https时，cpu马上就上去了。

### ISSUE THREAD

**Issue by jinleileiking** [alibaba/tengine#764]
是nginx就这样，还是有其他问题？

**Comment by wangfakang** [comment]
使用https了肯定会增加cpu消耗的，毕竟各种加解密算法是需要消耗cpu的，具体消耗可以使用perf工具查看。

**Comment by chobits** [comment]
* 暂时关闭，如有问题可以再次打开。
* `$ perf top -p <nginx worker>` 查看下主要cpu消耗是否在ssl相关函数

**Comment by jinleileiking** [comment]
感谢感谢，阿里的态度就是比某些开源framework框架的创始人好。
