### ISSUE TITLE
nginx: [emerg] unknown directive "fastcgi_intercept_errors"

### ISSUE THREAD

**Issue by xufqing** [alibaba/tengine#765]
[root@website tengine-2.1.2]# /usr/local/nginx/sbin/nginx -t -c /opt/conf/nginx.conf
nginx: the configuration file /opt/conf/nginx.conf syntax is ok
nginx: configuration file /opt/conf/nginx.conf test is successful

[root@website tengine-2.1.2]# /usr/local/tengine/sbin/nginx -t -c /opt/conf/nginx.conf
nginx: [emerg] unknown directive "fastcgi_intercept_errors" in /opt/conf/nginx.conf:46
configuration file /opt/conf/nginx.conf test failed

从Nginx切换到tengine，配置文件在Nginx检查通过，在tengine检查启动失败

**Comment by chobits** [comment]
把tengine如下指令返回贴出看一下：

```
/path/to/sbin/nginx -m
```

可能是没有编译    ngx_http_fastcgi_module 模块

**Comment by chobits** [comment]
暂时关闭，如有问题可以再次打开。
