### ISSUE TITLE
Tengine 2.1.2编译CNSRE-lua-upstream-nginx-module出现错误

### ISSUE THREAD

**Issue by saga1015** [alibaba/tengine#767]
@cfsego @chobits 
Tengine 2.1.2在编译CNSRE提供的lua-upstream-nginx-module时报如下错误
[root@localhost tengine-2.1.2]# make
make -f objs/Makefile
make[1]: Entering directory `/root/source/tengine/src/tengine-2.1.2'
cc -c -I/opt/websuite/tengine/include/luajit-2.1  -pipe  -O -W -Wall -Wpointer-arith -Wno-unused-parameter -Werror -w -pipe -march=native -mtune=native -m128bit-long-double -m64 -fno-builtin-malloc -DNDK_SET_VAR -DNDK_SET_VAR -DNDK_SET_VAR -DNDK_UPSTREAM_LIST -DNDK_SET_VAR  -I src/core -I src/event -I src/event/modules -I src/os/unix -I src/proc -I src/http/modules/tfs -I /root/source/tengine/module/ngx_devel_kit/objs -I objs/addon/ndk -I /root/source/tengine/module/lua-nginx-module-0.10.5/src/api -I /opt/websuite/tengine/include/luajit-2.1 -I ../pcre-8.36 -I /opt/websuite/tengine/include/yajl -I objs -I src/http -I src/http/modules -I src/http/v2 -I /root/source/tengine/module/ngx_devel_kit/src -I src/mail \
                -o objs/addon/src/ngx_http_lua_upstream_module.o \
                /root/source/tengine/module/lua-upstream-tengine-module/src/ngx_http_lua_upstream_module.c
/root/source/tengine/module/lua-upstream-tengine-module/src/ngx_http_lua_upstream_module.c: 在函数‘ngx_http_lua_upstream_add_peer’中:
/root/source/tengine/module/lua-upstream-tengine-module/src/ngx_http_lua_upstream_module.c:1024: 错误：‘ngx_http_upstream_rr_peer_t’没有名为‘server’的成员
/root/source/tengine/module/lua-upstream-tengine-module/src/ngx_http_lua_upstream_module.c:1064: 错误：‘ngx_http_upstream_rr_peer_t’没有名为‘server’的成员
make[1]: *** [objs/addon/src/ngx_http_lua_upstream_module.o] 错误 1
make[1]: Leaving directory `/root/source/tengine/src/tengine-2.1.2'
make: *** [build] 错误 2

编译参数为;
./configure --prefix=/opt/websuite/tengine \
--conf-path=/opt/config/tengine/nginx.conf \
--error-log-path=/opt/logs/tengine/error.log \
--http-log-path=/opt/logs/tengine/access.log \
--pid-path=/opt/run/tengine \
--user=websuite \
--group=websuite \
--dso-path=/opt/websuite/tengine/modules \
--without-select_module \
--without-poll_module \
--with-file-aio \
--with-http_spdy_module \
--with-http_v2_module \
--with-http_realip_module \
--with-http_gzip_static_module \
--with-http_auth_request_module \
--with-http_addition_module=shared \
--with-http_image_filter_module=shared \
--with-http_geoip_module=shared \
--with-http_concat_module=shared \
--with-http_random_index_module=shared \
--with-http_secure_link_module=shared \
--with-http_sysguard_module=shared \
--with-http_charset_filter_module=shared \
--with-http_userid_filter_module=shared \
--with-http_footer_filter_module=shared \
--with-http_trim_filter_module=shared \
--with-http_access_module=shared \
--with-http_autoindex_module=shared \
--with-http_map_module=shared \
--with-http_referer_module=shared \
--with-http_uwsgi_module=shared \
--with-http_scgi_module=shared \
--with-http_empty_gif_module=shared \
--with-http_limit_conn_module=shared \
--with-http_limit_req_module=shared \
--with-http_reqstat_module=shared \
--with-http_browser_module=shared \
--with-http_user_agent_module=shared \
--with-http_upstream_session_sticky_module=shared \
--with-http_upstream_ip_hash_module=shared \
--without-http_ssi_module \
--without-http_split_clients_module \
--without-http_memcached_module \
--without-http_upstream_least_conn_module \
--with-http_tfs_module=shared \
--with-libyajl-inc=/opt/websuite/tengine/include/yajl \
--with-libyajl-lib=/opt/websuite/tengine/lib \
--with-luajit-inc=/opt/websuite/tengine/include/luajit-2.1 \
--with-luajit-lib=/opt/websuite/tengine/lib \
--http-client-body-temp-path=/opt/websuite/tengine/cache/client_temp \
--http-proxy-temp-path=/opt/websuite/tengine/cache/proxy_temp \
--http-fastcgi-temp-path=/opt/websuite/tengine/cache/fastcgi_temp \
--http-uwsgi-temp-path=/opt/websuite/tengine/cache/uwsgi_temp \
--http-scgi-temp-path=/opt/websuite/tengine/cache/scgi_temp \
--without-mail_pop3_module \
--without-mail_imap_module \
--without-mail_smtp_module \
--with-pcre=../pcre-8.36 \
--with-pcre-opt=-fPIC \
--with-pcre-jit \
--with-jemalloc \
--with-cc-opt='-w -pipe -march=native -mtune=native -m128bit-long-double -m64 -fno-builtin-malloc' \
--add-module=/root/source/tengine/module/ngx_devel_kit \
--add-module=/root/source/tengine/module/lua-nginx-module-0.10.5 \
--add-module=/root/source/tengine/module/lua-upstream-tengine-module \
--add-module=/root/source/tengine/module/encrypted-session-nginx-module \
--add-module=/root/source/tengine/module/set-misc-nginx-module \
--add-module=/root/source/tengine/module/form-input-nginx-module

**Comment by wangfakang** [comment]
@saga1015 看了下CNSRE这个模块目前最新只支持tengine-2.1.1版本，可以使用这个分支的[for-tengine-2.1.1](https://github.com/CNSRE/lua-upstream-nginx-module/tree/dev(for-tengine-2.1.1))

**Comment by saga1015** [comment]
@wangfakang 好的，哈哈。感谢
