### ISSUE TITLE
Tengine 2.1.2启用reuseport后，执行stop报close() socket 172.16.2.71:80 failed (9: Bad file descriptor)

### ISSUE THREAD

**Issue by saga1015** [alibaba/tengine#769]
执行nginx -s stop时会报错，以下为debug日志
2016/07/29 10:44:10 [debug] 32415#0: bind() 172.16.2.71:80 #7 
2016/07/29 10:44:10 [notice] 32415#0: try again to bind() after 500ms
2016/07/29 10:44:10 [debug] 32415#0: bind() 172.16.2.71:80 #7 
2016/07/29 10:44:10 [notice] 32415#0: using the "epoll" event method
2016/07/29 10:44:10 [debug] 32415#0: counter: 00007F80C55C5080, 1
2016/07/29 10:44:10 [debug] 32415#0: add cleanup: 00007F80C3D13C08
2016/07/29 10:44:10 [debug] 32415#0: malloc: 00007F80C3CFE000:4096
2016/07/29 10:44:10 [debug] 32415#0: malloc: 00007F80C3D0C000:4096
2016/07/29 10:44:10 [debug] 32415#0: malloc: 00007F80C3D16000:4096
2016/07/29 10:44:10 [debug] 32415#0: malloc: 00007F80C3D17000:4096
2016/07/29 10:44:10 [debug] 32415#0: malloc: 00007F80C3D18000:4096
2016/07/29 10:44:10 [debug] 32415#0: malloc: 00007F80C3D19000:4096
2016/07/29 10:44:10 [debug] 32415#0: malloc: 00007F80C3D1A000:4096
2016/07/29 10:44:10 [debug] 32415#0: malloc: 00007F80C3D1B000:4096
2016/07/29 10:44:10 [notice] 32415#0: nginx/1.6.2
2016/07/29 10:44:10 [notice] 32415#0: built by gcc 4.4.7 20120313 (Red Hat 4.4.7-11) (GCC) 
2016/07/29 10:44:10 [notice] 32415#0: OS: Linux 2.6.32-431.29.2.el6.x86_64
2016/07/29 10:44:10 [notice] 32415#0: getrlimit(RLIMIT_NOFILE): 409600:409600
2016/07/29 10:44:10 [debug] 32416#0: write: 8, 00007FFF4EBCE230, 6, 0
2016/07/29 10:44:10 [debug] 32416#0: setproctitle: "nginx: master process /opt/websuite/tengine/sbin/nginx -c /opt/config/tengine/n
ginx.conf"
2016/07/29 10:44:10 [notice] 32416#0: start worker processes
2016/07/29 10:44:10 [debug] 32416#0: close listening 172.16.2.71:80 #7 
2016/07/29 10:44:10 [debug] 32416#0: channel 3:7
2016/07/29 10:44:10 [notice] 32416#0: start worker process 32417
2016/07/29 10:44:10 [debug] 32416#0: channel 8:9
2016/07/29 10:44:10 [debug] 32417#0: bind() 172.16.2.71:80 #8 
2016/07/29 10:44:10 [notice] 32416#0: start worker process 32419
2016/07/29 10:44:10 [debug] 32416#0: pass channel s:1 pid:32419 fd:8 to s:0 pid:32417 fd:3
2016/07/29 10:44:10 [notice] 32416#0: start procs processes
2016/07/29 10:44:10 [debug] 32416#0: sigsuspend
2016/07/29 10:44:10 [debug] 32419#0: bind() 172.16.2.71:80 #10 
2016/07/29 10:44:10 [notice] 32417#0: sched_setaffinity(0x0000000000800000)
2016/07/29 10:44:10 [debug] 32417#0: eventfd: 10
2016/07/29 10:44:10 [debug] 32417#0: malloc: 00007F80C3D1C000:6144
2016/07/29 10:44:10 [debug] 32417#0: malloc: 00007F80C3D1E000:1835008
2016/07/29 10:44:10 [debug] 32417#0: malloc: 00007F80C3EDE000:851968
2016/07/29 10:44:10 [notice] 32419#0: sched_setaffinity(0x0000000000400000)
2016/07/29 10:44:10 [debug] 32419#0: eventfd: 12
2016/07/29 10:44:10 [debug] 32419#0: malloc: 00007F80C3D1C000:6144
2016/07/29 10:44:10 [debug] 32419#0: malloc: 00007F80C3D1E000:1835008
2016/07/29 10:44:10 [debug] 32419#0: malloc: 00007F80C3EDE000:851968
2016/07/29 10:44:10 [debug] 32417#0: malloc: 00007F80C2806000:851968
2016/07/29 10:44:10 [debug] 32419#0: malloc: 00007F80C2806000:851968
2016/07/29 10:44:10 [debug] 32417#0: http check upstream init_process, shm_name: ngx_http_upstream_check#1, peer number: 0
2016/07/29 10:44:10 [debug] 32417#0: epoll add event: fd:7 op:1 ev:00002001
2016/07/29 10:44:10 [debug] 32417#0: setproctitle: "nginx: worker process"
2016/07/29 10:44:10 [debug] 32417#0: worker cycle
2016/07/29 10:44:10 [debug] 32417#0: epoll timer: -1
2016/07/29 10:44:11 [debug] 32417#0: epoll: fd:7 ev:0001 d:00007F80C3D1E0E0
2016/07/29 10:44:11 [debug] 32417#0: channel handler
2016/07/29 10:44:11 [debug] 32417#0: channel: 32
2016/07/29 10:44:11 [debug] 32417#0: channel command: 1
2016/07/29 10:44:11 [debug] 32417#0: get channel s:1 pid:32419 fd:3
2016/07/29 10:44:11 [debug] 32417#0: channel: -2
2016/07/29 10:44:11 [debug] 32417#0: timer delta: 510
2016/07/29 10:44:11 [debug] 32417#0: posted events 0000000000000000
2016/07/29 10:44:11 [debug] 32417#0: worker cycle
2016/07/29 10:44:11 [debug] 32417#0: epoll timer: -1
2016/07/29 10:44:10 [debug] 32419#0: http check upstream init_process, shm_name: ngx_http_upstream_check#1, peer number: 0
2016/07/29 10:44:10 [debug] 32419#0: epoll add event: fd:9 op:1 ev:00002001
2016/07/29 10:44:10 [debug] 32419#0: setproctitle: "nginx: worker process"
2016/07/29 10:44:10 [debug] 32419#0: worker cycle
2016/07/29 10:44:10 [debug] 32419#0: epoll timer: -1
2016/07/29 10:44:12 [notice] 32422#0: signal process started
2016/07/29 10:44:12 [notice] 32416#0: signal 15 (SIGTERM) received, exiting
2016/07/29 10:44:12 [debug] 32416#0: wake up, sigio 0
2016/07/29 10:44:12 [debug] 32416#0: child: 0 32417 e:0 t:0 d:0 r:1 j:0
2016/07/29 10:44:12 [debug] 32416#0: child: 1 32419 e:0 t:0 d:0 r:1 j:0
2016/07/29 10:44:12 [debug] 32416#0: termination cycle: 50
2016/07/29 10:44:12 [debug] 32416#0: sigsuspend
2016/07/29 10:44:12 [debug] 32417#0: epoll: fd:7 ev:0001 d:00007F80C3D1E0E0
2016/07/29 10:44:12 [debug] 32417#0: channel handler
2016/07/29 10:44:12 [debug] 32417#0: channel: 32
2016/07/29 10:44:12 [debug] 32417#0: channel command: 4
2016/07/29 10:44:12 [debug] 32417#0: channel: -2
2016/07/29 10:44:12 [debug] 32417#0: timer delta: 1286
2016/07/29 10:44:12 [debug] 32417#0: posted events 0000000000000000
2016/07/29 10:44:12 [notice] 32417#0: exiting
2016/07/29 10:44:12 [debug] 32419#0: epoll: fd:9 ev:0001 d:00007F80C3D1E0E0
2016/07/29 10:44:12 [debug] 32417#0: flush files
2016/07/29 10:44:12 [debug] 32419#0: channel handler
2016/07/29 10:44:12 [debug] 32417#0: run cleanup: 00007F80C3D13C08
2016/07/29 10:44:12 [debug] 32419#0: channel: 32
2016/07/29 10:44:12 [debug] 32419#0: channel command: 4
2016/07/29 10:44:12 [debug] 32419#0: channel: -2
2016/07/29 10:44:12 [debug] 32419#0: timer delta: 1796
2016/07/29 10:44:12 [debug] 32417#0: run cleanup: 00007F80C3D06D80
2016/07/29 10:44:12 [debug] 32419#0: posted events 0000000000000000
2016/07/29 10:44:12 [debug] 32417#0: cleanup resolver
2016/07/29 10:44:12 [notice] 32419#0: exiting
2016/07/29 10:44:12 [debug] 32417#0: run cleanup: 00007F80C3CD6128
2016/07/29 10:44:12 [debug] 32419#0: flush files
2016/07/29 10:44:12 [debug] 32419#0: run cleanup: 00007F80C3D13C08
2016/07/29 10:44:12 [debug] 32419#0: run cleanup: 00007F80C3D06D80
2016/07/29 10:44:12 [debug] 32419#0: cleanup resolver
2016/07/29 10:44:12 [debug] 32419#0: run cleanup: 00007F80C3CD6128
2016/07/29 10:44:12 [debug] 32417#0: free: 00007F80C3D1B000
2016/07/29 10:44:12 [debug] 32417#0: free: 00007F80C3D1A000
2016/07/29 10:44:12 [debug] 32417#0: free: 00007F80C3D19000
2016/07/29 10:44:12 [debug] 32417#0: free: 00007F80C3D18000
2016/07/29 10:44:12 [debug] 32417#0: free: 00007F80C3D17000
2016/07/29 10:44:12 [debug] 32417#0: free: 00007F80C3D16000
2016/07/29 10:44:12 [debug] 32417#0: free: 00007F80C3D0C000
2016/07/29 10:44:12 [debug] 32417#0: free: 00007F80C3CFE000
2016/07/29 10:44:12 [debug] 32417#0: free: 00007F80C3D0A000
2016/07/29 10:44:12 [debug] 32417#0: free: 00007F80C3D08000
2016/07/29 10:44:12 [debug] 32417#0: free: 00007F80C3D03000
2016/07/29 10:44:12 [debug] 32417#0: free: 00007F80C3CFD000
2016/07/29 10:44:12 [debug] 32417#0: free: 00007F80C3CF7000
2016/07/29 10:44:12 [debug] 32417#0: free: 00007F80C3CF5000
2016/07/29 10:44:12 [debug] 32417#0: free: 00007F80C3C9C000
2016/07/29 10:44:12 [debug] 32417#0: free: 00007F80C3CD5000, unused: 0
2016/07/29 10:44:12 [debug] 32417#0: free: 00007F80C3CF9000, unused: 0
2016/07/29 10:44:12 [debug] 32419#0: free: 00007F80C3D1B000
2016/07/29 10:44:12 [debug] 32417#0: free: 00007F80C3CFF000, unused: 0
2016/07/29 10:44:12 [debug] 32417#0: free: 00007F80C3D04000, unused: 0
2016/07/29 10:44:12 [debug] 32419#0: free: 00007F80C3D1A000
2016/07/29 10:44:12 [debug] 32417#0: free: 00007F80C3D12000, unused: 6592
2016/07/29 10:44:12 [debug] 32419#0: free: 00007F80C3D19000
2016/07/29 10:44:12 [notice] 32417#0: exit
2016/07/29 10:44:12 [debug] 32419#0: free: 00007F80C3D18000
2016/07/29 10:44:12 [debug] 32419#0: free: 00007F80C3D17000
2016/07/29 10:44:12 [debug] 32419#0: free: 00007F80C3D16000
2016/07/29 10:44:12 [debug] 32419#0: free: 00007F80C3D0C000
2016/07/29 10:44:12 [debug] 32419#0: free: 00007F80C3CFE000
2016/07/29 10:44:12 [debug] 32419#0: free: 00007F80C3D0A000
2016/07/29 10:44:12 [debug] 32419#0: free: 00007F80C3D08000
2016/07/29 10:44:12 [debug] 32419#0: free: 00007F80C3D03000
2016/07/29 10:44:12 [debug] 32419#0: free: 00007F80C3CFD000
2016/07/29 10:44:12 [debug] 32419#0: free: 00007F80C3CF7000
2016/07/29 10:44:12 [debug] 32419#0: free: 00007F80C3CF5000
2016/07/29 10:44:12 [debug] 32419#0: free: 00007F80C3C9C000
2016/07/29 10:44:12 [debug] 32419#0: free: 00007F80C3CD5000, unused: 0
2016/07/29 10:44:12 [debug] 32419#0: free: 00007F80C3CF9000, unused: 0
2016/07/29 10:44:12 [debug] 32419#0: free: 00007F80C3CFF000, unused: 0
2016/07/29 10:44:12 [debug] 32419#0: free: 00007F80C3D04000, unused: 0
2016/07/29 10:44:12 [debug] 32419#0: free: 00007F80C3D12000, unused: 6592
2016/07/29 10:44:12 [notice] 32419#0: exit
2016/07/29 10:44:12 [notice] 32416#0: signal 17 (SIGCHLD) received
2016/07/29 10:44:12 [notice] 32416#0: worker process 32417 exited with code 0
2016/07/29 10:44:12 [debug] 32416#0: shmtx forced unlock
2016/07/29 10:44:12 [debug] 32416#0: shmtx forced unlock
2016/07/29 10:44:12 [debug] 32416#0: wake up, sigio 4
2016/07/29 10:44:12 [debug] 32416#0: reap children
2016/07/29 10:44:12 [debug] 32416#0: child: 0 32417 e:1 t:1 d:0 r:1 j:0
2016/07/29 10:44:12 [debug] 32416#0: pass close channel s:0 pid:32417 to:32419
2016/07/29 10:44:12 [debug] 32416#0: child: 1 32419 e:1 t:0 d:0 r:1 j:0
2016/07/29 10:44:12 [debug] 32416#0: termination cycle: 50
2016/07/29 10:44:12 [debug] 32416#0: sigsuspend
2016/07/29 10:44:12 [notice] 32416#0: signal 17 (SIGCHLD) received
2016/07/29 10:44:12 [notice] 32416#0: worker process 32419 exited with code 0
2016/07/29 10:44:12 [debug] 32416#0: shmtx forced unlock
2016/07/29 10:44:12 [debug] 32416#0: shmtx forced unlock
2016/07/29 10:44:12 [debug] 32416#0: wake up, sigio 3
2016/07/29 10:44:12 [debug] 32416#0: reap children
2016/07/29 10:44:12 [debug] 32416#0: child: 0 -1 e:1 t:1 d:0 r:1 j:0
2016/07/29 10:44:12 [debug] 32416#0: child: 1 32419 e:1 t:1 d:0 r:1 j:0
2016/07/29 10:44:12 [notice] 32416#0: exit
2016/07/29 10:44:12 [debug] 32416#0: close listening 172.16.2.71:80 #-1 
2016/07/29 10:44:12 [emerg] 32416#0: close() socket 172.16.2.71:80 failed (9: Bad file descriptor)
2016/07/29 10:44:12 [debug] 32416#0: run cleanup: 00007F80C3D13C08
2016/07/29 10:44:12 [debug] 32416#0: run cleanup: 00007F80C3D06D80
2016/07/29 10:44:12 [debug] 32416#0: cleanup resolver
2016/07/29 10:44:12 [debug] 32416#0: run cleanup: 00007F80C3CD6128
2016/07/29 10:44:12 [debug] 32416#0: free: 00007F80C3D1B000
2016/07/29 10:44:12 [debug] 32416#0: free: 00007F80C3D1A000
2016/07/29 10:44:12 [debug] 32416#0: free: 00007F80C3D19000
2016/07/29 10:44:12 [debug] 32416#0: free: 00007F80C3D18000
2016/07/29 10:44:12 [debug] 32416#0: free: 00007F80C3D17000
2016/07/29 10:44:12 [debug] 32416#0: free: 00007F80C3D16000
2016/07/29 10:44:12 [debug] 32416#0: free: 00007F80C3D0C000
2016/07/29 10:44:12 [debug] 32416#0: free: 00007F80C3CFE000
2016/07/29 10:44:12 [debug] 32416#0: free: 00007F80C3D0A000
2016/07/29 10:44:12 [debug] 32416#0: free: 00007F80C3D08000
2016/07/29 10:44:12 [debug] 32416#0: free: 00007F80C3D03000
2016/07/29 10:44:12 [debug] 32416#0: free: 00007F80C3CFD000
2016/07/29 10:44:12 [debug] 32416#0: free: 00007F80C3CF7000
2016/07/29 10:44:12 [debug] 32416#0: free: 00007F80C3CF5000
2016/07/29 10:44:12 [debug] 32416#0: free: 00007F80C3C9C000
2016/07/29 10:44:12 [debug] 32416#0: free: 00007F80C3CD5000, unused: 0
2016/07/29 10:44:12 [debug] 32416#0: free: 00007F80C3CF9000, unused: 0
2016/07/29 10:44:12 [debug] 32416#0: free: 00007F80C3CFF000, unused: 0
2016/07/29 10:44:12 [debug] 32416#0: free: 00007F80C3D04000, unused: 0
2016/07/29 10:44:12 [debug] 32416#0: free: 00007F80C3D12000, unused: 6606

系统环境centos 6.5 
gcc 4.4.7
编译参数
./configure --prefix=/opt/websuite/tengine \
--conf-path=/opt/config/tengine/nginx.conf \
--error-log-path=/opt/logs/tengine/error.log \
--http-log-path=/opt/logs/tengine/access.log \
--pid-path=/opt/run/tengine \
--user=websuite \
--group=websuite \
--dso-path=/opt/websuite/tengine/modules \
--without-select_module \
--without-poll_module \
--with-file-aio \
--with-http_spdy_module \
--with-http_v2_module \
--with-http_realip_module \
--with-http_gzip_static_module \
--with-http_auth_request_module \
--with-http_addition_module=shared \
--with-http_image_filter_module=shared \
--with-http_geoip_module=shared \
--with-http_concat_module=shared \
--with-http_random_index_module=shared \
--with-http_secure_link_module=shared \
--with-http_sysguard_module=shared \
--with-http_charset_filter_module=shared \
--with-http_userid_filter_module=shared \
--with-http_footer_filter_module=shared \
--with-http_trim_filter_module=shared \
--with-http_access_module=shared \
--with-http_autoindex_module=shared \
--with-http_map_module=shared \
--with-http_referer_module=shared \
--with-http_uwsgi_module=shared \
--with-http_scgi_module=shared \
--with-http_empty_gif_module=shared \
--with-http_limit_conn_module=shared \
--with-http_limit_req_module=shared \
--with-http_reqstat_module=shared \
--with-http_browser_module=shared \
--with-http_user_agent_module=shared \
--with-http_upstream_session_sticky_module=shared \
--with-http_upstream_ip_hash_module=shared \
--without-http_ssi_module \
--without-http_split_clients_module \
--without-http_memcached_module \
--without-http_upstream_least_conn_module \
--with-http_tfs_module=shared \
--with-libyajl-inc=/opt/websuite/tengine/include/yajl \
--with-libyajl-lib=/opt/websuite/tengine/lib \
--with-luajit-inc=/opt/websuite/tengine/include/luajit-2.1 \
--with-luajit-lib=/opt/websuite/tengine/lib \
--http-client-body-temp-path=/opt/websuite/tengine/temp/client \
--http-proxy-temp-path=/opt/websuite/tengine/temp/proxy \
--http-fastcgi-temp-path=/opt/websuite/tengine/temp/fastcgi \
--http-uwsgi-temp-path=/opt/websuite/tengine/temp/uwsgi \
--http-scgi-temp-path=/opt/websuite/tengine/temp/scgi \
--without-mail_pop3_module \
--without-mail_imap_module \
--without-mail_smtp_module \
--with-pcre=../pcre-8.36 \
--with-pcre-opt=-fPIC \
--with-pcre-jit \
--with-openssl=/root/source/tengine/src/openssl-1.0.2h \
--with-openssl-opt=-fPIC \
--with-jemalloc \
--with-cc-opt='-w -pipe -march=native -mtune=native -m128bit-long-double -m64 -fno-builtin-malloc ' \
--with-debug

**Comment by saga1015** [comment]
分别测试了2.1.1和2.1.2，使用最基本的./configure编译安装，在启用reuse_port的情况下，error.log里都会有close() socket 0.0.0.0:80 failed (9: Bad file descriptor)这样的信息

**Comment by wangfakang** [comment]
@saga1015   已经修复了这个问题，你可以使用[tengine master分支](https://github.com/alibaba/tengine)代码进行编译。

**Comment by chobits** [comment]
认为已经解决，如有需要可重新打开
