### ISSUE TITLE
Tengine master版本关于reuse_port的疑问

### ISSUE THREAD

**Issue by saga1015** [alibaba/tengine#770]
@cfsego @chobits ，二位大神，tengine master我编译测试下来，发现这样一个现象
如果worker_processes 设置为auto，则reuse_port开启的情况下，使用ss -lnt只能发现对应的端口只监听在一个nginx进程上。
如果worker_processes 设置为NUM，则reuse_port开启的情况下，使用ss -lnt发现对应的端口只监听NUM个nginx进程上

请问二位大神，这个是否正常。2.1.1 和2.1.2 worker_processes设置为auto的时候，ss -lnt可以看到有多个80监听在多个Nginx进程上

**Comment by wangfakang** [comment]
@saga1015  感谢你的反馈，我在本地复现了这个问题。我们会尽快修复这个bug。

**Comment by chobits** [comment]
has been fixed in https://github.com/alibaba/tengine/pull/926.
