### ISSUE TITLE
如何在 Gzip 时支持 Weak ETag

### ISSUE THREAD

**Issue by larryzhao** [alibaba/tengine#787]
实际测试中发现，由于 Tengine 基于 Nginx 1.6.2 ，在 gzip 打开的情况下，会自动去掉 upstream response 中的 Etag header，并没有像 Nginx 1.7.3 之后那样保留 Weak Etag 。

请问有办法像 Nginx 1.7.3 之后那样支持 Weak Etag 么？

**Comment by larryzhao** [comment]
啊，翻了一下源码找到了，有一个 `gzip_clear_etag` 的 directive。

非常抱歉打扰了。

**Comment by chobits** [comment]
documentation: https://github.com/alibaba/tengine/blob/master/docs/modules/ngx_http_core_module_cn.md#gzip_clear_etag

**Comment by hax** [comment]
但 gzip_clear_etag 的行为跟 nginx 并不一样啊，并没有转换为 weak tag 啊！

**Comment by hax** [comment]
请求 reopen 此 issue。

**Comment by hax** [comment]
哦，似乎2.2.0已经好了。。。但 2.2 什么时候变稳定版啊。
