### ISSUE TITLE
limit_req_whitelist 白名单不起作用

### ISSUE THREAD

**Issue by 362228416** [alibaba/tengine#794]
配置如下

```
server {
        listen       4433;
        server_name  localhost;
        limit_req_whitelist geo_var_name=white_ip geo_var_value=1;
        location / {
            root html;
            index index.html;
        }
    }
```
```
geo $white_ip {
    ranges;
    default 0;
    127.0.0.1-127.0.0.255 1;
}
```

nginx 重启了还是不生效，也不报错，远程用另外一台电脑访问 还是可以正常访问，我的版本是:Tengine version: Tengine/2.1.2 (nginx/1.6.2)

**Comment by 80uncle** [comment]
http {

#Web限制访问速率 15r/s
    limit_req_zone $binary_remote_addr zone=one:5m rate=15r/s;
    limit_req_zone $binary_remote_addr $uri zone=two:5m rate=15r/s;
    limit_req_zone $binary_remote_addr $request_uri zone=three:5m rate=15r/s;

#限制连接白名单
geo $white_ip {
        ranges;
        default 0;
        127.0.0.1-127.0.0.255 1;
        172.10.20.1-172.10.20.254 1; #后端服务器网段
        192.168.30.99-192.168.30.99 2; #压力测试 IP,用于不同server需求
    }
}

server  {

limit_req zone=one burst=30;
limit_req zone=two burst=30;
limit_req zone=three burst=30;

#生效白名单
limit_req_whitelist geo_var_name=white_ip geo_var_value=1;
#limit_req_whitelist geo_var_name=white_ip geo_var_value=2;
}

#..........我这样是能用的.... 仅供参考

**Comment by 80uncle** [comment]
http {

#Web限制访问速率 15r/s
limit_req_zone $binary_remote_addr zone=one:5m rate=15r/s;
limit_req_zone $binary_remote_addr $uri zone=two:5m rate=15r/s;
limit_req_zone $binary_remote_addr $request_uri zone=three:5m rate=15r/s;

#限制连接白名单
geo $white_ip {
ranges;
default 0;
127.0.0.1-127.0.0.255 1;
172.10.20.1-172.10.20.254 1; #后端服务器网段
192.168.30.99-192.168.30.99 2; #压力测试 IP,用于不同server需求
}
}

server {

limit_req zone=one burst=30;
limit_req zone=two burst=30;
limit_req zone=three burst=30;

#生效白名单
limit_req_whitelist geo_var_name=white_ip geo_var_value=1;
#limit_req_whitelist geo_var_name=white_ip geo_var_value=2;
}

#..........我这样是能用的.... 仅供参考
