### ISSUE TITLE
快一年没更新了..... 是没有必要还是已经停止开发了???????

### ISSUE THREAD

**Issue by station19** [alibaba/tengine#795]
快一年没更新了..... 是没有必要还是已经停止开发了???????

**Comment by yaoweibin** [comment]
在双11之后会有更新的，最近资源紧张。如果大家有兴趣来参与的话，可以一起维护。

**Comment by IYism** [comment]
@yaoweibin @chobits
 Alibaba member
chobits commented on 24 Aug • edited
我们内部tengine有个功能，可以设置shutting down worker最大持续时间。
比如这个时间设置为60s： 如果老worker超过1分钟没有退出就强制退出其，不过这个会导致老worker上遗留的请求全部被中断处理（连接被关闭）。
后续我们也会把这个功能开源出来：）
 :+1: 4  
@IYism

 亲，shutting down worker好久开源出来呀。

**Comment by sunsan05** [comment]
都11月22日啦。。兄弟们什么时候放源~

**Comment by chobits** [comment]
最新的master分支已经整合了force_exit功能，文档参考: #809

**Comment by djhuahao** [comment]
@chobits 非常感谢~

**Comment by chobits** [comment]
最新的2.2.0版本已经发布，先关闭此问题。

* 最新版本release page: https://github.com/alibaba/tengine/releases/tag/tengine-2.2.0
* 也可以通过官网索取: http://tengine.taobao.org/
