### ISSUE TITLE
无法通过nginx-tests的测试

### ISSUE THREAD

**Issue by wangbin579** [alibaba/tengine#80]
[root@bgp176-148 nginx-tests]# TEST_NGINX_BINARY=/home/wangbin/work/tengine/objs/nginx TEST_NGINX_LEAVE=1 prove nginx-tests/http_server_name.t     

nginx-tests/http_server_name....nginx: [emerg] pcre_compile() failed: support for \P, \p, and \X has not been compiled in "^(?P<name>www\p{N}+).example.com$" at "p{N}+).example.com$" in /tmp/nginx-test-lFnGTu9KdQ/nginx.conf:67
Can't start nginx at lib/Test/Nginx.pm line 177.
 Looks like your test exited with 2 before it could output anything.
nginx-tests/http_server_name....dubious  
        Test returned status 2 (wstat 512, 0x200)
DIED. FAILED tests 1-9
        Failed 9/9 tests, 0.00% okay

**Comment by hwyuan** [comment]
不好意思，最近开始接触nginx，刚刚也遇到了这个问题。所以请问最终的解决方法是什么呢？我们需要手动更改/auto/lib/pcre/make文件么。谢谢。 @wangbin579
