### ISSUE TITLE
tengine 2.1.2支持tcp和udp的负载均衡吗

### ISSUE THREAD

**Issue by tjliupeng** [alibaba/tengine#805]
现在的nginx编译的时候有with-stream的选项支持tcp和udp的负载均衡，想问一下tengine有类似的编译选项吗？

谢谢

**Comment by chobits** [comment]
可以参考改模块：https://github.com/yaoweibin/nginx_tcp_proxy_module

在stream模块没出先前，这个模块已经有6-7年之久了。（功能上stream和tcp模块非常相似）

**Comment by tjliupeng** [comment]
恩，确实如此。

**Comment by moqianjun** [comment]
请问2.2.2现在支持了吗

**Comment by kongxianghe1234** [comment]
stream module support udp proxy
tcp proxy is like haproxy
try to use nginx 1.9.x+,stream module is quite popular nowadays.
