### ISSUE TITLE
亲，双11过了好久了，双12前会更新吗？

### ISSUE THREAD

**Issue by WPG** [alibaba/tengine#807]
@yaoweibin  @chobits

**Comment by nbubingo** [comment]
预计12月份发布

**Comment by chobits** [comment]
最新的2.2.0版本已经发布，先关闭此问题。

* 最新版本release page: https://github.com/alibaba/tengine/releases/tag/tengine-2.2.0
* 也可以通过官网获取: http://tengine.taobao.org/
