### ISSUE TITLE
TODO: "duplicate listen options" error of reuse_port feature

### ISSUE THREAD

**Issue by chobits** [alibaba/tengine#821]
* `sbin/nginx -t` will report error with following configure:

```
events {
    reuse_port on;        # << add reuse_port listen option for every server {}
}

http {
    server { 
        listen 8080;
        server_name a.com;
    }
    server { 
        listen 8080;
        server_name b.com;
    }
}
```

* error:

```
$ sbin/nginx -t
nginx: [emerg] duplicate listen options for 0.0.0.0:8080 in /home/xiaochen.wxc/work/github/tengine-xiaochen/output/./x.conf:11
nginx: configuration file /home/xiaochen.wxc/work/github/tengine-xiaochen/output/./x.conf test failed
```

**Comment by mojie126** [comment]
The same problem, has been returned to the 2.1.2

**Comment by chobits** [comment]
I recommend you enable reuseport in [listen](http://nginx.org/en/docs/http/ngx_http_core_module.html#listen) directive. (for example, `listen 80 reuseport;`
We'll make `events { reuse_port on; }` deprecated next version.

**Comment by mojie126** [comment]
Can u speak Chinese?
意思是以后的版本不支持reuse_port on这样的配置了？必须在listen后加reuseport？

**Comment by AstroProfundis** [comment]
Same here.

And `listen xx reuseport;` seems can only use in one `server{}` block, similiar to `default_server`.

**Comment by chobits** [comment]
hi @mojie126 我们先看看，最近接到不少需求希望保留这个全局开关的功能。如果容易实现的话，还是先尽量保留

**Comment by mojie126** [comment]
感谢，希望可以保留这个全局开关...

**Comment by chobits** [comment]
hi all,
This issue has been fixed in https://github.com/alibaba/tengine/issues/840.
You can check it with latest tengine master.
