### ISSUE TITLE
2.2.0版本已经基于nginx1.8.1了，但不支持--with-threads选项，这个选项在nginx1.7.11就已经支持了

### ISSUE THREAD

**Issue by WPG** [alibaba/tengine#823]
我们的系统主要是提供大文件下载的，nginx对文件下载可以优化
```
location /video/ {
    sendfile       on;
    aio            threads;
}
```
使用aio threads，需要添加--with-threads配置
`# ./configure --without-dso --without-http_autoindex_module --without-http_fastcgi_module --without-http_uwsgi_module --without-http_scgi_module --without-http_userid_module --without-http_footer_filter_module --without-http_upstream_dynamic_module --with-file-aio --with-http_sub_module --add-module=../echo-nginx-module-0.60/ --with-threads`
执行后提示
`./configure: error: invalid option "--with-threads"`

linux内核版本为2.6.32-279.el6.x86_64

**Comment by chobits** [comment]
目前proc模块和`--with-threads`功能还需要整合，所以暂时没有开放这个option

**Comment by chobits** [comment]
hi, `--with-threads` option已经在master最新分支中打开，可以使用了

**Comment by WPG** [comment]
感谢 @chobits , 好快啊

**Comment by chobits** [comment]
你先试用下，如果有问题可以反馈。这个功能只同步到官方1.8.1版本，如果后续还有更新，会继续merge到tengine master

**Comment by WPG** [comment]
压测暂时没发现问题，后续有问题再反馈，谢谢。
