### ISSUE TITLE
error: no member named 'aio_preload' in 'struct ngx_output_chain_ctx_s'

### ISSUE THREAD

**Issue by idreamsoft** [alibaba/tengine#837]
gmake -f objs/Makefile
gmake[1]: Entering directory '/usr/xxx/tengine-2.2.0'
cc -c -pipe  -O -Wall -Wextra -Wpointer-arith -Wno-unused-parameter -Werror -g  -fno-builtin-malloc -fno-builtin-calloc -fno-builtin-realloc -fno-builtin-free -I src/core -I src/event -I src/event/modules -I src/os/unix -I src/proc -I /usr/xxx/pcre-8.39 -I objs \
        -o objs/src/core/ngx_output_chain.o \
        src/core/ngx_output_chain.c
src/core/ngx_output_chain.c:267:14: error: no member named 'aio_preload' in 'struct ngx_output_chain_ctx_s'
    if (ctx->aio_preload && buf->in_file) {
        ~~~  ^
src/core/ngx_output_chain.c:291:15: error: no member named 'aio' in 'struct ngx_file_s'
    if (file->aio == NULL && ngx_file_aio_init(file, ctx->pool) != NGX_OK) {
        ~~~~  ^
src/core/ngx_output_chain.c:291:30: error: implicit declaration of function 'ngx_file_aio_init' is invalid in C99
      [-Werror,-Wimplicit-function-declaration]
    if (file->aio == NULL && ngx_file_aio_init(file, ctx->pool) != NGX_OK) {
                             ^
src/core/ngx_output_chain.c:295:17: error: no member named 'aio' in 'struct ngx_file_s'
    aio = file->aio;
          ~~~~  ^
src/core/ngx_output_chain.c:297:8: error: incomplete definition of type 'struct ngx_event_aio_s'
    aio->data = ctx->filter_ctx;
    ~~~^
src/core/ngx_core.h:25:16: note: forward declaration of 'struct ngx_event_aio_s'
typedef struct ngx_event_aio_s   ngx_event_aio_t;
               ^
src/core/ngx_output_chain.c:298:8: error: incomplete definition of type 'struct ngx_event_aio_s'
    aio->preload_handler = ctx->aio_preload;
    ~~~^
src/core/ngx_core.h:25:16: note: forward declaration of 'struct ngx_event_aio_s'
typedef struct ngx_event_aio_s   ngx_event_aio_t;
               ^
src/core/ngx_output_chain.c:298:33: error: no member named 'aio_preload' in 'struct ngx_output_chain_ctx_s'
    aio->preload_handler = ctx->aio_preload;
                           ~~~  ^
7 errors generated.
objs/Makefile:455: recipe for target 'objs/src/core/ngx_output_chain.o' failed
gmake[1]: *** [objs/src/core/ngx_output_chain.o] Error 1
gmake[1]: Leaving directory '/usr/xxx/tengine-2.2.0'
Makefile:8: recipe for target 'build' failed
gmake: *** [build] Error 2

系统:FreeBSD 10.1-RELEASE x64
Tengine-2.2.0

./configure --prefix=/usr/local/nginx --with-pcre=/usr/xxx/pcre-8.39 --with-perl=/usr/local --with-http_stub_status_module --with-http_concat_module --with-http_sysguard_module --with-http_gzip_static_module --add-module=/usr/xxx/ngx_cache_purge-2.3 --with-jemalloc --with-jemalloc=/usr/xxx/jemalloc-4.2.1 --with-http_sub_module --add-module=/usr/xxx/nginx-static-etags-master --with-http_concat_module


这是什么问题造成 怎么解决啊 
google上都找不到相关问题

**Comment by chobits** [comment]
>  ./configure --prefix=/usr/local/nginx --with-pcre=/usr/xxx/pcre-8.39 --with-perl=/usr/local --with-http_stub_status_module --with-http_concat_module --with-http_sysguard_module --with-http_gzip_static_module --add-module=/usr/xxx/ngx_cache_purge-2.3 --with-jemalloc --with-jemalloc=/usr/xxx/jemalloc-4.2.1 --with-http_sub_module --add-module=/usr/xxx/nginx-static-etags-master --with-http_concat_module

Can you post output of this command?

**Comment by idreamsoft** [comment]
@chobits 

checking for OS
 + FreeBSD 10.1-RELEASE amd64
checking for C compiler ... found
 + using Clang C compiler
 + clang version: 3.4.1 (tags/RELEASE_34/dot1-final 208032) 20140512
checking for gcc builtin atomic operations ... found
checking for C99 variadic macros ... found
checking for gcc variadic macros ... found
checking for compiler structure-packing pragma ... found
checking for unistd.h ... found
checking for inttypes.h ... found
checking for limits.h ... found
checking for sys/filio.h ... found
checking for sys/param.h ... found
checking for sys/mount.h ... found
checking for sys/statvfs.h ... found
checking for crypt.h ... not found
checking for FreeBSD specific features
 + sendfile() found
 + sendfile()'s SF_NODISKIO found
 + POSIX semaphores should work
 + kqueue found
 + kqueue's NOTE_LOWAT found
 + kqueue's EVFILT_TIMER found
 + cpuset_setaffinity() found
checking for nobody group ... found
checking for poll() ... found
checking for /dev/poll ... not found
checking for crypt() ... not found
checking for crypt() in libcrypt ... found
checking for F_READAHEAD ... found
checking for posix_fadvise() ... found
checking for O_DIRECT ... found
checking for F_NOCACHE ... not found
checking for directio() ... not found
checking for statfs() ... found
checking for statvfs() ... found
checking for dlopen() ... found
checking for sysinfo() ... not found
checking for getloadavg() ... found
checking for /proc/meminfo ... found but is not working
checking for sched_yield() ... found
checking for SO_SETFIB ... found
checking for SO_ACCEPTFILTER ... found
checking for TCP_DEFER_ACCEPT ... not found
checking for TCP_KEEPIDLE ... found
checking for TCP_FASTOPEN ... not found
checking for TCP_INFO ... found
checking for accept4() ... found
checking for eventfd() ... not found
checking for eventfd() (SYS_eventfd) ... not found
checking for int size ... 4 bytes
checking for long size ... 8 bytes
checking for long long size ... 8 bytes
checking for void * size ... 8 bytes
checking for uint64_t ... found
checking for sig_atomic_t ... found
checking for sig_atomic_t size ... 8 bytes
checking for socklen_t ... found
checking for in_addr_t ... found
checking for in_port_t ... found
checking for rlim_t ... found
checking for uintptr_t ... uintptr_t found
checking for system byte ordering ... little endian
checking for size_t size ... 8 bytes
checking for off_t size ... 8 bytes
checking for time_t size ... 8 bytes
checking for setproctitle() ... found
checking for pread() ... found
checking for pwrite() ... found
checking for sys_nerr ... found
checking for localtime_r() ... found
checking for posix_memalign() ... found
checking for memalign() ... not found
checking for mmap(MAP_ANON|MAP_SHARED) ... found
checking for mmap("/dev/zero", MAP_SHARED) ... found
checking for System V shared memory ... found
checking for POSIX semaphores ... found
checking for struct msghdr.msg_control ... found
checking for ioctl(FIONBIO) ... found
checking for struct tm.tm_gmtoff ... found
checking for struct dirent.d_namlen ... found
checking for struct dirent.d_type ... found
checking for sysconf(_SC_NPROCESSORS_ONLN) ... found
checking for openat(), fstatat() ... found
checking for getaddrinfo() ... found
configuring additional modules
adding module in /usr/src/ngx_cache_purge-2.3
 + ngx_http_cache_purge_module was configured
adding module in /usr/src/nginx-static-etags-master
 + ngx_http_static_etags_module was configured
checking for OpenSSL library ... found
checking for zlib library ... found
creating objs/Makefile

Configuration summary
  + using PCRE library: /usr/src/pcre-8.39
  + using system OpenSSL library
  + md5: using OpenSSL library
  + sha1: using OpenSSL library
  + using system zlib library
  + using system jemalloc library

  nginx path prefix: "/usr/local/nginx"
  nginx binary file: "/usr/local/nginx/sbin/nginx"
  nginx configuration prefix: "/usr/local/nginx/conf"
  nginx configuration file: "/usr/local/nginx/conf/nginx.conf"
  nginx pid file: "/usr/local/nginx/logs/nginx.pid"
  nginx error log file: "/usr/local/nginx/logs/error.log"
  nginx http access log file: "/usr/local/nginx/logs/access.log"
  nginx http client request body temporary files: "client_body_temp"
  nginx dso module path: "/usr/local/nginx/modules/"
  nginx http proxy temporary files: "proxy_temp"
  nginx http fastcgi temporary files: "fastcgi_temp"
  nginx http uwsgi temporary files: "uwsgi_temp"
  nginx http scgi temporary files: "scgi_temp"

**Comment by chobits** [comment]
hi, I pull one request to fix this problem: https://github.com/alibaba/tengine/pull/839.
You can check it with latest tengine master branch .

**Comment by chobits** [comment]
Consider it resolved. I am closing this issue.
 If you are still seeing this issue, feel free to reopen this.

**Comment by user454322** [comment]
I came across this problem in 11.2-RELEASE and tengine-2.2.0.

The linked PR solved the problem.
