### ISSUE TITLE
tengine2.1.2出现大量close_wait情况

### ISSUE THREAD

**Issue by keepersay** [alibaba/tengine#851]
上了http2模块发现有这样的情况，同时openssl从1.0.1升级到了1.0.2
Tengine version: Tengine/2.1.2 (nginx/1.6.2)
built by gcc 4.4.7 20120313 (Red Hat 4.4.7-4) (GCC) 
TLS SNI support enabled
configure arguments: --prefix=/usr/local/nginx --with-http_stub_status_module --with-pcre=/usr/local/src/pcre-8.38 --with-zlib=/usr/local/src/zlib-1.2.8 --with-syslog --with-http_lua_module --with-jemalloc=/usr/local/src/jemalloc-3.5.0 --with-http_v2_module --add-module=./modules/ngx_debug_pool
用的openssl-1.0.2h
出现的close_wait都在443上面
![image](https://cloud.githubusercontent.com/assets/7709274/21384060/aeb8f19e-c7a3-11e6-9566-767992668e98.png)

debug_pool
pid:7252
size:    50499584 num:     5786590 cnum:       12316 lnum:           0 ngx_http_v2_idle_handler
size:      282624 num:      354255 cnum:          69 lnum:           0 ngx_http_v2_init
size:  2417146703 num:    10665444 cnum:       13775 lnum:    23654399 ngx_http_create_request
size:           0 num:           1 cnum:           0 lnum:           0 main
size:           0 num:           4 cnum:           0 lnum:          24 ngx_http_server_names
size:    91050656 num:     4335583 cnum:       12601 lnum:    16742626 ngx_event_accept
size:     1143400 num:           4 cnum:           1 lnum:          41 ngx_init_cycle
size:         864 num:      119347 cnum:           6 lnum:           0 ngx_http_upstream_connect
size:      2441MB num:    21261228 cnum:       38768 lnum:    40397090 [SUMMARY]

**Comment by chobits** [comment]
尝试一下最新的master分支代码编译。
最近我们发现也有连接泄露，引入了1个官方patch修复了 `HTTP/2: flushing of the SSL buffer in transition to the idle state. by Valentin Bartenev`

这个patch我们在这里修复: https://github.com/alibaba/tengine/pull/832

**Comment by chobits** [comment]
This bug has been fixed in Tengine 2.3.0.

Tengine-2.3.0 has been released, it has been been upgraded to nginx 1.15.9.

For more details of new version, see https://github.com/alibaba/tengine/issues/1220.
