### ISSUE TITLE
why between nginx/nginx upstream use http/1.0?

### ISSUE THREAD

**Issue by djhuahao** [alibaba/tengine#852]
I have 3 server: A(nginx)-->B(nginx)-->C(nodejs),

When i access A or B,chrome use http/1.1+keepalive by default.

I do not set "proxy_http_version 1.1;" and proxy_set_header Connection "";

But between A and B,NGINX use http/1.0 by default。That is like:

**client** --> **nginxA(upstream to b)** --> **nginxB(upstream to c)** -->**C (nodejs)**

**http/1.1** --> **http/1.0** --> **http/1.1** --> **nodejs**

My questions is : why nginx use http/1.1 for upstream by default，between nginx and nginx, upstream use http/1.0 ?

THX.

**Comment by aholic** [comment]
`nginxB(upstream to c) -->C (nodejs)`
how do you know nginx use http/1.1 by default between them?

I don't have nodejs on my pc (hard to install). I use `nc` instead. See my test as follows:

1. start an nginx using conf:
```
    upstream ups_nc {
        server 127.0.0.1:38111;
    }
    server {
        listen 41872;
        location / {
            proxy_pass http://ups_data;
        }
    }
```

2. run `nc -l 38111` in an terminal1

3. run `curl 127.0.0.1:41872/` in another terminal2

terminal1 shows as follows:
```
➜ e100069208194.zmf /home/ruochen.xuruochen > nc -l 38111
GET /t HTTP/1.0
Host: ups_data
Connection: close
User-Agent: curl/7.29.0
Accept: */*

```

I guess, nginx always use http/1.0 upstream by default for more compatibility (just GUESS

It's late today......maybe I will go through the source code tomorrow.

**Comment by djhuahao** [comment]
Hi,aholic,Thank you for you reply.I thnk i find my result:http://serverfault.com/questions/442960/nginx-ignoring-clients-http-1-0-request-and-respond-by-http-1-1

**Comment by aholic** [comment]
The answer is cool !

Here are some snippets of the source code relative to it:

1. default http version to send
file: `src/http/modules/ngx_http_proxy_module.c`
function: `ngx_http_proxy_merge_loc_conf`
    ```
    ngx_conf_merge_uint_value(conf->http_version, prev->http_version,
                                                  NGX_HTTP_VERSION_10);
    ```

2. http version in response (no if condition, just send HTTP/1.1)
file: `src/http/ngx_http_header_filter_module.c`
function: `ngx_http_header_filter`
    ```
    /* "HTTP/1.x " */
    b->last = ngx_cpymem(b->last, "HTTP/1.1 ", sizeof("HTTP/1.x ") - 1);
    ```

**Comment by djhuahao** [comment]
@aholic many thanks~
