### ISSUE TITLE
支持http2之后 spdy 3.1是否还继续支持

### ISSUE THREAD

**Issue by megarzzy** [alibaba/tengine#858]
"NGINX 已经把 HTTP2 合并到 default 分支了，然后 SPDY 已经删除。Nginx 已经包含了HTTP/2 实现（RFC 7240，7241），因为 SPDY 不兼容新模块，Nginx 已经移除了对 SPDY 的支持。

详情请看这里：http://mailman.nginx.org/pipermail/nginx-devel/2015-September/007328.html  "

tengine是否能支持spdyV3 v3.1？

**Comment by aholic** [comment]
http://tengine.taobao.org/changelog_cn.html#2_2_0

```
Change: 合并HTTP/2模块，删除SPDY模块 [PeterDaveHello]
```

**Comment by chobits** [comment]
hi，后续tenigne新版本将不在支持spdy/3 spdy/3.1，鼓励和推荐使用h2协议，加速spdy的淘汰（这个也是未来其他 各大浏览器和平台的趋势）

另外，如有业务特殊需求扔需要使用spdy/3 spdy/3.1，只能使用老版本tengine的stable version （tengine-2.1.2)
