### ISSUE TITLE
关于X-Forwarded-For问题的请教。谢谢。

### ISSUE THREAD

**Issue by djhuahao** [alibaba/tengine#882]
我同时对比了最新版的tengine和nginx，配置了反向代理到另一台机器,参数如下：

proxy_set_header X-Real-IP $remote_addr;
proxy_set_header Host $host;
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
log_format server   '"$server_name" "$host" $http_x_forwarded_for' ;

但是，日志中$http_x_forwarded_for字段只显示为“-”，正常即使是未获取到客户端请求的header也应该显示$remote_addr的地址。我尝试将日志中的$http_x_forwarded_for字段替换为$proxy_add_x_forwarded_for就正常了。但在以前的版本中是没有问题的。

**Comment by chobits** [comment]
`$http_x_forwarded_for`没有单独处理过逻辑，这个变量的意思就是请求上的X-Forwarded-For头。
([`$http_`意义](http://nginx.org/en/docs/http/ngx_http_core_module.html#var_http_))

---

> 但在以前的版本中是没有问题的。

这个你可否复现出后，提供下之前版本号。

**Comment by djhuahao** [comment]
@chobits 尝试了多个版本都没有复现，怀疑是不是此前配置问题，该问题先closed。谢谢。
