### ISSUE TITLE
tengine reload dns queries

### ISSUE THREAD

**Issue by gcorrao** [alibaba/tengine#888]
Hi,
I'm using tengine to route and balance web traffic to some upstreams, and a few times per day we change and reload our tengine configuration. Because we have over 1500 upstreams, the reload operation performs a lot of DNS queries, taking sometimes 2 minutes to complete. Is there a way to change the reload to perform the DNS queries in parallel? I do not know if this is the best place for this, but the mailing list does not seem to be working.
Thanks in advance

**Comment by chobits** [comment]
hi @gcorrao 

Nginx/Tengine will perform dns lookup via `gethostbyname()`, which is blocking IO operation, for domain in `upstream {}`. On linux, it tries to query with dns server specified by `/etc/resolv.conf` or use static hostname table `/etc/hosts`.

You can use the following configuration to control nginx/tengine do dns lookup when handling http request. 

```
resolver 10.0.0.2 valid=10s;

server {
    location / {
        set $backend_servers backends.example.com;
        proxy_pass http://$backend_servers:8080;
    }
}
```

---
 Commercial NGINX Plus offers a better solution, see section `Using A Records with NGINX Plus` in [this page](https://www.nginx.com/blog/dns-service-discovery-nginx-plus/) and [its directive](http://nginx.org/en/docs/http/ngx_http_upstream_module.html?&_ga=1.136785456.1226688575.1492582772#resolve).

**Comment by Jeff885** [comment]
amazing! @chobits

**Comment by gcorrao** [comment]
Thanks for the reply! Using variables is a good workaround, but as far as I could test it can not be used in combination with keepalive connections to an upstream, which is a very important feature to have in my environment.
As for the problem I described, I'm already working in a DNS cache solution to speed up things :) . Since this is not a real issue, I'm closing it.
