### ISSUE TITLE
tengine是否可以安装verynginx？

### ISSUE THREAD

**Issue by ktvsos** [alibaba/tengine#890]
最近有个项目，上面的老大叫在tengine的基础上部署verynginx，安装了2个星期也装不上，有没部署好的前辈给指点迷津，或者是这个方案压根就没实现的可能，让我们趁早换方案

**Comment by itchenyi** [comment]
没问题的， 你应该提供更多的细节...

**Comment by ktvsos** [comment]
看着文档安装，编译tengine的时候，需要三个模块，包含上lua-nginx-module模块，提示该模块找不到，其余需要的两个模块，tengine默认安装有。
./configure: error: no lua-nginx-module/config was found
[root@localhost tengine-2.2.0]# make
make: *** No rule to make target `build', needed by `default'.  Stop.

**Comment by chobits** [comment]
hi @ktvsos 你用的lua-nginx-module是什么版本的？

**Comment by ktvsos** [comment]
试过lua-nginx-module-0.10.7.tar.gz和openresty-lua-nginx-module-v0.10.8-9-gca8ed0e.zip，两个都不行

**Comment by ktvsos** [comment]
是不是tengine的编译就编不过lua-nginx-module模块，阿里跟淘宝都是一个公司的，很奇怪

**Comment by itchenyi** [comment]
@ktvsos   要多实践，  要添加 lua-nginx-module 请去掉--with-http_lua_module 参数

**Comment by chobits** [comment]
试试 https://github.com/openresty/lua-nginx-module/releases/tag/v0.10.8 这个版本。我用这个版本编译没有出现编译报错

**Comment by ktvsos** [comment]
编译通过了，谢谢两位大神的指导

**Comment by chobits** [comment]
部分版本lua-nginx-module存在编译问题， 使用realse 版本的v0.10.8通过
