### ISSUE TITLE
Null pointer dereference?

### ISSUE THREAD

**Issue by zubinmeva** [alibaba/tengine#895]
I was curious if this was a real null pointer dereference issue, in ngx_readv_chain.c on line 82?

`iov` is assigned to `NULL` on line 57. If `chain` is not `NULL`, `limit` is `0`, and `prev == chain->buf->last` then `iov->iov_len` on line 82 would be a null pointer dereference.

CodeAi, an automated repair tool being developed at Qbit logic, suggested an if-guard as a fix.

```
diff --git a/src/os/unix/ngx_readv_chain.c b/src/os/unix/ngx_readv_chain.c
index 3544b4b..234a5cc 100644
--- a/src/os/unix/ngx_readv_chain.c
+++ b/src/os/unix/ngx_readv_chain.c
@@ -79,7 +79,9 @@ ngx_readv_chain(ngx_connection_t *c, ngx_chain_t *chain, off_t limit)
         }
 
         if (prev == chain->buf->last) {
-            iov->iov_len += n;
+            if(iov) {
+                iov->iov_len += n;
+            }
 
         } else {
             if (vec.nelts >= IOV_MAX) {
```

Could I submit this as a patch if it looks alright?

Thanks so much,

Zubin

**Comment by chobits** [comment]
On the first loop iteration, the condition `prev == chain->buf->last` must be false because of null pointer `prev`, then iov will be initialized. After this, `iov->iov_len` does not dereference NULL pointer.
