### ISSUE TITLE
dso_tool编译ngx_pagespeed-1.12.34.2-stable出现不兼容现象（可能模块太新或者tengine的dso_tool有bug）

### ISSUE THREAD

**Issue by xiao923077123** [alibaba/tengine#902]
`configuring additional modules
adding module in /root/ngx_pagespeed-1.12.34.2-stable
grep: src/core/nginx.h: No such file or directory
mod_pagespeed_dir=/root/ngx_pagespeed-1.12.34.2-stable/psol/include
build_from_source=false
checking for psol ...
 found
/etc/nginx/sbin/dso_tool: 271: [: =: unexpected operator
List of modules (in reverse order of applicability): 
checking for psol-compiler-compat ...
 found
/etc/nginx/sbin/dso_tool: 6: auto/have: cannot create objs/ngx_shared_config.h: Directory nonexistent
/root/ngx_pagespeed-1.12.34.2-stable
 + ngx_pagespeed will be compiled
cc -c -pipe  -O -W -Wall -Wpointer-arith -Wno-unused-parameter -Werror -g  -fPIC  -D_GLIBCXX_USE_CXX11_ABI=0 -I /root/ngx_pagespeed-1.12.34.2-stable/psol/include -I /root/ngx_pagespeed-1.12.34.2-stable/psol/include/third_party/chromium/src -I /root/ngx_pagespeed-1.12.34.2-stable/psol/include/third_party/google-sparsehash/src/src -I /root/ngx_pagespeed-1.12.34.2-stable/psol/include/third_party/google-sparsehash/gen/arch/linux/x64/include -I /root/ngx_pagespeed-1.12.34.2-stable/psol/include/third_party/grpc/src/include -I /root/ngx_pagespeed-1.12.34.2-stable/psol/include/third_party/protobuf/src/src -I /root/ngx_pagespeed-1.12.34.2-stable/psol/include/third_party/re2/src -I /root/ngx_pagespeed-1.12.34.2-stable/psol/include/out/Release/obj/gen -I /root/ngx_pagespeed-1.12.34.2-stable/psol/include/out/Release/obj/gen/protoc_out/instaweb -I /root/ngx_pagespeed-1.12.34.2-stable/psol/include/third_party/apr/src/include -I /root/ngx_pagespeed-1.12.34.2-stable/psol/include/third_party/aprutil/src/include -I /root/ngx_pagespeed-1.12.34.2-stable/psol/include/third_party/apr/gen/arch/linux/x64/include -I /root/ngx_pagespeed-1.12.34.2-stable/psol/include/third_party/aprutil/gen/arch/linux/x64/include -I /root/ngx_pagespeed-1.12.34.2-stable/psol/include/url  \
		-I/usr/include/libxml2 -Iobjs -I/etc/nginx/include \
		-o objs/src/src/log_message_handler.o \
		/root/ngx_pagespeed-1.12.34.2-stable/src/log_message_handler.cc
cc -c -pipe  -O -W -Wall -Wpointer-arith -Wno-unused-parameter -Werror -g  -fPIC  -D_GLIBCXX_USE_CXX11_ABI=0 -I /root/ngx_pagespeed-1.12.34.2-stable/psol/include -I /root/ngx_pagespeed-1.12.34.2-stable/psol/include/third_party/chromium/src -I /root/ngx_pagespeed-1.12.34.2-stable/psol/include/third_party/google-sparsehash/src/src -I /root/ngx_pagespeed-1.12.34.2-stable/psol/include/third_party/google-sparsehash/gen/arch/linux/x64/include -I /root/ngx_pagespeed-1.12.34.2-stable/psol/include/third_party/grpc/src/include -I /root/ngx_pagespeed-1.12.34.2-stable/psol/include/third_party/protobuf/src/src -I /root/ngx_pagespeed-1.12.34.2-stable/psol/include/third_party/re2/src -I /root/ngx_pagespeed-1.12.34.2-stable/psol/include/out/Release/obj/gen -I /root/ngx_pagespeed-1.12.34.2-stable/psol/include/out/Release/obj/gen/protoc_out/instaweb -I /root/ngx_pagespeed-1.12.34.2-stable/psol/include/third_party/apr/src/include -I /root/ngx_pagespeed-1.12.34.2-stable/psol/include/third_party/aprutil/src/include -I /root/ngx_pagespeed-1.12.34.2-stable/psol/include/third_party/apr/gen/arch/linux/x64/include -I /root/ngx_pagespeed-1.12.34.2-stable/psol/include/third_party/aprutil/gen/arch/linux/x64/include -I /root/ngx_pagespeed-1.12.34.2-stable/psol/include/url  \
		-I/usr/include/libxml2 -Iobjs -I/etc/nginx/include \
		-o objs/src/src/ngx_base_fetch.o \
		/root/ngx_pagespeed-1.12.34.2-stable/src/ngx_base_fetch.cc
In file included from /usr/include/c++/4.8/mutex:35:0,
                 from /root/ngx_pagespeed-1.12.34.2-stable/psol/include/third_party/re2/src/re2/re2.h:187,
                 from /root/ngx_pagespeed-1.12.34.2-stable/psol/include/pagespeed/kernel/util/re2.h:24,
                 from /root/ngx_pagespeed-1.12.34.2-stable/psol/include/pagespeed/kernel/http/user_agent_matcher.h:26,
                 from /root/ngx_pagespeed-1.12.34.2-stable/psol/include/net/instaweb/rewriter/public/rewrite_options.h:53,
                 from /root/ngx_pagespeed-1.12.34.2-stable/src/ngx_base_fetch.h:65,
                 from /root/ngx_pagespeed-1.12.34.2-stable/src/ngx_base_fetch.cc:23:
/usr/include/c++/4.8/bits/c++0x_warning.h:32:2: error: #error This file requires compiler and library support for the ISO C++ 2011 standard. This support is currently experimental, and must be enabled with the -std=c++11 or -std=gnu++11 compiler options.
 #error This file requires compiler and library support for the \
  ^
In file included from /root/ngx_pagespeed-1.12.34.2-stable/src/ngx_base_fetch.h:65:0,
                 from /root/ngx_pagespeed-1.12.34.2-stable/src/ngx_base_fetch.cc:23:
/root/ngx_pagespeed-1.12.34.2-stable/psol/include/net/instaweb/rewriter/public/rewrite_options.h:670:11: error: identifier ‘nullptr’ is a keyword in C++11 [-Werror=c++0x-compat]
           help_text_(nullptr),
           ^
In file included from /root/ngx_pagespeed-1.12.34.2-stable/psol/include/pagespeed/system/system_server_context.h:21:0,
                 from /root/ngx_pagespeed-1.12.34.2-stable/src/ngx_server_context.h:25,
                 from /root/ngx_pagespeed-1.12.34.2-stable/src/ngx_base_fetch.h:62,
                 from /root/ngx_pagespeed-1.12.34.2-stable/src/ngx_base_fetch.cc:23:
/root/ngx_pagespeed-1.12.34.2-stable/psol/include/net/instaweb/rewriter/public/server_context.h:561:36: error: ‘std::shared_ptr’ has not been declared
   void set_central_controller(std::shared_ptr<CentralController> controller) {
                                    ^
/root/ngx_pagespeed-1.12.34.2-stable/psol/include/net/instaweb/rewriter/public/server_context.h:561:46: error: expected ‘,’ or ‘...’ before ‘<’ token
   void set_central_controller(std::shared_ptr<CentralController> controller) {
                                              ^
/root/ngx_pagespeed-1.12.34.2-stable/psol/include/net/instaweb/rewriter/public/server_context.h:797:3: error: ‘shared_ptr’ in namespace ‘std’ does not name a type
   std::shared_ptr<CentralController> central_controller_;
   ^
/root/ngx_pagespeed-1.12.34.2-stable/psol/include/net/instaweb/rewriter/public/server_context.h: In member function ‘void net_instaweb::ServerContext::set_central_controller(int)’:
/root/ngx_pagespeed-1.12.34.2-stable/psol/include/net/instaweb/rewriter/public/server_context.h:562:5: error: ‘central_controller_’ was not declared in this scope
     central_controller_ = controller;
     ^
/root/ngx_pagespeed-1.12.34.2-stable/psol/include/net/instaweb/rewriter/public/server_context.h:562:27: error: ‘controller’ was not declared in this scope
     central_controller_ = controller;
                           ^
/root/ngx_pagespeed-1.12.34.2-stable/psol/include/net/instaweb/rewriter/public/server_context.h: In member function ‘net_instaweb::CentralController* net_instaweb::ServerContext::central_controller()’:
/root/ngx_pagespeed-1.12.34.2-stable/psol/include/net/instaweb/rewriter/public/server_context.h:566:12: error: ‘central_controller_’ was not declared in this scope
     return central_controller_.get();
            ^
In file included from /root/ngx_pagespeed-1.12.34.2-stable/psol/include/pagespeed/kernel/util/re2.h:24:0,
                 from /root/ngx_pagespeed-1.12.34.2-stable/psol/include/pagespeed/kernel/http/user_agent_matcher.h:26,
                 from /root/ngx_pagespeed-1.12.34.2-stable/psol/include/net/instaweb/rewriter/public/rewrite_options.h:53,
                 from /root/ngx_pagespeed-1.12.34.2-stable/src/ngx_base_fetch.h:65,
                 from /root/ngx_pagespeed-1.12.34.2-stable/src/ngx_base_fetch.cc:23:
/root/ngx_pagespeed-1.12.34.2-stable/psol/include/third_party/re2/src/re2/re2.h: At global scope:
/root/ngx_pagespeed-1.12.34.2-stable/psol/include/third_party/re2/src/re2/re2.h:351:46: error: variadic templates only available with -std=c++11 or -std=gnu++11 [-Werror]
   template <typename F, typename SP, typename... A>
                                              ^
/root/ngx_pagespeed-1.12.34.2-stable/psol/include/third_party/re2/src/re2/re2.h:352:67: error: variadic templates only available with -std=c++11 or -std=gnu++11 [-Werror]
   static inline bool Apply(F f, SP sp, const RE2& re, const A&... a) {
                                                                   ^
/root/ngx_pagespeed-1.12.34.2-stable/psol/include/third_party/re2/src/re2/re2.h:364:21: error: variadic templates only available with -std=c++11 or -std=gnu++11 [-Werror]
   template <typename... A>
                     ^
/root/ngx_pagespeed-1.12.34.2-stable/psol/include/third_party/re2/src/re2/re2.h:365:66: error: expected ‘,’ or ‘...’ before ‘&&’ token
   static bool FullMatch(const StringPiece& text, const RE2& re, A&&... a) {
                                                                  ^
/root/ngx_pagespeed-1.12.34.2-stable/psol/include/third_party/re2/src/re2/re2.h:365:73: error: parameter packs not expanded with ‘...’:
   static bool FullMatch(const StringPiece& text, const RE2& re, A&&... a) {
                                                                         ^
/root/ngx_pagespeed-1.12.34.2-stable/psol/include/third_party/re2/src/re2/re2.h:365:73: note:         ‘A’
/root/ngx_pagespeed-1.12.34.2-stable/psol/include/third_party/re2/src/re2/re2.h:369:21: error: variadic templates only available with -std=c++11 or -std=gnu++11 [-Werror]
   template <typename... A>
                     ^
/root/ngx_pagespeed-1.12.34.2-stable/psol/include/third_party/re2/src/re2/re2.h:370:69: error: expected ‘,’ or ‘...’ before ‘&&’ token
   static bool PartialMatch(const StringPiece& text, const RE2& re, A&&... a) {
                                                                     ^
/root/ngx_pagespeed-1.12.34.2-stable/psol/include/third_party/re2/src/re2/re2.h:370:76: error: parameter packs not expanded with ‘...’:
   static bool PartialMatch(const StringPiece& text, const RE2& re, A&&... a) {
                                                                            ^
/root/ngx_pagespeed-1.12.34.2-stable/psol/include/third_party/re2/src/re2/re2.h:370:76: note:         ‘A’
/root/ngx_pagespeed-1.12.34.2-stable/psol/include/third_party/re2/src/re2/re2.h:374:21: error: variadic templates only available with -std=c++11 or -std=gnu++11 [-Werror]
   template <typename... A>
                     ^
/root/ngx_pagespeed-1.12.34.2-stable/psol/include/third_party/re2/src/re2/re2.h:375:59: error: expected ‘,’ or ‘...’ before ‘&&’ token
   static bool Consume(StringPiece* input, const RE2& re, A&&... a) {
                                                           ^
/root/ngx_pagespeed-1.12.34.2-stable/psol/include/third_party/re2/src/re2/re2.h:375:66: error: parameter packs not expanded with ‘...’:
   static bool Consume(StringPiece* input, const RE2& re, A&&... a) {
                                                                  ^
/root/ngx_pagespeed-1.12.34.2-stable/psol/include/third_party/re2/src/re2/re2.h:375:66: note:         ‘A’
/root/ngx_pagespeed-1.12.34.2-stable/psol/include/third_party/re2/src/re2/re2.h:379:21: error: variadic templates only available with -std=c++11 or -std=gnu++11 [-Werror]
   template <typename... A>
                     ^
/root/ngx_pagespeed-1.12.34.2-stable/psol/include/third_party/re2/src/re2/re2.h:380:66: error: expected ‘,’ or ‘...’ before ‘&&’ token
   static bool FindAndConsume(StringPiece* input, const RE2& re, A&&... a) {
                                                                  ^
/root/ngx_pagespeed-1.12.34.2-stable/psol/include/third_party/re2/src/re2/re2.h:380:73: error: parameter packs not expanded with ‘...’:
   static bool FindAndConsume(StringPiece* input, const RE2& re, A&&... a) {
                                                                         ^
/root/ngx_pagespeed-1.12.34.2-stable/psol/include/third_party/re2/src/re2/re2.h:380:73: note:         ‘A’
/root/ngx_pagespeed-1.12.34.2-stable/psol/include/third_party/re2/src/re2/re2.h:747:11: error: ‘once_flag’ in namespace ‘std’ does not name a type
   mutable std::once_flag rprog_once_;
           ^
/root/ngx_pagespeed-1.12.34.2-stable/psol/include/third_party/re2/src/re2/re2.h:748:11: error: ‘once_flag’ in namespace ‘std’ does not name a type
   mutable std::once_flag num_captures_once_;
           ^
/root/ngx_pagespeed-1.12.34.2-stable/psol/include/third_party/re2/src/re2/re2.h:749:11: error: ‘once_flag’ in namespace ‘std’ does not name a type
   mutable std::once_flag named_groups_once_;
           ^
/root/ngx_pagespeed-1.12.34.2-stable/psol/include/third_party/re2/src/re2/re2.h:750:11: error: ‘once_flag’ in namespace ‘std’ does not name a type
   mutable std::once_flag group_names_once_;
           ^
/root/ngx_pagespeed-1.12.34.2-stable/psol/include/third_party/re2/src/re2/re2.h:752:21: error: defaulted and deleted functions only available with -std=c++11 or -std=gnu++11 [-Werror]
   RE2(const RE2&) = delete;
                     ^
/root/ngx_pagespeed-1.12.34.2-stable/psol/include/third_party/re2/src/re2/re2.h:753:32: error: defaulted and deleted functions only available with -std=c++11 or -std=gnu++11 [-Werror]
   RE2& operator=(const RE2&) = delete;
                                ^
/root/ngx_pagespeed-1.12.34.2-stable/psol/include/third_party/re2/src/re2/re2.h: In static member function ‘static bool re2::RE2::Apply(F, SP, const re2::RE2&, const A& ...)’:
/root/ngx_pagespeed-1.12.34.2-stable/psol/include/third_party/re2/src/re2/re2.h:354:28: error: variadic templates only available with -std=c++11 or -std=gnu++11 [-Werror]
     const int argc = sizeof...(a);
                            ^
/root/ngx_pagespeed-1.12.34.2-stable/psol/include/third_party/re2/src/re2/re2.h: In static member function ‘static bool re2::RE2::FullMatch(const re2::StringPiece&, const re2::RE2&, <type error>)’:
/root/ngx_pagespeed-1.12.34.2-stable/psol/include/third_party/re2/src/re2/re2.h:366:44: error: ‘forward’ is not a member of ‘std’
     return Apply(FullMatchN, text, re, Arg(std::forward<A>(a))...);
                                            ^
/root/ngx_pagespeed-1.12.34.2-stable/psol/include/third_party/re2/src/re2/re2.h:366:60: error: ‘a’ was not declared in this scope
     return Apply(FullMatchN, text, re, Arg(std::forward<A>(a))...);
                                                            ^
/root/ngx_pagespeed-1.12.34.2-stable/psol/include/third_party/re2/src/re2/re2.h:366:43: error: expected primary-expression before ‘(’ token
     return Apply(FullMatchN, text, re, Arg(std::forward<A>(a))...);
                                           ^
/root/ngx_pagespeed-1.12.34.2-stable/psol/include/third_party/re2/src/re2/re2.h:366:44: error: ‘forward’ is not a member of ‘std’
     return Apply(FullMatchN, text, re, Arg(std::forward<A>(a))...);
                                            ^
/root/ngx_pagespeed-1.12.34.2-stable/psol/include/third_party/re2/src/re2/re2.h:366:58: error: expected primary-expression before ‘>’ token
     return Apply(FullMatchN, text, re, Arg(std::forward<A>(a))...);
                                                          ^
/root/ngx_pagespeed-1.12.34.2-stable/psol/include/third_party/re2/src/re2/re2.h: In static member function ‘static bool re2::RE2::PartialMatch(const re2::StringPiece&, const re2::RE2&, <type error>)’:
/root/ngx_pagespeed-1.12.34.2-stable/psol/include/third_party/re2/src/re2/re2.h:371:47: error: ‘forward’ is not a member of ‘std’
     return Apply(PartialMatchN, text, re, Arg(std::forward<A>(a))...);
                                               ^
/root/ngx_pagespeed-1.12.34.2-stable/psol/include/third_party/re2/src/re2/re2.h:371:63: error: ‘a’ was not declared in this scope
     return Apply(PartialMatchN, text, re, Arg(std::forward<A>(a))...);
                                                               ^
/root/ngx_pagespeed-1.12.34.2-stable/psol/include/third_party/re2/src/re2/re2.h:371:46: error: expected primary-expression before ‘(’ token
     return Apply(PartialMatchN, text, re, Arg(std::forward<A>(a))...);
                                              ^
/root/ngx_pagespeed-1.12.34.2-stable/psol/include/third_party/re2/src/re2/re2.h:371:47: error: ‘forward’ is not a member of ‘std’
     return Apply(PartialMatchN, text, re, Arg(std::forward<A>(a))...);
                                               ^
/root/ngx_pagespeed-1.12.34.2-stable/psol/include/third_party/re2/src/re2/re2.h:371:61: error: expected primary-expression before ‘>’ token
     return Apply(PartialMatchN, text, re, Arg(std::forward<A>(a))...);
                                                             ^
/root/ngx_pagespeed-1.12.34.2-stable/psol/include/third_party/re2/src/re2/re2.h: In static member function ‘static bool re2::RE2::Consume(re2::StringPiece*, const re2::RE2&, <type error>)’:
/root/ngx_pagespeed-1.12.34.2-stable/psol/include/third_party/re2/src/re2/re2.h:376:43: error: ‘forward’ is not a member of ‘std’
     return Apply(ConsumeN, input, re, Arg(std::forward<A>(a))...);
                                           ^
/root/ngx_pagespeed-1.12.34.2-stable/psol/include/third_party/re2/src/re2/re2.h:376:59: error: ‘a’ was not declared in this scope
     return Apply(ConsumeN, input, re, Arg(std::forward<A>(a))...);
                                                           ^
/root/ngx_pagespeed-1.12.34.2-stable/psol/include/third_party/re2/src/re2/re2.h:376:42: error: expected primary-expression before ‘(’ token
     return Apply(ConsumeN, input, re, Arg(std::forward<A>(a))...);
                                          ^
/root/ngx_pagespeed-1.12.34.2-stable/psol/include/third_party/re2/src/re2/re2.h:376:43: error: ‘forward’ is not a member of ‘std’
     return Apply(ConsumeN, input, re, Arg(std::forward<A>(a))...);
                                           ^
/root/ngx_pagespeed-1.12.34.2-stable/psol/include/third_party/re2/src/re2/re2.h:376:57: error: expected primary-expression before ‘>’ token
     return Apply(ConsumeN, input, re, Arg(std::forward<A>(a))...);
                                                         ^
/root/ngx_pagespeed-1.12.34.2-stable/psol/include/third_party/re2/src/re2/re2.h: In static member function ‘static bool re2::RE2::FindAndConsume(re2::StringPiece*, const re2::RE2&, <type error>)’:
/root/ngx_pagespeed-1.12.34.2-stable/psol/include/third_party/re2/src/re2/re2.h:381:50: error: ‘forward’ is not a member of ‘std’
     return Apply(FindAndConsumeN, input, re, Arg(std::forward<A>(a))...);
                                                  ^
/root/ngx_pagespeed-1.12.34.2-stable/psol/include/third_party/re2/src/re2/re2.h:381:66: error: ‘a’ was not declared in this scope
     return Apply(FindAndConsumeN, input, re, Arg(std::forward<A>(a))...);
                                                                  ^
/root/ngx_pagespeed-1.12.34.2-stable/psol/include/third_party/re2/src/re2/re2.h:381:49: error: expected primary-expression before ‘(’ token
     return Apply(FindAndConsumeN, input, re, Arg(std::forward<A>(a))...);
                                                 ^
/root/ngx_pagespeed-1.12.34.2-stable/psol/include/third_party/re2/src/re2/re2.h:381:50: error: ‘forward’ is not a member of ‘std’
     return Apply(FindAndConsumeN, input, re, Arg(std::forward<A>(a))...);
                                                  ^
/root/ngx_pagespeed-1.12.34.2-stable/psol/include/third_party/re2/src/re2/re2.h:381:64: error: expected primary-expression before ‘>’ token
     return Apply(FindAndConsumeN, input, re, Arg(std::forward<A>(a))...);
                                                                ^
/root/ngx_pagespeed-1.12.34.2-stable/psol/include/third_party/re2/src/re2/re2.h: At global scope:
/root/ngx_pagespeed-1.12.34.2-stable/psol/include/third_party/re2/src/re2/re2.h:918:11: error: ‘once_flag’ in namespace ‘std’ does not name a type
   mutable std::once_flag once_;
           ^
/root/ngx_pagespeed-1.12.34.2-stable/psol/include/third_party/re2/src/re2/re2.h: In member function ‘re2::RE2* re2::LazyRE2::get() const’:
/root/ngx_pagespeed-1.12.34.2-stable/psol/include/third_party/re2/src/re2/re2.h:908:5: error: ‘call_once’ is not a member of ‘std’
     std::call_once(once_, [this]() { LazyRE2::Init(this); });
     ^
/root/ngx_pagespeed-1.12.34.2-stable/psol/include/third_party/re2/src/re2/re2.h:908:20: error: ‘once_’ was not declared in this scope
     std::call_once(once_, [this]() { LazyRE2::Init(this); });
                    ^
/root/ngx_pagespeed-1.12.34.2-stable/psol/include/third_party/re2/src/re2/re2.h:908:59: error: lambda expressions only available with -std=c++11 or -std=gnu++11 [-Werror]
     std::call_once(once_, [this]() { LazyRE2::Init(this); });
                                                           ^
In file included from /root/ngx_pagespeed-1.12.34.2-stable/src/ngx_base_fetch.h:65:0,
                 from /root/ngx_pagespeed-1.12.34.2-stable/src/ngx_base_fetch.cc:23:
/root/ngx_pagespeed-1.12.34.2-stable/psol/include/net/instaweb/rewriter/public/rewrite_options.h: At global scope:
/root/ngx_pagespeed-1.12.34.2-stable/psol/include/net/instaweb/rewriter/public/rewrite_options.h:3230:52: error: override controls (override/final) only available with -std=c++11 or -std=gnu++11 [-Werror]
     void InitializeOption(RewriteOptions* options) const override {
                                                    ^
/root/ngx_pagespeed-1.12.34.2-stable/psol/include/net/instaweb/rewriter/public/rewrite_options.h: In constructor ‘net_instaweb::RewriteOptions::PropertyBase::PropertyBase(const char*, base::StringPiece)’:
/root/ngx_pagespeed-1.12.34.2-stable/psol/include/net/instaweb/rewriter/public/rewrite_options.h:670:22: error: ‘nullptr’ was not declared in this scope
           help_text_(nullptr),
                      ^
In file included from /root/ngx_pagespeed-1.12.34.2-stable/src/ngx_base_fetch.cc:23:0:
/root/ngx_pagespeed-1.12.34.2-stable/src/ngx_base_fetch.h: At global scope:
/root/ngx_pagespeed-1.12.34.2-stable/src/ngx_base_fetch.h:134:58: error: override controls (override/final) only available with -std=c++11 or -std=gnu++11 [-Werror]
   bool IsCachedResultValid(const ResponseHeaders& headers) override;
                                                          ^
In file included from /root/ngx_pagespeed-1.12.34.2-stable/psol/include/net/instaweb/rewriter/public/resource_slot.h:33:0,
                 from /root/ngx_pagespeed-1.12.34.2-stable/psol/include/net/instaweb/rewriter/public/inline_attribute_slot.h:22,
                 from /root/ngx_pagespeed-1.12.34.2-stable/psol/include/net/instaweb/rewriter/public/rewrite_driver.h:35,
                 from /root/ngx_pagespeed-1.12.34.2-stable/src/ngx_base_fetch.cc:27:
/root/ngx_pagespeed-1.12.34.2-stable/psol/include/pagespeed/kernel/html/html_element.h: In member function ‘bool net_instaweb::HtmlElement::HasAttribute(net_instaweb::HtmlName::Keyword) const’:
/root/ngx_pagespeed-1.12.34.2-stable/psol/include/pagespeed/kernel/html/html_element.h:278:25: error: ‘nullptr’ was not declared in this scope
     return attribute != nullptr;
                         ^
In file included from /root/ngx_pagespeed-1.12.34.2-stable/psol/include/net/instaweb/rewriter/public/inline_attribute_slot.h:22:0,
                 from /root/ngx_pagespeed-1.12.34.2-stable/psol/include/net/instaweb/rewriter/public/rewrite_driver.h:35,
                 from /root/ngx_pagespeed-1.12.34.2-stable/src/ngx_base_fetch.cc:27:
/root/ngx_pagespeed-1.12.34.2-stable/psol/include/net/instaweb/rewriter/public/resource_slot.h: At global scope:
/root/ngx_pagespeed-1.12.34.2-stable/psol/include/net/instaweb/rewriter/public/resource_slot.h:206:3: error: ‘unique_ptr’ in namespace ‘std’ does not name a type
   std::unique_ptr<std::vector<InputInfo>> inputs_;
   ^
/root/ngx_pagespeed-1.12.34.2-stable/psol/include/net/instaweb/rewriter/public/resource_slot.h: In member function ‘const std::vector<net_instaweb::InputInfo>* net_instaweb::ResourceSlot::inputs() const’:
/root/ngx_pagespeed-1.12.34.2-stable/psol/include/net/instaweb/rewriter/public/resource_slot.h:147:57: error: ‘inputs_’ was not declared in this scope
   const std::vector<InputInfo>* inputs() const { return inputs_.get(); }
                                                         ^
In file included from /root/ngx_pagespeed-1.12.34.2-stable/psol/include/net/instaweb/rewriter/public/scan_filter.h:22:0,
                 from /root/ngx_pagespeed-1.12.34.2-stable/psol/include/net/instaweb/rewriter/public/rewrite_driver.h:44,
                 from /root/ngx_pagespeed-1.12.34.2-stable/src/ngx_base_fetch.cc:27:
/root/ngx_pagespeed-1.12.34.2-stable/psol/include/pagespeed/kernel/html/empty_html_filter.h: At global scope:
/root/ngx_pagespeed-1.12.34.2-stable/psol/include/pagespeed/kernel/html/empty_html_filter.h:60:32: error: override controls (override/final) only available with -std=c++11 or -std=gnu++11 [-Werror]
   ScriptUsage GetScriptUsage() const override { return kNeverInjectsScripts; }
                                ^
In file included from /root/ngx_pagespeed-1.12.34.2-stable/psol/include/net/instaweb/rewriter/public/rewrite_driver.h:46:0,
                 from /root/ngx_pagespeed-1.12.34.2-stable/src/ngx_base_fetch.cc:27:
/root/ngx_pagespeed-1.12.34.2-stable/psol/include/net/instaweb/rewriter/public/srcset_slot.h: In constructor ‘net_instaweb::SrcSetSlotCollection::ImageCandidate::ImageCandidate()’:
/root/ngx_pagespeed-1.12.34.2-stable/psol/include/net/instaweb/rewriter/public/srcset_slot.h:48:29: error: ‘nullptr’ was not declared in this scope
     ImageCandidate() : slot(nullptr) {}
                             ^
/root/ngx_pagespeed-1.12.34.2-stable/psol/include/net/instaweb/rewriter/public/srcset_slot.h: At global scope:
/root/ngx_pagespeed-1.12.34.2-stable/psol/include/net/instaweb/rewriter/public/srcset_slot.h:134:26: error: override controls (override/final) only available with -std=c++11 or -std=gnu++11 [-Werror]
   HtmlElement* element() const override { return parent_->element(); }
                          ^
/root/ngx_pagespeed-1.12.34.2-stable/psol/include/net/instaweb/rewriter/public/srcset_slot.h:135:15: error: override controls (override/final) only available with -std=c++11 or -std=gnu++11 [-Werror]
   void Render() override;
               ^
/root/ngx_pagespeed-1.12.34.2-stable/psol/include/net/instaweb/rewriter/public/srcset_slot.h:136:33: error: override controls (override/final) only available with -std=c++11 or -std=gnu++11 [-Werror]
   GoogleString LocationString() const override;
                                 ^
/root/ngx_pagespeed-1.12.34.2-stable/psol/include/net/instaweb/rewriter/public/srcset_slot.h:145:15: error: override controls (override/final) only available with -std=c++11 or -std=gnu++11 [-Werror]
   ~SrcSetSlot() override;
               ^
In file included from /root/ngx_pagespeed-1.12.34.2-stable/src/ngx_base_fetch.cc:27:0:
/root/ngx_pagespeed-1.12.34.2-stable/psol/include/net/instaweb/rewriter/public/rewrite_driver.h: In member function ‘bool net_instaweb::RewriteDriver::has_html_writer_filter() const’:
/root/ngx_pagespeed-1.12.34.2-stable/psol/include/net/instaweb/rewriter/public/rewrite_driver.h:1226:41: error: ‘nullptr’ was not declared in this scope
     return html_writer_filter_.get() != nullptr;
                                         ^
In file included from /root/ngx_pagespeed-1.12.34.2-stable/psol/include/net/instaweb/rewriter/public/rewrite_stats.h:24:0,
                 from /root/ngx_pagespeed-1.12.34.2-stable/src/ngx_base_fetch.cc:29:
/root/ngx_pagespeed-1.12.34.2-stable/psol/include/net/instaweb/rewriter/public/rewrite_driver_factory.h: At global scope:
/root/ngx_pagespeed-1.12.34.2-stable/psol/include/net/instaweb/rewriter/public/rewrite_driver_factory.h:407:11: error: ‘shared_ptr’ in namespace ‘std’ does not name a type
   virtual std::shared_ptr<CentralController> GetCentralController(
           ^
cc1plus: all warnings being treated as errors
make: *** [objs/src/src/ngx_base_fetch.o] Error 1
`

**Comment by hjweddie** [comment]
我尝试把 ngx_pagespeed-1.12编译进去Tengin 2.2.1会出现相同的问题，但是可以正常与Nginx 1.12版一起编译

ngx_pagespeed-1.12.34.2-stable 看起来是对应Nginx 1.12版的，而Tengine是Nginx 1.8.1的，不兼容可能是正常现象。 建议楼主尝试下 ngx_pagespeed 1.8的版本

**Comment by chobits** [comment]
最新版本2.3.0 已经使用官方的动态模块加载了。原有的dso feature被删除
