### ISSUE TITLE
ngx_http_reqstat_module 默认输出分隔符是 ”,“ 逗号，请问可以自定义成别的符号吗？

### ISSUE THREAD

**Issue by senzi1988** [alibaba/tengine#904]

**Comment by hongxiaolong** [comment]
```
static ngx_int_t
    ngx_http_reqstat_show_handler(ngx_http_request_t *r)
{
    ...

    b->last = ngx_slprintf(b->last, b->end, "%*s,",
                                   (size_t) node->len, node->data);

    ...
}
```

如上，有需要可以在"src/http/modules/ngx_http_reqstat_module.c"中自行调整

**Comment by senzi1988** [comment]
多谢

**Comment by senzi1988** [comment]
req_status_zone req_url "URL $uri $hostname $ups_addr " 64M;
req_status_zone_key_length req_url 1024;
req_status_zone_recycle req_url 10 60;
req_status_zone_add_indicator req_url $ups_addr;
req_status req_url;


......
set $ups_addr 123; --可以获取
set $ups_addr $upstream_addr; --获取不到
......

请问在 req_status_zon 里面我设置了自定义的变量 $ups_addr 但总是获取不到？
用 body_filter_by_lua 'ngx.var.ups_addr = ngx.var.upstream_addr'; 提取后也不行
是不是req_status_zon里面只能获取ngx全局的变量或常量，比如$uri $hostname 123等？
谢谢

**Comment by chobits** [comment]
可以在req_status_show输出上接一层body_filter_by_lua来过滤

或者重新开1个location+content_by_lua，由lua去抓去req_status输出内容，然后整体做内容过滤

**Comment by senzi1988** [comment]
谢谢
