### ISSUE TITLE
tengine2.2.0 unknown directive "expires_by_types"

### ISSUE THREAD

**Issue by geekcui** [alibaba/tengine#905]
相同编译参数，2.1.2没有这个问题；尝试过去掉所有非默认参数，仍然存在同样问题；./configure没有看到相关参数。
./configure --prefix=/usr/local/nginx \
  --with-http_perl_module \
  --with-http_stub_status_module \
  --with-http_ssl_module \
  --with-http_v2_module \
  --with-http_gzip_static_module \
  --with-http_realip_module \
  --http-client-body-temp-path=/usr/local/nginx/tmp/client \
  --http-proxy-temp-path=/usr/local/nginx/tmp/proxy \
  --http-fastcgi-temp-path=/usr/local/nginx/tmp/fastcgi \
  --without-http_uwsgi_module \
  --without-http_scgi_module \
  --with-jemalloc \
  --add-module=/var/data/resource/nginx/ngx-limit-req2-master \
  --add-module=/var/data/resource/nginx/ngx_cache_purge-2.3

**Comment by taoyuanyuan** [comment]
抱歉,这个指令在合并官方代码的时候被删掉了, 近期会加上.

**Comment by taoyuanyuan** [comment]
目前的版本支持变量, 针对content-type的功能, 可以这样使用.

```
map $sent_http_content_type $expires {
    default         off;
    application/pdf 42d;
    ~image/         max;
}

expires $expires;
```

**Comment by geekcui** [comment]
谢谢反馈和提供的解决方法.
辛苦了!

**Comment by chobits** [comment]
认为已经解决，如有需要可重新打开

**Comment by plainheart** [comment]
似乎现在最新版本 3.1.0 也无法识别 `expires_by_types` 指令，看了下代码似乎仍是因为合并代码导致的，是否需要恢复下？

**Comment by chobits** [comment]
> 似乎现在最新版本 3.1.0 也无法识别 `expires_by_types` 指令，看了下代码似乎仍是因为合并代码导致的，是否需要恢复下？

This directive has been deprecated, you could use this official method to implement it: https://github.com/alibaba/tengine/issues/905#issuecomment-325540921.

We added this directive just becase at that time, nginx did not support it.

**Comment by plainheart** [comment]
Thank you for the explanation. I saw this directive from the documentation where it is not marked as deprecated, so I left my question above. Again, thanks for your work!
