### ISSUE TITLE
location uri传递问题

### ISSUE THREAD

**Issue by wangyishuai007** [alibaba/tengine#915]
```
location /aaa {
     set $allow_ip '';
     if ( $remote_addr ~ 192.168.0.220){set $allow_ip 1;}
     if ( $allow_ip != 1) {
        return 503;
     }
     proxy_pass http://192.168.0.3:1080/path;
 }
```
当我的location配置如上时，我的0.3web服务器的访问日志是：
```
GET /path/aaa HTTP/1.0
```

而同样的配置文件，我在nginx-1.12.1上配置，0.3收到的访问是：
```
GET /path HTTP/1.0
```

**Comment by aholic** [comment]
这个预期就是这样的吧…

**Comment by aholic** [comment]
你是说 在tengine上用如上配置，192.168.0.3这台服务器收到的是下面的请求？

```
GET /path/aaa HTTP/1.0
```

**Comment by wangyishuai007** [comment]
对的， 同样的配置文件放在tengine 2.1.2和nginx-1.12.1上， 后端服务器192.168.0.3访问日志不一致。
tengine作为前端负载时，后端192.168.0.3日志为：GET /path/aaa HTTP/1.0，而实际应该是不追加才对吧。

**Comment by monkeyzhu123** [comment]
默认的nginx---->0.3  0.3上请求为 GET /path。 实际上如果你location都要proxy pass到/path,这也是你需要的话，直接用rewrite 或者return都可以，而且消除了歧义。

**Comment by wangyishuai007** [comment]
@monkeyzhu123 
```
location /aaa {
     set $allow_ip '';
     if ( $remote_addr ~ 192.168.0.220){set $allow_ip 1;}
     if ( $allow_ip != 1) {
        return 503;
     }
     proxy_pass http://192.168.0.3:1080/path;
 }
```  
```
location /aaa {
     proxy_pass http://192.168.0.3:1080/path;
 }
```  
不是怎么去实现proxy pass到/path路径，这么说吧，以上两个配置，按说是在同一个客户端IP访问情况下后端(192.168.0.3)接收是一致的请求(路径)，nginx是这样，而tengine不是。
我主要是想了解这里是个bug，还是说是tengine在location块里与nginx还是有一些区别的。

**Comment by taoyuanyuan** [comment]
哥可以升级 tengine-2.2.0试试, 已经修复这个bug, 这是nginx官方的一个bugfix.
https://github.com/nginx/nginx/commit/827b2511e6ffee946b7b5c00a67bc50449fc2d72

**Comment by taoyuanyuan** [comment]
https://www.nginx.com/resources/wiki/start/topics/depth/ifisevil/

if有很多坑, 也可以随便看看
