### ISSUE TITLE
Tengine future

### ISSUE THREAD

**Issue by Dead2** [alibaba/tengine#921]
I am wondering whether Alibaba is no longer actively maintaining tengine, with the current frequency of updates, it seems more like the maintainers do a little bit if they ever get some free time.

Tengine 2.2.0 release was 8.5 months ago, and there has been no minor release to fix the known and fixed in master bugs since then (reuseport for example).

When I changed from Nginx to Tengine, it was because Tengine was cutting-edge and had features not found in the free version of Nginx. Currently it seems more like Tengine is lagging behind Nginx badly, both in features and fixes. There are a couple of features I have suggested for Tengine, that people have implemented and created PRs for, but have been waiting for years now. This does not encourage the community to thrive.
I feel like I am doing the maintainers jobs every time I compile a new release for myself, looking through potential bugfixes and PRs to see whether there are important fixes to include, then doing the testing and validation to see whether this combination of patches even works like it should.

I and others, would very much like to continue using Tengine, but I feel forced to consider switching back to Nginx due to these issues.

So, Tengine maintainers, what is the outlook for the future, will things improve or are we in a continuing downwards spiral?

**Comment by ygl-rg** [comment]
well. you may consider [openresty](https://openresty.org/en/) right now.

**Comment by abitduck** [comment]
No tengine any more!

**Comment by IceHe** [comment]
Maybe no one (maintainers) will come… sigh

**Comment by Ballieas** [comment]
Just for kpi ...

**Comment by zhaopengme** [comment]
Keep away.

**Comment by crossPQW** [comment]
@Ballieas you got the truth~~

**Comment by ssuperdreamer** [comment]
far away from Alibaba

**Comment by tomzhang** [comment]
for anyone who still want to using tengine, maybe openresty is your best choice.

**Comment by qiqizjl** [comment]
yeah I also think that the transfer of the project was abandoned
So I'm going to use openresty

**Comment by wuyachao** [comment]
openresty is actively , https://github.com/openresty/lua-nginx-module

**Comment by yangjing1** [comment]
far away from Alibaba.  like those dubbo,druid,fastjson..

**Comment by orangle** [comment]
openresty is a good choice

**Comment by safeoy** [comment]
openresty is best

**Comment by taoyuanyuan** [comment]
sorry for our being late.

in alibaba, tengine is widely used as the base web service. The project is still alive as far as it is concerned.

Dev status is list below
* official release is published per quarter
* besides nginx official merge, specific features are developed, which can also work as common extension. such as  debugging module, dns cache, logback, sysguard-cpu, etc.
* highly active and quick responsed.

**Comment by warmchang** [comment]
@Dead2 , you can switch to openresty (https://github.com/openresty/openresty). @agentzh is the founder of this project and an expert in nginx/lua/openresty.

**Comment by Tinywan** [comment]
openresty

**Comment by fcharlie** [comment]
You can use Nginx now, Nginx has supported `Dynamic module` `HTTP2.0` and other features

**Comment by klzhong69** [comment]
阿里，汗颜吗

**Comment by yaoweibin** [comment]
Thank you for all the questiones and replies, Tengine is never a KPI project. I'm sorry that we have not updated the for such a long time.  The only reason is time limitation.

We use Tengine and optimize it all the time. Of course we can't abandon this project. Most of the new features are Alibaba's business related and we will not opensource it. But we do have new sexy features
 and want to make it public.

We have reorganized the Tengine opensource developer in Alibaba this week and going to put more resources in this project. And we also welcome any volunteer. Opensouce is not our KPI. We all do it for a share of knowledge.

If you have any feature request or question, any feedback is appreciated.

**Comment by anjia0532** [comment]
@Dead2 openresty+1, It has a rich ecosystem. website https://openresty.org/en/ project repo https://github.com/openresty/openresty

**Comment by ThinkCats** [comment]
Maybe you should fork from the official repo,  just like io.js or ayo.js . LOL ..

**Comment by Zhoulongqiang** [comment]
阿里程序狗哭晕在厕所。。。

**Comment by amoxoo** [comment]
阿里的开源项目基本是：开源就倒。

**Comment by DesignQu** [comment]
开源是需要大家共同维护，而不是饭来张口，衣来伸手。

**Comment by DesignQu** [comment]
I would like to ask you how much contribution have you made to this open source project? No one has the obligation to pay for your needs without pay.

**Comment by anjia0532** [comment]
This is not a critique,but a fear of the future. tenginer's work is great job,give us more choices. But it's a bit outdated now.

**Comment by klzhong69** [comment]
@DesignQu According to such kind of thought, open source is the boss which can be only praised, but no criticism.

**Comment by qwerttaa** [comment]
osc观光团

**Comment by DesignQu** [comment]
@klzhong69 Are you stupid? Did not see the official answer? People did not give up, has been updated, but no big version.

**Comment by klzhong69** [comment]
@DesignQu  Well, you got me sick. Bye bye

**Comment by lambdaq** [comment]
a little background here:

Alibaba group open sourced lots of stuff over the years, mainly because of one person 章文嵩(alias 正明).

Dr Zhang is of LVS fame and left Alibaba last year, so most of the projects staled. There's no top-down push for open sourcing and there are no inventive nor initiative for Alibaba group to open source their internal systems any more.

**Comment by railjty** [comment]
Alibaba is a Kitty

**Comment by TangHui123** [comment]
for KPI....the only reason

**Comment by khlipeng** [comment]
观光

**Comment by khlipeng** [comment]
这是阿里的第几个 kpi 项目？

**Comment by weizhenwei** [comment]
知乎观光团

**Comment by Muscliy** [comment]
far away from Alibaba

**Comment by fengqiangboy** [comment]
Good luck!

**Comment by Melody12ab** [comment]
open source is not easy ,soft and insist

**Comment by JunyiXie** [comment]
china open source... 💯

**Comment by a13821190779** [comment]
so, why despise Chinese?
just  talk about something,ok？
nobody forced you to see Chinese

**Comment by Equim-chan** [comment]
@a13821190779 This issue is not about racism. Don't get triggered.

**Comment by a13821190779** [comment]
@Equim-chan but, why do you send a contemptuous expression in Chinese comment below???
answer please

**Comment by Equim-chan** [comment]
@a13821190779 Because this comment is unhelpful to the subject. That's not even "contemptuous" at all.

**Comment by a13821190779** [comment]
@Equim-chan other irrelevant comments have not been despised

**Comment by Dead2** [comment]
Thank you @yaoweibin for your answer. I hope that the opensource contributions from Alibaba will continue at a more rapid pace from now on.

I am saddened by what @lambdaq is saying, and I hope others in Alibaba can pick up the torch and continue the open-source contributions.

And to everyone else that have suggested Openresty and similar, or bashing Alibaba, or even bashing me for asking. I opened this issue so we all could get some feedback from the developers, and let them have a chance to improve on the obviously worsening maintenance lately. Even for people that use some other fork than Tengine, the developments in Tengine have been a driving factor for some of the Nginx features and in the end it all helps the community as a whole.

Maintaining an open-source fork of popular software is a lot of work, and the expectations are high (I would know), but I hope Alibaba can see value in contributing something back to the community they already depend upon.

@yaoweibin This issue can be closed if you want.

**Comment by FrankFang** [comment]
Who wants weex?

**Comment by agentzh** [comment]
@Dead2 OpenResty is not a fork, it's a bundle per se. This is emphasized in its official web site. This means that there is never a problem sync'ing with the mainstream nginx core versions.

I think being a true fork is the biggest problem with Tengine's evolvement since it introduced incompatible features with the standard nginx core way before the nginx core designs them in a  different way. So it cannot really sync with the mainstream nginx code base without breaking its own backward compatibility. It has to go on by its own and never look back to most of the new development in the official nginx core. It cannot really use all the new goodies in the latest nginx mainstream versions. This also means Tengine has to create and maintain its own 3rd-party module ecosystem. This makes us decide not to support Tengine at all in our nginx modules even though Tengine bundles some of our modules like ngx_lua. I warned the original Tengine developers about the risks several years ago but unfortunately they still went down this path with such a dilemma.

Disclaimer: I'm the author and maintainer of OpenResty.

**Comment by Tinywan** [comment]
@agentzh Nice!

**Comment by itchenyi** [comment]
@agentzh  Nice!

**Comment by michealzh** [comment]
Maybe openresty is a better choice

**Comment by yaoweibin** [comment]
@Dead2 Thanks for your suggestion. It's a shame that this project has been stuck for these two years.  We are going to release a new version in September. It will contain these features:
- [ ] bugfix for 2.2.0
- [ ] new memory slab info diagnose tool
- [ ] new log slice features.
- [ ] dns cache

@agentzh We are going to use Macro to indicate the source code modification. It may take many months to refactor Tengine. I think a fork of Nginx is the key value for Tengine. Tengine has many useful features before Nginx, such as dynamic module, heath check, unbuffered uploading etc. Nginx is a commercial corporation. It has many private features in Nginx plus. Tengine can offer these useful free modules or features for users. 
 
 We are calling for volunteer, if anyone is interested in it, you can contact me: yaoweibin@gmail.com.

**Comment by chobits** [comment]
For new release, see [2.2.1 roadmap](https://github.com/alibaba/tengine/wiki/Roadmap#milestone-221).

**Comment by wbsdty331** [comment]
Igor Sysoev is very angry 😆

**Comment by Mircc** [comment]
@yaoweibin 请问下有支持TCP的打算么，nginx官方从1.9以后就支持TCP了，目前我们有一些业务，有用到需要TCP层的pr。比如类似客户端的ftp功能，目前是通过插件来实现的，但是希望能原生支持更简单

**Comment by yaoweibin** [comment]
有的。我们这个月会先发一个小版本，大版本估计要到双11之后了。

谢谢

**Comment by anguslee** [comment]
The 2.2.2 status on 2018/03/06

Milestone: 2.2.2

Due in 2017/12/30

Status: on-going development

**Comment by chobits** [comment]
hi @anguslee

We have realsed Tengine-2.2.2 on Jan 26.

For new feature & bugfix, see this [changelog](http://tengine.taobao.org/changelog.html#2_2_0).

For more details, see this [issue](https://github.com/alibaba/tengine/issues/1004).
