### ISSUE TITLE
这是国外的项目吗，怎么全是英文

### ISSUE THREAD

**Issue by itxiaohua** [alibaba/tengine#922]
这是国外的项目吗，怎么全是英文

**Comment by yaoweibin** [comment]
有中文，谢谢：https://github.com/alibaba/tengine/blob/master/CHANGES.cn

**Comment by yaoweibin** [comment]
![image](https://user-images.githubusercontent.com/153753/29773817-9bf5f9be-8c31-11e7-8852-d90b46bbedac.png)
