### ISSUE TITLE
tengine 2.1.2版本开启spdy咨询

### ISSUE THREAD

**Issue by leeweir** [alibaba/tengine#924]
在2.1.2上开了spdy进行测试，看到服务端是支持spdy的，但是一直测试不通。目前是如下配置的，是需要配置spdy_detect？我看在2.1.2上这个参数不支持
`        listen *:443 ssl spdy default_server;`

spdycat -nv https://xxx.com/domaninfo/onservice.html -3
[  0.009] NPN select next protocol: the remote server offers:
          * spdy/3.1
          * http/1.1
          NPN selected the protocol: spdy/3
[  0.017] Handshake complete
[  0.017] send SYN_STREAM frame <version=3, flags=1, length=247>
          (stream_id=1, assoc_stream_id=0, pri=3)
          :host: xxx.com
          :method: GET
          :path: /domaninfo/onservice.html
          :scheme: https
          :version: HTTP/1.1
          accept: */*
          accept-encoding: gzip, deflate
          user-agent: spdylay/1.1.0
Fatal: EOF
reqnum=1, completed=0
Some requests were not processed. total=1, processed=0

**Comment by leeweir** [comment]
已经解决

**Comment by chobits** [comment]
hi，原因是什么？

**Comment by leeweir** [comment]
spdylay使用上的问题，之前没注意，spdycat -nv https://xxx.com/domaninfo/onservice.html -3，发起的协议是spdy/3而不是spdy/3.1，使用spdy/3.1要使用--spdy3-1
![image](https://user-images.githubusercontent.com/4387357/29960731-72a0f068-8f2f-11e7-8645-89d265445323.png)
