### ISSUE TITLE
tengine 2.1.2 https 内存一直增长，有遇见过的么

### ISSUE THREAD

**Issue by china-mealtime** [alibaba/tengine#932]
我们tengine 2.1.2 稳定版本做websocket 负载。 两台服务器，分别使用http 和https ，配置文件除了端口，和证书 外，其他的都一致。其中https 内存每天都自增长，http的内存保持不变，请求量相同。

**Comment by chobits** [comment]
可以试下这个工具，看看内存占用分配在哪： http://tengine.taobao.org/document/ngx_debug_pool.html

**Comment by chobits** [comment]
另外可以看下 stub_status页面输出中writing这个值是否一直增大不退回（如果是，说明有请求一直没释放，或者流量一直上升）

**Comment by china-mealtime** [comment]
是有请求一直没释放，为什么http 的内存没增加，https的一直增加？

**Comment by chobits** [comment]
> 是有请求一直没释放，为什么http 的内存没增加，https的一直增加？

提供的信息太少没法分析。

另外fd泄露可以通过 `ss -tan|grep CLOSE-WAIT`查看

**Comment by china-mealtime** [comment]
pid:30296
size:     1212416 num:       22291 cnum:          75 lnum:       25510 ngx_http_create_request
size:     1322496 num:        9770 cnum:          86 lnum:       59921 ngx_event_accept
size:      719848 num:           2 cnum:           1 lnum:          15 ngx_init_cycle
size:     1244384 num:       22289 cnum:          74 lnum:       66865 ngx_http_upstream_connect
size:           0 num:           1 cnum:           0 lnum:           0 main
size:         4MB num:       54353 cnum:         236 lnum:      152311 [SUMMARY]

**Comment by china-mealtime** [comment]
ss -tan|grep CLOSE-WAIT
无任何信息

**Comment by chobits** [comment]
推测是HTTP/2导致的内存泄露：
* nginx-1.9.12: *) Bugfix: socket leak when using HTTP/2.

**Comment by chobits** [comment]
> pid:30296
> size: 1212416 num: 22291 cnum: 75 lnum: 25510 ngx_http_create_request
> size: 1322496 num: 9770 cnum: 86 lnum: 59921 ngx_event_accept
> size: 719848 num: 2 cnum: 1 lnum: 15 ngx_init_cycle
> size: 1244384 num: 22289 cnum: 74 lnum: 66865 ngx_http_upstream_connect
> size: 0 num: 1 cnum: 0 lnum: 0 main
> size: 4MB num: 54353 cnum: 236 lnum: 152311 [SUMMARY]

从这个看，nginx pool并没有泄露，总内存占用只有4MB

**Comment by china-mealtime** [comment]
好的，谢谢解答

**Comment by chobits** [comment]
这个问题已经定位在这个fix：http://hg.nginx.org/nginx/rev/4ba91a4c66a3

后续会把h2 fix移植过来

同时cc @taoyuanyuan @hongxiaolong 关注

**Comment by chobits** [comment]
注意这个patch是功能+修复都有的：http://hg.nginx.org/nginx/rev/4ba91a4c66a3

里面涉及到ev->write->{active|ready}的修正才是连接泄露的实际修复。

**Comment by chobits** [comment]
Note that some user has pulled a request to merge this official patch, see his pr https://github.com/alibaba/tengine/pull/779.

**Comment by martinko2009** [comment]
我用了tengine-2.2.3，http的服务器nginx所占的内存，还是不断在增大。

**Comment by chobits** [comment]
hi all 最新master已经更新到 nginx-1.15.2，涵盖h2/https连接泄露修复。

Hi all, current master is based on nginx 1.15.2, it has stream module. Please check it!
We'll release new version 2.3.x (based on nginx 1.15.x) soon.

# WARNING

Note that this version is slightly not backwards compatible, some tengine features have been replaced by nginx offical.  check the following list:
1. `--with-http_slice_module` configure option now works for [nginx slice module](http://nginx.org/en/docs/http/ngx_http_slice_module.html). Use `--add-module=modules/ngx_http_slice_module` for original [tengine slice module](http://tengine.taobao.org/document/http_slice.html).
2. Removed Tengine DSO feature, use [nginx dynamic modules feature](https://www.nginx.com/resources/wiki/extending/converting/) instead.
3. Removed `reuse_port` directive in `event {}` block, use [`listen .. reuseport;` directive](http://nginx.org/en/docs/http/ngx_http_core_module.html#listen) instead.
4. Extract the tengine modules to modules dir, if you need to use that module then use `--add-module=modules/xxx_module_name` way to compile.
5. The request counting logic for limit_req is consistent with the Nginx official. Now requests with all empty variable in `limit_req_zone` are not accounted. Original tengine does not account requests with any empty variable.


# 警告

注意当前版本不完全向后兼容，一些tengine的原有特性已经被官方nginx的替代。请检查如下列表：

1. `--with-http_slice_module` 编译参数现在适用于[nginx slice module](http://nginx.org/en/docs/http/ngx_http_slice_module.html). 如需tengine自有
的[tengine slice module]请使用`--add-module=modules/ngx_http_slice_module` 。
2. 删除Tengine DSO特性，使用[nginx dynamic modules feature](https://www.nginx.com/resources/wiki/extending/converting/) 作为替代。
3. 删除`event {}`块中`reuse_port`指令，使用 [`listen .. reuseport;` 指令](http://nginx.org/en/docs/http/ngx_http_core_module.html#listen) 作为>替代。
4. tengine模块已经迁入modules/目录，如需使用请用`--add-module=modules/xxx_module_name`编译参数开启。
5. limit_req模块模块的请求统计当前兼容nginx官方。如果当前请求的`limit_req_zone`中所有变量都为空时，请求计数才不会统计。原先版本的tengine中，请>求的`limit_req_zone`的`任意`变量为空时，请求计数才不会统计。
