### ISSUE TITLE
文档页面http://code.taobao.org/mailman/listinfo/tengine-cn无法访问

### ISSUE THREAD

**Issue by Long80A** [alibaba/tengine#940]
文档页面http://code.taobao.org/mailman/listinfo/tengine-cn无法访问
![image](https://user-images.githubusercontent.com/6187670/30314300-e4eca454-97d2-11e7-9c62-6257a0d32016.png)

**Comment by chobits** [comment]
后续不在code.taobao.org上服务了，文档参考: 

* [中文文档](http://tengine.taobao.org/documentation_cn.html)
* [英文文档](http://tengine.taobao.org/documentation.html)

**Comment by chobits** [comment]
问题关闭中，如有疑问可以再开启
