### ISSUE TITLE
Tengine-2.2.1 (development version) has been released!

### ISSUE THREAD

**Issue by taoyuanyuan** [alibaba/tengine#947]
Tengine-2.2.1(开发)版本发布了！
[download](http://tengine.taobao.org/download/tengine-2.2.1.tar.gz) [changelog](http://tengine.taobao.org/changelog_cn.html#2_2_1)

新增了如下新特性：
 - [ngx_slab_stat module](http://tengine.taobao.org/document_cn/ngx_slab_stat_cn.html) 查看共享内存的分配情况
 - [logback](http://tengine.taobao.org/document_cn/core_cn.html) 支持日志轮滚和自动删除功能
 - [DNS cache](http://tengine.taobao.org/document_cn/core_cn.html) 当DNS服务器不可用，使用上一次解析的ip
 - [sysguard_cpu](http://tengine.taobao.org/document_cn/http_sysguard_cn.html) 监控CPU利用率对系统进行保护等新特性

---

We are very excited to announce that Tengine-2.2.1 (development version) has
been released!
[download](http://tengine.taobao.org/download/tengine-2.2.1.tar.gz) [changelog](http://tengine.taobao.org/changelog.html#2_2_1)

Some features are as follows:
 - [ngx_slab_stat module](http://tengine.taobao.org/document/ngx_slab_stat.html) show shared memory statistics.
 - [logback](http://tengine.taobao.org/document/core.html) support roll back log file by time or file size.
 - [DNS cache](http://tengine.taobao.org/document/core.html) avoid tengine reload,start or stop etc failed when DNS server is unavailable.
 - [sysguard_cpu](http://tengine.taobao.org/document/http_sysguard.html) protect the system by monitoring the CPU usage.

**Comment by taoyuanyuan** [comment]
logback日志轮滚功能使用场景：
- 之前普遍的使用方式是用 cronolog 来做日志切割，且只能根据时间， 然后用crontab配置定时脚本来删除旧日志。 
- 新开发的logback功能， 集成并加强了这两个功能， 可以根据时间或者大小做切割， 可配置保存的个数， 超过了配置个数就删除。 比如硬盘配额只允许打10G日志，可以配置保存9个文件， 每个文件1G。

该特性减少了线上运维成本， 去除其他软件依赖。

**Comment by taoyuanyuan** [comment]
DNS cache功能使用场景：
```
nginx: [emerg] host not found in upstream "test.hello.com" in /usr/local/nginx/conf/nginx.conf:40
```
以上这个报错， 相信大部分同学都见过。

在DNS服务不可用的时候，将会导致执行reload、start等操作失败，从而无法生效一些紧急配置变更操作。

- 该特性可以在DNS服务器出现故障解析失败时，使用上一次解析的ip，正常启停服务。
- 有利有弊，需要用户自己评估：在DNS服务器出现问题时，是拒绝服务不启动， 还是使用上次解析的ip（可能域名解析已经换过，该ip已经失效）来提供服务。

**Comment by hongxiaolong** [comment]
ngx_slab_stat module 模块可以和 [ngx_debug_pool模块](http://tengine.taobao.org/document_cn/ngx_debug_pool_cn.html) 配合用来定位和管理内存相关问题：

该模块支持查看和定位NGINX官方指令分配的共享内存和lua-nginx-module分配的共享内存，可以详细地观察到free pages/slab的使用和分配情况：

  - 页级别：可以提供连续内存页统计，若碎片过多，不连续的内存页将明显过多，包含pages、start、end；
  - 块级别：可以提供slab的使用情况统计，一般从8Bytes-2048Bytes，包含total、used、reqs、fails；

**Comment by taoyuanyuan** [comment]
sysguard cpu使用场景：
之前sysguard有针对load的保护功能，但在实际使用中，有些场景load不高， 但是cpu利用率却不低，比如纯计算的场景。
- 增加cpu利用率的维度，对系统多一层保护。

**Comment by xinyingyin** [comment]
http://tengine.taobao.org/download/tengine-2.2.1.tar.gz  这个文件包，压缩格式有问题，使用-zxvf解压失败，-xvf才正常。

**Comment by taoyuanyuan** [comment]
谢谢，已经修复。

**Comment by qazzsq101** [comment]
官方的tcp/udp反向代理有计划合并进来吗？

**Comment by chobits** [comment]
I'm closing this issue.
