### ISSUE TITLE
make 2.2.1: src/os/unix/ngx_pipe.c:409:23: error: variable 'ccf' set but not used

### ISSUE THREAD

**Issue by sgub** [alibaba/tengine#948]
编译 2.2.1 版本出错（未用到的变量）

OS: CentOS 7.1    gcc version 4.8.5 20150623
$ ./configure
...
$ make
...
src/os/unix/ngx_pipe.c: In function 'ngx_open_pipe':
src/os/unix/ngx_pipe.c:409:23: error: variable 'ccf' set but not used [-Werror=unused-but-set-variable]
     ngx_core_conf_t  *ccf;
                       ^
cc1: all warnings being treated as errors
make[1]: *** [objs/src/os/unix/ngx_pipe.o] Error 1

**Comment by taoyuanyuan** [comment]
经测试高版本gcc有这个限制， 已经fix， 谢谢反馈！
可以用最新的mster分支。
