### ISSUE TITLE
Tengine 2.2.1 显示指令未识别unknown directive "fastcgi_upstream_tries"

### ISSUE THREAD

**Issue by alvin0chen** [alibaba/tengine#950]
版本为2.2.1
#/app/nginx/sbin/nginx -v
Tengine version: Tengine/2.2.1 (nginx/1.8.1)
关闭nginx 对后端fastcgi的重试时提示指令未识别
#/app/nginx/sbin/nginx -t 
nginx: [emerg] unknown directive "fastcgi_upstream_tries" in /app/nginx/conf/vhosts/weixin.api.xxxxx.com.conf:28
nginx: configuration file /app/nginx/conf/nginx.conf test failed
编译参数：
/app/nginx/sbin/nginx -V 
Tengine version: Tengine/2.2.1 (nginx/1.8.1)
built by gcc 4.4.7 20120313 (Red Hat 4.4.7-16) (GCC) 
TLS SNI support enabled
configure arguments: --prefix=/app/nginx --with-http_ssl_module --with-http_v2_module --with-openssl-opt=enable-tlsext --with-http_lua_module --with-luajit-inc=/app/luajit/include/luajit-2.1 --with-luajit-lib=/app/luajit/lib --with-libatomic --with-jemalloc --with-cc-opt='-O2 -Wno-error -O2 -g -pipe -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -march=native -mtune=native -D_GLIBCXX_USE_CXX11_ABI=0' --with-ld-opt=-Wl,-rpath,/app/luajit/lib --with-openssl=../openssl-1.0.2d --with-pcre=../pcre-8.36 --sbin-path=/app/nginx/sbin/nginx --conf-path=/app/nginx/conf/nginx.conf --http-log-path=/app/logs/nginx/access.log --error-log-path=/app/logs/nginx/error.log --pid-path=/var/run/nginx.pid --with-http_gzip_static_module --with-http_stub_status_module --with-http_secure_link_module --with-pcre-jit --with-file-aio --with-http_realip_module --with-http_addition_module --with-http_sub_module --with-http_gunzip_module --with-http_auth_request_module --with-http_random_index_module --with-http_degradation_module --http-client-body-temp-path=/app/temp/client_body_temp --http-proxy-temp-path=/app/temp/proxy_temp --http-fastcgi-temp-path=/app/temp/fastcgi_temp --http-uwsgi-temp-path=/app/temp/uwsgi_temp --http-scgi-temp-path=/app/temp/scgi_temp --with-http_limit_conn_module=shared --with-http_limit_req_module=shared

指令配置：
 location ~ \.php$ {
        include fastcgi.conf;
        fastcgi_intercept_errors on;
        fastcgi_upstream_tries 0;
        fastcgi_pass http://weixin.api;
    }

  upstream weixin.api {
        #ip_hash;
        server 127.0.0.1:9011;
        server 127.0.0.1:9010;
        check interval=60000 rise=1 fall=3 timeout=4000;
        keepalive 128;
    }

操作系统版本：
lsb_release -a 
LSB Version:    :base-4.0-amd64:base-4.0-noarch:core-4.0-amd64:core-4.0-noarch:graphics-4.0-amd64:graphics-4.0-noarch:printing-4.0-amd64:printing-4.0-noarch
Distributor ID: CentOS
Description:    CentOS release 6.7 (Final)
Release:        6.7
Codename:       Final

**Comment by wangfakang** [comment]
@alvin0chen  你可以使用这个指令配置`fastcgi_next_upstream_tries`替换`fastcgi_upstream_tries`.

**Comment by chobits** [comment]
hi @alvin0chen

你上一个使用的版本的tengine是什么版本的？

**Comment by alvin0chen** [comment]
上一个版本如下：
#/app/nginx/sbin/nginx -v 
Tengine version: Tengine/2.2.0 (nginx/1.8.0)
@chobits

**Comment by alvin0chen** [comment]
@wangfakang  fastcgi_next_upstream_tries 是nginx的指令，其实我主要是想关闭fastcgi的重试，但是好像
fastcgi_next_upstream off； 这个nginx指令根本不生效，然后查看Tengine文档http://tengine.taobao.org/document_cn/ngx_limit_upstream_tries_cn.html 发现有一个 fastcgi_upstream_tries  指令。但是无论我配置到http ,server 还是location 都会报unknown directive "fastcgi_upstream_tries"

**Comment by taoyuanyuan** [comment]
nginx官方后续开发了`fastcgi_next_upstream_tries`指令，我们就删掉了自身的实现， 你可以用这个指令来设置。
`fastcgi_next_upstream off`这个指令时可以生效的，你贴下配置， 我们看下。

**Comment by alvin0chen** [comment]
@taoyuanyuan
1、版本： 
/app/nginx/sbin/nginx -v 
Tengine version: Tengine/2.2.0 (nginx/1.8.0)
2、Tengine 配置
server 配置
server {
    listen       80;
    server_name weixin.api.xxxxxxx.com;
    access_log  /app/logs/nginx/weixin.api.xxxxxx.com.access.log  php0;
    fastcgi_next_upstream off;
 
    root /app/wwwroot/wap/api;
    index  index.html index.htm index.php;
    try_files $uri $uri/ @rewrite;
    location @rewrite {
        rewrite ^/(.*)$ /index.php?_url=/$1;
    }
    if (!-e $request_filename) {
        rewrite ^/zhws/(.*)$ /$1 last;
    }
    location ~ \.php$ {
        include fastcgi.conf;
        fastcgi_intercept_errors on;
        fastcgi_pass weixin.api;
    }
}

upstream配置：
    upstream weixin.api {
        #ip_hash;
        server 127.0.0.1:9011;
        server 127.0.0.1:9010;
        check interval=60000 rise=1 fall=3 timeout=4000 type=tcp;
        keepalive 32;
    }
日志格式：
log_format  php0  '$http_x_forwarded_for $remote_addr [$time_iso8601] $http_host "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '$request_time "$http_user_agent" '
                      '$upstream_addr $request_body $cookie_PHPSESSID $upstream_addr $upstream_response_time';


使用 fastcgi_next_upstream off; 关闭其中一台后的日志为：

10.8.2.93 192.168.1.27 [2017-09-29T11:38:00+08:00] weixin.api.xxxxx.com "POST /index.php?c=order&a=getUserYuyueSimple&cid=23 HTTP/1
.1" 200 44 "-" 0.090 "-" 127.0.0.1:9010, 127.0.0.1:9011 ------------------------------6d30eb380238\x0D\x0AContent-Disposition: form
-data; name=\x22f_id\x22\x0D\x0A\x0D\x0A3706690\x0D\x0A------------------------------6d30eb380238\x0D\x0AContent-Disposition: form-
data; name=\x22unit_id\x22\x0D\x0A\x0D\x0A21\x0D\x0A------------------------------6d30eb380238\x0D\x0AContent-Disposition: form-dat
a; name=\x22page\x22\x0D\x0A\x0D\x0A1\x0D\x0A------------------------------6d30eb380238\x0D\x0AContent-Disposition: form-data; name
=\x22page_size\x22\x0D\x0A\x0D\x0A50\x0D\x0A------------------------------6d30eb380238\x0D\x0AContent-Disposition: form-data; name=
\x22token\x22\x0D\x0A\x0D\x0A8222051b9cadd0ab4569423541f7640c\x0D\x0A------------------------------6d30eb380238\x0D\x0AContent-Disp
osition: form-data; name=\x22cid\x22\x0D\x0A\x0D\x0A23\x0D\x0A------------------------------6d30eb380238--\x0D\x0A - 127.0.0.1:9010, 127.0.0.1:9011 -, 0.067

**Comment by taoyuanyuan** [comment]
hi, 帮忙在日志里面打印下 `$upstream_status`, 然后error_log日志改成info，然后再试试看看日志。

**Comment by alvin0chen** [comment]
@taoyuanyuan 
您好，配置没有变，添加$upstrem_status后日志
log_format  php0  '$http_x_forwarded_for $remote_addr [$time_iso8601] $http_host "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '$request_time "$http_user_agent" '
                      '$upstream_addr $request_body $cookie_PHPSESSID $upstream_addr $upstream_status  $upstream_response_time';
打印的日志如下
access  log：
10.8.2.95 192.168.1.27 [2017-09-29T14:32:49+08:00] weixin.api.xxx.com "POST /index.php?c=wechat&a=getOrderNoticeInfo&cid=24 HTTP/
1.1" 200 2244 "-" 0.070 "-" 127.0.0.1:9011, 127.0.0.1:9010 ------------------------------29b51504c040\x0D\x0AContent-Disposition: f
orm-data; name=\x22order_id\x22\x0D\x0A\x0D\x0A175874818\x0D\x0A------------------------------29b51504c040\x0D\x0AContent-Dispositi
on: form-data; name=\x22type\x22\x0D\x0A\x0D\x0A\x0D\x0A------------------------------29b51504c040\x0D\x0AContent-Disposition: form
-data; name=\x22token\x22\x0D\x0A\x0D\x0A8222051b9cadd0ab4569423541f7640c\x0D\x0A------------------------------29b51504c040\x0D\x0A
Content-Disposition: form-data; name=\x22cid\x22\x0D\x0A\x0D\x0A24\x0D\x0A------------------------------29b51504c040--\x0D\x0A - 12
7.0.0.1:9011, 127.0.0.1:9010 -, 200  -, 0.051

error log：
2017/09/29 14:32:49 [error] 36934#0: *414 recv() failed (104: Connection reset by peer) while reading response header from upstream, client: 192.168.1.27, server: weixin.api.xxxx.com, request: "POST /index.php?c=wechat&a=getOrderNoticeInfo&cid=24 HTTP/1.1", upstream: "fastcgi://127.0.0.1:9011", host: "weixin.api.xxx.com"

**Comment by alvin0chen** [comment]
@taoyuanyuan 
我把upstream里面的节点调整为一个，在fastcgi_next_upstream off; 的情况下它还是会对同一个节点重试了一次。
upstream weixin.api {
        #ip_hash;
        server 127.0.0.1:9010;
        check interval=60000 rise=1 fall=3 timeout=4000;
        keepalive 32;
    }

访问日志：
10.8.4.42 192.168.1.27 [2017-09-29T14:53:26+08:00] weixin.api.xxxxx.com "POST /index.php?c=wechat&a=getIllDsec&cid=23 HTTP/1.1" 200
 67 "-" 0.078 "-" 127.0.0.1:9010, 127.0.0.1:9010 ------------------------------0e3200090cc1\x0D\x0AContent-Disposition: form-data; 
name=\x22type\x22\x0D\x0A\x0D\x0A0\x0D\x0A------------------------------0e3200090cc1\x0D\x0AContent-Disposition: form-data; name=\x
22f_id\x22\x0D\x0A\x0D\x0A1261860\x0D\x0A------------------------------0e3200090cc1\x0D\x0AContent-Disposition: form-data; name=\x2
2doctor_id\x22\x0D\x0A\x0D\x0A7797\x0D\x0A------------------------------0e3200090cc1\x0D\x0AContent-Disposition: form-data; name=\x
22order_id\x22\x0D\x0A\x0D\x0A177046839\x0D\x0A------------------------------0e3200090cc1\x0D\x0AContent-Disposition: form-data; na
me=\x22token\x22\x0D\x0A\x0D\x0A8222051b9cadd0ab4569423541f7640c\x0D\x0A------------------------------0e3200090cc1\x0D\x0AContent-D
isposition: form-data; name=\x22cid\x22\x0D\x0A\x0D\x0A23\x0D\x0A------------------------------0e3200090cc1--\x0D\x0A - 127.0.0.1:9
010, 127.0.0.1:9010 -, 200  -, 0.065

10.8.2.103 192.168.1.27 [2017-09-29T14:53:27+08:00] weixin.api.xxxxx.com "POST /index.php?c=wechat&a=getUnitConfig&cid=23 HTTP/1.1"
 200 660 "-" 0.043 "-" 127.0.0.1:9010, 127.0.0.1:9010 ------------------------------2e4bede580f2\x0D\x0AContent-Disposition: form-d
ata; name=\x22unit_id\x22\x0D\x0A\x0D\x0A356\x0D\x0A------------------------------2e4bede580f2\x0D\x0AContent-Disposition: form-dat
a; name=\x22cfg_type\x22\x0D\x0A\x0D\x0AFANGHAO_CFG\x0D\x0A------------------------------2e4bede580f2\x0D\x0AContent-Disposition: f
orm-data; name=\x22token\x22\x0D\x0A\x0D\x0A8222051b9cadd0ab4569423541f7640c\x0D\x0A------------------------------2e4bede580f2\x0D\
x0AContent-Disposition: form-data; name=\x22cid\x22\x0D\x0A\x0D\x0A23\x0D\x0A------------------------------2e4bede580f2--\x0D\x0A -
 127.0.0.1:9010, 127.0.0.1:9010 -, 200  -, 0.025

错误日志：
2017/09/29 14:53:26 [error] 55779#0: *36 recv() failed (104: Connection reset by peer) while reading response header from upstream, client: 192.168.1.27, server: weixin.api.xxxx.com, request: "POST /index.php?c=wechat&a=getIllDsec&cid=23 HTTP/1.1", upstream: "fastcgi://127.0.0.1:9010", host: "weixin.api.91160.com"

2017/09/29 14:53:27 [error] 55777#0: *226 recv() failed (104: Connection reset by peer) while reading response header from upstream, client: 192.168.1.27, server: weixin.api.xxxxx.com, request: "POST /index.php?c=wechat&a=getUnitConfig&cid=23 HTTP/1.1", upstream: "fastcgi://127.0.0.1:9010", host: "weixin.api.91160.com"

**Comment by taoyuanyuan** [comment]
我这儿不能复现， 麻烦在贴下 fastcgi.conf 的配置。

**Comment by taoyuanyuan** [comment]
你用最新版2.2.1也这样吗

**Comment by alvin0chen** [comment]
nginx 主配置：
user  nobody;
worker_processes  8;
events {
    worker_connections  10240;
}
http {
    #include /app/nginx/conf/limit/limit_zone.conf;
    server_tokens off;
    include       mime.types;
    default_type  application/octet-stream;
    log_format  main  '$http_x_forwarded_for $remote_addr [$time_local] $http_host "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '$request_time "$http_user_agent"';
    
    log_format debug  '$http_x_forwarded_for $remote_addr [$time_iso8601] $http_host "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '$request_time "$http_user_agent" '
                      '$upstream_addr - $request_body';
   log_format  php0  '$http_x_forwarded_for $remote_addr [$time_iso8601] $http_host "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '$request_time "$http_user_agent" '
                      '$upstream_addr $request_body $cookie_PHPSESSID $upstream_addr $upstream_status  $upstream_response_time';
    access_log  /app/logs/nginx/access.log  main;
    error_log   /app/logs/nginx/error.log ;
    #client_header_buffer_size 32k;
    #large_client_header_buffers 4 32k;
    client_max_body_size 80m;
    server_names_hash_bucket_size 640;
    sendfile        on;
    tcp_nopush     on;
    tcp_nodelay on;
    fastcgi_connect_timeout 300;
    fastcgi_send_timeout 300;
    fastcgi_read_timeout 300;
    fastcgi_buffer_size 128k;
    fastcgi_buffers 8 128k;
    fastcgi_busy_buffers_size 128k;
    fastcgi_temp_file_write_size 128k;
    keepalive_timeout  65;
    gzip on;
    gzip_min_length 1000;
    gzip_buffers 16 64k;
    gzip_http_version 1.0;
    gzip_comp_level 6;
    gzip_types text/plain application/x-javascript text/css application/xml;
    gzip_vary on;
    #优化性能参数，防止消耗资源类恶意攻击
    client_header_timeout 180;
    client_body_timeout 180;
    reset_timedout_connection on;
    send_timeout 10;
    #end
    #两层nginx,https协议转http问题
    map $http_x_forwarded_proto $forwarded_https { default off; https on; }
    fastcgi_keep_conn on;
     #nginx的各域名的状态检测(http_2xx,http_3xx,http_4xx)
    req_status_zone server "$host,$server_addr:$server_port" 10M;
    req_status server;
     upstream weixin.api {
        #ip_hash;
        server 127.0.0.1:9010;
        #server 127.0.0.1:9011;
        #server 127.0.0.1:9025;
        check interval=60000 rise=1 fall=3 timeout=4000;
        keepalive 32;
    }
    include /app/nginx/conf/vhosts/*.conf;
}
vhost配置
server {
    listen       80;
    server_name weixin.api.xxxx.com;
    #access_log  /app/logs/nginx/weixin.api.xxxx.com.access.log  main;
    access_log  /app/logs/nginx/weixin.api.xxxxx.com.access.log  php0;
    error_log   /app/logs/nginx/weixin.api.xxxxx.com.error.log info;
    fastcgi_next_upstream off;
    root /app/wwwroot/wap/api;
    index  index.html index.htm index.php;
    try_files $uri $uri/ @rewrite;
    location @rewrite {
        rewrite ^/(.*)$ /index.php?_url=/$1;
    }
    if (!-e $request_filename) {
        rewrite ^/zhws/(.*)$ /$1 last;
    }
    location ~ \.php$ {
        include fastcgi.conf;
        fastcgi_intercept_errors on;
        fastcgi_pass weixin.api;
    }
}

fastcgi.conf 配置：
fastcgi_param  SCRIPT_FILENAME    $document_root$fastcgi_script_name;
fastcgi_param  QUERY_STRING       $query_string;
fastcgi_param  REQUEST_METHOD     $request_method;
fastcgi_param  CONTENT_TYPE       $content_type;
fastcgi_param  CONTENT_LENGTH     $content_length;

fastcgi_param  SCRIPT_NAME        $fastcgi_script_name;
fastcgi_param  REQUEST_URI        $request_uri;
fastcgi_param  DOCUMENT_URI       $document_uri;
fastcgi_param  DOCUMENT_ROOT      $document_root;
fastcgi_param  SERVER_PROTOCOL    $server_protocol;
fastcgi_param  HTTPS              $https if_not_empty;

fastcgi_param  GATEWAY_INTERFACE  CGI/1.1;
fastcgi_param  SERVER_SOFTWARE    nginx/$nginx_version;

fastcgi_param  REMOTE_ADDR        $remote_addr;
fastcgi_param  REMOTE_PORT        $remote_port;
fastcgi_param  SERVER_ADDR        $server_addr;
fastcgi_param  SERVER_PORT        $server_port;
fastcgi_param  SERVER_NAME        $server_name;

# PHP only, required if PHP was built with --enable-force-cgi-redirect
fastcgi_param  REDIRECT_STATUS    200;

**Comment by taoyuanyuan** [comment]
`retry_cached_connection off；`  
你加一个这个试试

**Comment by alvin0chen** [comment]
@taoyuanyuan 你好，谢谢你的帮助，我对比测试了添加retry_cached_connection off；这个指令的结果，
目前来看，不添加会出现fastcgi的重试，添加后fastcgi的重试就没有。你能帮我解释一下这个指令吗，或者有文档我自己看；另外，如果我使用proxy模式代理其他服务，不使用fastcgi模式，这个指令是不是也要跟proxy_next_upstream off;一起使用才有效果呢？
没有重试的配置是这样的：
server {
    listen       80;
    server_name weixin.api.xxxx.com;
    access_log  /app/logs/nginx/weixin.api.xxxcom.access.log  php0;
    error_log   /app/logs/nginx/weixin.api.xxxx.com.error.log info;
    fastcgi_next_upstream off;
    retry_cached_connection off;
    root /app/wwwroot/wap/api;
    index  index.html index.htm index.php;
    try_files $uri $uri/ @rewrite;
    location @rewrite {
        rewrite ^/(.*)$ /index.php?_url=/$1;
    }
    if (!-e $request_filename) {
        rewrite ^/zhws/(.*)$ /$1 last;
    }
    location ~ \.php$ {
        include fastcgi.conf;
        fastcgi_intercept_errors on;
        fastcgi_pass weixin.api;
    }
}

**Comment by taoyuanyuan** [comment]
nginx官方代码对于upstream keepalive的部分失败请求， 会重试。
tengine-1.5.1添加了一个指令来关闭这个特性。
```
Tengine-1.5.1 [2013-08-29]

Feature: 增加retry_cached_connection指令，可以关闭对后端长连接的无条件重试 [yaoweibin]
```

你可以看这个commit
https://github.com/alibaba/tengine/pull/168

**Comment by alvin0chen** [comment]
好的，多谢。
