### ISSUE TITLE
Tengine 2.2.1 显示syslog参数错误

### ISSUE THREAD

**Issue by ruitingh** [alibaba/tengine#951]
原来tengine的版本是2.1.2；
日志配置在用：
    access_log  syslog:user:info:10.0.0.88:5114:1.test.com  main;
    error_log   syslog:user:err:10.0.0.88:5114:1.test.com_error info;
升级到2.2.1后，提示：
nginx: [emerg] unknown syslog parameter "user:info:10.0.0.88:5114:1.test.com" in /usr/local/nginx/conf/vhost/1.test.com.conf:14

请问是什么问题，怎么解决？谢谢！

**Comment by taoyuanyuan** [comment]
tengine-2.2.0合并了nginx-1.8.1的代码，nginx支持了syslog的功能， tengine就移除了自身的实现。
```
* Change:   支持nginx官方syslog，删除tengine原先支持的syslog功能
```
可以参考nginx的官方文档进行配置
http://nginx.org/en/docs/syslog.html

**Comment by ruitingh** [comment]
收到，非常感谢！
