### ISSUE TITLE
Tengine-2.2.1 No need for --with-syslog ? 

### ISSUE THREAD

**Issue by xinyingyin** [alibaba/tengine#956]
Tengine-2.2.1 ./configure: error: invalid option "--with-syslog"
Tengine-2.2.0 --with-syslog  is normal.

**Comment by taoyuanyuan** [comment]
*) Change:  official nginx syslog support, tengine syslog support is removed.

可以看changelog， nginx支持了syslog，tengine移除了自身的实现。
使用方式可以看官方文档： http://nginx.org/en/docs/syslog.html
