### ISSUE TITLE
504 Gateway Time-out

### ISSUE THREAD

**Issue by qiuhongli** [alibaba/tengine#966]
504 Gateway Time-out

The gateway did not receive a timely response from the upstream server or application.

Powered by Tengine

以上是报错后返回的。

从网站后台导出一个文件，大概1w多条记录 ，30s无相应就报错，导出5000多条，6000多条吗问题件，检查过nginx.conf php.ini都没有问题，请问是什么问题?

**Comment by taoyuanyuan** [comment]
你可以看下tengine的error日志

**Comment by qiuhongli** [comment]
这个日志在哪里可以查看

**Comment by taoyuanyuan** [comment]
error_log 配置的路径

**Comment by qiuhongli** [comment]
我安装的是nginx,没有安装tengine

**Comment by taoyuanyuan** [comment]
nginx和tengine指令一样的
为啥报错是  `Powered by Tengine` 。。。

**Comment by chobits** [comment]
* 这个报错一般是后端app返回太慢（超过你配置的nginx/tengine中读后端超时 proxy_read_timeout）然后报错。nginx/tengine报错可以看`$grep 'upstream timed out' logs/error.log`

* 一般这种报错应该首先查看后端是否异常

**Comment by chobits** [comment]
关闭中，认为已经修复，如有问题可以在打开。
