### ISSUE TITLE
ngx_http_dyups_module最多支持多少个upstream

### ISSUE THREAD

**Issue by BigbigY** [alibaba/tengine#973]
我的场景下upstream有100多个发现curl 出来的数量没超过50个，请问是需要挑什么配置吗，还是module本身的限制

**Comment by BigbigY** [comment]
error log中：
2017/11/16 10:53:15 [error] 11178#0: check time out with peer: 10.162.81.188:7001
2017/11/16 10:53:15 [info] 11178#0: [dyups] has 24 upstreams, 10 static, 0 deleted, all 34
--------
为什么有10个未加载到内存中

**Comment by leon0908** [comment]
老哥你试出来是什么坑了吗？我也遇到了
