### ISSUE TITLE
为什么2.2.0 及以上版本编译的时候加上 --with-http_spdy_module 都报错？？不支持了吗？

### ISSUE THREAD

**Issue by zhangxiangfeng** [alibaba/tengine#975]
```
./configure: error: invalid option "--with-http_spdy_module"
```

**Comment by chobits** [comment]
* 新版本spdy module已经被删除了，现在只能使用http2
* changelog for 2.2.0: http://tengine.taobao.org/changelog.html#2_2_0

> Change: merged HTTP/2 module, SPDY module is removed. (PeterDaveHello)

**Comment by zhangxiangfeng** [comment]
是类，后来自己也找到了。尴尬。。。。

**Comment by chobits** [comment]
关闭问题中，如有问题可再次打开
