### ISSUE TITLE
发现个问题 不知道是不是bug

### ISSUE THREAD

**Issue by zhangxiangfeng** [alibaba/tengine#980]
## 我通过 tengine-2.2.1 的 nginx_tcp_proxy_module 模块 做tcp转发.

> 但是...实际发现..断开的太快了. 大约不到1分钟就断开了ssh连接

不知道这是什么问题.

**Comment by yaoweibin** [comment]
是没有数据传输吗？扩大一下超时时间看看：https://github.com/yaoweibin/nginx_tcp_proxy_module/wiki/TIME_OUT

**Comment by zhangxiangfeng** [comment]
好使.

**Comment by chobits** [comment]
认为已经解决，关闭中，如果有需要可自行打开
