### ISSUE TITLE
权重不能设置为0

### ISSUE THREAD

**Issue by siyiys** [alibaba/tengine#982]
部署程序是需要设置权重切流量，但是权重不能设置为0
upstream cluster_80{
        server 127.0.0.1:8080 weight=0 ;  
权重设置为0时，会报：
invalid parameter "weight=0" in /usr/local/nginx/conf/nginx.conf:61
如何才能设置权重为0？

**Comment by chobits** [comment]
请求为你设置权重为0的目的是？如果是想取消ip被访问，可以使用bakup标记；


* [server directive](http://nginx.org/en/docs/http/ngx_http_upstream_module.html#server)
```
server backup1.example.com  backup;

backup
   marks the server as a backup server. It will be passed requests when the primary servers are unavailable.
```

**Comment by siyiys** [comment]
为了发布的时候，取消后端ip被访问，切走流量。后来我们也是使用了backup

**Comment by chobits** [comment]
认为已经解决，如有需要可自行reopen，关闭了。
