### ISSUE TITLE
开启ssl时server_tag无效

### ISSUE THREAD

**Issue by bluenochange** [alibaba/tengine#984]
如下配置
listen 443 ssl http2;
server_tag xxxx;
使用http协议，不使用ssl时server_tag功能正常

**Comment by taoyuanyuan** [comment]
麻烦贴一下全部配置

**Comment by chobits** [comment]
推荐使用官方指令：http://nginx.org/en/docs/http/ngx_http_core_module.html#server_tokens

最新tengine2.3.0已经支持。

Try it for https://github.com/alibaba/tengine/issues/1220.
