### ISSUE TITLE
ngx_stream_core_module

### ISSUE THREAD

**Issue by zhuozl** [alibaba/tengine#988]
什么时候才能merge nginx1.9的 stream 模块。

**Comment by TaChao** [comment]
+1

**Comment by frostsky** [comment]
+1

**Comment by yourchanges** [comment]
关注

**Comment by fishbar** [comment]
+1

**Comment by chobits** [comment]
1. 我们这个月会发tengine-2.2.2版本（bugfix+新feature+新module），这个将会是我们最后1个基于nginx-1.8 stable
2. 这个版本之后，我们会开始升级到1.9-1.10 这个大版本，届时会把nginx新功能整合进来（包括stream模块和openssl兼容和诸多fix）

---

1. We'll release tengine-2.2.2 this month, including bugfix, new features and new module. It will be final version tengine based on nginx-1.8 stable.
2. After this version, we'll try to merge nginx 1.9dev-1.10stable, which merges new feature of nginx, such as ngx-stream-module & some bugfix.

**Comment by fishbar** [comment]
@chobits  赞，升级到1.9版本有详细的时间计划了么？

**Comment by shuaizi** [comment]
mark

**Comment by roura356a** [comment]
Hi, any update to support `ngx_stream_core_module `?

**Comment by chobits** [comment]
Hi all, current master is based on nginx 1.15.2, it has stream module. Please check it!
