### ISSUE TITLE
sysguard 模块,部分设置不起作用?

### ISSUE THREAD

**Issue by zhangxiangfeng** [alibaba/tengine#995]
今天有空就研究了一下tengine 的sysguard 模块,发现了两个问题

-  1.sysguard_load 配置无效
-  2.sysguard_rt  配置无效

**配置如下图**

![](https://doc.openread.cn/uploads/201801/attach_150b77cdefe9dc89.png)

[官网关于sysguard 模块的介绍-http://tengine.taobao.org/document_cn/http_sysguard_cn.html](http://tengine.taobao.org/document_cn/http_sysguard_cn.html)

**配置后,sysguard_load 和 sysguard_rt未达到 期望的效果**

> sysguard_load load=5 action=/loadlimit;  期望 1分钟内超过5个access,就进行url转发
 
> sysguard_rt rt=0.001 period=2s action=/rtlimit; 期望 2s内,平均响应时间超过1毫秒,就进行url转发

**Comment by taoyuanyuan** [comment]
* ```sysguard_load``` 你的配置指的是系统load超过5，就做url转发， 可以查看 ```/proc/loadavg```这个文件查看当前load，通过 ```sysguard_interval```来控制间隔，默认一秒一次。不太清楚你说的5个access指的是什么？
 * ```sysguard_rt``` 麻烦发一下当时包含响应时间的access日志

**Comment by zhangxiangfeng** [comment]
![](https://doc.openread.cn/uploads/201801/attach_150c03bdbb85db89.png)

见上图,不过我已经感觉出来我明显理解错了, 有没有更加简介的介绍?

sysguard_rt 的日志

```
101.227.104.62 - tengine.stat.openread.cn - - - 22/Jan/2018:03:19:43 +0000 - GET /lua HTTP/1.1 - 200 - 28 - - 0.000
101.227.104.62 - tengine.stat.openread.cn - - - 22/Jan/2018:03:19:43 +0000 - GET /favicon.ico HTTP/1.1 - 302 - 235 - - 0.000
101.227.104.62 - tengine.stat.openread.cn - - - 22/Jan/2018:03:19:43 +0000 - GET /errors/404.html HTTP/1.1 - 200 - 2720 - - 0.000

```

**Comment by taoyuanyuan** [comment]
* load是一个系统负载衡量指标， 你可以看看这个连接 https://en.wikipedia.org/wiki/Load_(computing)
* 看你的日志，响应时间都很快 <1ms， 所以不会被拦截做跳转。

**Comment by zhangxiangfeng** [comment]
OK,;明白了

**Comment by taoyuanyuan** [comment]
http://nginx.org/en/docs/http/ngx_http_limit_req_module.html
请求限流你可以看这个模块
