### ISSUE TITLE
websocket转发多个server

### ISSUE THREAD

**Issue by yonghualuo** [alibaba/tengine#996]
配置了websocket转发，upstream模块配置了两个server，有一个on时，前端可以连接上，两个都是on时，就连不上了，请问是哪里没有配置好？session_sticky?

**Comment by taoyuanyuan** [comment]
麻烦贴一下配置和相关请求日志，错误日志。

**Comment by yonghualuo** [comment]
![image](https://user-images.githubusercontent.com/13300593/35260925-d35b23b2-0048-11e8-892c-f820f179eb96.png)

nginx配置如下
![image](https://user-images.githubusercontent.com/13300593/35261157-ee64b1c2-0049-11e8-8779-99123466ef33.png)


错误日志
![image](https://user-images.githubusercontent.com/13300593/35261125-ca41f0a2-0049-11e8-91ec-b95f1d278142.png)

**Comment by taoyuanyuan** [comment]
websocket怎么还有post请求，和200返回哦？ 你一台成功的时候走的是http吧？
你再贴一下一台机器正常情况的日志和截图

**Comment by yonghualuo** [comment]
这个post请求貌似是socket.js在websocket连接不上做的降级处理
下面是一台机器的请求日志


![1516697989524](https://user-images.githubusercontent.com/13300593/35266764-21945a06-005f-11e8-8efa-6cb26791321a.jpg)

**Comment by taoyuanyuan** [comment]
真正的websocket协商请求``101``前两次get请求干什么的？是否有相关性，必须在同一台机器上？

**Comment by taoyuanyuan** [comment]
你在你服务器上抓包看下两种情况的区别
```sudo tcpdump -nn -s0 -A -i any port 9099```

**Comment by yonghualuo** [comment]
从抓包来看，这三次请求都到了同一机器，可以连接成功；连接失败的确实是有一个请求去了另一台机器

**Comment by taoyuanyuan** [comment]
那你可以试试session_sticky 
http://tengine.taobao.org/document_cn/http_upstream_session_sticky_cn.html

**Comment by yonghualuo** [comment]
嗯，谢谢🙏！我加了consistent_hash就好了
