### ISSUE TITLE
打开reuse_port后，新Tengine实例不会报错

### ISSUE THREAD

**Issue by wuxin** [alibaba/tengine#999]
我理解的端口占用处理逻辑应该是：如果已经存在一个Tengine实例占用了端口，那再启动一个想使用该端口的Tengine实例时，应该报错然后退出。

在Tengine-2.1.3分支中，不论reuse_port是否打开，新启动Tengine实例发现端口占用会报错退出。

但是在Tengine-2.2.x中，如果reuse_port关闭，新启动Tengine实例发现端口占用会报错退出；如果reuse_port打开，则新启动Tengine实例不会报错，而且会获取一些请求。系统的整体负荷能力明显下降。

**Comment by taoyuanyuan** [comment]
开启reuse_port就支持多个进程绑定同样的端口，启动2个tengine实例，那么2个实例都会处理请求。
之前报错应该算是有问题，上一个版本做了修复。

**Comment by wuxin** [comment]
从测试来看，启动2个Tengine实例，确实2个实例都会处理请求。
但问题是：**2个实例的请求处理能力，远低于1个实例的请求处理能力。**

因此，这是系统设置或优化问题？还是Tengine没有处理好多实例共享的问题？

**Comment by taoyuanyuan** [comment]
请问你是怎么判断2个实例的处理能力远地低于一个实例的，怎样的测试方法？

**Comment by wuxin** [comment]
重做了一遍测试用例发现，之前的双实例性能裂化居然是系统参数没有优化导致的 （/手动尴尬）

新测试了四个实例并行，请求处理能力与单实例相当，这个正常？

另一个问题是：多实例运行时，多个实例能写到同一个日志文件吗？

**Comment by taoyuanyuan** [comment]
* 四个实例并存，其实就相当于 ```worker_processes``` x 4 的效果，因为nginx是做了cpu绑定的，一般场景来说一个进程绑定一个cpu性能最好，目前的情况就是4个进程绑定一个cpu，会有更多的进程上下文切换，按原理来说会比单实例低一点，但是也不会有你之前说的远低于。
*  同上， 单实例也是多个进程写日志文件，现在也就是多了4倍进程罢了，内核会处理写io的原子性。

ps： 你优化了什么系统参数？

**Comment by wuxin** [comment]
多谢说明，我前天重做测试用例时发现，确实是四个实例的性能略低于单实例。写同一个日志我再测试测试看。

系统参数的优化如下：
# 对于一个新建连接，内核要发送多少个SYN连接请求才决定放弃，不应该大于255，默认值是5，对应于180秒左右时间
sysctl -w net.ipv4.tcp_syn_retries=2
sysctl -w net.ipv4.tcp_synack_retries=2
# 表示当keepalive起用的时候，TCP发送keepalive消息的频度。缺省是2小时，改为300秒
sysctl -w net.ipv4.tcp_keepalive_time=1200
sysctl -w net.ipv4.tcp_orphan_retries=3
# 表示如果套接字由本端要求关闭，这个参数决定了它保持在FIN-WAIT-2状态的时间
sysctl -w net.ipv4.tcp_fin_timeout=15
# 表示SYN队列的长度，默认为1024，加大队列长度为16384，可以容纳更多等待连接的网络连接数。
sysctl -w net.ipv4.tcp_max_syn_backlog=32768
# 表示开启SYN Cookies。当出现SYN等待队列溢出时，启用cookies来处理，可防范少量SYN攻击，默认为0，表示关闭
sysctl -w net.ipv4.tcp_syncookies=1

# 表示开启重用。允许将TIME-WAIT sockets重新用于新的TCP连接，默认为0，表示关闭
sysctl -w net.ipv4.tcp_tw_reuse=1
# 表示开启TCP连接中TIME-WAIT sockets的快速回收，默认为0，表示关闭
sysctl -w net.ipv4.tcp_tw_recycle=0

# 减少超时前的探测次数
sysctl -w net.ipv4.tcp_keepalive_probes=5
# 优化核心层socket最大连接数
sysctl -w net.core.somaxconn=65535
# 优化网络设备接收队列
sysctl -w net.core.netdev_max_backlog=100000

这些参数现在搭配起来跑的还行，我的场景里很少有长连接，比较强调响应速度，而且下行内容不多。不知道设置是否合理。

**Comment by taoyuanyuan** [comment]
这些优化感觉不是导致双实例性能裂化的原因，应该单实例就会有问题吧？

**Comment by wuxin** [comment]
我没说清楚，同事的测试说性能劣化了，你提醒后，我**复查发现是他的测试过程有问题**，随后我自己是测试四个实例时性能并没有劣化，性能只是略有降低。

他测试的问题在于：单实例测试结束后，**重启了机器但是没有执行系统优化脚本**，随后执行双实例测试导致性能劣化。

**Comment by taoyuanyuan** [comment]
哦， 那我明白了，也就是测试环境不同了，他其实再测试一下单实例，也是劣化的。

**Comment by wuxin** [comment]
对的，这个乌龙闹得（/手动滑稽脸）

**Comment by chobits** [comment]
问题关闭中，如果有其他问题可以再打开。
